import { describe, expect, it } from 'vitest';
import { IvyRuntime } from './ivyRuntime.ts';

function publicRuntimeMethods() {
  const names = new Set();
  let proto = IvyRuntime.prototype;
  while (proto && proto !== Object.prototype) {
    for (const name of Object.getOwnPropertyNames(proto)) {
      if (name === 'constructor' || name.startsWith('_')) continue;
      if (typeof IvyRuntime.prototype[name] === 'function') names.add(name);
    }
    proto = Object.getPrototypeOf(proto);
  }
  return Array.from(names).sort();
}

describe('ivyRuntime public surface', () => {
  // This is a runtime debt inventory, not the desired command surface.
  // As service and command tests replace runtime-oriented coverage, this
  // list should shrink.
  it('inventories the public methods still exposed by the runtime coordinator', () => {
    expect(publicRuntimeMethods()).toEqual([
      'acceptArgSnapshot',
      'acceptConceptSnapshot',
      'activeEventSheet',
      'addCheckResultViewActions',
      'addEventPattern',
      'addProjection',
      'addRelationFromString',
      'addSheet',
      'analysisStateLimits',
      'applyEventPatternResult',
      'assertValidSheetId',
      'attachEventTraceHandlers',
      'attachGraphEventHandlers',
      'backtrack',
      'bindMenuAction',
      'boundedCheck',
      'buildAnalysisState',
      'buttonListDialog',
      'checkInduction',
      'chooseAndLoadAnalysisStateFile',
      'chooseAndLoadEventTraceFile',
      'chooseAndLoadModelFile',
      'clearEventPatterns',
      'closeAllDropdowns',
      'closeCurrentFile',
      'concreteStep',
      'createApi',
      'ctiConceptAction',
      'currentSheet',
      'diagramDomain',
      'dispatchMenuDescriptorAction',
      'doRedo',
      'doUndo',
      'downloadModel',
      'downloadModelForUnsupportedSave',
      'downloadTextFile',
      'entryDialog',
      'eventTraceRow',
      'executeArgEdgeAction',
      'executeArgNodeAction',
      'executeConceptEdgeAction',
      'executeConceptNodeAction',
      'exportConjecture',
      'filterEventTrace',
      'findEventTrace',
      'flashAndClose',
      'gatherFacts',
      'getEditorKeymap',
      'getMode',
      'graphElementsSnapshot',
      'handleEvent',
      'hideSaveAsExplanationNotice',
      'init',
      'installConceptGraphVisibilityHook',
      'integerDialog',
      'isValidSheetId',
      'isVisualOnlySheet',
      'listboxDialog',
      'loadAnalysisStateFile',
      'loadAnalysisStateObject',
      'loadEventPatterns',
      'loadEventTraceFile',
      'loadFile',
      'loadMenuDescriptors',
      'loadRecentSession',
      'lookupEventTrace',
      'makeConjecture',
      'materializeEdge',
      'materializeEdgeFromSelected',
      'materializeNode',
      'newModel',
      'okCancelDialog',
      'okDialog',
      'onArgEdgeRightClick',
      'onArgNodeClick',
      'onArgNodeRightClick',
      'onConceptEdgeRightClick',
      'onConceptNodeRightClick',
      'onEdgeToggle',
      'onEdgeToggleChange',
      'onLabelToggleChange',
      'openARGSheet',
      'openEventTraceSheet',
      'pathReach',
      'pdrStep',
      'populateConstraintFacts',
      'populateRecentFiles',
      'populateStateCheckboxes',
      'prepareArgNodeActionArgs',
      'reachStep',
      'readFileText',
      'recalculateGraph',
      'refreshAfterLoad',
      'refreshConceptGraph',
      'registerSheet',
      'rememberGraph',
      'removeAnalysisStateExtraSheets',
      'removeConcept',
      'removeSelectedEventPattern',
      'removeSheet',
      'renderEventPatternList',
      'renderEventTraceSheet',
      'renderEventTree',
      'renderEventTreeNode',
      'renderMenuDescriptor',
      'renderMenuRegion',
      'reopenLastFile',
      'resetDomain',
      'reverseStep',
      'runAction',
      'runCheck',
      'save',
      'saveAbstraction',
      'saveAnalysisState',
      'saveAs',
      'saveEventPatterns',
      'saveInvariant',
      'saveSession',
      'scrollEditorToLine',
      'selectConceptNode',
      'selectEventTraceRow',
      'selectedEventPattern',
      'setEditorContent',
      'setEditorKeymap',
      'setMode',
      'setVisualOnlySheet',
      'setupDetailsResizer',
      'setupDropdownMenus',
      'setupEventHandlers',
      'setupKeyboardShortcuts',
      'setupResizer',
      'setupResizer2',
      'setupResizer3',
      'setupResizerH',
      'setupTabs',
      'setupTutorialUrlBar',
      'sheetExists',
      'sheetTab',
      'showCheckResult',
      'showDirtyCloseDialog',
      'showExternalChangeDialog',
      'showReachableStates',
      'showSaveAsExplanationNotice',
      'showTextDialog',
      'splatterNode',
      'splitConcept',
      'supposeEmpty',
      'switchSheet',
      'tabLabelForSheet',
      'textDialog',
      'toggleEventTraceNode',
      'toggleTutorial',
      'uncoverEventTraceAddress',
      'updateSessionDisplay',
      'updateStateLabel',
      'validateAnalysisStateEvents',
      'validateAnalysisStateGraphPayload',
      'validateAnalysisStateObject',
      'validateAnalysisStateSheet',
      'visualOnlyMessage',
      'weakenInvariant',
    ]);
  });
});
