package ivy2golang

import (
	"errors"
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/glycerine/ivy/goivy"
)

type Config struct {
	Target          string
	RequestedTarget string
	ClassName       string
	MainName        string
	OutDir          string
	Compiler        string
	TestIters       string
	TestRuns        string
	Build           bool
	EmitMain        bool
	Trace           bool
	Stdafx          bool
	HostOS          string
}

type Output struct {
	Source          string
	BaseName        string
	ClassName       string
	Target          string
	EffectiveTarget string
	EmitMain        bool
	Config          Config
	ExtraFiles      map[string]string
	LibSpecs        []string
	Warnings        []string
}

type Generator struct {
	Mod       *goivy.Module
	Config    Config
	BaseName  string
	ClassName string

	tempID     int
	errs       []error
	warnings   []string
	warningSet map[string]bool

	locals             []map[string]goivy.Sort
	currentReturns     []*goivy.Const
	extRel             map[string]bool
	importCallersCache map[string]bool
	exprAliases        map[string]goivy.Expr
	exprOverrides      []map[string]string
	defStack           map[string]bool
}

func Generate(mod *goivy.Module, cfg Config) (*Output, error) {
	if mod == nil {
		return nil, fmt.Errorf("ivy2golang: nil module")
	}
	if cfg.Target == "" && cfg.RequestedTarget == "" {
		cfg.Target = "impl"
	}
	var err error
	cfg, _, err = normalizeConfig(cfg)
	if err != nil {
		return nil, err
	}
	base := moduleBaseName(mod)
	className := cfg.ClassName
	if className == "" {
		className = goName(base)
	}
	applySessionParameters(mod, cfg)
	prepareModuleForGo(mod, cfg)
	g := &Generator{
		Mod:       mod,
		Config:    cfg,
		BaseName:  base,
		ClassName: className,
	}
	g.validatePublicActions()
	src, err := g.generate()
	if err != nil {
		return nil, err
	}
	return &Output{
		Source:          src,
		BaseName:        base,
		ClassName:       className,
		Target:          cfg.RequestedTarget,
		EffectiveTarget: cfg.Target,
		EmitMain:        cfg.EmitMain,
		Config:          cfg,
		LibSpecs:        moduleLibSpecs(mod),
		Warnings:        append([]string(nil), g.warnings...),
	}, nil
}

func (g *Generator) generate() (string, error) {
	var w goWriter
	w.line("// Code generated by ivy2golang; DO NOT EDIT.")
	w.linef("package %s", g.packageName())
	w.blank()
	g.emitImports(&w)
	g.emitSortDecls(&w)
	g.emitRuntime(&w)
	g.emitStruct(&w)
	g.emitConstructor(&w)
	g.emitInitialState(&w)
	g.emitInit(&w)
	g.emitMethods(&w)
	g.emitTick(&w)
	if g.Config.EmitMain {
		if g.Config.Target == "test" {
			g.emitTestMain(&w)
		} else if g.Config.Target == "gen" {
			g.emitGenMain(&w)
		} else {
			g.emitSmokeMain(&w)
		}
		g.emitMainWrapper(&w)
	}
	return w.String(), errors.Join(g.errs...)
}

func (g *Generator) validatePublicActions() {
	if g == nil || g.Mod == nil || g.Mod.Actions == nil || g.Mod.PublicActions == nil {
		return
	}
	for name, act := range g.Mod.Actions.All() {
		if !g.Mod.PublicActions.Get(name) || act == nil {
			continue
		}
		if len(act.GetFormalReturns()) > 1 {
			g.errs = append(g.errs, fmt.Errorf("ivy2golang: cannot handle multiple output in exported actions: %s", name))
		}
	}
}

func (g *Generator) packageName() string {
	if g != nil && !g.Config.EmitMain {
		return "ivygenerated"
	}
	return "main"
}

func (g *Generator) emitImports(w *goWriter) {
	w.line("import (")
	w.indent++
	imports := []string{"fmt", "io", "math/rand/v2", "os", "strconv", "strings"}
	if g.Config.Target == "test" || g.Config.Target == "gen" {
		imports = append(imports, "time")
	}
	for _, imp := range imports {
		w.linef("%q", imp)
	}
	w.indent--
	w.line(")")
	w.blank()
}

func (g *Generator) emitSortDecls(w *goWriter) {
	if g.Mod == nil || g.Mod.Sig == nil {
		return
	}
	for _, name := range g.Mod.SortOrder {
		s, ok := g.Mod.Sig.Sorts.Get2(name)
		if !ok {
			continue
		}
		st, ok := s.(*goivy.LogicEnumeratedSort)
		if !ok || st.Name == "" || isNumericEnum(st) {
			continue
		}
		// Package-level Go type/const declarations are allowed to be unused,
		// and destructor-local variant construction can reference enum
		// constructors even when no retained state symbol mentions the enum
		// sort directly after isolate pruning.
		typeName := goName(st.Name)
		w.linef("type %s int", typeName)
		w.blank()
		w.line("const (")
		w.indent++
		for i, sym := range st.Extension {
			if i == 0 {
				w.linef("%s %s = iota", goName(sym), typeName)
			} else {
				w.line(goName(sym))
			}
		}
		w.indent--
		w.line(")")
		w.blank()
		w.open(fmt.Sprintf("func (v %s) String() string {", typeName))
		w.line("switch v {")
		w.indent++
		for _, sym := range st.Extension {
			w.linef("case %s:", goName(sym))
			w.indent++
			w.linef("return %q", memName(sym))
			w.indent--
		}
		w.indent--
		w.line("}")
		w.line(`return fmt.Sprintf("%d", int(v))`)
		w.close("")
		w.blank()
	}
	for _, name := range g.Mod.SortOrder {
		if !g.isVariantSuperName(name) {
			continue
		}
		g.emitVariantSuperDecl(w, name)
	}
	for _, name := range g.Mod.SortOrder {
		fields := g.destructorStructFields(name)
		if len(fields) == 0 {
			continue
		}
		typeName := goName(name)
		w.open(fmt.Sprintf("type %s struct {", typeName))
		for _, d := range fields {
			fs := d.CSort.(*goivy.LogicFunctionSort)
			w.linef("%s %s", goName(memName(d.Name)), g.goScalarType(fs.Range()))
		}
		w.close("")
		w.blank()
		w.open(fmt.Sprintf("func (v %s) String() string {", typeName))
		if len(fields) == 0 {
			w.line(`return "{}"`)
		} else {
			format := "{" + strings.Join(recordFormatLabels(fields), ",") + "}"
			args := make([]string, len(fields))
			for i, d := range fields {
				args[i] = "v." + goName(memName(d.Name))
			}
			w.linef("return fmt.Sprintf(%q, %s)", format, strings.Join(args, ", "))
		}
		w.close("")
		w.blank()
	}
}

func (g *Generator) emitVariantSuperDecl(w *goWriter, name string) {
	variants := g.Mod.Variants[name]
	typeName := goName(name)
	w.open(fmt.Sprintf("type %s struct {", typeName))
	w.line("tag int")
	w.line("value any")
	w.line("valid bool")
	w.close("")
	w.blank()
	w.open(fmt.Sprintf("func (v %s) String() string {", typeName))
	w.open("if !v.valid {")
	w.line(`return "{}"`)
	w.close("")
	w.line("switch v.tag {")
	w.indent++
	for i, sub := range variants {
		subName := sortName(sub)
		payloadType := g.goScalarType(sub)
		w.linef("case %d:", i)
		w.indent++
		w.linef("return fmt.Sprintf(%q, v.value.(%s))", "{"+subName+":%v}", payloadType)
		w.indent--
	}
	w.indent--
	w.line("}")
	w.line(`return "{}"`)
	w.close("")
	w.blank()
}

func recordFormatLabels(fields []*goivy.Const) []string {
	labels := make([]string, 0, len(fields))
	for _, d := range fields {
		labels = append(labels, fmt.Sprintf("%s:%%v", memName(d.Name)))
	}
	return labels
}

func (g *Generator) sortNeededForGoDecl(name string) bool {
	for _, sym := range g.stateSymbols() {
		if g.sortDependenciesReferenceName(sym.Sort, name) {
			return true
		}
	}
	if g.Mod.Actions != nil {
		for _, act := range g.Mod.Actions.All() {
			for _, p := range act.GetFormalParams() {
				if g.sortDependenciesReferenceName(p.CSort, name) {
					return true
				}
			}
			for _, r := range act.GetFormalReturns() {
				if g.sortDependenciesReferenceName(r.CSort, name) {
					return true
				}
			}
		}
	}
	return false
}

func (g *Generator) emitRuntime(w *goWriter) {
	w.line("var __ivy_out io.Writer = os.Stdout")
	w.line("var __ivy_rng = rand.NewChaCha8(ivySeedBytes(1))")
	w.blank()
	w.open("func parseIvyTestArgs(args []string) (map[string]string, []string) {")
	w.line("opts := map[string]string{}")
	w.line("var rest []string")
	w.open("for _, arg := range args {")
	w.line(`if key, value, ok := strings.Cut(arg, "="); ok {`)
	w.indent++
	w.line("opts[key] = value")
	w.indent--
	w.line("} else {")
	w.indent++
	w.line("rest = append(rest, arg)")
	w.indent--
	w.line("}")
	w.close("")
	w.line("return opts, rest")
	w.close("")
	w.blank()
	w.open("func ivyAtoiDefault(text string, def int) int {")
	w.open(`if text == "" {`)
	w.line("return def")
	w.close("")
	w.open("if n, err := strconv.Atoi(text); err == nil {")
	w.line("return n")
	w.close("")
	w.line("return def")
	w.close("")
	w.blank()
	w.open("func ivySeedBytes(seed int) [32]byte {")
	w.line("var key [32]byte")
	w.line("u := uint32(seed)")
	w.line("key[0] = byte(u)")
	w.line("key[1] = byte(u >> 8)")
	w.line("key[2] = byte(u >> 16)")
	w.line("key[3] = byte(u >> 24)")
	w.line("return key")
	w.close("")
	w.blank()
	w.open("func ivySetSeed(seed int) {")
	w.line("__ivy_rng = rand.NewChaCha8(ivySeedBytes(seed))")
	w.close("")
	w.blank()
	w.open("func ivyRand31() int {")
	w.line("return int(__ivy_rng.Uint64() >> 33)")
	w.close("")
	w.blank()
	w.open("func ivyRandRange64(rng int) int {")
	w.open("if rng <= 0 {")
	w.line("return 0")
	w.close("")
	w.line("return int(__ivy_rng.Uint64() % uint64(rng))")
	w.close("")
	w.blank()
	w.open("func ivyFailureEvent(event, msg string) {")
	w.line(`fmt.Fprintf(__ivy_out, "%s(%q)\n", event, msg)`)
	w.close("")
	w.blank()
	w.open("func ivyAssert(truth bool, msg string) {")
	w.open("if !truth {")
	w.line(`ivyFailureEvent("assertion_failed", msg)`)
	w.line(`fmt.Fprintf(os.Stderr, "%s: error: assertion failed\n", msg)`)
	w.line("os.Exit(1)")
	w.close("")
	w.close("")
	w.blank()
	w.open("func ivyAssume(truth bool, msg string) bool {")
	w.open("if !truth {")
	w.line(`ivyFailureEvent("assumption_failed", msg)`)
	w.line(`fmt.Fprintf(os.Stderr, "%s: error: assumption failed\n", msg)`)
	w.line("os.Exit(1)")
	w.line("return false")
	w.close("")
	w.line("return true")
	w.close("")
	w.blank()
	w.open("func ivyCheckProgress(counter, max int) {")
	w.line("_ = counter")
	w.line("_ = max")
	w.close("")
	w.blank()
	w.open("func ivyTernary[T any](cond bool, thenVal, elseVal T) T {")
	w.open("if cond {")
	w.line("return thenVal")
	w.close("")
	w.line("return elseVal")
	w.close("")
	w.blank()
	w.open("func ivyBoolOrd(v bool) int {")
	w.open("if v {")
	w.line("return 1")
	w.close("")
	w.line("return 0")
	w.close("")
	w.blank()
	w.open("func ivyTraceValue(value any, hex bool) string {")
	w.open("if s, ok := value.(fmt.Stringer); ok {")
	w.line("return s.String()")
	w.close("")
	w.open("if hex {")
	w.open("switch v := value.(type) {")
	w.line("case int:")
	w.indent++
	w.line(`return fmt.Sprintf("%#x", v)`)
	w.indent--
	w.line("case int8:")
	w.indent++
	w.line(`return fmt.Sprintf("%#x", v)`)
	w.indent--
	w.line("case int16:")
	w.indent++
	w.line(`return fmt.Sprintf("%#x", v)`)
	w.indent--
	w.line("case int32:")
	w.indent++
	w.line(`return fmt.Sprintf("%#x", v)`)
	w.indent--
	w.line("case int64:")
	w.indent++
	w.line(`return fmt.Sprintf("%#x", v)`)
	w.indent--
	w.line("case uint:")
	w.indent++
	w.line(`return fmt.Sprintf("%#x", v)`)
	w.indent--
	w.line("case uint8:")
	w.indent++
	w.line(`return fmt.Sprintf("%#x", v)`)
	w.indent--
	w.line("case uint16:")
	w.indent++
	w.line(`return fmt.Sprintf("%#x", v)`)
	w.indent--
	w.line("case uint32:")
	w.indent++
	w.line(`return fmt.Sprintf("%#x", v)`)
	w.indent--
	w.line("case uint64:")
	w.indent++
	w.line(`return fmt.Sprintf("%#x", v)`)
	w.indent--
	w.close("")
	w.close("")
	w.line("return fmt.Sprint(value)")
	w.close("")
	w.blank()
	w.open("type ivyThunkMap[K comparable, V any] struct {")
	w.line("overrides map[K]V")
	w.line("base func(K) V")
	w.line("zero V")
	w.close("")
	w.blank()
	w.open("func newIvyThunkMap[K comparable, V any](zero V) ivyThunkMap[K, V] {")
	w.line("return ivyThunkMap[K, V]{overrides: map[K]V{}, zero: zero}")
	w.close("")
	w.blank()
	w.open("func (m *ivyThunkMap[K, V]) Get(key K) V {")
	w.open("if m.overrides != nil {")
	w.open("if value, ok := m.overrides[key]; ok {")
	w.line("return value")
	w.close("")
	w.close("")
	w.open("if m.base != nil {")
	w.line("value := m.base(key)")
	w.open("if m.overrides == nil {")
	w.line("m.overrides = map[K]V{}")
	w.close("")
	w.line("m.overrides[key] = value")
	w.line("return value")
	w.close("")
	w.line("return m.zero")
	w.close("")
	w.blank()
	w.open("func (m *ivyThunkMap[K, V]) Set(key K, value V) {")
	w.open("if m.overrides == nil {")
	w.line("m.overrides = map[K]V{}")
	w.close("")
	w.line("m.overrides[key] = value")
	w.close("")
	w.blank()
}

func (g *Generator) emitStruct(w *goWriter) {
	w.open(fmt.Sprintf("type %s struct {", g.ClassName))
	w.line("__argv []string")
	for _, sym := range g.stateSymbols() {
		w.line(g.goStorageDecl(sym.Name, sym.Sort))
	}
	g.emitProgressCounterDecls(w)
	w.close("")
	w.blank()
}

func (g *Generator) emitConstructor(w *goWriter) {
	w.open(fmt.Sprintf("func new%s(%s) *%s {", exportedishName(g.ClassName), strings.Join(g.constructorParamDecls(), ", "), g.ClassName))
	w.linef("ivy := &%s{}", g.ClassName)
	w.line("ivy.__initStorage()")
	for _, p := range g.Mod.Params {
		if p == nil {
			continue
		}
		w.linef("ivy.%s = %s", goName(p.Name), goName(p.Name))
	}
	w.line("ivy.__initState()")
	w.line("ivy.__init()")
	w.line("return ivy")
	w.close("")
	w.blank()
	w.open(fmt.Sprintf("func (ivy *%s) __initStorage() {", g.ClassName))
	for _, sym := range g.stateSymbols() {
		if fs, ok := sym.Sort.(*goivy.LogicFunctionSort); ok && len(fs.Domain()) > 0 {
			w.linef("ivy.%s = %s", goName(sym.Name), g.goFunctionStorageInit(fs.Domain(), fs.Range()))
		}
	}
	g.emitProgressStorageInitializers(w)
	w.close("")
	w.blank()
	w.open(fmt.Sprintf("func (ivy *%s) ___ivy_choose(rng int, name string, id int) int {", g.ClassName))
	w.line("_ = name")
	w.line("_ = id")
	w.open("if rng <= 0 {")
	w.line("return 0")
	w.close("")
	w.line("return ivyRand31() % rng")
	w.close("")
	w.blank()
	w.open(fmt.Sprintf("func (ivy *%s) ___ivy_randomize(rng int, name string, id int) int {", g.ClassName))
	w.line("_ = name")
	w.line("_ = id")
	w.line("return ivyRandRange64(rng)")
	w.close("")
	w.blank()
}

func (g *Generator) emitInitialState(w *goWriter) {
	w.open(fmt.Sprintf("func (ivy *%s) __initState() {", g.ClassName))
	for _, sym := range g.stateSymbols() {
		if g.isParamName(sym.Name) {
			continue
		}
		g.emitRandomizeSymbol(w, sym, "init")
	}
	acts, err := g.initialConditionActions()
	if err != nil {
		g.unsupported(w, "unsupported initial condition: %s", err.Error())
	} else {
		for _, act := range acts {
			g.emitAction(w, act)
		}
	}
	w.close("")
	w.blank()
}

func (g *Generator) emitRandomizeSymbol(w *goWriter, sym stateSymbol, label string) {
	if sym.Name == "_generating" {
		w.line(`_ = ivy.___ivy_randomize(2, "init._generating", 0)`)
		w.line(`ivy._generating = ivy.___ivy_choose(0, "init", 0) != 0`)
		return
	}
	if g.isVariantSuperName(sortName(sym.Sort)) {
		w.linef("ivy.%s = %s", goName(sym.Name), g.goZeroValue(sym.Sort))
		return
	}
	if fs, ok := sym.Sort.(*goivy.LogicFunctionSort); ok && len(fs.Domain()) > 0 {
		if !g.canEnumerateDomain(fs.Domain()) {
			base := "ivy." + goName(sym.Name)
			w.linef("%s = %s", base, g.goFunctionStorageInit(fs.Domain(), fs.Range()))
			g.emitNondetThunkBase(w, base, fs.Domain(), fs.Range(), label, 0)
			return
		}
		g.emitDomainLoops(w, fs.Domain(), func(args []string) {
			expr, err := g.goRandomValueExpr(fs.Range(), label+"."+sym.Name, int64(len(args)))
			if err != nil {
				g.unsupported(w, "%s", err.Error())
				return
			}
			w.linef("%s = %s", g.goStorageAccess(sym.Name, sym.Sort, args, "ivy"), expr)
		})
		return
	}
	expr, err := g.goRandomValueExpr(sym.Sort, label+"."+sym.Name, 0)
	if err != nil {
		g.unsupported(w, "%s", err.Error())
		return
	}
	w.linef("ivy.%s = %s", goName(sym.Name), expr)
}

func (g *Generator) emitNondetThunkBase(w *goWriter, base string, domain []goivy.Sort, rng goivy.Sort, label string, id int64) {
	st := g.goFunctionStorageFor(domain, rng)
	if !st.Large {
		return
	}
	expr, err := g.goLocalNondetValueExpr(rng, label, id)
	if err != nil {
		g.unsupported(w, "unsupported nondet thunk range: %s", err.Error())
		return
	}
	w.open(fmt.Sprintf("%s.base = func(__ivy_key %s) %s {", base, st.KeyType, st.RangeType))
	w.line("_ = __ivy_key")
	w.linef("return %s", expr)
	w.close("")
}

func (g *Generator) emitDomainLoops(w *goWriter, domain []goivy.Sort, body func(args []string)) {
	var args []string
	var recur func(int)
	recur = func(i int) {
		if i == len(domain) {
			body(args)
			return
		}
		name := fmt.Sprintf("__i%d", i)
		vals, ok := g.finiteValueExprs(domain[i])
		if !ok {
			g.unsupported(w, "cannot enumerate function domain sort %s", sortName(domain[i]))
			return
		}
		w.open(fmt.Sprintf("for _, %s := range []%s{%s} {", name, g.goScalarType(domain[i]), strings.Join(vals, ", ")))
		args = append(args, name)
		recur(i + 1)
		args = args[:len(args)-1]
		w.close("")
	}
	recur(0)
}

func (g *Generator) emitInit(w *goWriter) {
	w.open(fmt.Sprintf("func (ivy *%s) __init() {", g.ClassName))
	if len(g.Mod.InitialActions) > 0 {
		for _, act := range g.Mod.InitialActions {
			g.emitAction(w, act)
		}
		w.close("")
		w.blank()
		return
	}
	for _, na := range g.Mod.Initializers {
		if act, ok := na.Action.(goivy.Action); ok {
			g.emitAction(w, act)
		}
	}
	if len(g.Mod.Initializers) == 0 && g.Mod.Actions != nil && g.Mod.Mixins != nil {
		for _, mixin := range g.Mod.Mixins.Get("init") {
			if act, ok := g.Mod.Actions.Get2(mixin.Mixer()); ok {
				g.emitAction(w, act)
			}
		}
	}
	w.close("")
	w.blank()
}

func (g *Generator) emitMethods(w *goWriter) {
	if g.Mod.Actions == nil {
		return
	}
	initActions := g.initialMixinActionNames()
	for name, act := range g.Mod.Actions.All() {
		if initActions[name] {
			continue
		}
		g.emitSomeAction(w, name, act)
	}
}

func (g *Generator) emitSomeAction(w *goWriter, name string, act goivy.Action) {
	sig, returnNames := g.methodSignature(name, act)
	w.open(sig + " {")
	g.pushScope()
	for _, p := range act.GetFormalParams() {
		g.addLocal(p.Name)
	}
	traceImportCaller := g.importCallers()[name]
	if traceImportCaller {
		g.emitTraceActionPrologue(w, name, act.GetFormalParams())
		if g.Config.Trace {
			w.line(`fmt.Fprintln(__ivy_out, "{")`)
		}
	}
	returns := act.GetFormalReturns()
	prevReturns := g.currentReturns
	g.currentReturns = returns
	for _, r := range returns {
		g.addLocal(r.Name)
		w.linef("%s := %s", goName(r.Name), g.goZeroValue(r.CSort))
	}
	g.emitAction(w, act)
	g.currentReturns = prevReturns
	if traceImportCaller && g.Config.Trace {
		w.line(`fmt.Fprintln(__ivy_out, "}")`)
	}
	if len(returnNames) > 0 {
		w.linef("return %s", strings.Join(returnNames, ", "))
	}
	g.popScope()
	w.close("")
	w.blank()
}

// importCallers mirrors Python find_import_callers through the ivy2cpp port.
// For target=test, unscoped imports named as known actions get a callback
// trace prologue at the top of the corresponding action body.
func (g *Generator) importCallers() map[string]bool {
	if g.importCallersCache != nil {
		return g.importCallersCache
	}
	out := map[string]bool{}
	if g.Config.Target == "test" && g.Mod != nil && g.Mod.Actions != nil {
		for _, imp := range g.Mod.Imports {
			impDef, ok := imp.(*goivy.ImportDef)
			if !ok {
				continue
			}
			if atom, ok := impDef.Scope.(*goivy.Atom); ok && atom.Relname() != "" {
				continue
			}
			name := ""
			if atom, ok := impDef.Imported.(*goivy.Atom); ok {
				name = atom.Relname()
			}
			if name == "" {
				continue
			}
			if _, ok := g.Mod.Actions.Get2(name); !ok {
				continue
			}
			caller := name
			if strings.HasPrefix(caller, "imp__") {
				caller = strings.TrimPrefix(caller, "imp__")
			} else {
				caller = strings.TrimPrefix(caller, "ext:")
			}
			out["ext:"+caller] = true
			out[caller] = true
		}
	}
	g.importCallersCache = out
	return out
}

func (g *Generator) isTestImportCallback(name string) bool {
	if g == nil || g.Config.Target != "test" {
		return false
	}
	return g.importCallers()[name]
}

func (g *Generator) emitTraceActionPrologue(w *goWriter, name string, formals []*goivy.Const) {
	display := actionDisplayName(name)
	w.linef("fmt.Fprint(__ivy_out, %q)", "< "+display)
	if len(formals) > 0 {
		w.line(`fmt.Fprint(__ivy_out, "(")`)
		for i, p := range formals {
			if i > 0 {
				w.line(`fmt.Fprint(__ivy_out, ",")`)
			}
			w.linef("fmt.Fprint(__ivy_out, ivyTraceValue(%s, %t))", goName(p.Name), g.traceHex())
		}
		w.line(`fmt.Fprint(__ivy_out, ")")`)
	}
	w.line("fmt.Fprintln(__ivy_out)")
}

func (g *Generator) methodSignature(name string, act goivy.Action) (string, []string) {
	fn, err := funName(name)
	if err != nil {
		fn = goName(name)
		g.errs = append(g.errs, err)
	}
	var params []string
	for _, p := range act.GetFormalParams() {
		params = append(params, fmt.Sprintf("%s %s", goName(p.Name), g.goType(p.CSort)))
	}
	var retTypes []string
	var retNames []string
	for _, r := range act.GetFormalReturns() {
		retTypes = append(retTypes, g.goType(r.CSort))
		retNames = append(retNames, goName(r.Name))
	}
	ret := ""
	if len(retTypes) == 1 {
		ret = " " + retTypes[0]
	} else if len(retTypes) > 1 {
		ret = " (" + strings.Join(retTypes, ", ") + ")"
	}
	return fmt.Sprintf("func (ivy *%s) %s(%s)%s", g.ClassName, fn, strings.Join(params, ", "), ret), retNames
}

func (g *Generator) emitTick(w *goWriter) {
	w.open(fmt.Sprintf("func (ivy *%s) __tick(timeout int) {", g.ClassName))
	w.line("_ = timeout")
	g.emitProgressTick(w)
	w.close("")
	w.blank()
}

func (g *Generator) constructorParamDecls() []string {
	if g == nil || g.Mod == nil {
		return nil
	}
	decls := make([]string, 0, len(g.Mod.Params))
	for _, p := range g.Mod.Params {
		if p == nil {
			continue
		}
		decls = append(decls, fmt.Sprintf("%s %s", goName(p.Name), g.goType(p.CSort)))
	}
	return decls
}

func (g *Generator) constructorParamArgNames() []string {
	if g == nil || g.Mod == nil {
		return nil
	}
	args := make([]string, 0, len(g.Mod.Params))
	for _, p := range g.Mod.Params {
		if p == nil {
			continue
		}
		args = append(args, "p__"+goName(p.Name))
	}
	return args
}

func (g *Generator) emitModuleParamSetup(w *goWriter, optsName, restName string) {
	if g == nil || g.Mod == nil || len(g.Mod.Params) == 0 {
		return
	}
	positional := 0
	for i, p := range g.Mod.Params {
		if p == nil {
			continue
		}
		local := "p__" + goName(p.Name)
		w.linef("%s := %s", local, g.moduleParamDefaultExpr(i, p))
		if !g.moduleParamHasDefault(i) {
			positional++
			continue
		}
		w.open(fmt.Sprintf("if __ivy_param, ok := %s[%q]; ok {", optsName, p.Name))
		g.emitModuleParamParseAssign(w, local, "__ivy_param", p)
		w.linef("delete(%s, %q)", optsName, p.Name)
		w.close("")
	}
	if positional == 0 {
		g.emitZeroParamArgSetup(w, restName)
		return
	}
	g.emitCommandFileArgSetup(w, restName, positional)
	w.open(fmt.Sprintf("if len(%s) != %d {", restName, positional))
	g.emitUsageExit(w)
	w.close("")
	idx := 0
	for i, p := range g.Mod.Params {
		if p == nil || g.moduleParamHasDefault(i) {
			continue
		}
		g.emitModuleParamParseAssign(w, "p__"+goName(p.Name), fmt.Sprintf("%s[%d]", restName, idx), p)
		idx++
	}
}

func (g *Generator) emitZeroParamArgSetup(w *goWriter, restName string) {
	g.emitCommandFileArgSetup(w, restName, 0)
	w.open(fmt.Sprintf("if len(%s) != 0 {", restName))
	g.emitUsageExit(w)
	w.close("")
}

func (g *Generator) emitCommandFileArgSetup(w *goWriter, restName string, positional int) {
	w.open(fmt.Sprintf("if len(%s) == %d {", restName, positional+1))
	w.linef("__ivy_stdin, err := os.Open(%s[%d])", restName, positional)
	w.open("if err != nil {")
	w.linef("fmt.Fprintf(os.Stderr, %q, %s[%d])", "cannot open to read: %s\n", restName, positional)
	w.line("os.Exit(1)")
	w.close("")
	w.line("defer __ivy_stdin.Close()")
	w.line("os.Stdin = __ivy_stdin")
	w.linef("%s = %s[:%d]", restName, restName, positional)
	w.close("")
}

func (g *Generator) emitUsageExit(w *goWriter) {
	usage := strings.Join(g.positionalParamNames(), " ")
	w.linef("fmt.Fprintf(os.Stderr, %q)", fmt.Sprintf("usage: %s %s\n", g.ClassName, usage))
	w.line("os.Exit(1)")
}

func (g *Generator) positionalParamNames() []string {
	if g == nil || g.Mod == nil {
		return nil
	}
	var names []string
	for i, p := range g.Mod.Params {
		if p == nil || g.moduleParamHasDefault(i) {
			continue
		}
		names = append(names, p.Name)
	}
	return names
}

func (g *Generator) moduleParamHasDefault(i int) bool {
	return g != nil && g.Mod != nil && i < len(g.Mod.ParamDefaults) && g.Mod.ParamDefaults[i] != nil
}

func (g *Generator) moduleParamDefaultExpr(i int, p *goivy.Const) string {
	if p == nil {
		return "0"
	}
	if !g.moduleParamHasDefault(i) {
		return g.goZeroValue(p.CSort)
	}
	text := paramDefaultText(g.Mod.ParamDefaults[i])
	if expr, ok := g.goParamLiteralExpr(p.CSort, text); ok {
		return expr
	}
	return g.goZeroValue(p.CSort)
}

func paramDefaultText(n goivy.Node) string {
	if n == nil {
		return ""
	}
	if a, ok := n.(*goivy.Atom); ok {
		return a.Relname()
	}
	type relnamer interface{ Relname() string }
	if r, ok := n.(relnamer); ok {
		return r.Relname()
	}
	return fmt.Sprintf("%v", n)
}

func (g *Generator) goParamLiteralExpr(s goivy.Sort, text string) (string, bool) {
	text = strings.TrimSpace(text)
	if text == "" {
		return "", false
	}
	switch st := s.(type) {
	case *goivy.BooleanSort:
		switch strings.ToLower(text) {
		case "true", "1":
			return "true", true
		case "false", "0":
			return "false", true
		}
	case *goivy.LogicEnumeratedSort:
		if st.Name != "" && !isNumericEnum(st) {
			for _, elem := range st.Extension {
				if elem == text {
					return goName(elem), true
				}
			}
			return "", false
		}
		if _, err := strconv.Atoi(text); err == nil {
			return text, true
		}
	case *goivy.RangeSort:
		if _, err := strconv.Atoi(text); err == nil {
			return text, true
		}
	case *goivy.UninterpretedSort:
		if g.hasStringInterp(st) {
			if strings.HasPrefix(text, `"`) && strings.HasSuffix(text, `"`) {
				return text, true
			}
			return strconv.Quote(text), true
		}
		if _, err := strconv.Atoi(text); err == nil {
			return text, true
		}
	default:
		if _, err := strconv.Atoi(text); err == nil {
			return text, true
		}
	}
	return "", false
}

func (g *Generator) emitModuleParamParseAssign(w *goWriter, dst, text string, p *goivy.Const) {
	if p == nil {
		return
	}
	switch st := p.CSort.(type) {
	case *goivy.BooleanSort:
		w.open("switch strings.ToLower(" + text + ") {")
		w.line(`case "true", "1":`)
		w.indent++
		w.linef("%s = true", dst)
		w.indent--
		w.line(`case "false", "0":`)
		w.indent++
		w.linef("%s = false", dst)
		w.indent--
		w.line("default:")
		w.indent++
		g.emitParamParseError(w, "syntax error in parameter value", p.Name)
		w.indent--
		w.close("")
	case *goivy.LogicEnumeratedSort:
		if st.Name != "" && !isNumericEnum(st) {
			w.open("switch " + text + " {")
			for _, elem := range st.Extension {
				w.linef("case %q:", elem)
				w.indent++
				w.linef("%s = %s", dst, goName(elem))
				w.indent--
			}
			w.line("default:")
			w.indent++
			g.emitParamParseError(w, "parameter out of bounds", p.Name)
			w.indent--
			w.close("")
			return
		}
		g.emitNumericParamParseAssign(w, dst, text, p.Name, "", "")
	case *goivy.RangeSort:
		lo, hi, ok := numericRangeBounds(st)
		if ok {
			g.emitNumericParamParseAssign(w, dst, text, p.Name, strconv.Itoa(lo), strconv.Itoa(hi))
		} else {
			g.emitNumericParamParseAssign(w, dst, text, p.Name, "", "")
		}
	case *goivy.UninterpretedSort:
		if g.hasStringInterp(st) {
			w.linef("%s = %s", dst, text)
			return
		}
		g.emitNumericParamParseAssign(w, dst, text, p.Name, "", "")
	default:
		g.emitNumericParamParseAssign(w, dst, text, p.Name, "", "")
	}
}

func (g *Generator) emitNumericParamParseAssign(w *goWriter, dst, text, name, lo, hi string) {
	w.open("{")
	w.linef("__ivy_param, err := strconv.Atoi(%s)", text)
	w.open("if err != nil {")
	g.emitParamParseError(w, "syntax error in parameter value", name)
	w.close("")
	if lo != "" && hi != "" {
		w.open(fmt.Sprintf("if __ivy_param < %s || __ivy_param > %s {", lo, hi))
		g.emitParamParseError(w, "parameter out of bounds", name)
		w.close("")
	}
	w.linef("%s = __ivy_param", dst)
	w.close("")
}

func (g *Generator) emitParamParseError(w *goWriter, prefix, name string) {
	if prefix == "parameter out of bounds" {
		w.linef("fmt.Fprintf(os.Stderr, %q)", fmt.Sprintf("parameter %s out of bounds\n", name))
		w.line("os.Exit(1)")
		return
	}
	w.linef("fmt.Fprintf(os.Stderr, %q)", fmt.Sprintf("%s %s\n", prefix, name))
	w.line("os.Exit(1)")
}

func (g *Generator) emitUnknownOptionCheck(w *goWriter) {
	w.open(`for key := range opts {`)
	w.line("switch key {")
	w.indent++
	w.line(`case "out", "iters", "runs", "seed", "delay", "wait", "modelfile":`)
	w.line("default:")
	w.indent++
	w.line(`fmt.Fprintf(os.Stderr, "unknown option: %s\n", key)`)
	w.line("os.Exit(1)")
	w.indent--
	w.indent--
	w.line("}")
	w.close("")
}

func (g *Generator) emitRuntimeOptionSetup(w *goWriter, optsName string) {
	w.linef("seed := ivyAtoiDefault(%s[%q], 1)", optsName, "seed")
	w.line("ivySetSeed(seed)")
	g.emitRuntimeFilesSetup(w, optsName)
}

func (g *Generator) emitRuntimeFilesSetup(w *goWriter, optsName string) {
	w.open(fmt.Sprintf(`if out := %s["out"]; out != "" {`, optsName))
	w.line("f, err := os.Create(out)")
	w.open("if err != nil {")
	w.line(`fmt.Fprintf(os.Stderr, "cannot open to write: %s\n", out)`)
	w.line("os.Exit(1)")
	w.close("")
	w.line("defer f.Close()")
	w.line("__ivy_out = f")
	w.close("")
	w.open(fmt.Sprintf(`if modelfile := %s["modelfile"]; modelfile != "" {`, optsName))
	w.line("f, err := os.Create(modelfile)")
	w.open("if err != nil {")
	w.line(`fmt.Fprintf(os.Stderr, "cannot open to write: %s\n", modelfile)`)
	w.line("os.Exit(1)")
	w.close("")
	w.line("defer f.Close()")
	w.close("")
}

func (g *Generator) emitSmokeMain(w *goWriter) {
	w.open(fmt.Sprintf("func %s() {", g.Config.MainName))
	w.line("opts, rest := parseIvyTestArgs(os.Args[1:])")
	if len(g.Mod.Params) == 0 {
		g.emitZeroParamArgSetup(w, "rest")
	} else {
		g.emitModuleParamSetup(w, "opts", "rest")
	}
	g.emitRuntimeOptionSetup(w, "opts")
	g.emitUnknownOptionCheck(w)
	w.linef("ivy := new%s(%s)", exportedishName(g.ClassName), strings.Join(g.constructorParamArgNames(), ", "))
	w.line("ivy.__argv = append([]string{os.Args[0]}, rest...)")
	w.line("_ = ivy")
	w.close("")
	w.blank()
}

func (g *Generator) runnableActionNames() []string {
	names := g.publicActionNamesSorted()
	initActions := g.initialMixinActionNames()
	var runnable []string
	for _, name := range names {
		if initActions[name] || isFinalizeName(name) {
			continue
		}
		runnable = append(runnable, name)
	}
	return runnable
}

func (g *Generator) emitTestMain(w *goWriter) {
	runnable := g.runnableActionNames()
	w.open(fmt.Sprintf("func %s() {", g.Config.MainName))
	if len(g.Mod.Params) == 0 {
		w.line("opts, rest := parseIvyTestArgs(os.Args[1:])")
		g.emitZeroParamArgSetup(w, "rest")
	} else {
		w.line("opts, rest := parseIvyTestArgs(os.Args[1:])")
		g.emitModuleParamSetup(w, "opts", "rest")
	}
	w.linef("testIters := ivyAtoiDefault(opts[%q], %s)", "iters", g.Config.TestIters)
	w.linef("runs := ivyAtoiDefault(opts[%q], %s)", "runs", g.Config.TestRuns)
	w.line(`seed := ivyAtoiDefault(opts["seed"], 1)`)
	w.line(`sleepMs := ivyAtoiDefault(opts["delay"], 10)`)
	w.line(`finalMs := ivyAtoiDefault(opts["wait"], 0)`)
	w.line("ivySetSeed(seed)")
	g.emitRuntimeFilesSetup(w, "opts")
	g.emitUnknownOptionCheck(w)
	w.open("for runidx := 0; runidx < runs; runidx++ {")
	w.linef("ivy := new%s(%s)", exportedishName(g.ClassName), strings.Join(g.constructorParamArgNames(), ", "))
	w.line("ivy.__argv = append([]string{os.Args[0]}, rest...)")
	w.line("ivy._generating = false")
	g.emitRandomizedActionCycles(w, runnable, "testIters", "sleepMs")
	g.emitTestMainTail(w, "finalMs")
	w.close("")
	w.close("")
	w.blank()
}

func (g *Generator) emitGenMain(w *goWriter) {
	runnable := g.runnableActionNames()
	g.emitGenInitGeneratorType(w)
	g.emitGenActionGeneratorTypes(w, runnable)
	w.open(fmt.Sprintf("func ivy2golangGenerate(ivy *%s, testIters int, sleepMs int) {", g.ClassName))
	w.linef("init_generator := &%s{ivy: ivy}", g.goInitGeneratorTypeName())
	w.line("_ = init_generator.generate()")
	g.emitGenActionCycles(w, runnable, "testIters", "sleepMs")
	w.close("")
	w.blank()
	w.open(fmt.Sprintf("func %s() {", g.Config.MainName))
	if len(g.Mod.Params) == 0 {
		w.line("opts, rest := parseIvyTestArgs(os.Args[1:])")
		g.emitZeroParamArgSetup(w, "rest")
	} else {
		w.line("opts, rest := parseIvyTestArgs(os.Args[1:])")
		g.emitModuleParamSetup(w, "opts", "rest")
	}
	w.linef("testIters := ivyAtoiDefault(opts[%q], %s)", "iters", g.Config.TestIters)
	w.linef("runs := ivyAtoiDefault(opts[%q], %s)", "runs", g.Config.TestRuns)
	w.line(`seed := ivyAtoiDefault(opts["seed"], 1)`)
	w.line(`sleepMs := ivyAtoiDefault(opts["delay"], 10)`)
	w.line(`finalMs := ivyAtoiDefault(opts["wait"], 0)`)
	w.line("ivySetSeed(seed)")
	g.emitRuntimeFilesSetup(w, "opts")
	g.emitUnknownOptionCheck(w)
	w.open("for runidx := 0; runidx < runs; runidx++ {")
	w.linef("ivy := new%s(%s)", exportedishName(g.ClassName), strings.Join(g.constructorParamArgNames(), ", "))
	w.line("ivy.__argv = append([]string{os.Args[0]}, rest...)")
	w.line("ivy._generating = false")
	w.line("ivy2golangGenerate(ivy, testIters, sleepMs)")
	g.emitTestMainTail(w, "finalMs")
	w.close("")
	w.close("")
	w.blank()
}

func (g *Generator) emitGenInitGeneratorType(w *goWriter) {
	typeName := g.goInitGeneratorTypeName()
	w.open(fmt.Sprintf("type %s struct {", typeName))
	w.linef("ivy *%s", g.ClassName)
	w.close("")
	w.blank()
	w.open(fmt.Sprintf("func (gen *%s) generate() bool {", typeName))
	w.line("_ = gen.ivy")
	w.line("return true")
	w.close("")
	w.blank()
	w.open(fmt.Sprintf("func (gen *%s) execute() {", typeName))
	w.line("_ = gen.ivy")
	w.close("")
	w.blank()
}

func (g *Generator) emitGenActionGeneratorTypes(w *goWriter, runnable []string) {
	for _, name := range runnable {
		act, _ := g.Mod.Actions.Get2(name)
		typeName := g.goActionGeneratorTypeName(name)
		w.open(fmt.Sprintf("type %s struct {", typeName))
		w.linef("ivy *%s", g.ClassName)
		if act != nil {
			for _, p := range act.GetFormalParams() {
				w.linef("%s %s", goName(p.Name), g.goType(p.CSort))
			}
		}
		w.close("")
		w.blank()
		w.open(fmt.Sprintf("func (gen *%s) generate() bool {", typeName))
		g.emitGenActionGeneratorGenerate(w, name, act)
		w.close("")
		w.blank()
		w.open(fmt.Sprintf("func (gen *%s) execute() {", typeName))
		g.emitGenActionGeneratorExecute(w, name, act)
		w.close("")
		w.blank()
	}
}

func (g *Generator) emitGenActionGeneratorGenerate(w *goWriter, name string, act goivy.Action) {
	w.line("ivy := gen.ivy")
	if act == nil {
		w.line("_ = ivy")
		w.line("return true")
		return
	}
	g.emitGenActionGeneratorRandomizeState(w)
	if len(act.GetFormalParams()) == 0 {
		w.line("_ = ivy")
		g.emitGenActionGeneratorAssumeGuards(w, name, act)
		w.line("return true")
		return
	}
	for i, p := range act.GetFormalParams() {
		expr, err := g.goActionParamRandomValueExpr(p.CSort, actionFormalGeneratorLabel(p), int64(i))
		if err != nil {
			g.unsupported(w, "unsupported action generator parameter: %s", err.Error())
			continue
		}
		w.linef("gen.%s = %s", goName(p.Name), expr)
	}
	g.emitGenActionGeneratorDefinedInputs(w, name, act)
	g.emitGenActionGeneratorAssumeGuards(w, name, act)
	w.line("return true")
}

func (g *Generator) emitGenActionGeneratorRandomizeState(w *goWriter) {
	for _, sym := range g.stateSymbols() {
		if g.isParamName(sym.Name) {
			continue
		}
		g.emitGenRandomizeSymbol(w, sym, "randomize")
	}
}

func (g *Generator) emitGenRandomizeSymbol(w *goWriter, sym stateSymbol, label string) {
	if g.isVariantSuperName(sortName(sym.Sort)) {
		w.linef("ivy.%s = %s", goName(sym.Name), g.goZeroValue(sym.Sort))
		return
	}
	if fs, ok := sym.Sort.(*goivy.LogicFunctionSort); ok && len(fs.Domain()) > 0 {
		if !g.canEnumerateDomain(fs.Domain()) {
			base := "ivy." + goName(sym.Name)
			w.linef("%s = %s", base, g.goFunctionStorageInit(fs.Domain(), fs.Range()))
			g.emitNondetThunkBase(w, base, fs.Domain(), fs.Range(), label, 0)
			return
		}
		g.emitDomainLoops(w, fs.Domain(), func(args []string) {
			expr, err := g.goActionParamRandomValueExpr(fs.Range(), label+"."+sym.Name, int64(len(args)))
			if err != nil {
				g.unsupported(w, "%s", err.Error())
				return
			}
			w.linef("%s = %s", g.goStorageAccess(sym.Name, sym.Sort, args, "ivy"), expr)
		})
		return
	}
	expr, err := g.goActionParamRandomValueExpr(sym.Sort, label+"."+sym.Name, 0)
	if err != nil {
		g.unsupported(w, "%s", err.Error())
		return
	}
	w.linef("ivy.%s = %s", goName(sym.Name), expr)
}

type genDefinedInput struct {
	param *goivy.Const
	value goivy.Expr
}

func (g *Generator) emitGenActionGeneratorDefinedInputs(w *goWriter, name string, act goivy.Action) {
	defs := genActionGeneratorDefinedInputs(act, g.genActionPreconditionFormulas(name, act))
	if len(defs) == 0 {
		return
	}
	g.pushExprOverrides(genActionFormalExprOverrides(act))
	defer g.popExprOverrides()
	for _, def := range defs {
		expr, err := g.emitExpr(def.value)
		if err != nil {
			g.unsupported(w, "unsupported action generator defined input: %s", err.Error())
			continue
		}
		w.linef("gen.%s = %s", goName(def.param.Name), expr)
	}
}

func genActionGeneratorDefinedInputs(act goivy.Action, guards []goivy.Expr) []genDefinedInput {
	params := genActionFormalParamMap(act)
	if len(params) == 0 {
		return nil
	}
	var defs []genDefinedInput
	for _, guard := range guards {
		eq, ok := guard.(*goivy.Eq)
		if !ok {
			continue
		}
		if p, ok := genExprFormalParam(eq.T1, params); ok {
			defs = append(defs, genDefinedInput{param: p, value: eq.T2})
			continue
		}
		if p, ok := genExprFormalParam(eq.T2, params); ok {
			defs = append(defs, genDefinedInput{param: p, value: eq.T1})
		}
	}
	return defs
}

func genActionFormalParamMap(act goivy.Action) map[string]*goivy.Const {
	params := map[string]*goivy.Const{}
	if act == nil {
		return params
	}
	for _, p := range act.GetFormalParams() {
		if p == nil {
			continue
		}
		for _, name := range formalExprOverrideNames(p.Name) {
			params[name] = p
		}
	}
	return params
}

func genExprFormalParam(e goivy.Expr, params map[string]*goivy.Const) (*goivy.Const, bool) {
	c, ok := e.(*goivy.Const)
	if !ok || c == nil {
		return nil, false
	}
	p, ok := params[c.Name]
	return p, ok
}

func genActionFormalExprOverrides(act goivy.Action) map[string]string {
	overrides := map[string]string{}
	if act == nil {
		return overrides
	}
	for _, p := range act.GetFormalParams() {
		if p == nil {
			continue
		}
		field := "gen." + goName(p.Name)
		for _, name := range formalExprOverrideNames(p.Name) {
			overrides[name] = field
		}
	}
	return overrides
}

func (g *Generator) emitGenActionGeneratorAssumeGuards(w *goWriter, name string, act goivy.Action) {
	guards := g.genActionPreconditionFormulas(name, act)
	if len(guards) == 0 {
		return
	}
	g.pushExprOverrides(genActionFormalExprOverrides(act))
	defer g.popExprOverrides()
	for _, guard := range guards {
		expr, err := g.emitExpr(goivy.CloseFormula(guard))
		if err != nil {
			g.unsupported(w, "unsupported action generator assume guard: %s", err.Error())
			continue
		}
		w.open(fmt.Sprintf("if !(%s) {", expr))
		w.line("return false")
		w.close("")
	}
}

func (g *Generator) genActionPreconditionFormulas(name string, act goivy.Action) []goivy.Expr {
	var guards []goivy.Expr
	if g != nil && g.Mod != nil && g.Mod.ExtPreconds != nil {
		if pre := g.Mod.ExtPreconds[name]; pre != nil {
			guards = append(guards, pre)
		}
	}
	guards = append(guards, leadingAssumeFormulas(act)...)
	return guards
}

func leadingAssumeFormulas(act goivy.Action) []goivy.Expr {
	switch a := act.(type) {
	case *goivy.LogicAssumeAction:
		if a.Formula == nil {
			return nil
		}
		return []goivy.Expr{a.Formula}
	case *goivy.LogicSequence:
		var guards []goivy.Expr
		for _, elem := range a.Elems {
			assume, ok := elem.(*goivy.LogicAssumeAction)
			if !ok {
				break
			}
			if assume.Formula != nil {
				guards = append(guards, assume.Formula)
			}
		}
		return guards
	default:
		return nil
	}
}

func formalExprOverrideNames(name string) []string {
	base := name
	switch {
	case strings.HasPrefix(name, "__fml:"):
		base = strings.TrimPrefix(name, "__fml:")
	case strings.HasPrefix(name, "fml:"):
		base = strings.TrimPrefix(name, "fml:")
	}
	candidates := []string{name, base, "fml:" + base, "__fml:" + base}
	names := make([]string, 0, len(candidates))
	seen := map[string]bool{}
	for _, candidate := range candidates {
		if seen[candidate] {
			continue
		}
		seen[candidate] = true
		names = append(names, candidate)
	}
	return names
}

func actionFormalGeneratorLabel(p *goivy.Const) string {
	if p == nil {
		return "__fml:"
	}
	name := p.Name
	switch {
	case strings.HasPrefix(name, "__fml:"):
		return name
	case strings.HasPrefix(name, "fml:"):
		return "__" + name
	default:
		return "__fml:" + name
	}
}

func (g *Generator) emitGenActionGeneratorExecute(w *goWriter, name string, act goivy.Action) {
	w.line("ivy := gen.ivy")
	if act == nil {
		w.line("_ = ivy")
		return
	}
	args := make([]string, 0, len(act.GetFormalParams()))
	for _, p := range act.GetFormalParams() {
		args = append(args, "gen."+goName(p.Name))
	}
	fn, err := funName(name)
	if err != nil {
		fn = goName(name)
		g.errs = append(g.errs, err)
	}
	call := fmt.Sprintf("ivy.%s(%s)", fn, strings.Join(args, ", "))
	w.line(g.actionTraceLine(name, args))
	if g.Config.Trace {
		w.line(`fmt.Fprintln(__ivy_out, "{")`)
	}
	w.line("ivy._generating = true")
	if g.isTestImportCallback(name) {
		switch nret := len(act.GetFormalReturns()); nret {
		case 0:
		case 1:
			w.linef("fmt.Fprintf(__ivy_out, %q, %s)", "= %v\n", g.goZeroValue(act.GetFormalReturns()[0].CSort))
		default:
			lhs := strings.TrimSuffix(strings.Repeat("_, ", nret), ", ")
			rhs := make([]string, nret)
			for i := range rhs {
				rhs[i] = "0"
			}
			w.line(lhs + " = " + strings.Join(rhs, ", "))
		}
		w.line("ivy._generating = false")
		w.line("return")
		return
	}
	switch nret := len(act.GetFormalReturns()); nret {
	case 0:
		w.line(call)
		if g.Config.Trace {
			w.line(`fmt.Fprintln(__ivy_out, "}")`)
		}
	case 1:
		if g.Config.Trace {
			w.linef("__res := %s", call)
			w.line(`fmt.Fprintln(__ivy_out, "}")`)
			w.linef("fmt.Fprintf(__ivy_out, %q, __res)", "= %v\n")
		} else {
			w.linef("fmt.Fprintf(__ivy_out, %q, %s)", "= %v\n", call)
		}
	default:
		w.line(strings.TrimSuffix(strings.Repeat("_, ", nret), ", ") + " = " + call)
		if g.Config.Trace {
			w.line(`fmt.Fprintln(__ivy_out, "}")`)
		}
	}
	w.line("ivy._generating = false")
}

func (g *Generator) emitGenActionCycles(w *goWriter, runnable []string, testItersName, sleepMsName string) {
	if len(runnable) == 0 {
		w.line("_ = ivy")
		w.linef("_ = %s", testItersName)
		w.linef("_ = %s", sleepMsName)
		return
	}
	for _, name := range runnable {
		w.linef("%s := &%s{ivy: ivy}", g.goActionGeneratorVarName(name), g.goActionGeneratorTypeName(name))
	}
	w.open(fmt.Sprintf("for cycle := 0; cycle < %s; cycle++ {", testItersName))
	totalWeight := 0.0
	for _, name := range runnable {
		totalWeight += g.actionWeight(name)
	}
	w.linef("__choices := %s + 5.0", goFloatLiteral(totalWeight))
	w.line("__choice := float64(ivyRand31()) * __choices / 2147483648.0")
	w.open(fmt.Sprintf("if __choice >= %s {", goFloatLiteral(totalWeight)))
	w.line("cycle--")
	w.line("continue")
	w.close("")
	cumulative := 0.0
	for i, name := range runnable {
		genVar := g.goActionGeneratorVarName(name)
		cumulative += g.actionWeight(name)
		if i == 0 {
			w.open(fmt.Sprintf("if __choice < %s {", goFloatLiteral(cumulative)))
		} else {
			w.close(fmt.Sprintf(" else if __choice < %s {", goFloatLiteral(cumulative)))
			w.indent++
		}
		w.line("ivy._generating = true")
		w.open(fmt.Sprintf("if %s.generate() {", genVar))
		w.linef("%s.execute()", genVar)
		w.line("ivy._generating = false")
		w.close(" else {")
		w.indent++
		w.line("ivy._generating = false")
		w.line("cycle--")
		w.line("continue")
		w.indent--
		w.close("")
	}
	w.close("")
	w.line("ivy.__tick(0)")
	w.open(fmt.Sprintf("if %s > 0 {", sleepMsName))
	w.linef("time.Sleep(time.Duration(%s) * time.Millisecond)", sleepMsName)
	w.close("")
	w.close("")
}

func (g *Generator) goInitGeneratorTypeName() string {
	return exportedishName(g.ClassName) + "_init_gen"
}

func (g *Generator) goActionGeneratorTypeName(name string) string {
	display := strings.TrimPrefix(name, "ext:")
	return exportedishName(g.ClassName) + "_" + goName(display) + "_generator"
}

func (g *Generator) goActionGeneratorVarName(name string) string {
	display := strings.TrimPrefix(name, "ext:")
	return goName(display) + "_generator"
}

func (g *Generator) emitRandomizedActionCycles(w *goWriter, runnable []string, testItersName, sleepMsName string) {
	if len(runnable) == 0 {
		w.line("_ = ivy")
		w.linef("_ = %s", testItersName)
		w.linef("_ = %s", sleepMsName)
	} else {
		w.open(fmt.Sprintf("for cycle := 0; cycle < %s; cycle++ {", testItersName))
		totalWeight := 0.0
		for _, name := range runnable {
			totalWeight += g.actionWeight(name)
		}
		w.linef("__choices := %s + 5.0", goFloatLiteral(totalWeight))
		w.line("__choice := float64(ivyRand31()) * __choices / 2147483648.0")
		w.open(fmt.Sprintf("if __choice >= %s {", goFloatLiteral(totalWeight)))
		w.line("cycle--")
		w.line("continue")
		w.close("")
		cumulative := 0.0
		for i, name := range runnable {
			fn, err := funName(name)
			if err != nil {
				fn = goName(name)
				g.errs = append(g.errs, err)
			}
			act, _ := g.Mod.Actions.Get2(name)
			cumulative += g.actionWeight(name)
			argExprs := g.randomActualArgs(name, act)
			if i == 0 {
				w.open(fmt.Sprintf("if __choice < %s {", goFloatLiteral(cumulative)))
			} else {
				w.close(fmt.Sprintf(" else if __choice < %s {", goFloatLiteral(cumulative)))
				w.indent++
			}
			args := argExprs
			if len(argExprs) > 0 {
				args = make([]string, len(argExprs))
				for i, arg := range argExprs {
					args[i] = fmt.Sprintf("__arg%d", i)
					w.linef("%s := %s", args[i], arg)
				}
			}
			call := fmt.Sprintf("ivy.%s(%s)", fn, strings.Join(args, ", "))
			trace := g.actionTraceLine(name, args)
			w.line(trace)
			w.line("ivy._generating = true")
			if g.isTestImportCallback(name) {
				switch nret := len(act.GetFormalReturns()); nret {
				case 0:
				case 1:
					w.linef("fmt.Fprintf(__ivy_out, %q, %s)", "= %v\n", g.goZeroValue(act.GetFormalReturns()[0].CSort))
				default:
					lhs := strings.TrimSuffix(strings.Repeat("_, ", nret), ", ")
					rhs := make([]string, nret)
					for i := range rhs {
						rhs[i] = "0"
					}
					w.line(lhs + " = " + strings.Join(rhs, ", "))
				}
				w.line("ivy._generating = false")
				continue
			}
			switch nret := len(act.GetFormalReturns()); nret {
			case 0:
				w.line(call)
			case 1:
				w.linef("fmt.Fprintf(__ivy_out, %q, %s)", "= %v\n", call)
			default:
				w.line(strings.TrimSuffix(strings.Repeat("_, ", nret), ", ") + " = " + call)
			}
			w.line("ivy._generating = false")
		}
		w.close("")
		w.line("ivy.__tick(0)")
		w.open(fmt.Sprintf("if %s > 0 {", sleepMsName))
		w.linef("time.Sleep(time.Duration(%s) * time.Millisecond)", sleepMsName)
		w.close("")
		w.close("")
	}
}

func (g *Generator) emitTestMainTail(w *goWriter, finalMsName string) {
	if g.hasFinalizeExport() {
		if fn, err := funName("ext:_finalize"); err == nil {
			w.linef("ivy.%s()", fn)
		}
	}
	w.open(fmt.Sprintf("if %s > 0 {", finalMsName))
	w.linef("time.Sleep(time.Duration(%s) * time.Millisecond)", finalMsName)
	w.close("")
	w.line(`fmt.Fprintln(__ivy_out, "test_completed")`)
	w.open("if runidx == runs-1 {")
	w.line("time.Sleep(50 * time.Millisecond)")
	w.line("os.Exit(0)")
	w.close("")
}

func (g *Generator) emitMainWrapper(w *goWriter) {
	if g.Config.MainName == "" || g.Config.MainName == "main" {
		return
	}
	w.open("func main() {")
	w.linef("%s()", g.Config.MainName)
	w.close("")
	w.blank()
}

func (g *Generator) randomActualArgs(actionName string, act goivy.Action) []string {
	if act == nil {
		return nil
	}
	formals := act.GetFormalParams()
	args := make([]string, len(formals))
	for i, p := range formals {
		if p == nil {
			continue
		}
		expr, err := g.goActionParamRandomValueExpr(p.CSort, actionName+"."+p.Name, int64(i))
		if err != nil {
			g.errs = append(g.errs, err)
			expr = g.goZeroValue(p.CSort)
		}
		args[i] = expr
	}
	return args
}

func (g *Generator) actionTraceLine(name string, args []string) string {
	display := actionDisplayName(name)
	if len(args) == 0 {
		return fmt.Sprintf("fmt.Fprintln(__ivy_out, %q)", "> "+display)
	}
	format := "> " + display + "(" + strings.TrimSuffix(strings.Repeat("%v,", len(args)), ",") + ")\n"
	return fmt.Sprintf("fmt.Fprintf(__ivy_out, %q, %s)", format, strings.Join(args, ", "))
}

func actionDisplayName(name string) string {
	if idx := strings.LastIndex(name, ":"); idx >= 0 {
		return name[idx+1:]
	}
	return name
}

func goFloatLiteral(f float64) string {
	s := strconv.FormatFloat(f, 'g', -1, 64)
	lower := strings.ToLower(s)
	if strings.Contains(s, ".") || strings.Contains(lower, "e") || strings.Contains(lower, "nan") || strings.Contains(lower, "inf") {
		return s
	}
	return s + ".0"
}

func (g *Generator) publicActionNamesSorted() []string {
	if g.Mod == nil || g.Mod.PublicActions == nil {
		return nil
	}
	var names []string
	for name := range g.Mod.PublicActions.All() {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func (g *Generator) initialMixinActionNames() map[string]bool {
	out := map[string]bool{}
	if g.Mod == nil || g.Mod.Mixins == nil {
		return out
	}
	for _, mixin := range g.Mod.Mixins.Get("init") {
		out[mixin.Mixer()] = true
	}
	return out
}

func isFinalizeName(name string) bool {
	return name == "ext:_finalize"
}

func (g *Generator) hasFinalizeExport() bool {
	if g.Mod == nil || g.Mod.PublicActions == nil {
		return false
	}
	for name := range g.Mod.PublicActions.All() {
		if isFinalizeName(name) {
			return true
		}
	}
	return false
}

func (g *Generator) actionWeight(name string) float64 {
	username := strings.TrimPrefix(name, "ext:")
	if g.Mod == nil || g.Mod.Attributes == nil {
		return 1.0
	}
	raw, ok := g.Mod.Attributes.Get2(username + ".weight")
	if !ok {
		return 1.0
	}
	type relnamer interface{ Relname() string }
	var s string
	switch v := raw.(type) {
	case string:
		s = v
	case relnamer:
		s = v.Relname()
	default:
		return 1.0
	}
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		s = s[1 : len(s)-1]
	}
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return 1.0
	}
	return f
}

func (g *Generator) nextTemp(prefix string) string {
	id := g.tempID
	g.tempID++
	return fmt.Sprintf("%s%d", prefix, id)
}

func (g *Generator) allStateSymbols() []stateSymbol {
	if g == nil || g.Mod == nil {
		return nil
	}
	seen := map[string]bool{}
	var out []stateSymbol
	add := func(name string, s goivy.Sort) {
		if name == "" || seen[name] {
			return
		}
		if g.Mod.Sig != nil && g.Mod.Sig.Constructors[name] {
			return
		}
		if g.isDefinitionName(name) {
			return
		}
		if g.isDestructorName(name) {
			return
		}
		if g.isSortConstructorName(name) {
			return
		}
		seen[name] = true
		out = append(out, stateSymbol{Name: name, Sort: s})
	}
	if g.Mod.Sig != nil {
		for _, sym := range g.Mod.SymbolOrder {
			if sym == nil {
				continue
			}
			name := sym.Name
			if name == "" || seen[name] {
				continue
			}
			if !g.sigHasExactSymbol(name, sym.CSort) {
				continue
			}
			if g.Mod.Sig.Constructors[name] || g.isDestructorName(name) || g.isSortConstructorName(name) {
				continue
			}
			if g.isDefinitionName(name) {
				continue
			}
			n, err := goivy.SolverName(sym, g.Mod.Sig, nil)
			if err == nil && n == "" {
				continue
			}
			add(name, sym.CSort)
		}
		for _, sym := range g.Mod.Sig.AllSymbols() {
			name := sym.Name
			if name == "" || seen[name] {
				continue
			}
			if g.Mod.Sig.Constructors[name] || g.isDestructorName(name) || g.isSortConstructorName(name) {
				continue
			}
			if g.isDefinitionName(name) {
				continue
			}
			n, err := goivy.SolverName(sym, g.Mod.Sig, nil)
			if err == nil && n == "" {
				continue
			}
			add(name, sym.CSort)
		}
	}
	return out
}

func (g *Generator) stateSymbols() []stateSymbol {
	var out []stateSymbol
	seen := map[string]bool{}
	add := func(name string, s goivy.Sort) {
		if name == "" || seen[name] {
			return
		}
		if g.Mod.Sig != nil && g.Mod.Sig.Constructors[name] {
			return
		}
		if g.isDestructorName(name) {
			return
		}
		if g.isSortConstructorName(name) {
			return
		}
		seen[name] = true
		out = append(out, stateSymbol{Name: name, Sort: s})
	}
	for _, sym := range g.allStateSymbols() {
		add(sym.Name, sym.Sort)
	}
	return out
}

func (g *Generator) sigHasExactSymbol(name string, sort goivy.Sort) bool {
	if g == nil || g.Mod == nil || g.Mod.Sig == nil || name == "" {
		return false
	}
	entry, ok := g.Mod.Sig.Symbols.Get2(name)
	if !ok || entry == nil {
		return false
	}
	if entry.Union != nil {
		for _, s := range entry.Union.Sorts {
			if goivy.SortEqual(s, sort) {
				return true
			}
		}
		return false
	}
	return goivy.SortEqual(entry.Sort, sort)
}

func (g *Generator) isSortConstructorName(name string) bool {
	if g == nil || g.Mod == nil || name == "" {
		return false
	}
	if g.Mod.ConstructorSorts != nil {
		if _, ok := g.Mod.ConstructorSorts[name]; ok {
			return true
		}
	}
	if g.Mod.SortConstructors != nil {
		for _, conss := range g.Mod.SortConstructors.All() {
			for _, cons := range conss {
				if cons != nil && cons.Name == name {
					return true
				}
			}
		}
	}
	return false
}

func (g *Generator) isDestructorName(name string) bool {
	if g == nil || g.Mod == nil || name == "" || g.Mod.DestructorSorts == nil {
		return false
	}
	_, ok := g.Mod.DestructorSorts[name]
	return ok
}

func (g *Generator) isStateSymbolName(name string) (goivy.Sort, bool) {
	for _, sym := range g.stateSymbols() {
		if sym.Name == name {
			return sym.Sort, true
		}
	}
	return nil, false
}

func (g *Generator) isParamName(name string) bool {
	if g == nil || g.Mod == nil {
		return false
	}
	for _, p := range g.Mod.Params {
		if p != nil && p.Name == name {
			return true
		}
	}
	return false
}

func (g *Generator) pushScope() {
	g.locals = append(g.locals, map[string]goivy.Sort{})
}

func (g *Generator) popScope() {
	if len(g.locals) > 0 {
		g.locals = g.locals[:len(g.locals)-1]
	}
}

func (g *Generator) addLocal(name string) {
	g.addLocalSort(name, nil)
}

func (g *Generator) addLocalSort(name string, sort goivy.Sort) {
	if len(g.locals) == 0 {
		g.pushScope()
	}
	g.locals[len(g.locals)-1][name] = sort
}

func (g *Generator) isLocal(name string) bool {
	_, ok := g.localSort(name)
	return ok
}

func (g *Generator) localSort(name string) (goivy.Sort, bool) {
	for i := len(g.locals) - 1; i >= 0; i-- {
		if sort, ok := g.locals[i][name]; ok {
			return sort, true
		}
	}
	return nil, false
}

func (g *Generator) pushExprOverrides(overrides map[string]string) {
	g.exprOverrides = append(g.exprOverrides, overrides)
}

func (g *Generator) popExprOverrides() {
	if len(g.exprOverrides) > 0 {
		g.exprOverrides = g.exprOverrides[:len(g.exprOverrides)-1]
	}
}

func (g *Generator) exprOverride(name string) (string, bool) {
	if g == nil {
		return "", false
	}
	for i := len(g.exprOverrides) - 1; i >= 0; i-- {
		if code, ok := g.exprOverrides[i][name]; ok {
			return code, true
		}
	}
	return "", false
}

func (g *Generator) unsupported(w *goWriter, format string, args ...any) {
	err := fmt.Errorf("ivy2golang: "+format, args...)
	g.errs = append(g.errs, err)
	w.linef("panic(%q)", err.Error())
}

func (g *Generator) warnOnce(message string) {
	if g.warningSet == nil {
		g.warningSet = map[string]bool{}
	}
	if g.warningSet[message] {
		return
	}
	g.warningSet[message] = true
	g.warnings = append(g.warnings, message)
}

func linenoStr(loc goivy.Location) string {
	for loc.Reference != nil {
		loc = *loc.Reference
	}
	label := ""
	if loc.Filename != "" {
		label += filepath.Base(loc.Filename) + ": "
	}
	if loc.Line > 0 {
		label += fmt.Sprintf("line %d: ", loc.Line)
	}
	return strings.TrimSuffix(label, ": ")
}
