import { blake3HashString } from "../blake3.js";
import {
  generatedMixedWasmArtifactSource,
  GOJR_GOARCH,
  GOJR_GOOS,
  type GoJuniorPackageExportData
} from "../build.js";
import { checkedInWasmStencil } from "./stencils.js";

export interface MixedWasmArtifactFixture {
  pkgdef: GoJuniorPackageExportData;
  javascript: string;
  wasmBase64: string;
  artifactSource: string;
}

export function createMixedWasmArtifactFixture(): MixedWasmArtifactFixture {
  const stencil = checkedInWasmStencil("f64.slice.sum.kernel");
  const sourceHash = blake3HashString(stencil.cSource);
  const pkgdef: GoJuniorPackageExportData = {
    exportFormat: "gojr-iexport",
    exportVersion: 1,
    exportIndex: {
      SumF64: {
        exportIndex: 0,
        kind: "func",
        typeText: "func(ptr int, n int) float64"
      }
    },
    layoutVersion: "gojr-js-v5-mixed-fixture",
    compilerVersion: "gojr-mixed-fixture",
    backend: "copy-patch-wasm-fixture",
    hostSpecVersion: "host-v0",
    capabilityPolicy: "default",
    goos: GOJR_GOOS,
    goarch: GOJR_GOARCH,
    buildTags: [GOJR_GOARCH, GOJR_GOOS].sort(),
    standardLibrary: false,
    importPath: "example.com/gojr/mixedwasm",
    packageName: "mixedwasm",
    sourceHash,
    cacheKey: blake3HashString([
      "mixed-wasm-fixture",
      sourceHash,
      stencil.name,
      stencil.wasmBase64
    ].join("\0")),
    dependencies: [],
    dependencyCacheKeys: [],
    exports: [{
      name: "SumF64",
      kind: "func",
      typeText: "func(ptr int, n int) float64"
    }],
    sources: [{
      filename: "gojr:stencil/f64.slice.sum.kernel.c",
      hash: sourceHash
    }]
  };
  const javascript = mixedWasmFixtureJavaScript(pkgdef);
  return {
    pkgdef,
    javascript,
    wasmBase64: stencil.wasmBase64,
    artifactSource: generatedMixedWasmArtifactSource(pkgdef, javascript, stencil.wasmBase64)
  };
}

export function createChunkedMixedWasmArtifactFixture(): MixedWasmArtifactFixture {
  const stencil = checkedInWasmStencil("f64.slice.sum.chunk.kernel");
  const sourceHash = blake3HashString(stencil.cSource);
  const pkgdef: GoJuniorPackageExportData = {
    exportFormat: "gojr-iexport",
    exportVersion: 1,
    exportIndex: {
      SumF64Chunked: {
        exportIndex: 0,
        kind: "func",
        typeText: "func(ptr int, n int, fuel int) float64"
      }
    },
    layoutVersion: "gojr-js-v5-mixed-fixture",
    compilerVersion: "gojr-mixed-fixture",
    backend: "copy-patch-wasm-fixture",
    hostSpecVersion: "host-v0",
    capabilityPolicy: "default",
    goos: GOJR_GOOS,
    goarch: GOJR_GOARCH,
    buildTags: [GOJR_GOARCH, GOJR_GOOS].sort(),
    standardLibrary: false,
    importPath: "example.com/gojr/chunkedwasm",
    packageName: "chunkedwasm",
    sourceHash,
    cacheKey: blake3HashString([
      "chunked-mixed-wasm-fixture",
      sourceHash,
      stencil.name,
      stencil.wasmBase64
    ].join("\0")),
    dependencies: [],
    dependencyCacheKeys: [],
    exports: [{
      name: "SumF64Chunked",
      kind: "func",
      typeText: "func(ptr int, n int, fuel int) float64"
    }],
    sources: [{
      filename: "gojr:stencil/f64.slice.sum.chunk.kernel.c",
      hash: sourceHash
    }]
  };
  const javascript = chunkedMixedWasmFixtureJavaScript(pkgdef);
  return {
    pkgdef,
    javascript,
    wasmBase64: stencil.wasmBase64,
    artifactSource: generatedMixedWasmArtifactSource(pkgdef, javascript, stencil.wasmBase64)
  };
}

function mixedWasmFixtureJavaScript(pkgdef: GoJuniorPackageExportData): string {
  return [
    "// Code generated by gojr mixed Wasm fixture; DO NOT EDIT.",
    "// This module intentionally receives _gojr.wasm bytes from the package archive.",
    `export const gojrPackageArtifact = ${JSON.stringify(pkgdef, null, 2)};`,
    "export async function instantiateGoJrPackage(runtime = {}, options = {}) {",
    "  const wasmBase64 = options.wasmBase64 || runtime.wasmBase64;",
    "  if (typeof wasmBase64 !== \"string\" || wasmBase64.length === 0) {",
    "    throw new Error(\"gojr mixed Wasm fixture requires options.wasmBase64 from _gojr.wasm\");",
    "  }",
    "  const memory = options.memory || new WebAssembly.Memory({ initial: 2 });",
    "  const bytes = __gojrDecodeBase64(wasmBase64);",
    "  const module = new WebAssembly.Module(bytes);",
    "  const instance = new WebAssembly.Instance(module, { env: { memory } });",
    "  const sum = instance.exports.sum_f64;",
    "  if (typeof sum !== \"function\") throw new Error(\"sum_f64 Wasm export is missing\");",
    "  const pkg = {",
    "    SumF64(ptr, n) { return sum(ptr, n); }",
    "  };",
    "  return {",
    "    diagnostics: [],",
    "    output: [],",
    "    package: pkg,",
    "    wasm: instance,",
    "    memory",
    "  };",
    "}",
    "function __gojrDecodeBase64(base64) {",
    "  if (typeof Buffer !== \"undefined\") return new Uint8Array(Buffer.from(base64, \"base64\"));",
    "  const binary = atob(base64);",
    "  const out = new Uint8Array(binary.length);",
    "  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);",
    "  return out;",
    "}",
    "export default { artifact: gojrPackageArtifact, instantiateGoJrPackage };",
    ""
  ].join("\n");
}

function chunkedMixedWasmFixtureJavaScript(pkgdef: GoJuniorPackageExportData): string {
  return [
    "// Code generated by gojr chunked mixed Wasm fixture; DO NOT EDIT.",
    "// This module intentionally receives _gojr.wasm bytes from the package archive.",
    `export const gojrPackageArtifact = ${JSON.stringify(pkgdef, null, 2)};`,
    "export async function instantiateGoJrPackage(runtime = {}, options = {}) {",
    "  const wasmBase64 = options.wasmBase64 || runtime.wasmBase64;",
    "  if (typeof wasmBase64 !== \"string\" || wasmBase64.length === 0) {",
    "    throw new Error(\"gojr chunked Wasm fixture requires options.wasmBase64 from _gojr.wasm\");",
    "  }",
    "  const memory = options.memory || new WebAssembly.Memory({ initial: 2 });",
    "  const bytes = __gojrDecodeBase64(wasmBase64);",
    "  const module = new WebAssembly.Module(bytes);",
    "  const instance = new WebAssembly.Instance(module, { env: { memory } });",
    "  const chunk = instance.exports.sum_f64_chunk;",
    "  if (typeof chunk !== \"function\") throw new Error(\"sum_f64_chunk Wasm export is missing\");",
    "  const statePtr = 0;",
    "  const stateSumOffset = 8;",
    "  const view = () => new DataView(memory.buffer);",
    "  const pkg = {",
    "    async SumF64Chunked(ptr, n, fuel) {",
    "      const stateView = view();",
    "      stateView.setInt32(statePtr, 0, true);",
    "      stateView.setFloat64(statePtr + stateSumOffset, 0, true);",
    "      let done = 0;",
    "      while (done === 0) {",
    "        done = chunk(statePtr, ptr, n, fuel);",
    "        await Promise.resolve();",
    "      }",
    "      return view().getFloat64(statePtr + stateSumOffset, true);",
    "    }",
    "  };",
    "  return {",
    "    diagnostics: [],",
    "    output: [],",
    "    package: pkg,",
    "    wasm: instance,",
    "    memory",
    "  };",
    "}",
    "function __gojrDecodeBase64(base64) {",
    "  if (typeof Buffer !== \"undefined\") return new Uint8Array(Buffer.from(base64, \"base64\"));",
    "  const binary = atob(base64);",
    "  const out = new Uint8Array(binary.length);",
    "  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);",
    "  return out;",
    "}",
    "export default { artifact: gojrPackageArtifact, instantiateGoJrPackage };",
    ""
  ].join("\n");
}
