// Code generated by goyacc -o ev_parser.go -p ev ev_grammar.y. DO NOT EDIT.

//line ev_grammar.y:15
package evparser

import __yyfmt__ "fmt"

//line ev_grammar.y:15

//line ev_grammar.y:18
type evSymType struct {
	yys    int
	events Events
	event  *Event
	dir    EventDir
	values []Value
	value  Value
	dict   *DictValue
	str    string
}

const EV_SYMBOL = 57346
const EV_COMMA = 57347
const EV_LPAREN = 57348
const EV_RPAREN = 57349
const EV_LBR = 57350
const EV_RBR = 57351
const EV_LCB = 57352
const EV_RCB = 57353
const EV_SEMI = 57354
const EV_COLON = 57355
const EV_GT = 57356
const EV_LT = 57357

var evToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"EV_SYMBOL",
	"EV_COMMA",
	"EV_LPAREN",
	"EV_RPAREN",
	"EV_LBR",
	"EV_RBR",
	"EV_LCB",
	"EV_RCB",
	"EV_SEMI",
	"EV_COLON",
	"EV_GT",
	"EV_LT",
}

var evStatenames = [...]string{}

const evEofCode = 1
const evErrCode = 2
const evInitialStackSize = 16

//line ev_grammar.y:162

//line yacctab:1
var evExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	4, 5,
	-2, 1,
}

const evPrivate = 57344

const evLast = 45

var evAct = [...]int8{
	14, 13, 27, 5, 6, 5, 6, 37, 33, 15,
	12, 2, 11, 16, 22, 17, 15, 21, 23, 32,
	16, 28, 17, 29, 18, 31, 26, 9, 20, 20,
	35, 34, 30, 24, 36, 20, 7, 19, 38, 25,
	8, 10, 4, 3, 1,
}

var evPact = [...]int16{
	-1000, -1000, -11, -1000, 32, -1000, -1000, 21, 0, 12,
	-1000, -1000, -1000, 30, -1000, 11, 5, 22, -9, -1000,
	12, 12, -1000, 23, -1000, 14, -5, -1000, -1000, 24,
	-1000, -1000, 26, 12, -1000, -6, -1000, 12, -1000,
}

var evPgo = [...]int8{
	0, 44, 11, 43, 42, 41, 40, 1, 0, 39,
}

var evR1 = [...]int8{
	0, 1, 2, 2, 3, 4, 4, 4, 5, 5,
	5, 6, 6, 8, 8, 8, 8, 8, 8, 7,
	7, 9, 9,
}

var evR2 = [...]int8{
	0, 1, 0, 2, 4, 0, 1, 1, 0, 1,
	3, 0, 3, 1, 4, 2, 3, 2, 3, 1,
	3, 3, 5,
}

var evChk = [...]int16{
	-1000, -1, -2, -3, -4, 14, 15, 4, -6, 6,
	-5, 12, 10, -7, -8, 4, 8, 10, -2, 7,
	5, 6, 9, -7, 11, -9, 4, 11, -8, -7,
	9, 11, 5, 13, 7, 4, -8, 13, -8,
}

var evDef = [...]int8{
	2, -2, -2, 3, 0, 6, 7, 11, 8, 0,
	4, 9, 2, 0, 19, 13, 0, 0, 5, 12,
	0, 0, 15, 0, 17, 0, 0, 10, 20, 0,
	16, 18, 0, 0, 14, 0, 21, 0, 22,
}

var evTok1 = [...]int8{
	1,
}

var evTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15,
}

var evTok3 = [...]int8{
	0,
}

var evErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	evDebug        = 0
	evErrorVerbose = false
)

type evLexer interface {
	Lex(lval *evSymType) int
	Error(s string)
}

type evParser interface {
	Parse(evLexer) int
	Lookahead() int
}

type evParserImpl struct {
	lval  evSymType
	stack [evInitialStackSize]evSymType
	char  int
}

func (p *evParserImpl) Lookahead() int {
	return p.char
}

func evNewParser() evParser {
	return &evParserImpl{}
}

const evFlag = -1000

func evTokname(c int) string {
	if c >= 1 && c-1 < len(evToknames) {
		if evToknames[c-1] != "" {
			return evToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func evStatname(s int) string {
	if s >= 0 && s < len(evStatenames) {
		if evStatenames[s] != "" {
			return evStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func evErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !evErrorVerbose {
		return "syntax error"
	}

	for _, e := range evErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + evTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(evPact[state])
	for tok := TOKSTART; tok-1 < len(evToknames); tok++ {
		if n := base + tok; n >= 0 && n < evLast && int(evChk[int(evAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if evDef[state] == -2 {
		i := 0
		for evExca[i] != -1 || int(evExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; evExca[i] >= 0; i += 2 {
			tok := int(evExca[i])
			if tok < TOKSTART || evExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if evExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += evTokname(tok)
	}
	return res
}

func evlex1(lex evLexer, lval *evSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(evTok1[0])
		goto out
	}
	if char < len(evTok1) {
		token = int(evTok1[char])
		goto out
	}
	if char >= evPrivate {
		if char < evPrivate+len(evTok2) {
			token = int(evTok2[char-evPrivate])
			goto out
		}
	}
	for i := 0; i < len(evTok3); i += 2 {
		token = int(evTok3[i+0])
		if token == char {
			token = int(evTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(evTok2[1]) /* unknown char */
	}
	if evDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", evTokname(token), uint(char))
	}
	return char, token
}

func evParse(evlex evLexer) int {
	return evNewParser().Parse(evlex)
}

func (evrcvr *evParserImpl) Parse(evlex evLexer) int {
	var evn int
	var evVAL evSymType
	var evDollar []evSymType
	_ = evDollar // silence set and not used
	evS := evrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	evstate := 0
	evrcvr.char = -1
	evtoken := -1 // evrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		evstate = -1
		evrcvr.char = -1
		evtoken = -1
	}()
	evp := -1
	goto evstack

ret0:
	return 0

ret1:
	return 1

evstack:
	/* put a state and value onto the stack */
	if evDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", evTokname(evtoken), evStatname(evstate))
	}

	evp++
	if evp >= len(evS) {
		nyys := make([]evSymType, len(evS)*2)
		copy(nyys, evS)
		evS = nyys
	}
	evS[evp] = evVAL
	evS[evp].yys = evstate

evnewstate:
	evn = int(evPact[evstate])
	if evn <= evFlag {
		goto evdefault /* simple state */
	}
	if evrcvr.char < 0 {
		evrcvr.char, evtoken = evlex1(evlex, &evrcvr.lval)
	}
	evn += evtoken
	if evn < 0 || evn >= evLast {
		goto evdefault
	}
	evn = int(evAct[evn])
	if int(evChk[evn]) == evtoken { /* valid shift */
		evrcvr.char = -1
		evtoken = -1
		evVAL = evrcvr.lval
		evstate = evn
		if Errflag > 0 {
			Errflag--
		}
		goto evstack
	}

evdefault:
	/* default state action */
	evn = int(evDef[evstate])
	if evn == -2 {
		if evrcvr.char < 0 {
			evrcvr.char, evtoken = evlex1(evlex, &evrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if evExca[xi+0] == -1 && int(evExca[xi+1]) == evstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			evn = int(evExca[xi+0])
			if evn < 0 || evn == evtoken {
				break
			}
		}
		evn = int(evExca[xi+1])
		if evn < 0 {
			goto ret0
		}
	}
	if evn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			evlex.Error(evErrorMessage(evstate, evtoken))
			Nerrs++
			if evDebug >= 1 {
				__yyfmt__.Printf("%s", evStatname(evstate))
				__yyfmt__.Printf(" saw %s\n", evTokname(evtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for evp >= 0 {
				evn = int(evPact[evS[evp].yys]) + evErrCode
				if evn >= 0 && evn < evLast {
					evstate = int(evAct[evn]) /* simulate a shift of "error" */
					if int(evChk[evstate]) == evErrCode {
						goto evstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if evDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", evS[evp].yys)
				}
				evp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if evDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", evTokname(evtoken))
			}
			if evtoken == evEofCode {
				goto ret1
			}
			evrcvr.char = -1
			evtoken = -1
			goto evnewstate /* try again in the same state */
		}
	}

	/* reduction by production evn */
	if evDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", evn, evStatname(evstate))
	}

	evnt := evn
	evpt := evp
	_ = evpt // guard against "declared and not used"

	evp -= int(evR2[evn])
	// evp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if evp+1 >= len(evS) {
		nyys := make([]evSymType, len(evS)*2)
		copy(nyys, evS)
		evS = nyys
	}
	evVAL = evS[evp+1]

	/* consult goto table to find next state */
	evn = int(evR1[evn])
	evg := int(evPgo[evn])
	evj := evg + evS[evp].yys + 1

	if evj >= evLast {
		evstate = int(evAct[evg])
	} else {
		evstate = int(evAct[evj])
		if int(evChk[evstate]) != -evn {
			evstate = int(evAct[evg])
		}
	}
	// dummy call; replaced with literal code
	switch evnt {

	case 1:
		evDollar = evS[evpt-1 : evpt+1]
//line ev_grammar.y:46
		{
			evlex.(*evLexAdapter).result = evDollar[1].events
		}
	case 2:
		evDollar = evS[evpt-0 : evpt+1]
//line ev_grammar.y:53
		{
			evVAL.events = nil
		}
	case 3:
		evDollar = evS[evpt-2 : evpt+1]
//line ev_grammar.y:57
		{
			evVAL.events = append(evDollar[1].events, evDollar[2].event)
		}
	case 4:
		evDollar = evS[evpt-4 : evpt+1]
//line ev_grammar.y:64
		{
			evVAL.event = &Event{Dir: evDollar[1].dir, Rep: evDollar[2].str, Args: evDollar[3].values, Children: evDollar[4].events}
		}
	case 5:
		evDollar = evS[evpt-0 : evpt+1]
//line ev_grammar.y:71
		{
			evVAL.dir = DirNone
		}
	case 6:
		evDollar = evS[evpt-1 : evpt+1]
//line ev_grammar.y:75
		{
			evVAL.dir = DirIn
		}
	case 7:
		evDollar = evS[evpt-1 : evpt+1]
//line ev_grammar.y:79
		{
			evVAL.dir = DirOut
		}
	case 8:
		evDollar = evS[evpt-0 : evpt+1]
//line ev_grammar.y:86
		{
			evVAL.events = nil
		}
	case 9:
		evDollar = evS[evpt-1 : evpt+1]
//line ev_grammar.y:90
		{
			evVAL.events = nil
		}
	case 10:
		evDollar = evS[evpt-3 : evpt+1]
//line ev_grammar.y:94
		{
			evVAL.events = evDollar[2].events
		}
	case 11:
		evDollar = evS[evpt-0 : evpt+1]
//line ev_grammar.y:101
		{
			evVAL.values = nil
		}
	case 12:
		evDollar = evS[evpt-3 : evpt+1]
//line ev_grammar.y:105
		{
			evVAL.values = evDollar[2].values
		}
	case 13:
		evDollar = evS[evpt-1 : evpt+1]
//line ev_grammar.y:112
		{
			evVAL.value = &Symbol{Name: evDollar[1].str}
		}
	case 14:
		evDollar = evS[evpt-4 : evpt+1]
//line ev_grammar.y:116
		{
			evVAL.value = &App{Rep: evDollar[1].str, Args: evDollar[3].values}
		}
	case 15:
		evDollar = evS[evpt-2 : evpt+1]
//line ev_grammar.y:120
		{
			evVAL.value = &ListValue{}
		}
	case 16:
		evDollar = evS[evpt-3 : evpt+1]
//line ev_grammar.y:124
		{
			evVAL.value = &ListValue{Items: evDollar[2].values}
		}
	case 17:
		evDollar = evS[evpt-2 : evpt+1]
//line ev_grammar.y:128
		{
			evVAL.value = NewDictValue()
		}
	case 18:
		evDollar = evS[evpt-3 : evpt+1]
//line ev_grammar.y:132
		{
			evVAL.value = evDollar[2].dict
		}
	case 19:
		evDollar = evS[evpt-1 : evpt+1]
//line ev_grammar.y:139
		{
			evVAL.values = []Value{evDollar[1].value}
		}
	case 20:
		evDollar = evS[evpt-3 : evpt+1]
//line ev_grammar.y:143
		{
			evVAL.values = append(evDollar[1].values, evDollar[3].value)
		}
	case 21:
		evDollar = evS[evpt-3 : evpt+1]
//line ev_grammar.y:150
		{
			d := NewDictValue()
			d.Set(evDollar[1].str, evDollar[3].value)
			evVAL.dict = d
		}
	case 22:
		evDollar = evS[evpt-5 : evpt+1]
//line ev_grammar.y:156
		{
			evDollar[1].dict.Set(evDollar[3].str, evDollar[5].value)
			evVAL.dict = evDollar[1].dict
		}
	}
	goto evstack /* stack new state and value */
}
