// Package parser provides a full LALR(1) parser for Ivy, generated by
// goyacc, mechanically translated from the Python PLY grammar. It parses
// complete Ivy files (top-level declarations), unlike lalr_logicparser
// which only handles formulas/terms/actions.
package parser

import (
	"fmt"

	"github.com/glycerine/ivy/goivy/ast"
	iu "github.com/glycerine/ivy/goivy/ivyutils"
	"github.com/glycerine/ivy/goivy/xtracer"
)

// ParseResult bundles the declarations returned by the LALR parser.
// This matches the structure of parser.ParseResult so consumers can
// use either parser interchangeably. We define it here to avoid a
// circular import on the parser package.
type ParseResult struct {
	Decls    []ast.Node
	Modules  map[string]*ast.ModuleDecl
	Included map[string]bool
}

// definedEntry matches Python's tuple elements stored in Ivy.defined[name]:
//
//	(lineno, cls)                  — basic definition
//	(lineno, cls, module_defined)  — after set_object_defined enrichment
//
// Python: self.defined = defaultdict(list) mapping name → [(lineno, cls, ...), ...]
type definedEntry struct {
	Lineno        ast.Location
	DeclType      string                    // e.g. "ObjectDecl", "TypeDecl", "DestructorDecl", or ""
	ObjectDefined map[string][]definedEntry // third element: stored module.defined (may be nil)
}

// ivyAccum is the internal accumulator used during LALR parsing.
// It mirrors the Python Ivy class's role as a declaration collector
// during parsing (ivy_parser.py Ivy class). After parsing completes,
// this is converted into a ParseResult.
//
// This is NOT a replacement for module.Module — that is the compiled
// semantic representation. This is just the raw parse-time collector.
//
// ivyAccum implements ast.Node so it can be stored directly as the
// module body in Definition(name, ivyAccum), matching Python where
// the Ivy instance IS the module body RHS.
type ivyAccum struct {
	parent     *ivyAccum // link to enclosing scope; matches Python's global stack
	decls      []ast.Node
	modules    map[string]*ast.ModuleDecl
	macros     map[string]ast.Node
	actions    map[string]ast.Node
	included   map[string]bool
	isModule   bool
	isObject   bool // Python: stack[-1].is_object — set by objectend
	params     []ast.Node
	attributes []string // Python: ivy.attributes — tuple of attribute strings
	static     map[string]bool
	defined    map[string][]definedEntry // Python: defaultdict(list)
	objects    map[string]interface{}    // Python: ivy.objects
	merkle     iu.MerkleState            // rolling Merkle hash of declared AST nodes
	astCfg     *ast.AstConfig            // per-parse AST config (replaces globals)
}

// --- ast.Node interface for ivyAccum ---
// Python's Ivy class IS stored as module body in Definition(name, ivy_instance).
// Ivy.args returns [], Ivy.clone returns self (ivy_parser.py:393-399).

func (m *ivyAccum) Args() []ast.Node { return nil }

func (m *ivyAccum) Clone(args []ast.Node) ast.Node { return m }

func (m *ivyAccum) GetLineno() ast.Location      { return ast.Location{} }
func (m *ivyAccum) SetLineno(loc ast.Location)   {}
func (m *ivyAccum) GetAstConfig() *ast.AstConfig { return nil }

func (m *ivyAccum) String() string {
	return fmt.Sprintf("<ivyAccum decls=%d>", len(m.decls))
}

func (m *ivyAccum) Canon() iu.Canonical {
	// Module body appears as the RHS of a Definition inside ModuleDecl.
	// Emit the decls as a sequence for cross-language canon comparison.
	// Match Sequence.Canon() format: "(sequence%v stmts:[...])"
	return iu.Canonical(fmt.Sprintf("(sequence stmts:%s)", ast.SliceCanon(m.decls)))
}

// Rewrite implements ast.AstRewritable for ivyAccum.
// Matches Python Ivy.rewrite (ivy_parser.py:401-406):
//
//	def rewrite(self, rewrite):
//	    if isinstance(rewrite, AstRewriteSubstPrefix):
//	        res = Ivy()
//	        inst_mod(res, self, None, rewrite.subst, dict())
//	        return res
//	    return self
func (m *ivyAccum) Rewrite(rewrite ast.AstRewriter) ast.Node {
	if sp, ok := rewrite.(*ast.AstRewriteSubstPrefix); ok {
		res := newIvyAccum(m.parent, "")
		instMod(res, m, nil, sp.Subst, nil, "")
		return res
	}
	return m
}

// newIvyAccum creates a fresh accumulator, matching Python Ivy.__init__.
// parent is the enclosing scope (Python: stack[-1]).
// parentObjName is the object name for inheriting defined names (Python: parent_object).
// Pass "" for parentObjName when no object inheritance is needed.
func newIvyAccum(parent *ivyAccum, parentObjName string) *ivyAccum {
	xtracer.Trace("parser.__init__ ENTER")
	m := &ivyAccum{
		modules:  make(map[string]*ast.ModuleDecl),
		macros:   make(map[string]ast.Node),
		actions:  make(map[string]ast.Node),
		included: make(map[string]bool),
		defined:  make(map[string][]definedEntry),
	}
	// Propagate astCfg from parent if available
	if parent != nil && parent.astCfg != nil {
		m.astCfg = parent.astCfg
	}
	// Python: if parent_object is not None:
	//             parent = stack[-1]
	//             if parent_object == "this":
	//                 defined = parent.defined
	//             else:
	//                 defined = parent.get_object_defined(parent_object)
	//             if defined is not None: self.defined = defined
	//             parent_object = None
	if parentObjName != "" && parent != nil {
		if parentObjName == "this" {
			if parent.defined != nil {
				m.defined = parent.defined
			}
		} else {
			inherited := getObjectDefined(parent, parentObjName)
			if inherited != nil {
				m.defined = inherited
			}
		}
	}
	return m
}

// define tracks a name definition, matching Python Ivy.define() (ivy_parser.py:363-378).
//
//	def define(self, df, allow_redef=False):
//	    if len(df) == 3: name, lineno, cls = df
//	    else:            name, lineno = df; cls = None
//	    for x in self.defined[name]:          # auto-vivifies
//	        olineno, ocls = x[0], x[1]
//	        conflict = ...
//	        if conflict:
//	            if allow_redef: return
//	            report_error(Redefining(name, lineno, olineno))
//	    self.defined[name].append((lineno, cls))
func (m *ivyAccum) define(name string, lineno ast.Location, cls string) {
	xtracer.Trace("parser.define ENTER")
	if m.defined == nil {
		m.defined = make(map[string][]definedEntry)
	}
	// Match Python defaultdict auto-vivification: self.defined[name]
	if _, ok := m.defined[name]; !ok {
		m.defined[name] = nil
	}
	// Check for redefinition conflicts
	for _, x := range m.defined[name] {
		conflict := true
		if cls == "TypeDecl" {
			conflict = (x.DeclType != "ObjectDecl")
		} else if cls == "ObjectDecl" {
			conflict = (x.DeclType != "TypeDecl")
		}
		if conflict && x.DeclType != "" {
			// Python: report_error(Redefining(name, lineno, olineno))
			// For now, log but don't error — matches Python's default allow_redef=False
			// but we don't have report_error wired up yet.
			_ = conflict
		}
	}
	m.defined[name] = append(m.defined[name], definedEntry{Lineno: lineno, DeclType: cls})
}

// declare adds a declaration, matching Python Ivy.declare().
// Python iterates decl.defines() and calls self.define(df) for each.
func (m *ivyAccum) declare(decl ast.Node) {
	xtracer.Trace("parser.declare ENTER")
	// Python: decl.attributes = self.attributes + decl.attributes
	if db := ast.GetDeclBase(decl); db != nil && len(m.attributes) > 0 {
		attrNodes := make([]ast.Node, len(m.attributes))
		for i, a := range m.attributes {
			attrNodes[i] = m.astCfg.NewAtom(a)
		}
		db.Attributes = append(attrNodes, db.Attributes...)
	}
	// Python: if "common" in self.attributes and decl.common == None:
	//             decl.common = 'this'
	if hasAttributeStr(m.attributes, "common") {
		if db := ast.GetDeclBase(decl); db != nil {
			if db.Common == nil {
				db.Common = m.astCfg.NewAtom("this")
			}
		}
	}
	// Python: if "common" in decl.attributes:
	//             for df in decl.defines(): self.static.add(df[0])
	if db := ast.GetDeclBase(decl); db != nil {
		if hasAttributeNode(db.Attributes, "common") {
			if definer, ok := decl.(interface{ Defines() []string }); ok {
				for _, name := range definer.Defines() {
					if m.static == nil {
						m.static = make(map[string]bool)
					}
					m.static[name] = true
				}
			}
		}
	}
	// Call define for each name defined by this declaration.
	// Matches Python: for df in decl.defines(): self.define(df)
	// Python defines() returns tuples (name, lineno) or (name, lineno, cls).
	// Go Defines() returns []string (just names). We determine cls from decl type.
	var cls string
	switch decl.(type) {
	case *ast.ObjectDecl:
		cls = "ObjectDecl"
	case *ast.TypeDecl:
		cls = "TypeDecl"
	case *ast.DestructorDecl:
		cls = "DestructorDecl"
	}
	declLineno := decl.GetLineno()
	if definer, ok := decl.(interface{ Defines() []string }); ok {
		for _, name := range definer.Defines() {
			m.define(name, declLineno, cls)
		}
	}
	m.decls = append(m.decls, decl)
	if xtracer.Enabled {
		canonical := decl.Canon()
		leaf, root := m.merkle.AddLeaf(canonical)
		if xtracer.HashVerbose {
			xtracer.Trace("parser.declare HASH leaf=%s root=%s canon=%s", leaf, root, string(canonical))
		} else {
			xtracer.Trace("parser.declare HASH leaf=%s root=%s", leaf, root)
		}
	}
	// Track modules for lookup during instantiation.
	if md, ok := decl.(*ast.ModuleDecl); ok {
		for _, arg := range md.Args() {
			if d, ok := arg.(*ast.Definition); ok {
				if a, ok := d.Lhs.(*ast.Atom); ok {
					m.modules[a.Rep] = md
				}
			}
		}
	}
	if ad, ok := decl.(*ast.ActionDecl); ok {
		for _, arg := range ad.Args() {
			if d, ok := arg.(*ast.ActionDef); ok {
				// Python stores the ActionDef (not ActionDecl) in actions dict.
				// See ivy_parser.py:344-345: d.attributes = decl.attributes; self.actions[d.defines()] = d
				d.Attributes = nodeAttrsToStrings(ad.DeclBase.Attributes)
				if d.Name != nil {
					if a, ok := d.Name.(*ast.Atom); ok {
						m.actions[a.Rep] = d
					}
				}
			}
		}
	}
}

// toResult converts the accumulator into a ParseResult.
func (m *ivyAccum) toResult() *ParseResult {
	return &ParseResult{
		Decls:    m.decls,
		Modules:  m.modules,
		Included: m.included,
	}
}

// hasAttributeStr checks if a string attribute list contains the given attribute.
func hasAttributeStr(attrs []string, name string) bool {
	for _, a := range attrs {
		if a == name {
			return true
		}
	}
	return false
}

// nodeAttrsToStrings converts []Node attributes to []string.
func nodeAttrsToStrings(attrs []ast.Node) []string {
	if len(attrs) == 0 {
		return nil
	}
	result := make([]string, 0, len(attrs))
	for _, a := range attrs {
		if atom, ok := a.(*ast.Atom); ok {
			result = append(result, atom.Rep)
		} else {
			result = append(result, fmt.Sprint(a))
		}
	}
	return result
}

// hasAttributeNode checks if an ast.Node attribute list contains a named attribute.
func hasAttributeNode(attrs []ast.Node, name string) bool {
	for _, a := range attrs {
		if atom, ok := a.(*ast.Atom); ok && atom.Rep == name {
			return true
		}
		if sym, ok := a.(*ast.Symbol); ok && sym.Rep == name {
			return true
		}
	}
	return false
}

// filterCommonAttrs returns only "common" from a string attribute list.
// Python: tuple(x for x in ivy.attributes if x == "common")
func filterCommonAttrs(attrs []string) []string {
	var result []string
	for _, a := range attrs {
		if a == "common" {
			result = append(result, a)
		}
	}
	return result
}

// declHasCommonAttribute checks if a declaration has "common" in its attributes.
func declHasCommonAttribute(decl ast.Node) bool {
	if db := ast.GetDeclBase(decl); db != nil {
		return hasAttributeNode(db.Attributes, "common")
	}
	return false
}
