#lang ivy1.6
################################################################################
#
# A basic version of alternating bit protocol with binary (1-bit)
# sequence number and FIFO channels.
#
# The liveness proof is according to the current version of our methodology:
#
# * all existentially quantified variables come from action parameters
#
# * d is updated automatically by inserting all action parameters
#
# * the index from the negation of the property i0, is assumed to be
#   larger than only a finite set of indices, so all the indices lower
#   than i0 are initially in d_index. this is an alternative to
#   explicitly modeling the loop that puts values in the array.
#
################################################################################
#

################################################################################
#
# Module for axiomatizing a totally ordered set with fixed order
#
# The module includes an le relation, a minimal element (zero) and
# get_succ and get_pred actions.
#
# In this module, the order is arbitrary and fixed.
#
################################################################################

module total_order(carrier) = {
    relation le(X:carrier,Y:carrier)   # less than or equal

    axiom le(X, X)                        # Reflexivity
    axiom le(X, Y) & le(Y, Z) -> le(X, Z) # Transitivity
    axiom le(X, Y) & le(Y, X) -> X = Y    # Anti-symmetry
    axiom le(X, Y) | le(Y, X)             # Totality

    individual zero:carrier
    axiom le(zero, X)

    action get_succ(x:carrier) returns (y:carrier) = {
       assume le(x,y) & x ~= y & ((le(x, Z) & x ~= Z) -> le(y, Z))
    }

    action get_pred(y:carrier) returns (x:carrier) = {
       assume le(x,y) & x ~= y & ((le(x, Z) & x ~= Z) -> le(y, Z))
    }
}

################################################################################
#
# A module for a fifo channel
#
################################################################################

module fifo_channel(m_t) = {
    relation le(X:m_t,Y:m_t)  # partial order representing messages in
                              # the channel - larger messages are
                              # older. le(x,x) means message x is in
                              # the channel

    conjecture le(X, Y) & le(Y, Z) -> le(X, Z)  # Transitivity
    conjecture le(X, Y) & le(Y, X) -> X = Y  # Anti-symmetry
    conjecture le(X, Y) -> le(X, X) & le(Y, Y)  # Partial reflexivity
    conjecture le(X, X) & le(Y, Y) -> le(X, Y) | le(Y, X)  # Partial Totality

    init ~le(X, Y)

    action send(m: m_t) = {
        # insert m as a newest message
        assume ~le(m, m);
        le(m, m) := true;
        le(m, X) := le(X,X)
    }

    action receive returns (m: m_t) = {
        # receive the oldest message and remove it
        assume le(m, m);
        assume le(m,X) -> X = m;
        le(X,m) := false
    }

    action drop(m:m_t) = {
        # drop a message
        le(X,Y) := le(X, Y) & X ~= m & Y ~= m
    }
}

object abp = {

    ################################################################################
    #
    # Types, relations and functions describing state of the network
    #
    ################################################################################

    ################################################################################
    #
    # The protocol itself, together with encoding the fairness
    # constraints and the negation of the liveness property
    #
    # property:      forall I:index_t. F. receiver_array(I) = sender_array(I)
    # ~property:     exists I:index_t. G. receiver_array(I) ~= sender_array(I)
    # Sk(~property): G. receiver_array(i0) ~= sender_array(i0)
    #
    # fairness 1:    scheduling fairness: G.F. sender_send_data invoked
    # fairness 2:    scheduling fairness: G.F. receiver_send_ack invoked
    # fairness 3:    data channel fairness: (G.F. data message sent) -> (G.F. data message received)
    # fairness 4:    ack  channel fairness: (G.F. ack  message sent) -> (G.F. ack  message received)
    #
    # To encode (G.F. A) -> (G.F. B) === (F.G. ~A) \/ (G.F. B), we
    # introduce a flag, not_a_flag, that is initially false and can
    # non-deterministically become true and start enfocing G. ~A. We
    # then require that the formula (not_a_flag \/ B) is true
    # infinitely often.
    #
    ################################################################################

    # a totally ordered set for indices
    type index_t
    instantiate index : total_order(index_t)

    # an uninterpreted sort for data items
    type value

    # data messages (sent from sender to received), with a fifo channel,
    # and a data item and sequence bit for every message
    type data_msg_t
    instantiate data_msg : fifo_channel(data_msg_t)
    individual d(D:data_msg_t) : value  # immutable
    relation dbit(D:data_msg_t)  # immutable

    # ack messages (sent from receiver to sender), with a fifo channel and
    # a sequence number bit for every message.
    type ack_msg_t
    instantiate ack_msg : fifo_channel(ack_msg_t)
    relation abit(A:ack_msg_t)  # immutable

    # sender array and receiver array
    individual sender_array(I:index_t) : value
    individual receiver_array(I:index_t) : value

    # sender index and receiver index
    individual sender_i:index_t
    init sender_i = index.zero
    individual receiver_i:index_t
    init receiver_i = index.zero

    # sender and receiver bits, initially 0 (false)
    relation sender_bit
    init ~sender_bit
    relation receiver_bit
    init ~receiver_bit

    # state for encoding the negation of the liveness property:
    individual i0:index_t

    # state for encoding the fairness constraints (see explanation above)
    relation data_no_send_flag
    init ~data_no_send_flag
    relation ack_no_send_flag
    init ~ack_no_send_flag
    relation fair_1 # sender_send_data invoked
    relation fair_2 # receiver_send_ack invoked
    relation fair_3 # (data_no_send_flag \/ data message received)
    relation fair_4 # (ack_no_send_flag \/ ack message received)

    ################################################################################
    #
    # Protocol actions
    #
    ################################################################################

    action sender_send_data(m:data_msg_t, a:ack_msg_t) = {
        assume d(m) = sender_array(sender_i);
        assume dbit(m) <-> sender_bit;
        call data_msg.send(m);

        # from fairness monitor
        fair_1 := true;
        fair_2 := false;
        fair_3 := data_no_send_flag;
        fair_4 := ack_no_send_flag;
        if data_no_send_flag {
            assume false  # block transition where we send data message after data_no_send_flag becomes true
        };
        if ~data_no_send_flag {
            data_no_send_flag := *
        };
        if ~ack_no_send_flag {
            ack_no_send_flag := *
        }
    }

    action sender_receive_ack(m:data_msg_t, a:ack_msg_t) =  {
        a := ack_msg.receive();
        if abit(a) <-> sender_bit {
            sender_bit := ~sender_bit;
            sender_i := index.get_succ(sender_i)
        };

        # from fairness monitor
        fair_1 := false;
        fair_2 := false;
        fair_3 := data_no_send_flag;
        fair_4 := true;
        if ~data_no_send_flag {
            data_no_send_flag := *
        };
        if ~ack_no_send_flag {
            ack_no_send_flag := *
        }

    }

    action receiver_receive_data(m:data_msg_t, a:ack_msg_t) = {
        m := data_msg.receive();
        if dbit(m) <-> receiver_bit {
            # flip receiver bit, append to receiver array
            receiver_bit := ~receiver_bit;
            receiver_array(receiver_i) := d(m);
            receiver_i := index.get_succ(receiver_i)
        };

        # from monitor of negation of liveness property
        assume receiver_array(i0) ~= sender_array(i0);

        # from fairness monitor
        fair_1 := false;
        fair_2 := false;
        fair_3 := true;
        fair_4 := ack_no_send_flag;
        if ~data_no_send_flag {
            data_no_send_flag := *
        };
        if ~ack_no_send_flag {
            ack_no_send_flag := *
        }
    }

    action receiver_send_ack(m:data_msg_t, a:ack_msg_t) = {
        # send ack with ~receiver_bit
        assume abit(a) <-> ~receiver_bit;
        call ack_msg.send(a);

        # from fairness monitor
        fair_1 := false;
        fair_2 := true;
        fair_3 := data_no_send_flag;
        fair_4 := ack_no_send_flag;
        if ack_no_send_flag {
            assume false  # block transition where we send ack message after ack_no_send_flag becomes true
        };
        if ~data_no_send_flag {
            data_no_send_flag := *
        };
        if ~ack_no_send_flag {
            ack_no_send_flag := *
        }
    }

    action data_msg_drop(m:data_msg_t, a:ack_msg_t) = {
        call data_msg.drop(m);

        # from fairness monitor
        fair_1 := false;
        fair_2 := false;
        fair_3 := false;
        fair_4 := false
    }

    action ack_msg_drop(m:data_msg_t, a:ack_msg_t) = {
        call ack_msg.drop(a);

        # from fairness monitor
        fair_1 := false;
        fair_2 := false;
        fair_3 := false;
        fair_4 := false
    }

    export sender_send_data
    export sender_receive_ack
    export receiver_receive_data
    export receiver_send_ack
    export data_msg_drop
    export ack_msg_drop

    ################################################################################
    #
    # Conjectures for proving safety (also helps for liveness)
    #
    ################################################################################

    # safety - receiver array has values from sender array for all received indices
    conjecture ~index.le(receiver_i, I) -> receiver_array(I) = sender_array(I)

    # inductive invariant for proving safety

    conjecture ~sender_bit & ~receiver_bit & ack_msg.le(A,A) -> abit(A)
    conjecture ~sender_bit & ~receiver_bit & data_msg.le(M1,M2) -> ~(dbit(M1) & ~dbit(M2))

    conjecture sender_bit & receiver_bit & ack_msg.le(A,A) -> ~abit(A)
    conjecture sender_bit & receiver_bit & data_msg.le(M1,M2) -> ~(~dbit(M1) & dbit(M2))

    conjecture ~sender_bit & receiver_bit & data_msg.le(M,M) -> ~dbit(M)
    conjecture ~sender_bit & receiver_bit & ack_msg.le(A1,A2) -> ~(abit(A1) & ~abit(A2))

    conjecture sender_bit & ~receiver_bit & data_msg.le(M,M) -> dbit(M)
    conjecture sender_bit & ~receiver_bit & ack_msg.le(A1,A2) -> ~(~abit(A1) & abit(A2))

    conjecture (sender_bit <-> receiver_bit)  -> sender_i = receiver_i
    conjecture (sender_bit <-> ~receiver_bit) -> (
        # receiver_i = sender_i + 1
        ~index.le(receiver_i, sender_i) &
        (forall I. ~index.le(I,sender_i) -> index.le(receiver_i,I))
    )

    conjecture data_msg.le(M,M) & (dbit(M) <-> sender_bit) -> d(M) = sender_array(sender_i)
    conjecture ack_msg.le(A,A) & (abit(A) <-> sender_bit) -> ~index.le(receiver_i,sender_i)

    ################################################################################
    #
    # The liveness to safety construction
    #
    # The proof uses a nesting structure with 2 components:
    # eta_0 = true
    # eta_1 = sender_bit and receiver_bit don't change, i.e.,
    #       = (sender_bit <-> old sender_bit) & (receiver_bit <-> old receiver_bit)
    #
    ################################################################################

    object l2s = {

        # the states of the monitor
        relation waiting
        relation frozen
        relation saved
        init waiting & ~frozen & ~saved
        conjecture waiting | frozen | saved
        conjecture ~waiting | ~frozen
        conjecture ~waiting | ~saved
        conjecture ~frozen  | ~saved

        # d - the finite footprint
        relation d_index(I:index_t)
        relation d_value(V:value)
        relation d_data_msg(M:data_msg_t)
        relation d_ack_msg(A:ack_msg_t)
        # initially d contains all indices <= i0
        init d_index(I) <-> index.le(I,i0)
        init ~d_value(V)
        init ~d_data_msg(M)
        init ~d_ack_msg(A)

        # W - waiting for fairness constraints, in this case all nullary
        relation w_1
        relation w_2
        relation w_3
        relation w_4
        # initially, all w_i are true (mu is trivial and includes all 4)
        init w_1
        init w_2
        init w_3
        init w_4

        # a - the frozen copy of d
        relation a_index(I:index_t)
        relation a_value(V:value)
        relation a_data_msg(M:data_msg_t)
        relation a_ack_msg(A:ack_msg_t)

        # copies of all the state relations and constants, including
        # state that comes from encoding fairness (*_no_send_flag)
        instantiate s_data_msg : fifo_channel(data_msg_t)
        instantiate s_ack_msg : fifo_channel(ack_msg_t)
        individual  s_sender_array(I:index_t) : value
        individual  s_receiver_array(I:index_t) : value
        individual  s_sender_i:index_t
        individual  s_receiver_i:index_t
        relation    s_sender_bit
        relation    s_receiver_bit
        relation    s_data_no_send_flag
        relation    s_ack_no_send_flag

        # choice of level
        relation monitor_level_0
        relation monitor_level_1
        axiom monitor_level_0 | monitor_level_1
        axiom ~monitor_level_0 | ~monitor_level_1

        # auxiliary relations for postlude
        # relation eta_0  = true
        relation eta_1 # = (sender_bit <-> old sender_bit) & (receiver_bit <-> old receiver_bit)

        action prelude = {
            # guess eta_1, in the postlude we assume we guessed right
            eta_1 := *;

            # level >= i === (monitor_level_1 -> eta_1)
            # level < i  === (monitor_level_1 & ~eta_1)
            # level = i  === (monitor_level_1 <-> eta_1)

            if (monitor_level_1 & ~eta_1) {
                # level < i
                waiting := true;
                frozen := false;
                saved := false;
                # reset W
                w_1 := true;
                w_2 := true;
                w_3 := true;
                w_4 := true
            } else {
                # level >= i
                if waiting & ~w_1 & ~w_2 & ~w_3 & ~w_4 {
                    a_index(I) := d_index(I);
                    a_value(V) := d_value(V);
                    a_data_msg(M) := d_data_msg(M);
                    a_ack_msg(A) := d_ack_msg(A);
                    waiting := false;
                    frozen := true
                };
                if frozen & (monitor_level_1 <-> eta_1) {
                    # level = i
                    saved := *;
                    if saved {
                        frozen := false;
                        # copy relations
                        s_data_msg.le(X,Y) := data_msg.le(X,Y);
                        s_ack_msg.le(X,Y) := ack_msg.le(X,Y);
                        s_sender_array(I) := sender_array(I);
                        s_receiver_array(I) := receiver_array(I);
                        s_sender_i := sender_i;
                        s_receiver_i := receiver_i;
                        s_sender_bit := sender_bit;
                        s_receiver_bit := receiver_bit;
                        s_data_no_send_flag := data_no_send_flag;
                        s_ack_no_send_flag := ack_no_send_flag;
                        # reset W
                        w_1 := true;
                        w_2 := true;
                        w_3 := true;
                        w_4 := true
                    }
                }
            }
        }
        before sender_send_data { call prelude }
        before sender_receive_ack { call prelude }
        before receiver_receive_data { call prelude }
        before receiver_send_ack { call prelude }
        before data_msg_drop { call prelude }
        before ack_msg_drop { call prelude }

        action postlude(m:data_msg_t, a:ack_msg_t) = {
            # level >= i === (monitor_level_1 -> eta_1)
            # level < i  === (monitor_level_1 & ~eta_1)
            # level = i  === (monitor_level_1 <-> eta_1)

            if (monitor_level_1 -> eta_1) {
                # update W
                w_1 := w_1 & ~fair_1;
                w_2 := w_2 & ~fair_2;
                w_3 := w_3 & ~fair_3;
                w_4 := w_4 & ~fair_4
            };

            # update d
            d_value(d(m)) := true;
            d_data_msg(m) := true;
            d_ack_msg(a) := true;

            # assert no abstract fair cycle
            assert ~(
                saved &
                (monitor_level_1 <-> eta_1) & # level = i
                ~w_1 &
                ~w_2 &
                ~w_3 &
                ~w_4 &
                (forall M1:data_msg_t,M2:data_msg_t. a_data_msg(M1) & a_data_msg(M2) -> (s_data_msg.le(M1,M2) <-> data_msg.le(M1,M2))) &
                (forall A1:ack_msg_t,A2:ack_msg_t. a_ack_msg(A1) & a_ack_msg(A2) -> (s_ack_msg.le(A1,A2) <-> ack_msg.le(A1,A2))) &
                (forall I:index_t, V:value. a_index(I) & a_value(V) -> (s_sender_array(I) = V <-> sender_array(I) = V)) &
                (forall I:index_t, V:value. a_index(I) & a_value(V) -> (s_receiver_array(I) = V <-> receiver_array(I) = V)) &
                (forall I:index_t. a_index(I) -> (s_sender_i   = I <-> sender_i   = I)) &
                (forall I:index_t. a_index(I) -> (s_receiver_i = I <-> receiver_i = I)) &
                (s_sender_bit <-> sender_bit) &
                (s_receiver_bit <-> receiver_bit) &
                (s_data_no_send_flag <-> data_no_send_flag) &
                (s_ack_no_send_flag <-> ack_no_send_flag)
            )
        }

        after sender_send_data {
            assume eta_1 <-> ((sender_bit <-> old sender_bit) & (receiver_bit <-> old receiver_bit));
            call postlude(m,a)
        }
        after sender_receive_ack {
            assume eta_1 <-> ((sender_bit <-> old sender_bit) & (receiver_bit <-> old receiver_bit));
            call postlude(m,a)
        }
        after receiver_receive_data {
            assume eta_1 <-> ((sender_bit <-> old sender_bit) & (receiver_bit <-> old receiver_bit));
            call postlude(m,a)
        }
        after receiver_send_ack {
            assume eta_1 <-> ((sender_bit <-> old sender_bit) & (receiver_bit <-> old receiver_bit));
            call postlude(m,a)
        }
        after data_msg_drop {
            assume eta_1 <-> ((sender_bit <-> old sender_bit) & (receiver_bit <-> old receiver_bit));
            call postlude(m,a)
        }
        after ack_msg_drop {
            assume eta_1 <-> ((sender_bit <-> old sender_bit) & (receiver_bit <-> old receiver_bit));
            call postlude(m,a)
        }

    }

    ################################################################################
    #
    # Conjectures for proving liveness
    #
    ################################################################################

    # all safety conjectures for s_ state
    conjecture l2s.saved -> (  ~index.le(l2s.s_receiver_i, I) -> l2s.s_receiver_array(I) = l2s.s_sender_array(I)  )
    conjecture l2s.saved -> (  ~l2s.s_sender_bit & ~l2s.s_receiver_bit & l2s.s_ack_msg.le(A,A) -> abit(A)  )
    conjecture l2s.saved -> (  ~l2s.s_sender_bit & ~l2s.s_receiver_bit & l2s.s_data_msg.le(M1,M2) -> ~(dbit(M1) & ~dbit(M2))  )
    conjecture l2s.saved -> (  l2s.s_sender_bit & l2s.s_receiver_bit & l2s.s_ack_msg.le(A,A) -> ~abit(A)  )
    conjecture l2s.saved -> (  l2s.s_sender_bit & l2s.s_receiver_bit & l2s.s_data_msg.le(M1,M2) -> ~(~dbit(M1) & dbit(M2))  )
    conjecture l2s.saved -> (  ~l2s.s_sender_bit & l2s.s_receiver_bit & l2s.s_data_msg.le(M,M) -> ~dbit(M)  )
    conjecture l2s.saved -> (  ~l2s.s_sender_bit & l2s.s_receiver_bit & l2s.s_ack_msg.le(A1,A2) -> ~(abit(A1) & ~abit(A2))  )
    conjecture l2s.saved -> (  l2s.s_sender_bit & ~l2s.s_receiver_bit & l2s.s_data_msg.le(M,M) -> dbit(M)  )
    conjecture l2s.saved -> (  l2s.s_sender_bit & ~l2s.s_receiver_bit & l2s.s_ack_msg.le(A1,A2) -> ~(~abit(A1) & abit(A2))  )
    conjecture l2s.saved -> (  (l2s.s_sender_bit <-> l2s.s_receiver_bit)  -> l2s.s_sender_i = l2s.s_receiver_i  )
    conjecture l2s.saved -> (  (l2s.s_sender_bit <-> ~l2s.s_receiver_bit) -> (
        ~index.le(l2s.s_receiver_i, l2s.s_sender_i) &
        (forall I. ~index.le(I,l2s.s_sender_i) -> index.le(l2s.s_receiver_i,I))
    )  )
    conjecture l2s.saved -> (  l2s.s_data_msg.le(M,M) & (dbit(M) <-> l2s.s_sender_bit) -> d(M) = l2s.s_sender_array(l2s.s_sender_i)  )
    conjecture l2s.saved -> (  l2s.s_ack_msg.le(A,A) & (abit(A) <-> l2s.s_sender_bit) -> ~index.le(l2s.s_receiver_i,l2s.s_sender_i)  )

    # conjecture that l2s.d is large enough
    conjecture index.le(I,i0) -> l2s.d_index(I)
    conjecture data_msg.le(M,M) -> l2s.d_data_msg(M)
    conjecture ack_msg.le(A,A) -> l2s.d_ack_msg(A)
    # conjecture that l2s.a is large enough
    conjecture ~l2s.waiting -> ( index.le(I,i0) -> l2s.a_index(I) )
    conjecture ~l2s.waiting & l2s.monitor_level_1 -> ( data_msg.le(M,M) & (dbit(M) <-> ~sender_bit) -> l2s.a_data_msg(M) )
    conjecture ~l2s.waiting & l2s.monitor_level_1 -> ( ack_msg.le(A,A) & (abit(A) <-> receiver_bit) -> l2s.a_ack_msg(A) )

    # more properties of reachable protocol states
    conjecture index.le(sender_i, i0)
    conjecture index.le(receiver_i, i0)
    # and their saved state counterparts
    conjecture l2s.saved -> index.le(l2s.s_sender_i, i0)
    conjecture l2s.saved -> index.le(l2s.s_receiver_i, i0)

    # relating current state and saved state
    conjecture l2s.saved & l2s.monitor_level_0 -> ~index.le(sender_i, l2s.s_sender_i) | ~index.le(receiver_i, l2s.s_receiver_i)
    conjecture l2s.saved & l2s.monitor_level_1 & data_msg.le(M,M) & (dbit(M) <-> ~sender_bit) -> l2s.s_data_msg.le(M,M)
    conjecture l2s.saved & l2s.monitor_level_1 & ack_msg.le(A,A)  & (abit(A) <-> receiver_bit) -> l2s.s_ack_msg.le(A,A)
    conjecture l2s.saved & l2s.monitor_level_1 -> l2s.s_sender_i = sender_i
    conjecture l2s.saved & l2s.monitor_level_1 -> l2s.s_receiver_i = receiver_i
    conjecture l2s.saved & l2s.monitor_level_1 -> (l2s.s_sender_bit <-> sender_bit)
    conjecture l2s.saved & l2s.monitor_level_1 -> (l2s.s_receiver_bit <-> receiver_bit)

    # conjectures for proving messages are infinitely often received
    conjecture l2s.saved -> (l2s.s_data_no_send_flag -> data_no_send_flag)
    conjecture l2s.saved -> (l2s.s_ack_no_send_flag -> ack_no_send_flag)
    conjecture l2s.saved & ~l2s.w_1 -> ~l2s.s_data_no_send_flag
    conjecture l2s.saved & ~l2s.w_2 -> ~l2s.s_ack_no_send_flag

    # the messages that exist and show the difference between current state and saved state
    conjecture l2s.saved & l2s.monitor_level_1 & ~l2s.w_3 & ~data_no_send_flag & (l2s.s_sender_bit <-> l2s.s_receiver_bit) ->
        exists M:data_msg_t. l2s.a_data_msg(M) & ~data_msg.le(M,M) & l2s.s_data_msg.le(M,M) & (dbit(M) <-> ~receiver_bit)

    conjecture l2s.saved & l2s.monitor_level_1 & ~l2s.w_4 & ~ack_no_send_flag & (l2s.s_sender_bit <-> ~l2s.s_receiver_bit) ->
        exists A:ack_msg_t. l2s.a_ack_msg(A) & ~ack_msg.le(A,A) & l2s.s_ack_msg.le(A,A) & (abit(A) <-> ~sender_bit)

}
