#lang ivy1.5

################################################################################
# A liveness proof of the TLB shootdown algorithm according to the "modern"
# version of our methodology:
# * all existentially quantified variables come from action parameters
# * d is updated automatically by inserting all action parameters
# * change from paper: there are constant symbols in the vocabulary -
#   and they are handled both when updating d and when comparing states
################################################################################

################################################################################
#
# Types, relations and functions describing the state
#
################################################################################

object tlb = {

    ################################################################################
    #
    # The protocol itself.  This closely follows the algorithm written in Figure 9 of
    #
    #  J. Hoenicke, R. Majumdar, A. Podelski: Thread Modularity at Many Levels. POPL 2017
    #
    # The locations match the line number in the figure.
    #
    ################################################################################

    # we distinguish between processors and pagemaps -- the above paper misused
    # processors for both.
    #
    # pageentry is an abstract type to represent the value in a pagemap (the paper used integers).
    #
    type processor
    type pmap
    type pageentry

    # the locations closely match the line numbers in Figure 9
    type location = {i1,i2,i3,i4,i5,i6,i7,i8,i9,i11,i12,i14,i15,
                     m2,m3,m5,
                     r1,r2,r3,r5,r6,r7,r8,
                     b1}
    
    individual pc(P:processor):location
    
    individual userpmap(P:processor):pmap
    # this variable is called pmap in the paper
    individual writepmap(P:processor):pmap
    relation actionlock(P:processor)
    relation actionneeded(P:processor)
    relation active(P:processor)
    relation interrupt(P:processor)
    # this represents the cpu variable as relation
    relation currentcpu(P:processor, CPU:processor)
    relation plock(M:pmap)
    individual tlb(P:processor):pageentry
    individual pentry(M:pmap):pageentry

    # elements to iterate in the for cpu ~= pid loops.
    relation todo(P1:processor, P2:processor)

    # error is set if some assertions fails, e.g. lock not held on unlock.
    relation error

    init pc(P)=b1
    init ~currentcpu(P,C)
    init ~plock(P)
    init ~actionlock(P) & ~actionneeded(P) & ~interrupt(P) & active(P)
    init ~error

    # stubs to add annotations later
    action atLevel1(p:processor) = {}
    action atLevel2(p:processor) = {}
    action fairInit2(p:processor) = {}
    action fairResp3(p:processor) = {}
    action fairScheduled(p:processor) = {}
    action useProc(p:processor) = {}
    action useMap(m:pmap) = {}
    action prelude = {}
    action postlude(p:processor) = {
        call fairScheduled(p)
    }

    # i1: active := false   we also havoc writepmap here
    action initiator1(p:processor, m:pmap) = {
        call prelude();
        call useProc(p); call useMap(m);
        assume pc(p) = i1;
        active(p) := false;
        writepmap(p) := m;
        pc(p) := i2;
        call atLevel1(p);
        call postlude(p)
    }

    # i2: lock plock(writepmap)
    # Also prepares for cpu ~= pid loop.
    # Note that we busy-loop if lock is taken.  This is necessary to
    # detect deadlock as non-terminating runs.
    action initiator2(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=i2;
        if (~plock(writepmap(p))) {
            plock(writepmap(p)) := true;
            todo(p,X) := pc(X) ~= b1 & p ~= X;
            pc(p) := i3;
            call atLevel2(p);
            call fairInit2(p)
        };
        call postlude(p)
    }
    
    # i3: for cpu ~= pid
    # This translates for (cpu ~= pid)
    # if todo contains a cpu, it is set in the currentcpu relation and we enter the loop
    action initiator3(p:processor, cpu:processor) = {
        call prelude();
        call useProc(p); call useProc(cpu);
        assume pc(p)=i3;
        assume todo(p, cpu);
        currentcpu(p, X) := X = cpu;
        todo(p, cpu) := false;
        pc(p) := i4;
        call postlude(p)
    }

    # Otherwise if todo list is empty, we leave the loop
    # and prepare the next for pid ~= cpu loop.
    action initiator3exit(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=i3;
        assume ~todo(p, X);
        todo(p, X) := pc(X) ~= b1 & X ~= p;
        pc(p) := i9;
        call atLevel2(p);
        call postlude(p)
    }
    
    # i4:    if userpmap[cpu] = pmap
    action initiator4(p:processor, cpu:processor) = {
        call prelude();
        call useProc(p); call useProc(cpu);
        assume pc(p)=i4;
        assume currentcpu(p, cpu);
        if (userpmap(cpu) = writepmap(p)) {
            pc(p) := i5
        } else {
            pc(p) := i3
        };
        call postlude(p)
    }
    
    # i5:        lock actionlock[cpu]
    action initiator5(p:processor, cpu:processor) = {
        call prelude();
        call useProc(p); call useProc(cpu);
        assume pc(p)=i5;
        assume currentcpu(p, cpu);
        if (~actionlock(cpu)) {
            actionlock(cpu) := true;
            pc(p) := i6
        };
        call postlude(p)
    }
    
    # i6:        actionneeded[cpu] := true
    action initiator6(p:processor, cpu:processor) = {
        call prelude();
        call useProc(p); call useProc(cpu);
        assume pc(p)=i6;
        assume currentcpu(p, cpu);
        actionneeded(cpu) := true;
        pc(p) := i7;
        call postlude(p)
    }
    
    # i7:        unlock actionlock[cpu]
    action initiator7(p:processor, cpu:processor) = {
        call prelude();
        call useProc(p); call useProc(cpu);
        assume pc(p)=i7;
        assume currentcpu(p, cpu);
        if (~actionlock(cpu)) {
            error := true
        };
        actionlock(cpu) := false;
        pc(p) := i8;
        call postlude(p)
    }
    
    # i8:        interrupt[cpu] := true
    action initiator8(p:processor, cpu:processor) = {
        call prelude();
        call useProc(p); call useProc(cpu);
        assume pc(p)=i8;
        assume currentcpu(p, cpu);
        interrupt(cpu) := true;
        pc(p) := i3;
        call postlude(p)
    }

    # i9: for cpu ~= pid
    # i10:    wait until ~active[cpu] | userpmap[cpu] ~= writepmap
    action initiator9(p:processor, cpu:processor) = {
        call prelude();
        call useProc(p); call useProc(cpu);
        assume pc(p)=i9;
        assume todo(p, cpu);
        if (~active(cpu) | userpmap(cpu) ~= writepmap(p)) {
            todo(p, cpu) := false
        };
        call postlude(p)
    }
    
    action initiator9exit(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=i9;
        assume ~todo(p, X);
        pc(p) := i11;
        call atLevel2(p);
        call postlude(p)
    }
    
    # i11: entry[pmap] := *
    action initiator11(p:processor, e:pageentry) = {
        call prelude();
        call useProc(p);
        assume pc(p)=i11;
        pentry(writepmap(p)) := e;
        pc(p) := i12;
        call postlude(p)
    }
    
    # i12: if (userpmap = pmap)
    # i13:    tlb := entry[pmap]
    action initiator12(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=i12;
        if (userpmap(p) = writepmap(p)) {
           tlb(p) := pentry(writepmap(p))
        };
        pc(p) := i14;
        call postlude(p)
    }

    # i14: unlock plock[pmap]
    action initiator14(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=i14;
        if (~plock(writepmap(p))) {
           error := true
        };
        plock(writepmap(p)) := false;
        pc(p) := i15;
        call postlude(p)
    }
    
    # i15: active := true
    action initiator15(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=i15;
        active(p) := true;
        pc(p) := m5;
        call postlude(p)
    }

    # r1: while actionneeded
    action responder1(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=r1;
        if (actionneeded(p)) {
            pc(p) := r2
        } else {
            pc(p) := m2
        };
        call postlude(p)
    }
    
    # r2:   active := false
    action responder2(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=r2;
        active(p) := false;
        pc(p) := r3;
        call atLevel1(p);
        call postlude(p)
    }

    # this must be atomic (bug in original TLB algorithm, see paper)
    # r3:   wait until plock[userpmap] = unlocked
    # r4:   lock actionlock(p)
    action responder3(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=r3;
        if (~plock(userpmap(p))) {
            if actionlock(p) {
                error := true
            };
            actionlock(p) := true;
            pc(p) := r5;
            call fairResp3(p)
        };
        call postlude(p)
    }
    
    # r5:   tlb := entry[userpmap]
    action responder5(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=r5;
        tlb(p) := pentry(userpmap(p));
        pc(p) := r6;
        call postlude(p)
    }
    
    # r6:   actionneeded := false
    action responder6(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=r6;
        actionneeded(p) := false;
        pc(p) := r7;
        call postlude(p)
    }
    
    # r7:   unlock actionlock
    action responder7(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=r7;
        if (~actionlock(p)) {
            error := true
        };
        actionlock(p) := false;
        pc(p) := r8;
        call postlude(p)
    }
    
    # r8:   active := false
    action responder8(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=r8;
        active(p) := true;
        pc(p) := r1;
        call postlude(p)
    }
    
    # m1: while true
    # m2:    assert tlb = entry[userpmap]
    action main2(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=m2;
        if (tlb(p) ~= pentry(userpmap(p))) {
            error := true
        };
        pc(p) := m3;
        call postlude(p)
    }
    
    # m3:    if (*)
    # m4:        Initiator()
    action main3a(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=m3;
        pc(p) := i1;
        call postlude(p)
    }
    action main3b(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=m3;
        pc(p) := m5;
        call postlude(p)
    }
    
    # m5:    if (interrupt)
    # m6:        interrupt := false; Responder()
    action main5(p:processor) = {
        call prelude();
        call useProc(p);
        assume pc(p)=m5;
        if (interrupt(p)) {
            interrupt(p) := false;
            pc(p) := r1
        } else {
            pc(p) := m2
        };
        call postlude(p)
    }

    # b1: pid := ++n  // create process
    # b2: atomic userpmap := *
    #            assume plock[userpmap] = unlocked
    #            tlb := entry[userpmap]
    # b3: Main()
    action boot1(p:processor, m:pmap) = {
        call prelude();
        call useProc(p); call useMap(m);
        assume pc(p) = b1;
        assume ~plock(m);
        userpmap(p) := m;
        tlb(p) := pentry(m);
        pc(p) := m2;
        call postlude(p)
    }

    export initiator1
    export initiator2
    export initiator3
    export initiator3
    export initiator4
    export initiator5
    export initiator6
    export initiator7
    export initiator8
    export initiator3exit
    export initiator9
    export initiator9exit
    export initiator11
    export initiator12
    export initiator14
    export initiator15
    export responder1
    export responder2
    export responder3
    export responder5
    export responder6
    export responder7
    export responder8
    export main2
    export main3a
    export main3b
    export main5

    # show safety
    # all invariants are universal with at most two variables (provable at level 2)

    # plock(writemap) is taken in i3-i14
    conjecture pc(P)=i3 | pc(P)=i4 | pc(P)=i5 | pc(P)=i6 | pc(P)=i7 | pc(P)=i8 | pc(P)=i9 | pc(P)=i11 | pc(P)=i12 | pc(P)=i14 -> plock(writepmap(P))
    # plock(writemap) ensures mutual exclusion of i3-i14
    conjecture (pc(P1)=i3 | pc(P1)=i4 | pc(P1)=i5 | pc(P1)=i6 | pc(P1)=i7 | pc(P1)=i8 | pc(P1)=i9 | pc(P1)=i11 | pc(P1)=i12 | pc(P1)=i14)
             & (pc(P2)=i3 | pc(P2)=i4 | pc(P2)=i5 | pc(P2)=i6 | pc(P2)=i7 | pc(P2)=i8 | pc(P2)=i9 | pc(P2)=i11 | pc(P2)=i12 | pc(P2)=i14)
             -> writepmap(P1) ~= writepmap(P2) | P1 = P2
    
    # currentcpu has at most one value
    conjecture currentcpu(P,C1) & currentcpu(P, C2) -> C1 = C2

    # actionlock(cpu) is taken in i6-i7
    conjecture (pc(P)=i6 | pc(P)=i7) & currentcpu(P, C) -> actionlock(C)
    # actionlock(p) is taken in r5-r7
    conjecture (pc(P)=r5 | pc(P)=r6 | pc(P)=r7) -> actionlock(P)
    # actionlock(p) ensures mutual exclusion of i6-i7
    conjecture (pc(P1)=i6 | pc(P1)=i7) & currentcpu(P1, C) & (pc(P2)=i6 | pc(P2)=i7) & currentcpu(P2, C) -> P1 = P2
    # actionlock(p) ensures mutual exclusion of r5-r7 and i6-i7
    conjecture ~((pc(P1)=r5 | pc(P1)=r6 | pc(P1)=r7) & (pc(P2)=i6 | pc(P2)=i7) & currentcpu(P2, P1))

    # while actionlock(p) is taken outside r5-r7 it can only be if someone is in i6-i7, so plock(userpmap) should hold
    conjecture actionlock(C) & ~(pc(C)=r5 | pc(C)=r6 | pc(C)=r7) -> plock(userpmap(C))
    # and then no other process with the same writemap can be in i3-i14
    conjecture actionlock(C) & ~(pc(C)=r5 | pc(C)=r6 | pc(C)=r7) &
       (pc(P)=i3 | pc(P)=i4 | pc(P)=i5 | pc(P)=i6 | pc(P)=i7 | pc(P)=i8 | pc(P)=i9 | pc(P)=i11 | pc(P)=i12 | pc(P)=i14) ->
       userpmap(C) ~= writepmap(P) | (currentcpu(P,C) & (pc(P)=i6 | pc(P)=i7))
       
    # instructions i5-i7 are only executed if writepmap = userpmap(cpu)
    conjecture (pc(P)=i5 | pc(P)=i6 | pc(P)=i7) & currentcpu(P,C) -> writepmap(P) = userpmap(C)
    
    # active is only exactly set in these limited locations
    conjecture active(P) <->
      (pc(P)=b1 | pc(P)=m2 | pc(P)=m3 | pc(P) = m5 | pc(P) = i1 | pc(P) = r1 | pc(P) = r2)

    # If we already iterated over a process C in the i3-i8 loop of P or if we are currently iterating and we
    # are past the i6 instruction, and userpmap(C) = writepmap(P) then we set the actionneeded flag, so it is
    # still set and C cannot enter the actionlock
    conjecture (pc(P)=i3 | pc(P)=i7 | pc(P)=i8) & ~todo(P,C) & pc(C) ~= b1 & userpmap(C) = writepmap(P) -> (actionneeded(C) & ~pc(C)=r5  & ~pc(C)=r6) | P = C
    conjecture (pc(P)=i4 | pc(P)=i5 | pc(P)=i6) & ~todo(P,C) & ~currentcpu(P,C) & pc(C) ~= b1 & userpmap(C) = writepmap(P) -> (actionneeded(C) & ~pc(C)=r5  & ~pc(C)=r6) | P = C
    # The same if we are in the i9 loop or in i11
    conjecture (pc(P)=i9 | pc(P)=i11) & pc(C) ~= b1 & userpmap(C) = writepmap(P) -> (actionneeded(C) & ~pc(C)=r5  & ~pc(C)=r6) | P = C
    
    # When the tlb(P) is incorrect actionneded(P) is still set (unless we changed our own tlb, but then
    # we are in i12 where we fix it in the next step)
    conjecture pc(P) ~= b1 & tlb(P) ~= pentry(userpmap(P)) -> (actionneeded(P) & ~pc(P)=r6) | (pc(P)=i12 & userpmap(P) = writepmap(P))
    
    # If we already iterated over a process C in the i3-i8 loop of P and userpmap(C) = writepmap(P) then
    # we set the interrupt flag, so it is still set or C is in the interrupt routine
    conjecture (pc(P)=i3) & ~todo(P,C) & pc(C) ~= b1 & userpmap(C) = writepmap(P) -> interrupt(C) | P = C | (pc(C)=r1 | pc(C)=r2 | pc(C)=r3)
    conjecture (pc(P)=i4 | pc(P)=i5 | pc(P)=i6 | pc(P)=i7 | pc(P)=i8) & ~todo(P,C) & pc(C) ~= b1 & ~currentcpu(P,C) & userpmap(C) = writepmap(P) -> interrupt(C) | P = C | (pc(C)=r1 | pc(C)=r2 | pc(C)=r3)
    conjecture (pc(P)=i9 | pc(P)=i11) & pc(C) ~= b1 & userpmap(C) = writepmap(P) -> interrupt(C) | P = C | (pc(C)=r1 | pc(C)=r2 | pc(C)=r3)
    # When the tlb(C) is incorrect the process must be interrupted
    conjecture tlb(C) ~= pentry(userpmap(C)) & pc(C) ~= b1 -> interrupt(C) | (pc(C)=r1 | pc(C)=r2 | pc(C)=r3 | pc(C) = r5) | (pc(C)=i12 & writepmap(C) = userpmap(C))
    
    # We wait for a process in the i9 loop at least until it leaves m2 and it cannot enter m2 again before i11
    conjecture ((pc(P)=i9 & ~todo(P,C)) | pc(P)=i11) & userpmap(C) = writepmap(P) -> pc(C)~=m2
    # When the tlb(C) is incorrect the process is not in m2
    conjecture tlb(P) ~= pentry(userpmap(P)) -> ~pc(P)=m2
    
    conjecture ~error

    object liveness = {
        ################################################################################
        #
        # Augmentation for Fairness/liveness property
        #
        ################################################################################
        #
        # property:      forall P:processor. G. F. pc(P) = m2 | pc(P) = r6
        # fairness:      forall P. G. F. scheduled(P)
        #                forall P. (G. F. enabled(initiator2(P)) ->  G. F. initiator2(P))
        #                forall P. (G. F. enabled(responder3(P)) ->  G. F. responder3(P))
        #
        # the strong fairness for initiator2 is implemented as
        #                forall P. G. F. (G ~enabled(initiator2(P))) | initiator2(P)
        # we use a non-deterministically assigned variable "disableInit2(P)" for
        #                (G. ~enabled(initiator2(P)))
        #
        # Similarly for the negated and skolemized property
        #                F. (G. (pc(p0) ~= m2 & pc(p0) ~= r6))
        # We use a non-deterministically assigned variable "disableProcess0" that represents
        #                (G. pc(p0) ~= m2 & pc(p0) ~= r6)
        #
        # The fairness assumptions are then
        #   forall P. G. F. scheduled(P)
        #   forall P. G. F. (disableInit2(P) | initiator2(P))
        #   forall P. G. F. (disableResp3(P) | responder3(P))
        #             G. F. disableProcess0
        #
        ################################################################################

        # the auxiliary variables for the property monitor
        individual p0:processor
        relation disableInit2(P:processor)
        relation disableResp3(P:processor)
        relation disableProcess0

        # the fairness stubs
        action fairProcess0 = {}
        
        action monitor = {
            # disableInit2 stands for G. pc(P) ~= i2 | plock(writepmap(P))
            assume disableInit2(P) -> (pc(P) ~= i2 | plock(writepmap(P)));
            # disableResp3 stands for G. pc(P) ~= r3 | plock(userpmap(P))
            assume disableResp3(P) -> (pc(P) ~= r3 | plock(userpmap(P)));
            # disableProcess0 stands for G. (pc(p0) ~= m2 & pc(p0) ~= r6)
            assume disableProcess0 -> (pc(p0) ~= m2 & pc(p0) ~= r6)
        }

        action actDisableInit2(p:processor) = {
            call useProc(p);
            call fairInit2(p);
            if (~disableInit2(p)) {
                disableInit2(p) := true;
                call atLevel1(p)
            };
            call monitor()
        }
        action actDisableResp3(p:processor) = {
            call useProc(p);
            call fairResp3(p);
            if (~disableResp3(p)) {
                disableResp3(p) := true;
                call atLevel1(p)
            };
            call monitor()
        }
        action actDisableProcess0 = {
            call fairProcess0();
            if (~disableProcess0) {
                disableProcess0 := true
            };
            call monitor()
        }

        after postlude(p:processor) {
            call monitor()
        }

        export actDisableInit2
        export actDisableResp3
        export actDisableProcess0
    }

    ################################################################################
    #
    # The liveness to safety construction
    #
    ################################################################################

    object l2s = {
        type level = { level1, level2, level3 }

        individual monitor_level : level
        individual lvl : level
        relation frozen
        relation saved
        init ~frozen & ~saved

        # snapshot variables
        individual s_pc(P:processor):location
        individual s_userpmap(P:processor):pmap
        individual s_writepmap(P:processor):pmap
        relation s_actionlock(P:processor)
        relation s_actionneeded(P:processor)
        relation s_active(P:processor)
        relation s_interrupt(P:processor)
        relation s_currentcpu(P:processor, CPU:processor)
        relation s_plock(M:pmap)
        individual s_tlb(P:processor):pageentry
        individual s_pentry(M:pmap):pageentry
        relation s_todo(P1:processor, P2:processor)
        relation s_error

        relation s_disableInit2(P:processor)
        relation s_disableResp3(P:processor)
        relation s_disableProcess0

        # the d relation
        relation d_proc(P:processor)
        relation d_map(M:pmap)
        # the copy used for abstraction
        relation a_proc(P:processor)
        relation a_map(M:pmap)

        # the fairness constraints not yet satisfied
        relation w_scheduled(P:processor)
        relation w_init2(P:processor)
        relation w_resp3(P:processor)
        relation w_process0

        init d_proc(P) <-> (P = liveness.p0)
        init ~d_map(M)
        init w_scheduled(P) = d_proc(P)
        init w_init2(P) = d_proc(P)
        init w_resp3(P) = d_proc(P)
        init w_process0
        
        after useProc(p:processor) {
            d_proc(p) := true
        }
        after useMap(m:pmap) {
            d_map(m) := true
        }

        after fairScheduled(p:processor) {
            w_scheduled(p) := false
        }
        after fairInit2(p:processor) {
            w_init2(p) := false
        }
        after fairResp3(p:processor) {
            w_resp3(p) := false
        }
        after liveness.fairProcess0 {
            w_process0 := false
        }

        before prelude {
            lvl := level3
        }
        after atLevel1(p:processor) {
            if (p = liveness.p0) {
                lvl := level1
            }
        }
        after atLevel2(p:processor) {
            if (p = liveness.p0 |
                (pc(liveness.p0) = i2 & writepmap(p) = writepmap(liveness.p0)) |
                (pc(liveness.p0) = r3 & writepmap(p) = userpmap(liveness.p0))) {
                lvl := level2
            }
        }

        # The monitor from Fig.8 in our paper.
        after liveness.monitor {
            # we use boolean variables frozen and saved for the monitor state.
            # The variable saved is only set when frozen is also set:
            # waiting: ~frozen & ~saved
            # frozen:   frozen & ~saved
            # saved:    frozen &  saved
            if (~frozen &
                ~w_scheduled(P) & ~w_process0 &
                ~w_init2(P) & ~w_resp3(P)) {
                # non-deterministically enter frozen when waiting and W = emptyset
                frozen := *;
                if (frozen) {
                    a_proc(P) := d_proc(P);
                    a_map(M) := d_map(M)
                }
            };
            if (frozen & monitor_level = lvl & ~saved) {
                # non-deterministically enter saved when frozen and level == monitor_level
                saved := *;
                if (saved) {
                    # take snapshot
                    s_pc(P) := pc(P);
                    s_userpmap(P) := userpmap(P);
                    s_writepmap(P) := writepmap(P);
                    s_actionlock(P) := actionlock(P);
                    s_actionneeded(P) := actionneeded(P);
                    s_active(P) := active(P);
                    s_interrupt(P) := interrupt(P);
                    s_currentcpu(P,CPU) := currentcpu(P,CPU);
                    s_plock(P) := plock(P);
                    s_tlb(P) := tlb(P);
                    s_pentry(M) := pentry(M);
                    s_todo(P1,P2) := todo(P1,P2);
                    s_error := error;
    
                    s_disableInit2(P) := liveness.disableInit2(P);
                    s_disableResp3(P) := liveness.disableResp3(P);
                    s_disableProcess0 := liveness.disableProcess0;
    
                    # initialize fairness relations
                    w_scheduled(P) := d_proc(P);
                    w_init2(P) := d_proc(P);
                    w_resp3(P) := d_proc(P);
                    w_process0 := true
                }
            };
            if (frozen) {
                # in states frozen and saved check that lvl >= monitor_level
                assume monitor_level = level2 -> lvl = level2 | lvl = level3;
                assume monitor_level = level3 -> lvl = level3
            }
        }


    conjecture pc(P) ~= b1 -> d_proc(P)
    conjecture (pc(P)=i3 | pc(P)=i4 | pc(P)=i5 | pc(P)=i6 | pc(P)=i7 | pc(P)=i8 | pc(P)=i9) &
               todo(P,C) -> pc(C) ~= b1 & C ~= P
    conjecture (pc(P)=i5 | pc(P)=i6 | pc(P)=i7 | pc(P)=i8) & currentcpu(P,C) -> userpmap(C) = writepmap(P)
    ##NOT ALTERNATION FREE
    conjecture (pc(P)=i4 | pc(P)=i5 | pc(P)=i6 | pc(P)=i7 | pc(P)=i8) -> exists C. currentcpu(P,C)
    
    ## plock is taken by some initiator
    ##NOT ALTERNATION FREE
    conjecture plock(M) ->
       (exists P. writepmap(P) = M &
        (pc(P) = i3 | pc(P) = i4 | pc(P) = i5 | pc(P) = i6 | pc(P) = i7 |
         pc(P) = i8 | pc(P) = i9 | pc(P) = i11 | pc(P) = i12 | pc(P) = i14))
    
    ## actionlock is taken by some initiator or responder
    ##NOT ALTERNATION FREE
    conjecture actionlock(P1) ->
       (pc(P1) = r5 | pc(P1) = r6 | pc(P1) = r7) |
       (exists P2. writepmap(P2) = userpmap(P1) & currentcpu(P2, P1) &
        (pc(P2) = i6 | pc(P2) = i7))

    conjecture saved -> frozen
    conjecture ~w_process0 -> liveness.disableProcess0
    conjecture frozen -> liveness.disableProcess0
    
    conjecture d_proc(liveness.p0)
    conjecture ~w_scheduled(liveness.p0) -> pc(liveness.p0) ~= b1
    conjecture frozen -> a_proc(liveness.p0)
    
    # show that P2 with  todo(P1,P2) and currentcpu(P1,P2) are in d_proc
    # and on level 3 if P1 is the critical process then P2 is even in a_proc
    conjecture (pc(P1) = i3 | pc(P1) = i4 | pc(P1) = i5 | pc(P1) = i6 | pc(P1) = i7 | pc(P1) = i8 | pc(P1) = i9) &
               todo(P1,P2) -> pc(P2) ~= b1 & P2 ~= P1
    conjecture frozen & monitor_level = level3 &
               (P1 = liveness.p0 | (pc(liveness.p0) = i2 & writepmap(liveness.p0) = writepmap(P1)) | (pc(liveness.p0) = r3 & userpmap(liveness.p0) = writepmap(P1))) &
               (pc(P1) = i3 | pc(P1) = i4 | pc(P1) = i5 | pc(P1) = i6 | pc(P1) = i7 | pc(P1) = i8 | pc(P1) = i9) &
               todo(P1, P2) -> a_proc(P2)
    conjecture saved & monitor_level = level3 &
               (P1 = liveness.p0 | (s_pc(liveness.p0) = i2 & s_writepmap(liveness.p0) = s_writepmap(P1)) | (s_pc(liveness.p0) = r3 & s_userpmap(liveness.p0) = s_writepmap(P1))) &
               (s_pc(P1) = i3 | s_pc(P1) = i4 | s_pc(P1) = i5 | s_pc(P1) = i6 | s_pc(P1) = i7 | s_pc(P1) = i8 | s_pc(P1) = i9) &
               s_todo(P1,P2) -> a_proc(P2) & s_pc(P2) ~= b1 & P2 ~= P1
    
    conjecture 
       (pc(P1) = i4 | pc(P1) = i5 | pc(P1) = i6 | pc(P1) = i7 | pc(P1) = i8) &
       currentcpu(P1, CPU) -> d_proc(CPU) & ~todo(P1,CPU)
    conjecture frozen & monitor_level = level3 &
       (P1 = liveness.p0 | 
        (pc(liveness.p0) = i2 & writepmap(P1) = writepmap(liveness.p0)) |
        (pc(liveness.p0) = r3 & writepmap(P1) = userpmap(liveness.p0))) &
       (pc(P1) = i4 | pc(P1) = i5 | pc(P1) = i6 | pc(P1) = i7 | pc(P1) = i8) &
       currentcpu(P1, CPU) -> a_proc(CPU)
    conjecture saved & monitor_level = level3 &
       (P1 = liveness.p0 | 
        (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0)) |
        (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0))) &
       (s_pc(P1) = i4 | s_pc(P1) = i5 | s_pc(P1) = i6 | s_pc(P1) = i7 | s_pc(P1) = i8) &
       s_currentcpu(P1, CPU) -> ~todo(P1, CPU) & a_proc(CPU)
    
    
    # As long as a process wasn't scheduled it stays in its location
    conjecture saved & w_scheduled(P) -> s_pc(P) = pc(P)
    
    # lift some lemmas to saved
    conjecture saved -> (s_active(P) <->
      (s_pc(P) = b1 | s_pc(P) = m2 | s_pc(P) = m3 | s_pc(P) = m5 |
       s_pc(P) = i1 | s_pc(P) = r1 | s_pc(P) = r2))
    conjecture saved -> 
      (s_pc(P1)=i3 | s_pc(P1)=i4 | s_pc(P1)=i5 | s_pc(P1)=i6 | s_pc(P1)=i7 | s_pc(P1)=i8 | s_pc(P1)=i9 | s_pc(P1)=i11 | s_pc(P1)=i12 | s_pc(P1)=i14)
      & (s_pc(P2)=i3 | s_pc(P2)=i4 | s_pc(P2)=i5 | s_pc(P2)=i6 | s_pc(P2)=i7 | s_pc(P2)=i8 | s_pc(P2)=i9 | s_pc(P2)=i11 | s_pc(P2)=i12 | s_pc(P2)=i14)
       -> s_writepmap(P1) ~= s_writepmap(P2) | P1 = P2
    
    
    # The disabled flags are monotonous
    conjecture saved & s_disableInit2(P) -> liveness.disableInit2(P)
    conjecture saved & s_disableResp3(P) -> liveness.disableResp3(P)
    
    conjecture liveness.disableInit2(P) -> pc(P) ~= i2 | plock(writepmap(P))
    conjecture liveness.disableResp3(P) -> pc(P) ~= r3 | plock(userpmap(P))
    
    # As long as a process is not scheduled it stays in its location
    conjecture saved & w_scheduled(P) -> s_pc(P) = pc(P)

    # Process liveness.p0 can only go in one direction, except for the i3-i8 loop.
    # it also makes progress except for some level2/level3 steps.
    conjecture saved & s_pc(liveness.p0) = m2 ->
        pc(liveness.p0) ~= m2 | w_scheduled(liveness.p0)
    conjecture saved & s_pc(liveness.p0) = m3 ->
        pc(liveness.p0) ~= m2 & (pc(liveness.p0) ~= m3 | w_scheduled(liveness.p0))
    conjecture saved & (s_pc(liveness.p0) = i1 | s_pc(liveness.p0) = i2) ->
       (pc(liveness.p0) = i2 | pc(liveness.p0) = i3 | pc(liveness.p0) = i4 | pc(liveness.p0) = i5 |
        pc(liveness.p0) = i6 | pc(liveness.p0) = i7 | pc(liveness.p0) = i8 | pc(liveness.p0) = i9 |
        pc(liveness.p0) = i11 | pc(liveness.p0) = i12 | pc(liveness.p0) = i14 | pc(liveness.p0) = i15 |
        pc(liveness.p0) = m5 | 
        pc(liveness.p0) = r1 | pc(liveness.p0) = r2 | pc(liveness.p0) = r3 | pc(liveness.p0) = r5 |
        w_scheduled(liveness.p0))
    conjecture saved & s_pc(liveness.p0) = i2 & lvl = level1 ->
       (pc(liveness.p0) ~= i2 | w_scheduled(liveness.p0) |
        s_disableInit2(liveness.p0) ~= liveness.disableInit2(liveness.p0) |
        s_disableResp3(liveness.p0) ~= liveness.disableResp3(liveness.p0))
    conjecture saved &
       (s_pc(liveness.p0) = i3 | s_pc(liveness.p0) = i4 | s_pc(liveness.p0) = i5 | s_pc(liveness.p0) = i6 |
        s_pc(liveness.p0) = i7 | s_pc(liveness.p0) = i8) ->
       (pc(liveness.p0) = i3 | pc(liveness.p0) = i4 | pc(liveness.p0) = i5 | pc(liveness.p0) = i6 |
        pc(liveness.p0) = i7 | pc(liveness.p0) = i8 |
        pc(liveness.p0) = i9 | pc(liveness.p0) = i11 |
        pc(liveness.p0) = i12 | pc(liveness.p0) = i14 | pc(liveness.p0) = i15 |
        pc(liveness.p0) = m5 | 
        pc(liveness.p0) = r1 | pc(liveness.p0) = r2 | pc(liveness.p0) = r3 | pc(liveness.p0) = r5)
    conjecture saved & lvl ~= level3 &
       (s_pc(liveness.p0) = i3 | s_pc(liveness.p0) = i4 | s_pc(liveness.p0) = i5 | s_pc(liveness.p0) = i6 |
        s_pc(liveness.p0) = i7 | s_pc(liveness.p0) = i8) ->
       (pc(liveness.p0) = i9 | pc(liveness.p0) = i11 |
        pc(liveness.p0) = i12 | pc(liveness.p0) = i14 | pc(liveness.p0) = i15 |
        pc(liveness.p0) = m5 | 
        pc(liveness.p0) = r1 | pc(liveness.p0) = r2 | pc(liveness.p0) = r3 | pc(liveness.p0) = r5 |
        w_scheduled(liveness.p0) |
        s_disableInit2(liveness.p0) ~= liveness.disableInit2(liveness.p0) |
        s_disableResp3(liveness.p0) ~= liveness.disableResp3(liveness.p0))
    conjecture saved & s_pc(liveness.p0) = i9 ->
       (pc(liveness.p0) = i9 | pc(liveness.p0) = i11 |
        pc(liveness.p0) = i12 | pc(liveness.p0) = i14 | pc(liveness.p0) = i15 |
        pc(liveness.p0) = m5 | 
        pc(liveness.p0) = r1 | pc(liveness.p0) = r2 | pc(liveness.p0) = r3 | pc(liveness.p0) = r5)
    conjecture saved & lvl ~= level3 & s_pc(liveness.p0) = i9 ->
       (pc(liveness.p0) ~= i9 | w_scheduled(liveness.p0) |
        s_disableInit2(liveness.p0) ~= liveness.disableInit2(liveness.p0) |
        s_disableResp3(liveness.p0) ~= liveness.disableResp3(liveness.p0))
    conjecture saved & s_pc(liveness.p0) = i11 ->
       (pc(liveness.p0) = i12 | pc(liveness.p0) = i14 | pc(liveness.p0) = i15 |
        pc(liveness.p0) = m5 | 
        pc(liveness.p0) = r1 | pc(liveness.p0) = r2 | pc(liveness.p0) = r3 | pc(liveness.p0) = r5 |
        w_scheduled(liveness.p0))
    conjecture saved & s_pc(liveness.p0) = i12 ->
       (pc(liveness.p0) = i14 | pc(liveness.p0) = i15 |
        pc(liveness.p0) = m5 | 
        pc(liveness.p0) = r1 | pc(liveness.p0) = r2 | pc(liveness.p0) = r3 | pc(liveness.p0) = r5 |
        w_scheduled(liveness.p0))
    conjecture saved & s_pc(liveness.p0) = i14 ->
       (pc(liveness.p0) = i15 |
        pc(liveness.p0) = m5 | 
        pc(liveness.p0) = r1 | pc(liveness.p0) = r2 | pc(liveness.p0) = r3 | pc(liveness.p0) = r5 |
        w_scheduled(liveness.p0))
    conjecture saved & s_pc(liveness.p0) = i15 ->
       (pc(liveness.p0) = m5 | 
        pc(liveness.p0) = r1 | pc(liveness.p0) = r2 | pc(liveness.p0) = r3 | pc(liveness.p0) = r5 |
        w_scheduled(liveness.p0))
    conjecture saved & s_pc(liveness.p0) = m5 ->
       (pc(liveness.p0) = r1 | pc(liveness.p0) = r2 | pc(liveness.p0) = r3 | pc(liveness.p0) = r5 |
       w_scheduled(liveness.p0))
    conjecture saved & s_pc(liveness.p0) = r1 ->
       (pc(liveness.p0) = r2 | pc(liveness.p0) = r3 | pc(liveness.p0) = r5 | w_scheduled(liveness.p0))
    conjecture saved & s_pc(liveness.p0) = r2 ->
       (pc(liveness.p0) = r3 | pc(liveness.p0) = r5 | w_scheduled(liveness.p0))
    conjecture saved & s_pc(liveness.p0) = r3 ->
       (pc(liveness.p0) = r3 | pc(liveness.p0) = r5)
    conjecture saved & s_pc(liveness.p0) = r3 & lvl = level1 ->
       (pc(liveness.p0) = r5 | w_scheduled(liveness.p0) | 
        s_disableInit2(liveness.p0) ~= liveness.disableInit2(liveness.p0) |
        s_disableResp3(liveness.p0) ~= liveness.disableResp3(liveness.p0))
    conjecture saved & s_pc(liveness.p0) = r5 -> w_scheduled(liveness.p0)
    conjecture saved & s_pc(liveness.p0) = r6 ->
       (pc(liveness.p0) = r7 | pc(liveness.p0) = r8 |
        pc(liveness.p0) = r1 | pc(liveness.p0) = r2 | pc(liveness.p0) = r3 | pc(liveness.p0) = r5 |
        w_scheduled(liveness.p0))
    conjecture saved & s_pc(liveness.p0) = r7 ->
       (pc(liveness.p0) = r8 |
        pc(liveness.p0) = r1 | pc(liveness.p0) = r2 | pc(liveness.p0) = r3 | pc(liveness.p0) = r5 |
        w_scheduled(liveness.p0))
    conjecture saved & s_pc(liveness.p0) = r8 ->
       (pc(liveness.p0) = r1 | pc(liveness.p0) = r2 | pc(liveness.p0) = r3 | pc(liveness.p0) = r5 |
        w_scheduled(liveness.p0))

    # if we freeze on level2/level3 and p0 is in waiting on the lock in i2/r3, then the processor that
    # has the lock is in the a_proc set.
    conjecture frozen & monitor_level ~= level1 & liveness.disableInit2(liveness.p0) & pc(liveness.p0) = i2 ->
      exists P1. a_proc(P1) & writepmap(P1) = writepmap(liveness.p0) &
        (pc(P1)=i3 | pc(P1)=i4 | pc(P1)=i5 | pc(P1)=i6 | pc(P1)=i7 | pc(P1)=i8 | pc(P1)=i9 | pc(P1)=i11 | pc(P1)=i12 | pc(P1)=i14)
    conjecture frozen & monitor_level ~= level1 & liveness.disableResp3(liveness.p0) & pc(liveness.p0) = r3 ->
      exists P1. a_proc(P1) & writepmap(P1) = userpmap(liveness.p0) &
        (pc(P1)=i3 | pc(P1)=i4 | pc(P1)=i5 | pc(P1)=i6 | pc(P1)=i7 | pc(P1)=i8 | pc(P1)=i9 | pc(P1)=i11 | pc(P1)=i12 | pc(P1)=i14)
    # and the same for saved
    conjecture saved & monitor_level ~= level1 & s_disableInit2(liveness.p0) & s_pc(liveness.p0) = i2 ->
      exists P1. s_writepmap(P1) = s_writepmap(liveness.p0) &
        (s_pc(P1)=i3 | s_pc(P1)=i4 | s_pc(P1)=i5 | s_pc(P1)=i6 | s_pc(P1)=i7 | s_pc(P1)=i8 | s_pc(P1)=i9 | s_pc(P1)=i11 | s_pc(P1)=i12 | s_pc(P1)=i14)
    conjecture saved & monitor_level ~= level1 & s_disableResp3(liveness.p0) & s_pc(liveness.p0) = r3 ->
      exists P1. s_writepmap(P1) = s_userpmap(liveness.p0) &
        (s_pc(P1)=i3 | s_pc(P1)=i4 | s_pc(P1)=i5 | s_pc(P1)=i6 | s_pc(P1)=i7 | s_pc(P1)=i8 | s_pc(P1)=i9 | s_pc(P1)=i11 | s_pc(P1)=i12 | s_pc(P1)=i14)
    
    # if liveness.p0 is waiting for lock in init2 and strong fairness calls, it is scheduled and never comes back.
    conjecture saved & s_pc(liveness.p0) = i2 & ~liveness.disableInit2(liveness.p0) & ~w_init2(liveness.p0) ->
      pc(liveness.p0) ~= i2
    # same for resp3
    conjecture saved & s_pc(liveness.p0) = r3 & ~liveness.disableResp3(liveness.p0) & ~w_resp3(liveness.p0) ->
      pc(liveness.p0) ~= r3
    
    # if liveness.p0 is waiting for lock in init2 or resp2 and we decide to never enable
    # init2 for liveness.p0 again, liveness.p0 is trapped
    conjecture saved & s_pc(liveness.p0) = i2 & s_disableInit2(liveness.p0) ->
      pc(liveness.p0) = i2 & writepmap(liveness.p0) = s_writepmap(liveness.p0)
    conjecture saved & s_pc(liveness.p0) = r3 & s_disableResp3(liveness.p0) ->
      pc(liveness.p0) = r3 & userpmap(liveness.p0) = s_userpmap(liveness.p0)
    
    # and so is every process that blocks the lock
    conjecture saved & monitor_level ~= level1 & 
      (  (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0) & s_disableInit2(liveness.p0))
       | (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0) & s_disableResp3(liveness.p0))) &
        (s_pc(P1) = i3 | s_pc(P1) = i4 | s_pc(P1) = i5 | s_pc(P1) = i6 |
         s_pc(P1) = i7 | s_pc(P1) = i8 | s_pc(P1) = i9 | s_pc(P1) = i11 |
         s_pc(P1) = i12 | s_pc(P1) = i14) ->
        s_writepmap(P1) = writepmap(P1) &
        (pc(P1) = i3 | pc(P1) = i4 | pc(P1) = i5 | pc(P1) = i6 |
         pc(P1) = i7 | pc(P1) = i8 | pc(P1) = i9 | pc(P1) = i11 |
         pc(P1) = i12 | pc(P1) = i14)
    
    # ... it can only go forward
    conjecture saved & monitor_level ~= level1 & 
      (  (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0) & s_disableInit2(liveness.p0))
       | (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0) & s_disableResp3(liveness.p0))) &
        s_pc(P1) = i9 ->
        (pc(P1) = i9 | pc(P1) = i11 | pc(P1) = i12 | pc(P1) = i14)
    conjecture saved & monitor_level ~= level1 & 
      (  (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0) & s_disableInit2(liveness.p0))
       | (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0) & s_disableResp3(liveness.p0))) &
        s_pc(P1) = i11 ->
        (pc(P1) = i12 | pc(P1) = i14 | w_scheduled(P1))
    conjecture saved & monitor_level ~= level1 & 
      (  (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0) & s_disableInit2(liveness.p0))
       | (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0) & s_disableResp3(liveness.p0))) &
        s_pc(P1) = i12 ->
        s_writepmap(P1) = writepmap(P1) &
        (pc(P1) = i14 | w_scheduled(P1))
    conjecture saved & monitor_level ~= level1 & 
      (  (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0) & s_disableInit2(liveness.p0))
       | (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0) & s_disableResp3(liveness.p0))) &
        s_pc(P1) = i14 ->
        s_writepmap(P1) = writepmap(P1) &
        (w_scheduled(P1))
    
    # ... and it must make progress if scheduled on level2
    conjecture saved & monitor_level ~= level1 & lvl = level2 ->
      (  (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0) & s_disableInit2(liveness.p0))
       | (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0) & s_disableResp3(liveness.p0))) &
        (s_pc(P1) = i3 | s_pc(P1) = i4 | s_pc(P1) = i5 | s_pc(P1) = i6 |
         s_pc(P1) = i7 | s_pc(P1) = i8) ->
        (w_scheduled(P1) | pc(P1) = i9 | pc(P1) = i11 | pc(P1) = i12 | pc(P1) = i14)
    conjecture saved & monitor_level ~= level1 & lvl = level2 ->
      (  (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0) & s_disableInit2(liveness.p0))
       | (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0) & s_disableResp3(liveness.p0))) &
      s_pc(P1) = i9 -> w_scheduled(P1) | pc(P1) ~= i9

    # it remains to show that the i3-i8 loop and the i9 loop terminate on level 3
    
    ## level3:
    # On level3 P1 is locked into i3-i8 loop or i9 loop
    conjecture saved & monitor_level = level3 &
       (P1 = liveness.p0 |
        (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0)) |
        (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0))) &
       (s_pc(P1) = i3 | s_pc(P1) = i4 | s_pc(P1) = i5 | s_pc(P1) = i6 | s_pc(P1) = i7 | s_pc(P1) = i8)
        ->
       writepmap(P1) = s_writepmap(P1) &
       (pc(P1) = i3 | pc(P1) = i4 | pc(P1) = i5 | pc(P1) = i6 | pc(P1) = i7 | pc(P1) = i8) &
       (P1 = liveness.p0 |
        (pc(liveness.p0) = i2 & writepmap(P1) = writepmap(liveness.p0)) |
        (pc(liveness.p0) = r3 & writepmap(P1) = userpmap(liveness.p0)))
    conjecture saved & monitor_level = level3 &
       (P1 = liveness.p0 |
        (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0)) |
        (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0))) &
       s_pc(P1) = i9
        ->
       writepmap(P1) = s_writepmap(P1) &
       pc(P1) = i9 &
       (P1 = liveness.p0 |
        (pc(liveness.p0) = i2 & writepmap(P1) = writepmap(liveness.p0)) |
        (pc(liveness.p0) = r3 & writepmap(P1) = userpmap(liveness.p0)))
    
    # todo monotonous
    conjecture saved & monitor_level = level3 &
       (P1 = liveness.p0 | 
        (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0)) |
        (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0))) &
       (s_pc(P1) = i3 | s_pc(P1) = i4 | s_pc(P1) = i5 | s_pc(P1) = i6 |
        s_pc(P1) = i7 | s_pc(P1) = i8 | s_pc(P1) = i9) ->
       todo(P1,P2) -> s_todo(P1,P2)

    # if we are in the i5, we hold the lock for the page map for each cpu and we never release it
    conjecture saved & monitor_level = level3 &
       (P1 = liveness.p0 | 
        (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0)) |
        (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0))) &
       s_pc(P1) = i5 & s_currentcpu(P1,CPU) ->
       userpmap(CPU) = writepmap(P1)
    
    # while some process is waiting to enter actionlock in i5, the other CPU
    # cannot enter its actionlock.
    conjecture saved & monitor_level = level3 &
       (P1 = liveness.p0 | 
        (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0)) |
        (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0))) &
       s_pc(P1) = i5 & s_currentcpu(P1, CPU) & 
       s_pc(CPU) ~= r5 & s_pc(CPU) ~= r6 & s_pc(CPU) ~= r7 ->
       pc(CPU) ~= r5 & pc(CPU) ~= r6 & pc(CPU) ~= r7
    # ... and if it entered it before, it has to change when scheduled.
    conjecture saved & monitor_level = level3 &
       (P1 = liveness.p0 | 
        (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0)) |
        (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0))) &
       s_pc(P1) = i5 & s_currentcpu(P1, CPU) & ~w_scheduled(CPU) ->
       (s_pc(CPU) = r5 -> pc(CPU) ~= r5) &
       (s_pc(CPU) = r6 -> pc(CPU) ~= r5 & pc(CPU) ~= r6) &
       (s_pc(CPU) = r7 -> pc(CPU) ~= r5 & pc(CPU) ~= r6 & pc(CPU) ~= r7)
    
    # others change currentcpu or go only until i3
    conjecture saved & monitor_level = level3 &
       (P1 = liveness.p0 | 
        (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0)) |
        (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0))) &
       (s_pc(P1) = i4 | s_pc(P1) = i5 | s_pc(P1) = i6 | s_pc(P1) = i7 | s_pc(P1) = i8) &
       s_currentcpu(P1, CPU) ->
       w_scheduled(P1) | ~currentcpu(P1, CPU) | pc(P1) = i3 |
       (pc(P1) = i8 & s_pc(P1) ~= i8) |
       (pc(P1) = i7 & s_pc(P1) ~= i8 & s_pc(P1) ~= i7) | 
       (pc(P1) = i6 & s_pc(P1) ~= i8 & s_pc(P1) ~= i7 & s_pc(P1) ~= i6) | 
       (pc(P1) = i5 & s_pc(P1) ~= i8 & s_pc(P1) ~= i7 & s_pc(P1) ~= i6 &
        (s_pc(P1) ~= i5 | s_pc(CPU) = r5 | s_pc(CPU) = r6 | s_pc(CPU) = r7))

    # Finally, show that i9 loop terminates

    # If it waits for a process that is in m5-r3, that process is trapped (because the lock is taken by P1)
    conjecture saved & monitor_level = level3 &
       (P1 = liveness.p0 | 
        (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0)) |
        (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0))) &
      s_pc(P1) = i9 & 
      todo(P1,P2) & userpmap(P2) = writepmap(P1) & P1 ~= P2 &
      (s_pc(P2) = m5 | s_pc(P2) = r1 | s_pc(P2) = r2 | s_pc(P2) = r3)
      ->
      (pc(P2) = m5 | pc(P2) = r1 | pc(P2) = r2 | pc(P2) = r3)
    
    # If P1 is waiting for P2 in second loop on level3,
    #  and P2 is active and scheduled, then P2 did make progress
    conjecture saved & monitor_level = level3 &
       (P1 = liveness.p0 | 
        (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0)) |
        (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0))) &
      s_pc(P1) = i9 & 
      todo(P1,P2) & userpmap(P2) = writepmap(P1) &
      active(P2) & ~w_scheduled(P2)
      ->
      (s_pc(P2) = m2 &
         (pc(P2) = m3 | pc(P2) = i1 | pc(P2) = m5 | pc(P2) = r1 | pc(P2) = r2)) |
      (s_pc(P2) = m3 &
         (pc(P2) = i1 | pc(P2) = m5 | pc(P2) = r1 | pc(P2) = r2)) |
      (s_pc(P2) = i1 &
         (pc(P2) = m5 | pc(P2) = r1 | pc(P2) = r2)) |
      (~s_active(P2) & s_pc(P2) ~= r3 &
         (pc(P2) = m5 | pc(P2) = r1 | pc(P2) = r2)) |
      (s_pc(P2) = m5 &
         (pc(P2) = r1 | pc(P2) = r2)) |
      (s_pc(P2) = r1 &
         (pc(P2) = r2))
    
    # This finally shows that for s_pc=i3 and s_pc=i9  the loops terminate
    # for i3 it shows that todo shrinks
    # for i9 if todo doesn't shrink, the process it was waiting for makes progress.
    conjecture saved & monitor_level = level3 &
      ((s_disableInit2(liveness.p0) & s_pc(liveness.p0) = i2) |
       (s_disableResp3(liveness.p0) & s_pc(liveness.p0) = r3) |
       s_pc(liveness.p0) = i3 | s_pc(liveness.p0) = i9) ->
      exists P1. a_proc(P1) &
        (P1 = liveness.p0 | 
         (s_pc(liveness.p0) = i2 & s_writepmap(P1) = s_writepmap(liveness.p0)) |
         (s_pc(liveness.p0) = r3 & s_writepmap(P1) = s_userpmap(liveness.p0))) &
        (s_pc(P1) = i3 | s_pc(P1) = i4 | s_pc(P1)=i5 | s_pc(P1)=i6 | s_pc(P1)=i7 | s_pc(P1)=i8 | s_pc(P1)=i9 | s_pc(P1)=i11 | s_pc(P1)=i12 | s_pc(P1)=i14) &
        (s_pc(P1) = i3 & ~w_scheduled(P1) ->
          (exists P2. s_todo(P1,P2) & ~todo(P1,P2))) &
        (s_pc(P1) = i9 & ~w_scheduled(P1) ->
          (exists P2. s_todo(P1,P2) &
               (~todo(P1,P2) | (userpmap(P2) = writepmap(P1) & P1 ~= P2 & s_pc(P2) ~= r3 &
                                (active(P2) | pc(P2) = r3 | s_pc(P2) = i1 | s_pc(P2) = m2 | s_pc(P2) = m3)))))

    # This is the liveness to safety verification condition:
    # If saved and the last step was on the freeze level,
    # there is either a fairness condition not satisfied or some relation or individual changed
    conjecture saved & monitor_level = lvl ->
         (exists P:processor. w_scheduled(P) | w_init2(P) | w_resp3(P)) |
         w_process0 |
         s_disableProcess0 ~= liveness.disableProcess0 |
         s_error ~= error |
         (exists P:processor.
                  a_proc(P) &
               (s_pc(P) ~= pc(P) |
                s_disableInit2(P) ~= liveness.disableInit2(P) |
                s_disableResp3(P) ~= liveness.disableResp3(P) |
                (s_userpmap(P) ~= userpmap(P) & a_map(s_userpmap(P)) & a_map(userpmap(P))) |
                (s_writepmap(P) ~= writepmap(P) & a_map(s_writepmap(P)) & a_map(writepmap(P))) |
                s_actionlock(P) ~= actionlock(P) |
                s_actionneeded(P) ~= actionneeded(P) |
                s_active(P) ~= active(P) |
                s_interrupt(P) ~= interrupt(P))) | 
         (exists P:processor, P2:processor.
                  a_proc(P) & a_proc(P2) &
                (s_currentcpu(P,P2) ~= currentcpu(P,P2) |
                s_todo(P,P2) ~= todo(P,P2))) |
         (exists M:pmap.
                  a_map(M) &
               (s_plock(M) ~= plock(M)))

    }
}
