// Package lalr_full provides a full LALR(1) parser for Ivy, generated by
// goyacc, mechanically translated from the Python PLY grammar. It parses
// complete Ivy files (top-level declarations), unlike lalr_logicparser
// which only handles formulas/terms/actions.
package lalr_full

import (
	"github.com/glycerine/goivy/ast"
)

// ParseResult bundles the declarations returned by the LALR parser.
// This matches the structure of parser.ParseResult so consumers can
// use either parser interchangeably. We define it here to avoid a
// circular import on the parser package.
type ParseResult struct {
	Decls   []ast.Node
	Modules map[string]*ast.ModuleDecl
}

// ivyAccum is the internal accumulator used during LALR parsing.
// It mirrors the Python Ivy class's role as a declaration collector
// during parsing (ivy_parser.py Ivy class). After parsing completes,
// this is converted into a ParseResult.
//
// This is NOT a replacement for module.Module — that is the compiled
// semantic representation. This is just the raw parse-time collector.
type ivyAccum struct {
	decls    []ast.Node
	modules  map[string]*ast.ModuleDecl
	macros   map[string]ast.Node
	actions  map[string]ast.Node
	included map[string]bool
	isModule bool
	params   []ast.Node
}

// newIvyAccum creates a fresh accumulator, matching Python Ivy.__init__.
func newIvyAccum() *ivyAccum {
	return &ivyAccum{
		modules:  make(map[string]*ast.ModuleDecl),
		macros:   make(map[string]ast.Node),
		actions:  make(map[string]ast.Node),
		included: make(map[string]bool),
	}
}

// declare adds a declaration, matching Python Ivy.declare().
func (m *ivyAccum) declare(decl ast.Node) {
	m.decls = append(m.decls, decl)
	// Track modules for lookup during instantiation.
	if md, ok := decl.(*ast.ModuleDecl); ok {
		for _, arg := range md.Args() {
			if d, ok := arg.(*ast.Definition); ok {
				if a, ok := d.Lhs.(*ast.Atom); ok {
					m.modules[a.Rep] = md
				}
			}
		}
	}
	if ad, ok := decl.(*ast.ActionDecl); ok {
		for _, arg := range ad.Args() {
			if d, ok := arg.(*ast.ActionDef); ok {
				if d.Name != nil {
					if a, ok := d.Name.(*ast.Atom); ok {
						m.actions[a.Rep] = ad
					}
				}
			}
		}
	}
}

// toResult converts the accumulator into a ParseResult.
func (m *ivyAccum) toResult() *ParseResult {
	return &ParseResult{
		Decls:   m.decls,
		Modules: m.modules,
	}
}
