// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/builtins.go

// Copyright 2012 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file implements typechecking of builtin function calls.

import { PosOf, Unparen, type CallExpr, type SelectorExpr } from "../../front/ast.js";
import type { Type } from "./type.js";
import { Array as ArrayType } from "./array.js";
import { Basic, Complex128, Complex64, Float32, Float64, Int, String as StringKind, Uintptr, UnsafePointer, UntypedComplex, UntypedFloat } from "./basic.js";
import { Chan, ChanDir } from "./chan.js";
import { Checker, atPos, nopos } from "./check.js";
import { imag, makeComplex, real } from "./const.js";
import { invalidArg, invalidOp } from "./errors.js";
import { Interface, emptyInterface, NewInterfaceType } from "./interface.js";
import { derefStructPtr, lookupFieldOrMethod } from "./lookup.js";
import { Map as MapType } from "./map.js";
import { Named } from "./named.js";
import { Func, NewParam, NewTypeName, ResultVar, newVar } from "./object.js";
import { operand, builtin as builtinMode, constant_, invalid, novalue, typexpr, value, variable } from "./operand.js";
import { NewPointer, Pointer } from "./pointer.js";
import { allOrdered, allString, Comparable, Default, Identical, isBoolean, isComplex, isInteger, isNumeric, isString, isTypeParam, isUntyped, isValid } from "./predicates.js";
import { FieldVal } from "./selection.js";
import { Signature } from "./signature.js";
import { NewSlice, Slice } from "./slice.js";
import { Struct } from "./struct.js";
import { NewTuple } from "./tuple.js";
import { TypeParam } from "./typeparam.js";
import { term } from "./typeterm.js";
import { commonUnder, typeError, typeErrorf, typeset, underIs } from "./under.js";
import { NewTerm, NewUnion, Term } from "./union.js";
import { builtinId, predeclaredFuncs, Typ, universeByte } from "./universe.js";
import { go1_17, go1_20, go1_21, go1_26 } from "./version.js";
import { Unalias } from "./alias.js";
import { assert } from "./util.js";

declare module "./check.js" {
  interface Checker {
    builtin(x: operand, call: unknown, id: builtinId | null): boolean;
    hasVarSize(t: Type): boolean;
    applyTypeFunc(f: (typ: Type) => Type | null, x: operand, id: builtinId): Type | null;
    recordTypes(): boolean;
    recordBuiltinType(f: unknown, sig: Signature): void;
  }
}

Checker.prototype.recordTypes = function recordTypes(): boolean {
  return this.Info.recordTypes();
};

// builtin type-checks a call to the built-in specified by id and
// reports whether the call is valid, with *x holding the result;
// but x.expr is not set. If the call is invalid, the result is
// false, and *x is undefined.
Checker.prototype.builtin = function builtin(x: operand, call0: unknown, id0: builtinId | null): boolean {
  assert(id0 !== null);
  const id = id0;
  const call = call0 as CallExpr;
  const argList = call.args;

  // append is the only built-in that permits the use of ... for the last argument
  const bin = predeclaredFuncs[id]!;
  if (call.ellipsis && id !== builtinId._Append) {
    this.errorf(call, "InvalidDotDotDot", invalidOp + "invalid use of ... with built-in %s", bin.name);
    this.use(...argList);
    return false;
  }

  // For len(x) and cap(x) we need to know if x contains any function calls or
  // receive operations. Save/restore current setting and set hasCallOrRecv to
  // false for the evaluation of x so that we can check it afterwards.
  // Note: We must do this _before_ calling exprList because exprList evaluates
  //       all arguments.
  const savedHasCallOrRecv = this.hasCallOrRecv;
  if (id === builtinId._Len || id === builtinId._Cap) {
    this.hasCallOrRecv = false;
  }

  try {
    // Evaluate arguments for built-ins that use ordinary (value) arguments.
    // For built-ins with special argument handling (make, new, etc.),
    // evaluation is done by the respective built-in code.
    let args: operand[] = []; // not valid for _Make, _New, _Offsetof, _Trace
    let nargs: number;
    switch (id) {
      default:
        // check all arguments
        args = this.exprList(argList);
        nargs = args.length;
        for (const a of args) {
          if (!a.isValid()) {
            return false;
          }
        }
        // first argument is always in x
        if (nargs > 0) {
          copyOperand(x, args[0]!);
        }
        break;
      case builtinId._Make:
      case builtinId._New:
      case builtinId._Offsetof:
      case builtinId._Trace:
        // arguments require special handling
        nargs = argList.length;
        break;
    }

    // check argument count
    {
      let msg = "";
      if (nargs < bin.nargs) {
        msg = "not enough";
      } else if (!bin.variadic && nargs > bin.nargs) {
        msg = "too many";
      }
      if (msg !== "") {
        this.errorf(call, "WrongArgCount", invalidOp + "%s arguments for %v (expected %d, found %d)", msg, call, bin.nargs, nargs);
        return false;
      }
    }

    switch (id) {
      case builtinId._Append: {
        // append(s S, x ...E) S, where E is the element type of S
        const [E, err] = sliceElem(x);
        if (err !== null) {
          this.errorf(x, "InvalidAppend", "invalid append: %s", err.format(this));
          return false;
        }

        let sig: Signature | null = null;
        if (nargs === 2 && call.ellipsis) {
          if (x.assignableTo(this, NewSlice(universeByte), null)[0]) {
            let y: operand | null = args[1]!;
            let hasString = false;
            for (const [, u] of typeset(y.typ()!)) {
              if (u instanceof Slice && Identical(u.elem, universeByte)) {
                // typeset ⊇ {[]byte}
              } else if (u !== null && isString(u)) {
                // typeset ⊇ {string}
                hasString = true;
              } else {
                y = null;
                break;
              }
            }
            if (y !== null && hasString) {
              // setting the signature also signals that we're done
              sig = makeSig(x.typ(), x.typ()!, y.typ()!);
              sig.variadic = true;
            }
          }
        }

        if (sig === null) {
          // check arguments by creating custom signature
          sig = makeSig(x.typ(), x.typ()!, NewSlice(E!)); // []E required for variadic signature
          sig.variadic = true;
          this.arguments(call, sig, null, null, args, null); // discard result (we know the result type)
          // ok to continue even if check.arguments reported errors
        }

        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, sig);
        }
        x.mode_ = value;
        // x.typ is unchanged
        break;
      }

      case builtinId._Cap:
      case builtinId._Len: {
        // cap(x)
        // len(x)
        let mode = invalid;
        let val: unknown = null;
        const t = arrayPtrDeref(x.typ()!.Underlying());
        if (t instanceof Basic) {
          if (isString(t) && id === builtinId._Len) {
            if (x.mode() === constant_) {
              mode = constant_;
              val = String(x.val).length;
            } else {
              mode = value;
            }
          }
        } else if (t instanceof ArrayType) {
          mode = value;
          if (!this.hasCallOrRecv) {
            mode = constant_;
            val = t.len >= 0 ? BigInt(t.len) : null;
          }
        } else if (t instanceof Slice || t instanceof Chan) {
          mode = value;
        } else if (t instanceof MapType) {
          if (id === builtinId._Len) {
            mode = value;
          }
        } else if (t instanceof Interface) {
          if (!isTypeParam(x.typ()!)) {
            break;
          }
          if (underIs(x.typ()!, (u: Type | null) => {
            const tt = u !== null ? arrayPtrDeref(u) : null;
            if (tt instanceof Basic) {
              if (isString(tt) && id === builtinId._Len) {
                return true;
              }
            } else if (tt instanceof ArrayType || tt instanceof Slice || tt instanceof Chan) {
              return true;
            } else if (tt instanceof MapType) {
              if (id === builtinId._Len) {
                return true;
              }
            }
            return false;
          })) {
            mode = value;
          }
        }

        if (mode === invalid) {
          // avoid error if underlying type is invalid
          if (isValid(x.typ()!.Underlying())) {
            let code: unknown = "InvalidCap";
            if (id === builtinId._Len) {
              code = "InvalidLen";
            }
            this.errorf(x, code, invalidArg + "%s for built-in %s", x, bin.name);
          }
          return false;
        }

        // record the signature before changing x.typ
        if (this.recordTypes() && mode !== constant_) {
          this.recordBuiltinType(call.fun, makeSig(Typ[Int]!, x.typ()!));
        }

        x.mode_ = mode;
        x.typ_ = Typ[Int]!;
        x.val = val;
        break;
      }

      case builtinId._Clear:
        // clear(m)
        this.verifyVersionf(atPos(PosOf(call.fun)), go1_21, "clear");

        if (!underIs(x.typ()!, (u: Type | null) => {
          if (u instanceof MapType || u instanceof Slice) {
            return true;
          }
          this.errorf(x, "InvalidClear", invalidArg + "cannot clear %s: argument must be (or constrained by) map or slice", x);
          return false;
        })) {
          return false;
        }

        x.mode_ = novalue;
        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, makeSig(null, x.typ()!));
        }
        break;

      case builtinId._Close:
        // close(c)
        if (!underIs(x.typ()!, (u: Type | null) => {
          const uch = u instanceof Chan ? u : null;
          if (uch === null) {
            this.errorf(x, "InvalidClose", invalidOp + "cannot close non-channel %s", x);
            return false;
          }
          if (uch.dir === ChanDir.RecvOnly) {
            this.errorf(x, "InvalidClose", invalidOp + "cannot close receive-only channel %s", x);
            return false;
          }
          return true;
        })) {
          return false;
        }
        x.mode_ = novalue;
        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, makeSig(null, x.typ()!));
        }
        break;

      case builtinId._Complex: {
        // complex(x, y floatT) complexT
        const y = args[1]!;

        let d = 0;
        if (isUntyped(x.typ()!)) {
          d |= 1;
        }
        if (isUntyped(y.typ()!)) {
          d |= 2;
        }
        switch (d) {
          case 0:
            break;
          case 1:
            this.convertUntyped(x, y.typ()!);
            break;
          case 2:
            this.convertUntyped(y, x.typ()!);
            break;
          case 3:
            if (x.mode() === constant_ && y.mode() === constant_) {
              const toFloatTyp = (z: operand) => {
                if (isNumeric(z.typ()!) && Number(imag(makeComplex(z.val, 0))) === 0) {
                  z.typ_ = Typ[UntypedFloat]!;
                }
              };
              toFloatTyp(x);
              toFloatTyp(y);
            } else {
              this.convertUntyped(x, Typ[Float64]!);
              this.convertUntyped(y, Typ[Float64]!);
            }
            break;
        }
        if (!x.isValid() || !y.isValid()) {
          return false;
        }

        if (!Identical(x.typ(), y.typ())) {
          this.errorf(x, "InvalidComplex", invalidOp + "%v (mismatched types %s and %s)", call, x.typ(), y.typ());
          return false;
        }

        const f = (typ: Type): Type | null => {
          assert(!isTypeParam(typ));
          const t = typ.Underlying();
          if (t instanceof Basic) {
            switch (t.kind) {
              case Float32:
                return Typ[Complex64]!;
              case Float64:
                return Typ[Complex128]!;
              case UntypedFloat:
                return Typ[UntypedComplex]!;
            }
          }
          return null;
        };
        const resTyp = this.applyTypeFunc(f, x, id);
        if (resTyp === null) {
          this.errorf(x, "InvalidComplex", invalidArg + "arguments have type %s, expected floating-point", x.typ());
          return false;
        }

        if (x.mode() === constant_ && y.mode() === constant_) {
          x.val = makeComplex(x.val, y.val);
        } else {
          x.mode_ = value;
        }

        if (this.recordTypes() && x.mode() !== constant_) {
          this.recordBuiltinType(call.fun, makeSig(resTyp, x.typ()!, x.typ()!));
        }

        x.typ_ = resTyp;
        break;
      }

      case builtinId._Copy: {
        // copy(x, y []E) int
        const [dstE, err] = sliceElem(x);
        if (err !== null) {
          this.errorf(x, "InvalidCopy", "invalid copy: %s", err.format(this));
          return false;
        }

        const y = args[1]!;
        let special = false;
        if (x.assignableTo(this, NewSlice(universeByte), null)[0]) {
          special = true;
          for (const [, u] of typeset(y.typ()!)) {
            if (u instanceof Slice && Identical(u.elem, universeByte)) {
              // typeset ⊇ {[]byte}
            } else if (u !== null && isString(u)) {
              // typeset ⊇ {string}
            } else {
              special = false;
              break;
            }
          }
        }

        if (!special) {
          let [srcE, err2] = sliceElem(y);
          if (err2 !== null) {
            if (!allString(y.typ()!)) {
              this.errorf(y, "InvalidCopy", "invalid copy: %s", err2.format(this));
              return false;
            }
            srcE = universeByte;
          }
          if (!Identical(dstE, srcE)) {
            this.errorf(x, "InvalidCopy", "invalid copy: arguments %s and %s have different element types %s and %s", x, y, dstE, srcE);
            return false;
          }
        }

        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, makeSig(Typ[Int]!, x.typ()!, y.typ()!));
        }
        x.mode_ = value;
        x.typ_ = Typ[Int]!;
        break;
      }

      case builtinId._Delete: {
        // delete(map_, key)
        const map_ = x.typ()!;
        let key: Type | null = null;
        if (!underIs(map_, (u: Type | null) => {
          const m = u instanceof MapType ? u : null;
          if (m === null) {
            this.errorf(x, "InvalidDelete", invalidArg + "%s is not a map", x);
            return false;
          }
          if (key !== null && !Identical(m.key, key)) {
            this.errorf(x, "InvalidDelete", invalidArg + "maps of %s must have identical key types", x);
            return false;
          }
          key = m.key;
          return true;
        })) {
          return false;
        }

        copyOperand(x, args[1]!); // key
        this.assignment(x, key, "argument to delete");
        if (!x.isValid()) {
          return false;
        }

        x.mode_ = novalue;
        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, makeSig(null, map_, key!));
        }
        break;
      }

      case builtinId._Imag:
      case builtinId._Real: {
        // imag(complexT) floatT
        // real(complexT) floatT
        if (isUntyped(x.typ()!)) {
          if (x.mode() === constant_) {
            if (isNumeric(x.typ()!)) {
              x.typ_ = Typ[UntypedComplex]!;
            }
          } else {
            this.convertUntyped(x, Typ[Complex128]!);
            if (!x.isValid()) {
              return false;
            }
          }
        }

        const f = (typ: Type): Type | null => {
          assert(!isTypeParam(typ));
          const t = typ.Underlying();
          if (t instanceof Basic) {
            switch (t.kind) {
              case Complex64:
                return Typ[Float32]!;
              case Complex128:
                return Typ[Float64]!;
              case UntypedComplex:
                return Typ[UntypedFloat]!;
            }
          }
          return null;
        };
        const resTyp = this.applyTypeFunc(f, x, id);
        if (resTyp === null) {
          let code: unknown = "InvalidImag";
          if (id === builtinId._Real) {
            code = "InvalidReal";
          }
          this.errorf(x, code, invalidArg + "argument has type %s, expected complex type", x.typ());
          return false;
        }

        if (x.mode() === constant_) {
          if (id === builtinId._Real) {
            x.val = real(makeComplex(x.val, 0));
          } else {
            x.val = imag(makeComplex(0, x.val));
          }
        } else {
          x.mode_ = value;
        }

        if (this.recordTypes() && x.mode() !== constant_) {
          this.recordBuiltinType(call.fun, makeSig(resTyp, x.typ()!));
        }

        x.typ_ = resTyp;
        break;
      }

      case builtinId._Make: {
        // make(T, n)
        // make(T, n, m)
        const arg0 = argList[0]!;
        const T = this.varType(arg0);
        if (!isValid(T)) {
          return false;
        }

        const [u, err] = commonUnder(T, (_: Type | null, u: Type | null) => {
          if (u instanceof Slice || u instanceof MapType || u instanceof Chan) {
            return null; // ok
          }
          if (u === null) {
            return typeErrorf("no specific type");
          }
          return typeErrorf("type must be slice, map, or channel");
        });
        if (err !== null) {
          this.errorf(arg0, "InvalidMake", invalidArg + "cannot make %s: %s", arg0, err.format(this));
          return false;
        }

        let min: number;
        if (u instanceof Slice) {
          min = 2;
        } else if (u instanceof MapType || u instanceof Chan) {
          min = 1;
        } else {
          throw new Error("unreachable");
        }
        if (nargs < min || min + 1 < nargs) {
          this.errorf(call, "WrongArgCount", invalidOp + "%v expects %d or %d arguments; found %d", call, min, min + 1, nargs);
          return false;
        }

        const types: Type[] = [T];
        const sizes: number[] = [];
        for (const arg of argList.slice(1)) {
          const [typ, size] = this.index(arg, -1); // ok to continue with typ == Typ[Invalid]
          types.push(typ);
          if (size >= 0) {
            sizes.push(size);
          }
        }
        if (sizes.length === 2 && sizes[0]! > sizes[1]!) {
          this.error(argList[1], "SwappedMakeArgs", invalidArg + "length and capacity swapped");
          // safe to continue
        }
        x.mode_ = value;
        x.typ_ = T;
        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, makeSig(x.typ(), ...types));
        }
        break;
      }

      case builtinId._Max:
      case builtinId._Min: {
        // max(x, ...)
        // min(x, ...)
        this.verifyVersionf(atPos(PosOf(call.fun)), go1_21, "built-in %s", bin.name);

        for (let i = 0; i < args.length; i++) {
          const a = args[i]!;
          if (!a.isValid()) {
            return false;
          }

          if (!allOrdered(a.typ()!)) {
            this.errorf(a, "InvalidMinMaxOperand", invalidArg + "%s cannot be ordered", a);
            return false;
          }

          if (i > 0) {
            this.matchTypes(x, a);
            if (!x.isValid()) {
              return false;
            }

            if (!Identical(x.typ(), a.typ())) {
              this.errorf(a, "MismatchedTypes", invalidArg + "mismatched types %s (previous argument) and %s (type of %s)", x.typ(), a.typ(), a.expr);
              return false;
            }

            if (!(x.mode() === constant_ && a.mode() === constant_)) {
              x.mode_ = value;
            }
          }
        }

        if (x.mode() !== constant_) {
          x.mode_ = value;
          this.assignment(x, emptyInterface, "argument to built-in " + bin.name);
          if (!x.isValid()) {
            return false;
          }
        }

        for (const a of args) {
          this.updateExprType(a.expr, x.typ()!, true);
        }

        if (this.recordTypes() && x.mode() !== constant_) {
          const types = new Array<Type>(nargs);
          for (let i = 0; i < types.length; i++) {
            types[i] = x.typ()!;
          }
          this.recordBuiltinType(call.fun, makeSig(x.typ(), ...types));
        }
        break;
      }

      case builtinId._New: {
        // new(T) or new(expr)
        const arg = argList[0]!;
        this.exprOrType(x, arg, false);
        this.exclude(x, 1 << novalue | 1 << builtinMode);
        switch (x.mode()) {
          case invalid:
            return false;
          case typexpr:
            this.validVarType(arg, x.typ());
            break;
          default:
            if (isUntyped(x.typ()!)) {
              this.assignment(x, null, "argument to new");
              if (!x.isValid()) {
                return false;
              }
              assert(!isUntyped(x.typ()!));
            }
            this.verifyVersionf(atPos(PosOf(call.fun)), go1_26, "new(%s)", arg);
            break;
        }

        const T = x.typ()!;
        x.mode_ = value;
        x.typ_ = NewPointer(T);
        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, makeSig(x.typ(), T));
        }
        break;
      }

      case builtinId._Panic:
        // panic(x)
        if (this.sig !== null && (this.sig.results?.Len() ?? 0) > 0) {
          let p = this.isPanic;
          if (p === null) {
            p = new Map();
            this.isPanic = p;
          }
          p.set(call, true);
        }

        this.assignment(x, emptyInterface, "argument to panic");
        if (!x.isValid()) {
          return false;
        }

        x.mode_ = novalue;
        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, makeSig(null, emptyInterface));
        }
        break;

      case builtinId._Print:
      case builtinId._Println: {
        // print(x, y, ...)
        // println(x, y, ...)
        const params: Type[] = [];
        if (nargs > 0) {
          for (const a of args) {
            this.assignment(a, null, "argument to built-in " + predeclaredFuncs[id]!.name);
            if (!a.isValid()) {
              return false;
            }
            params.push(a.typ()!);
          }
        }

        x.mode_ = novalue;
        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, makeSig(null, ...params));
        }
        break;
      }

      case builtinId._Recover:
        // recover() interface{}
        x.mode_ = value;
        x.typ_ = emptyInterface;
        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, makeSig(x.typ()));
        }
        break;

      case builtinId._Add: {
        // unsafe.Add(ptr unsafe.Pointer, len IntegerType) unsafe.Pointer
        this.verifyVersionf(atPos(PosOf(call.fun)), go1_17, "unsafe.Add");

        this.assignment(x, Typ[UnsafePointer]!, "argument to unsafe.Add");
        if (!x.isValid()) {
          return false;
        }

        const y = args[1]!;
        if (!this.isValidIndex(y, "InvalidUnsafeAdd", "length", true)) {
          return false;
        }

        x.mode_ = value;
        x.typ_ = Typ[UnsafePointer]!;
        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, makeSig(x.typ(), x.typ()!, y.typ()!));
        }
        break;
      }

      case builtinId._Alignof:
      case builtinId._Sizeof:
        if (id === builtinId._Alignof) {
          // unsafe.Alignof(x T) uintptr
          this.assignment(x, null, "argument to unsafe.Alignof");
        } else {
          // unsafe.Sizeof(x T) uintptr
          this.assignment(x, null, "argument to unsafe.Sizeof");
        }
        if (!x.isValid()) {
          return false;
        }

        if (this.hasVarSize(x.typ()!)) {
          x.mode_ = value;
          if (this.recordTypes()) {
            this.recordBuiltinType(call.fun, makeSig(Typ[Uintptr]!, x.typ()!));
          }
        } else {
          x.mode_ = constant_;
          x.val = id === builtinId._Alignof ? BigInt(this.conf.Sizes?.Alignof(x.typ()!) ?? 1) : BigInt(this.conf.Sizes?.Sizeof(x.typ()!) ?? 0);
        }
        x.typ_ = Typ[Uintptr]!;
        break;

      case builtinId._Offsetof: {
        // unsafe.Offsetof(x T) uintptr, where x must be a selector
        const arg0 = argList[0]!;
        const selx = Unparen(arg0);
        if (selx.kind !== "SelectorExpr") {
          this.errorf(arg0, "BadOffsetofSyntax", invalidArg + "%s is not a selector expression", arg0);
          this.use(arg0);
          return false;
        }

        this.expr(null, x, selx.object);
        if (!x.isValid()) {
          return false;
        }

        const base = derefStructPtr(x.typ()!);
        const sel = selx.selector.name;
        const [obj, index, indirect] = lookupFieldOrMethod(base, false, this.pkg, sel, false);
        if (obj === null) {
          this.errorf(x, "MissingFieldOrMethod", invalidArg + "%s has no single field %s", base, sel);
          return false;
        }
        if (obj instanceof Func) {
          this.errorf(arg0, "InvalidOffsetof", invalidArg + "%s is a method value", arg0);
          return false;
        }
        if (indirect) {
          this.errorf(x, "InvalidOffsetof", invalidArg + "field %s is embedded via a pointer in %s", sel, base);
          return false;
        }

        this.recordSelection(selx, FieldVal, base, obj, index ?? [], false);
        this.record(new operand(x.mode() === variable || indirect ? variable : value, selx, obj.Type(), null, null));

        if (this.hasVarSize(base)) {
          x.mode_ = value;
          if (this.recordTypes()) {
            this.recordBuiltinType(call.fun, makeSig(Typ[Uintptr]!, obj.Type()!));
          }
        } else {
          x.mode_ = constant_;
          x.val = 0n;
        }
        x.typ_ = Typ[Uintptr]!;
        break;
      }

      case builtinId._Slice: {
        // unsafe.Slice(ptr *T, len IntegerType) []T
        this.verifyVersionf(atPos(PosOf(call.fun)), go1_17, "unsafe.Slice");

        const [u] = commonUnder(x.typ()!, null);
        const ptr = u instanceof Pointer ? u : null;
        if (ptr === null) {
          this.errorf(x, "InvalidUnsafeSlice", invalidArg + "%s is not a pointer", x);
          return false;
        }

        const y = args[1]!;
        if (!this.isValidIndex(y, "InvalidUnsafeSlice", "length", false)) {
          return false;
        }

        x.mode_ = value;
        x.typ_ = NewSlice(ptr.base);
        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, makeSig(x.typ(), ptr, y.typ()!));
        }
        break;
      }

      case builtinId._SliceData: {
        // unsafe.SliceData(slice []T) *T
        this.verifyVersionf(atPos(PosOf(call.fun)), go1_20, "unsafe.SliceData");

        const [u] = commonUnder(x.typ()!, null);
        const slice = u instanceof Slice ? u : null;
        if (slice === null) {
          this.errorf(x, "InvalidUnsafeSliceData", invalidArg + "%s is not a slice", x);
          return false;
        }

        x.mode_ = value;
        x.typ_ = NewPointer(slice.elem);
        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, makeSig(x.typ(), slice));
        }
        break;
      }

      case builtinId._String: {
        // unsafe.String(ptr *byte, len IntegerType) string
        this.verifyVersionf(atPos(PosOf(call.fun)), go1_20, "unsafe.String");

        this.assignment(x, NewPointer(universeByte), "argument to unsafe.String");
        if (!x.isValid()) {
          return false;
        }

        const y = args[1]!;
        if (!this.isValidIndex(y, "InvalidUnsafeString", "length", false)) {
          return false;
        }

        x.mode_ = value;
        x.typ_ = Typ[StringKind]!;
        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, makeSig(x.typ(), NewPointer(universeByte), y.typ()!));
        }
        break;
      }

      case builtinId._StringData:
        // unsafe.StringData(str string) *byte
        this.verifyVersionf(atPos(PosOf(call.fun)), go1_20, "unsafe.StringData");

        this.assignment(x, Typ[StringKind]!, "argument to unsafe.StringData");
        if (!x.isValid()) {
          return false;
        }

        x.mode_ = value;
        x.typ_ = NewPointer(universeByte);
        if (this.recordTypes()) {
          this.recordBuiltinType(call.fun, makeSig(x.typ(), Typ[StringKind]!));
        }
        break;

      case builtinId._Assert:
        // assert(pred) causes a typechecker error if pred is false.
        if (x.mode() !== constant_ || !isBoolean(x.typ()!)) {
          this.errorf(x, "Test", invalidArg + "%s is not a boolean constant", x);
          return false;
        }
        if (x.val !== true) {
          this.errorf(call, "Test", "%v failed", call);
        }
        break;

      case builtinId._Trace: {
        // trace(x, y, z, ...) dumps the positions, expressions, and
        // values of its arguments. The result of trace is the value of the first argument.
        if (nargs === 0) {
          this.dump?.("%v: trace() without arguments", PosOf(call));
          x.mode_ = novalue;
          break;
        }
        const t = new operand();
        let x1 = x;
        for (const arg of argList) {
          this.rawExpr(null, x1, arg, null, false);
          this.dump?.("%v: %s", x1.Pos(), x1);
          x1 = t;
        }
        if (!x.isValid()) {
          return false;
        }
        break;
      }

      default:
        throw new Error("unreachable");
    }

    assert(x.isValid());
    return true;
  } finally {
    if (id === builtinId._Len || id === builtinId._Cap) {
      this.hasCallOrRecv = savedHasCallOrRecv;
    }
  }
};

// sliceElem returns the slice element type for a slice operand x
// or a type error if x is not a slice (or a type set of slices).
export function sliceElem(x: operand): [Type | null, typeError | null] {
  let E: Type | null = null;
  for (const [, u] of typeset(x.typ()!)) {
    const s = u instanceof Slice ? u : null;
    if (s === null) {
      if (x.isNil()) {
        // Printing x in this case would just print "nil".
        // Special case this so we can emphasize "untyped".
        return [null, typeErrorf("argument must be a slice; have untyped nil")];
      }
      return [null, typeErrorf("argument must be a slice; have %s", x)];
    }
    if (E === null) {
      E = s.elem;
    } else if (!Identical(E, s.elem)) {
      return [null, typeErrorf("mismatched slice element types %s and %s in %s", E, s.elem, x)];
    }
  }
  return [E, null];
}

// hasVarSize reports if the size of type t is variable due to type parameters
// or if the type is infinitely-sized due to a cycle for which the type has not
// yet been checked.
Checker.prototype.hasVarSize = function hasVarSize(t0: Type): boolean {
  // Note: We could use Underlying here, but passing through the RHS may yield
  // better error messages and allows us to stash the result on each traversed
  // Named type.
  const t = Unalias(t0);
  if (t instanceof Named) {
    return this.hasVarSize(t.Underlying());
  }
  if (t instanceof ArrayType) {
    return this.hasVarSize(t.elem);
  }
  if (t instanceof Struct) {
    for (const f of t.fields ?? []) {
      if (this.hasVarSize(f.typ!)) {
        return true;
      }
    }
  }
  if (t instanceof TypeParam) {
    return true;
  }
  return false;
};

// applyTypeFunc applies f to x. If x is a type parameter,
// the result is a type parameter constrained by a new
// interface bound. The type bounds for that interface
// are computed by applying f to each of the type bounds
// of x. If any of these applications of f return nil,
// applyTypeFunc returns nil.
// If x is not a type parameter, the result is f(x).
Checker.prototype.applyTypeFunc = function applyTypeFunc(f: (typ: Type) => Type | null, x: operand, id: builtinId): Type | null {
  const tp = Unalias(x.typ()) instanceof TypeParam ? Unalias(x.typ()) as TypeParam : null;
  if (tp !== null) {
    // Test if t satisfies the requirements for the argument
    // type and collect possible result types at the same time.
    const terms: Term[] = [];
    if (!tp.is((t: term | null) => {
      if (t === null) {
        return false;
      }
      const r = f(t.typ!);
      if (r !== null) {
        terms.push(NewTerm(t.tilde, r));
        return true;
      }
      return false;
    })) {
      return null;
    }

    let code: unknown;
    switch (id) {
      case builtinId._Real:
        code = "InvalidReal";
        break;
      case builtinId._Imag:
        code = "InvalidImag";
        break;
      case builtinId._Complex:
        code = "InvalidComplex";
        break;
      default:
        throw new Error("unreachable");
    }
    this.softErrorf(x, code, "%s not supported as argument to built-in %s for go1.18 (see go.dev/issue/50937)", x, predeclaredFuncs[id]!.name);

    const tpar = NewTypeName(nopos, this.pkg, tp.obj.name, null);
    const ptyp = this.newTypeParam(tpar, NewInterfaceType(null, [NewUnion(terms)])); // assigns type to tpar as a side-effect
    ptyp.index = tp.index;

    return ptyp;
  }

  return f(x.typ()!);
};

// makeSig makes a signature for the given argument and result types.
// Default types are used for untyped arguments, and res may be nil.
export function makeSig(res: Type | null, ...args: Type[]): Signature {
  const list = new Array<import("./object.js").Var>(args.length);
  for (let i = 0; i < args.length; i++) {
    const param = args[i]!;
    list[i] = NewParam(nopos, null, "", Default(param));
  }
  const params = NewTuple(...list);
  let result = null;
  if (res !== null) {
    assert(!isUntyped(res));
    result = NewTuple(newVar(ResultVar, nopos, null, "", res));
  }
  const sig = new Signature();
  sig.params = params;
  sig.results = result;
  return sig;
}

// arrayPtrDeref returns A if typ is of the form *A and A is an array;
// otherwise it returns typ.
export function arrayPtrDeref(typ: Type): Type {
  const p = Unalias(typ);
  if (p instanceof Pointer) {
    const a = p.base.Underlying();
    if (a instanceof ArrayType) {
      return a;
    }
  }
  return typ;
}

function copyOperand(dst: operand, src: operand): void {
  dst.mode_ = src.mode_;
  dst.expr = src.expr;
  dst.typ_ = src.typ_;
  dst.val = src.val;
  dst.id = src.id;
}
