// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/call.go

// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file implements typechecking of call and selector expressions.

import { NewIdent, PosOf, Unparen, type CallExpr, type Expr, type SelectorExpr } from "../../front/ast.js";
import type { Type } from "./type.js";
import { Checker, atPos, debug, noposn, type positioner } from "./check.js";
import { invalidOp } from "./errors.js";
import { newTarget, type target } from "./expr.js";
import type { indexedExpr } from "./index_expr.js";
import type { genericType } from "./instantiate.js";
import { enableReverseTypeInference, isParameterized } from "./infer.js";
import { Interface } from "./interface.js";
import { isInterfacePtr, lookupFieldOrMethod } from "./lookup.js";
import { Func, Const, Builtin, NewParam, PkgName, TypeName, Var, type Object } from "./object.js";
import { operand, builtin, cgofunc, commaerr, constant_, invalid, novalue, typexpr, value, variable } from "./operand.js";
import { Pointer } from "./pointer.js";
import { clone, isTypeParam, isValid, isValidName } from "./predicates.js";
import { FieldVal, MethodExpr, MethodVal } from "./selection.js";
import { Signature, methodExprSentinel, NewSignatureType } from "./signature.js";
import { Slice } from "./slice.js";
import { makeSubstMap } from "./subst.js";
import { Tuple, NewTuple } from "./tuple.js";
import { TypeParam } from "./typeparam.js";
import { TypeParamList } from "./typelists.js";
import { commonUnder, typeErrorf } from "./under.js";
import { builtinId, exprKind, predeclaredFuncs, Typ } from "./universe.js";
import { go1_18, go1_21 } from "./version.js";
import { assert } from "./util.js";

export const cgoPrefixes = [
  "_Ciconst_",
  "_Cfconst_",
  "_Csconst_",
  "_Ctype_",
  "_Cvar_", // actually a pointer to the var
  "_Cfpvar_fp_",
  "_Cfunc_",
  "_Cmacro_", // function to evaluate the expanded expression
];

declare module "./check.js" {
  interface Checker {
    funcInst(T: target | null, pos: number, x: operand, ix: indexedExpr | null, infer: boolean): Type[] | null;
    instantiateSignature(pos: number, expr: unknown, typ: Signature, targs: Type[], xlist: unknown[] | null): Signature;
    callExpr(x: operand, call: unknown): exprKind;
    exprList(exprs: unknown[]): operand[];
    genericExprList(exprs: unknown[]): [operand[], Type[][] | null];
    arguments(call: unknown, sig: Signature, targs: Type[] | null, xlist: unknown[] | null, args: operand[], atargs: Type[][] | null): Signature;
    selector(x: operand, e: unknown, wantType: boolean): void;
    use(...args: unknown[]): boolean;
    useLHS(...args: unknown[]): boolean;
    useN(args: unknown[], lhs: boolean): boolean;
    use1(e: unknown, lhs: boolean): boolean;
    conversion(x: operand, T: Type): void;
    builtin(x: operand, call: unknown, id: builtinId | null): boolean;
    renameTParams(pos: number, tparams: TypeParam[], typ: Type): [TypeParam[], Type];
    infer(posn: positioner | unknown, tparams: TypeParam[], targs: (Type | null)[], params: Tuple | null, args: operand[] | null, reverse: boolean, err: unknown): Type[] | null;
    objDecl(obj: Object): void;
  }
}

// funcInst type-checks a function instantiation.
// The incoming x must be a generic function.
// If ix != nil, it provides some or all of the type arguments (ix.Indices).
// If target != nil, it may be used to infer missing type arguments of x, if any.
// At least one of T or ix must be provided.
//
// There are two modes of operation:
//
//  1. If infer == true, funcInst infers missing type arguments as needed and
//     instantiates the function x. The returned results are nil.
//
//  2. If infer == false and inst provides all type arguments, funcInst
//     instantiates the function x. The returned results are nil.
//     If inst doesn't provide enough type arguments, funcInst returns the
//     available arguments; x remains unchanged.
//
// If an error (other than a version error) occurs in any case, it is reported
// and x.mode is set to invalid.
Checker.prototype.funcInst = function funcInst(T: target | null, pos: number, x: operand, ix: indexedExpr | null, infer: boolean): Type[] | null {
  assert(T !== null || ix !== null);

  let instErrPos: positioner;
  if (ix !== null) {
    instErrPos = new atPos(ix.lbrack);
    x.expr = ix.orig; // if we don't have an index expression, keep the existing expression of x
  } else {
    instErrPos = new atPos(pos);
  }
  const versionErr = !this.verifyVersionf(instErrPos, go1_18, "function instantiation");

  // targs and xlist are the type arguments and corresponding type expressions, or nil.
  let targs: Type[] | null = null;
  let xlist: unknown[] | null = null;
  if (ix !== null) {
    xlist = ix.indices;
    targs = this.typeList(xlist);
    if (targs === null) {
      x.invalidate();
      return null;
    }
    assert(targs.length === xlist.length);
  }

  // Check the number of type arguments (got) vs number of type parameters (want).
  // Note that x is a function value, not a type expression, so we don't need to
  // call Underlying below.
  let sig = x.typ() as Signature;
  let got = targs?.length ?? 0;
  const want = sig.TypeParams()!.Len();
  if (got > want) {
    // Providing too many type arguments is always an error.
    this.errorf(ix!.indices[got - 1], "WrongTypeArgCount", "got %d type arguments but want %d", got, want);
    x.invalidate();
    return null;
  }

  if (got < want) {
    if (!infer) {
      return targs ?? [];
    }

    // If the uninstantiated or partially instantiated function x is used in
    // an assignment (tsig != nil), infer missing type arguments by treating
    // the assignment
    //
    //    var tvar tsig = x
    //
    // like a call g(tvar) of the synthetic generic function g
    //
    //    func g[type_parameters_of_x](func_type_of_x)
    let args: operand[] | null = null;
    let params: Var[] = [];
    let reverse = false;
    if (T !== null && sig.tparams !== null) {
      if (!versionErr && !this.allowVersion(go1_21)) {
        if (ix !== null) {
          this.versionErrorf(instErrPos, go1_21, "partially instantiated function in assignment");
        } else {
          this.versionErrorf(instErrPos, go1_21, "implicitly instantiated function in assignment");
        }
      }
      const gsig = NewSignatureType(null, null, null, sig.params, sig.results, sig.variadic);
      params = [NewParam(x.Pos(), this.pkg, "", gsig)];
      // The type of the argument operand is tsig, which is the type of the LHS in an assignment
      // or the result type in a return statement. Create a pseudo-expression for that operand
      // that makes sense when reported in error messages from infer, below.
      const expr = NewIdent(T.desc);
      expr.span = (x.expr as { span?: unknown } | null)?.span as never;
      args = [new operand(value, expr, T.sig)];
      reverse = true;
    }

    // Rename type parameters to avoid problems with recursive instantiations.
    // Note that NewTuple(params...) below is (*Tuple)(nil) if len(params) == 0, as desired.
    const [tparams, params2] = this.renameTParams(pos, sig.TypeParams()!.list(), NewTuple(...params) ?? new Tuple([]));

    const err = this.newError("CannotInferTypeArgs");
    const inferred = this.infer(new atPos(pos), tparams, targs ?? [], params2 as Tuple, args, reverse, err);
    if (inferred === null) {
      if (!err.empty()) {
        err.report();
      }
      x.invalidate();
      return null;
    }
    targs = inferred;
    got = targs.length;
  }
  assert(got === want);

  // instantiate function signature
  sig = this.instantiateSignature(x.Pos(), x.expr, sig, targs!, xlist);
  x.typ_ = sig;
  x.mode_ = value;
  return null;
};

Checker.prototype.instantiateSignature = function instantiateSignature(pos: number, expr: unknown, typ: Signature, targs: Type[], xlist: unknown[] | null): Signature {
  assert(this !== null);
  assert(targs.length === typ.TypeParams()!.Len());

  if (this.conf._Trace) {
    this.trace?.(pos, "-- instantiating signature %s with %s", typ, targs);
    this.indent++;
  }
  let res: Signature;
  try {
    // For signatures, Checker.instance will always succeed because the type argument
    // count is correct at this point (see assertion above); hence the type assertion
    // to *Signature will always succeed.
    const inst = this.instance(pos, typ as genericType, targs, null, this.context()) as Signature;
    assert(inst.TypeParams()!.Len() === 0); // signature is not generic anymore
    this.recordInstance(expr, targs, inst);
    assert((xlist?.length ?? 0) <= targs.length);

    // verify instantiation lazily (was go.dev/issue/50450)
    this.later(() => {
      const tparams = typ.TypeParams()!.list();
      // check type constraints
      const [i, err] = this.verify(pos, tparams, targs, this.context());
      if (err !== null) {
        // best position for error reporting
        let pos2 = pos;
        if (xlist !== null && i < xlist.length) {
          pos2 = PosOf(xlist[i] as Expr);
        }
        this.softErrorf(new atPos(pos2), "InvalidTypeArg", "%s", err);
      } else {
        (this.mono as { recordInstance(pkg: unknown, pos: number, tparams: TypeParam[], targs: Type[], xlist: unknown[]): void }).recordInstance(this.pkg, pos, tparams, targs, xlist ?? []);
      }
    }).describef(new atPos(pos), "verify instantiation");

    res = inst;
  } finally {
    if (this.conf._Trace) {
      this.indent--;
      this.trace?.(pos, "=> %s (under = %s)", (res! as Signature), (res! as Signature).Underlying());
    }
  }

  return res!;
};

Checker.prototype.callExpr = function callExpr(x: operand, call0: unknown): exprKind {
  const call = call0 as CallExpr;
  let ix = this.unpackIndexedExpr(call.fun);
  if (ix !== null) {
    if (this.indexExpr(x, ix)) {
      // Delay function instantiation to argument checking,
      // where we combine type and value arguments for type
      // inference.
      assert(x.mode() === value);
    } else {
      ix = null;
    }
    x.expr = call.fun;
    this.record(x);
  } else {
    this.exprOrType(x, call.fun, true);
  }
  // x.typ may be generic

  switch (x.mode()) {
    case invalid:
      this.use(...call.args);
      x.expr = call;
      return exprKind.statement;

    case typexpr: {
      // conversion
      this.nonGeneric(null, x);
      if (!x.isValid()) {
        return exprKind.conversion;
      }
      const T = x.typ()!;
      x.invalidate();
      // We cannot convert a value to an incomplete type; make sure it's complete.
      if (!this.isComplete?.(T)) {
        x.expr = call;
        return exprKind.conversion;
      }
      switch (call.args.length) {
        case 0:
          this.errorf(new atPos(PosOf(call)), "WrongArgCount", "missing argument in conversion to %s", T);
          break;
        case 1:
          this.expr(newTarget(T, "conversion"), x, call.args[0]);
          if (x.isValid()) {
            if (hasDots(call)) {
              this.errorf(call.args[0], "BadDotDotDotSyntax", "invalid use of ... in conversion to %s", T);
              break;
            }
            const t = T.Underlying();
            if (t instanceof Interface && !isTypeParam(T)) {
              if (!t.IsMethodSet()) {
                this.errorf(call, "MisplacedConstraintIface", "cannot use interface %s in conversion (contains specific type constraints or is comparable)", T);
                break;
              }
            }
            this.conversion(x, T);
          }
          break;
        default:
          this.use(...call.args);
          this.errorf(call.args[call.args.length - 1], "WrongArgCount", "too many arguments in conversion to %s", T);
          break;
      }
      x.expr = call;
      return exprKind.conversion;
    }

    case builtin: {
      // no need to check for non-genericity here
      const id = x.id;
      if (!this.builtin(x, call, id)) {
        x.invalidate();
      }
      x.expr = call;
      // a non-constant result implies a function call
      if (x.isValid() && x.mode() !== constant_) {
        this.hasCallOrRecv = true;
      }
      return predeclaredFuncs[id!]!.kind;
    }
  }

  // ordinary function/method call
  // signature may be generic
  const cgocall = x.mode() === cgofunc;

  // If the operand type is a type parameter, all types in its type set
  // must have a common underlying type, which must be a signature.
  const [u, err] = commonUnder(x.typ()!, (t: Type | null, u: Type | null) => {
    if (u !== null && !(u instanceof Signature)) {
      return typeErrorf("%s is not a function", t);
    }
    return null;
  });
  if (err !== null) {
    this.errorf(x, "InvalidCall", invalidOp + "cannot call %s: %s", x, err.format(this));
    x.invalidate();
    x.expr = call;
    return exprKind.statement;
  }
  let sig = u as Signature; // u must be a signature per the commonUnder condition

  // Capture wasGeneric before sig is potentially instantiated below.
  const wasGeneric = (sig.TypeParams()?.Len() ?? 0) > 0;

  // evaluate type arguments, if any
  let xlist: unknown[] | null = null;
  let targs: Type[] | null = null;
  if (ix !== null) {
    xlist = ix.indices;
    targs = this.typeList(xlist);
    if (targs === null) {
      this.use(...call.args);
      x.invalidate();
      x.expr = call;
      return exprKind.statement;
    }
    assert(targs.length === xlist.length);

    // check number of type arguments (got) vs number of type parameters (want)
    const got = targs.length;
    const want = sig.TypeParams()!.Len();
    if (got > want) {
      this.errorf(xlist[want], "WrongTypeArgCount", "got %d type arguments but want %d", got, want);
      this.use(...call.args);
      x.invalidate();
      x.expr = call;
      return exprKind.statement;
    }

    // If sig is generic and all type arguments are provided, preempt function
    // argument type inference by explicitly instantiating the signature. This
    // ensures that we record accurate type information for sig, even if there
    // is an error checking its arguments (for example, if an incorrect number
    // of arguments is supplied).
    if (got === want && want > 0) {
      this.verifyVersionf(new atPos(ix.lbrack), go1_18, "function instantiation");
      sig = this.instantiateSignature(ix.Pos(), ix.orig, sig, targs, xlist);
      // targs have been consumed; proceed with checking arguments of the
      // non-generic signature.
      targs = null;
      xlist = null;
    }
  }

  // evaluate arguments
  const [args, atargs] = this.genericExprList(call.args);
  sig = this.arguments(call, sig, targs, xlist, args, atargs);

  if (wasGeneric && (sig.TypeParams()?.Len() ?? 0) === 0) {
    // Update the recorded type of call.Fun to its instantiated type.
    this.recordTypeAndValue(call.fun, value, sig, null);
  }

  // determine result
  switch (sig.results?.Len() ?? 0) {
    case 0:
      x.mode_ = novalue;
      break;
    case 1: {
      if (cgocall) {
        x.mode_ = commaerr;
      } else {
        x.mode_ = value;
      }
      const typ = sig.results!.vars[0]!.typ!; // unpack tuple
      // We cannot return a value of an incomplete type; make sure it's complete.
      if (!this.isComplete?.(typ)) {
        x.invalidate();
        x.expr = call;
        return exprKind.statement;
      }
      x.typ_ = typ;
      break;
    }
    default:
      x.mode_ = value;
      x.typ_ = sig.results;
      break;
  }
  x.expr = call;
  this.hasCallOrRecv = true;

  // if type inference failed, a parameterized result must be invalidated
  if (x.mode() === value && (sig.TypeParams()?.Len() ?? 0) > 0 && isParameterized(sig.TypeParams()!.list(), x.typ())) {
    x.invalidate();
  }

  return exprKind.statement;
};

// exprList evaluates a list of expressions and returns the corresponding operands.
// A single-element expression list may evaluate to multiple operands.
Checker.prototype.exprList = function exprList(elist: unknown[]): operand[] {
  let xlist: operand[] = [];
  const n = elist.length;
  if (n === 1) {
    [xlist] = this.multiExpr(elist[0], false);
  } else if (n > 1) {
    // multiple (possibly invalid) values
    xlist = new globalThis.Array<operand>(n);
    for (let i = 0; i < elist.length; i++) {
      const e = elist[i];
      const x = new operand();
      this.expr(null, x, e);
      xlist[i] = x;
    }
  }
  return xlist;
};

// genericExprList is like exprList but result operands may be uninstantiated or partially
// instantiated generic functions (where constraint information is insufficient to infer
// the missing type arguments) for Go 1.21 and later.
// For each non-generic or uninstantiated generic operand, the corresponding targsList and
// elements do not exist (targsList is nil) or the elements are nil.
// For each partially instantiated generic function operand, the corresponding
// targsList elements are the operand's partial type arguments.
Checker.prototype.genericExprList = function genericExprList(elist: unknown[]): [operand[], Type[][] | null] {
  let resList: operand[] = [];
  let targsList: Type[][] | null = null;
  try {
    // Before Go 1.21, uninstantiated or partially instantiated argument functions are
    // not permitted. Checker.funcInst must infer missing type arguments in that case.
    let infer = true; // for -lang < go1.21
    const n = elist.length;
    if (n > 0 && this.allowVersion(go1_21)) {
      infer = false;
    }

    if (n === 1) {
      // single value (possibly a partially instantiated function), or a multi-valued expression
      const e = elist[0];
      const x = new operand();
      const ix = this.unpackIndexedExpr?.(e) ?? null;
      if (ix !== null && this.indexExpr?.(x, ix)) {
        // x is a generic function.
        const targs = this.funcInst?.(null, x.Pos(), x, ix, infer) ?? null;
        if (targs !== null) {
          // x was not instantiated: collect the (partial) type arguments.
          targsList = [targs];
          // Update x.expr so that we can record the partially instantiated function.
          x.expr = (ix as { orig?: unknown }).orig ?? e;
        } else {
          // x was instantiated: we must record it here because we didn't
          // use the usual expression evaluators.
          this.record(x);
        }
        resList = [x];
      } else {
        // x is not a function instantiation (it may still be a generic function).
        this.rawExpr(null, x, e, null, true);
        this.exclude(x, (1 << novalue) | (1 << builtin) | (1 << typexpr));
        if (x.typ() instanceof Tuple && x.isValid()) {
          const t = x.typ() as Tuple;
          // x is a function call returning multiple values; it cannot be generic.
          resList = new globalThis.Array<operand>(t.Len());
          for (let i = 0; i < t.vars.length; i++) {
            const v = t.vars[i]!;
            resList[i] = new operand(value, e, v.typ);
          }
        } else {
          // x is exactly one value (possibly invalid or uninstantiated generic function).
          resList = [x];
        }
      }
    } else if (n > 1) {
      // multiple values
      resList = new globalThis.Array<operand>(n);
      targsList = new globalThis.Array<Type[]>(n);
      for (let i = 0; i < elist.length; i++) {
        const e = elist[i];
        const x = new operand();
        const ix = this.unpackIndexedExpr?.(e) ?? null;
        if (ix !== null && this.indexExpr?.(x, ix)) {
          // x is a generic function.
          const targs = this.funcInst?.(null, x.Pos(), x, ix, infer) ?? null;
          if (targs !== null) {
            // x was not instantiated: collect the (partial) type arguments.
            targsList[i] = targs;
            // Update x.expr so that we can record the partially instantiated function.
            x.expr = (ix as { orig?: unknown }).orig ?? e;
          } else {
            // x was instantiated: we must record it here because we didn't
            // use the usual expression evaluators.
            this.record(x);
          }
        } else {
          // x is exactly one value (possibly invalid or uninstantiated generic function).
          this.genericExpr(x, e, null);
        }
        resList[i] = x;
      }
    }
  } finally {
    if (debug) {
      // type arguments must only exist for partially instantiated functions
      for (let i = 0; i < resList.length; i++) {
        const x = resList[i]!;
        if (targsList !== null && i < targsList.length) {
          const n = targsList[i]?.length ?? 0;
          if (n > 0) {
            // x must be a partially instantiated function
            assert(n < (x.typ() as Signature).TypeParams()!.Len());
          }
        }
      }
    }
  }

  return [resList, targsList];
};

// arguments type-checks arguments passed to a function call with the given signature.
// The function and its arguments may be generic, and possibly partially instantiated.
// targs and xlist are the function's type arguments (and corresponding expressions).
// args are the function arguments. If an argument args[i] is a partially instantiated
// generic function, atargs[i] are the corresponding type arguments.
// If the callee is variadic, arguments adjusts its signature to match the provided
// arguments. The type parameters and arguments of the callee and all its arguments
// are used together to infer any missing type arguments, and the callee and argument
// functions are instantiated as necessary.
// The result signature is the (possibly adjusted and instantiated) function signature.
// If an error occurred, the result signature is the incoming sig.
Checker.prototype.arguments = function arguments_(call0: unknown, sig: Signature, targs0: Type[] | null, xlist: unknown[] | null, args: operand[], atargs: Type[][] | null): Signature {
  const call = call0 as CallExpr;
  let rsig = sig;
  let targs: (Type | null)[] = targs0 ?? [];

  // Function call argument/parameter count requirements
  //
  //               | standard call    | dotdotdot call |
  // --------------+------------------+----------------+
  // standard func | nargs == npars   | invalid        |
  // --------------+------------------+----------------+
  // variadic func | nargs >= npars-1 | nargs == npars |
  // --------------+------------------+----------------+

  const nargs = args.length;
  let npars = sig.params?.Len() ?? 0;
  const ddd = hasDots(call);

  // set up parameters
  let sigParams = sig.params; // adjusted for variadic functions (may be nil for empty parameter lists!)
  let adjusted = false; // indicates if sigParams is different from sig.params
  if (sig.variadic) {
    if (ddd) {
      // variadic_func(a, b, c...)
      if (call.args.length === 1 && nargs > 1) {
        // f()... is not permitted if f() is multi-valued
        this.errorf(call, "InvalidDotDotDot", "cannot use ... with %d-valued %s", nargs, call.args[0]);
        return rsig;
      }
    } else {
      // variadic_func(a, b, c)
      if (nargs >= npars - 1) {
        // Create custom parameters for arguments: keep
        // the first npars-1 parameters and add one for
        // each argument mapping to the ... parameter.
        const vars = (sig.params?.vars ?? []).slice(0, Math.max(npars - 1, 0)); // npars > 0 for variadic functions
        const last = sig.params!.vars[npars - 1]!;
        const slice = last.typ!.Underlying() as Slice;
        const typ = slice.elem;
        while (vars.length < nargs) {
          vars.push(NewParam(last.pos, last.pkg, last.name, typ));
        }
        sigParams = NewTuple(...vars); // possibly nil!
        adjusted = true;
        npars = nargs;
      } else {
        // nargs < npars-1
        npars--; // for correct error message below
      }
    }
  } else {
    if (ddd) {
      // standard_func(a, b, c...)
      this.errorf(call, "NonVariadicDotDotDot", "cannot use ... in call to non-variadic %s", call.fun);
      return rsig;
    }
    // standard_func(a, b, c)
  }

  // check argument count
  if (nargs !== npars) {
    let at: unknown = call;
    let qualifier = "not enough";
    if (nargs > npars) {
      at = args[npars]?.expr ?? call; // report at first extra argument
      qualifier = "too many";
    } else {
      at = new atPos(PosOf(call)); // report at closing )
    }
    // take care of empty parameter lists represented by nil tuples
    const params = sig.params?.vars ?? [];
    const err = this.newError("WrongArgCount");
    err.addf(at, "%s arguments in call to %s", qualifier, call.fun);
    err.addf(noposn, "have %s", this.typesSummary(operandTypesLocal(args), false, ddd));
    err.addf(noposn, "want %s", this.typesSummary(varTypesLocal(params), sig.variadic, false));
    err.report();
    return rsig;
  }

  // collect type parameters of callee and generic function arguments
  let tparams: TypeParam[] = [];

  // collect type parameters of callee
  const n = sig.TypeParams()?.Len() ?? 0;
  if (n > 0) {
    if (!this.allowVersion(go1_18)) {
      if (call.fun.kind === "IndexExpr" || call.fun.kind === "IndexListExpr") {
        const ix = this.unpackIndexedExpr(call.fun)!;
        this.versionErrorf(new atPos(ix.lbrack), go1_18, "function instantiation");
      } else {
        this.versionErrorf(new atPos(PosOf(call)), go1_18, "implicit function instantiation");
      }
    }
    // rename type parameters to avoid problems with recursive calls
    const [renamed, tmp] = this.renameTParams(PosOf(call), sig.TypeParams()!.list(), sigParams ?? new Tuple([]));
    tparams = renamed;
    sigParams = tmp as Tuple;
    // make sure targs and tparams have the same length
    while (targs.length < tparams.length) {
      targs.push(null);
    }
  }
  assert(tparams.length === targs.length);

  // collect type parameters from generic function arguments
  const genericArgs: number[] = []; // indices of generic function arguments
  if (enableReverseTypeInference) {
    for (let i = 0; i < args.length; i++) {
      const arg = args[i]!;
      // generic arguments cannot have a defined (*Named) type - no need for underlying type below
      let asig = arg.typ() instanceof Signature ? arg.typ() as Signature : null;
      if (asig !== null && (asig.TypeParams()?.Len() ?? 0) > 0) {
        // The argument type is a generic function signature. This type is
        // pointer-identical with (it's copied from) the type of the generic
        // function argument and thus the function object.
        // Before we change the type (type parameter renaming, below), make
        // a clone of it as otherwise we implicitly modify the object's type
        // (go.dev/issues/63260).
        asig = clone(asig);
        // Rename type parameters for cases like f(g, g); this gives each
        // generic function argument a unique type identity (go.dev/issues/59956).
        // TODO(gri) Consider only doing this if a function argument appears
        //           multiple times, which is rare (possible optimization).
        const [atparams, tmp] = this.renameTParams(PosOf(call), asig.TypeParams()!.list(), asig);
        asig = tmp as Signature;
        asig.tparams = new TypeParamList(atparams); // renameTParams doesn't touch associated type parameters
        arg.typ_ = asig; // new type identity for the function argument
        tparams.push(...atparams);
        // add partial list of type arguments, if any
        if (atargs !== null && i < atargs.length && atargs[i] !== undefined) {
          targs.push(...atargs[i]!);
        }
        // make sure targs and tparams have the same length
        while (targs.length < tparams.length) {
          targs.push(null);
        }
        genericArgs.push(i);
      }
    }
  }
  assert(tparams.length === targs.length);

  // at the moment we only support implicit instantiations of argument functions
  void (genericArgs.length > 0 && this.verifyVersionf(args[genericArgs[0]!]!, go1_21, "implicitly instantiated function as argument"));

  // tparams holds the type parameters of the callee and generic function arguments, if any:
  // the first n type parameters belong to the callee, followed by mi type parameters for each
  // of the generic function arguments, where mi = args[i].typ.(*Signature).TypeParams().Len().

  // infer missing type arguments of callee and function arguments
  if (tparams.length > 0) {
    const err = this.newError("CannotInferTypeArgs");
    const inferred = this.infer(call, tparams, targs, sigParams ?? new Tuple([]), args, false, err);
    if (inferred === null) {
      // TODO(gri) If infer inferred the first targs[:n], consider instantiating
      //           the call signature for better error messages/gopls behavior.
      //           Perhaps instantiate as much as we can, also for arguments.
      //           This will require changes to how infer returns its results.
      if (!err.empty()) {
        this.errorf(err.posn(), "CannotInferTypeArgs", "in call to %s, %s", call.fun, err.msg());
      }
      return rsig;
    }
    targs = inferred;

    // update result signature: instantiate if needed
    if (n > 0) {
      rsig = this.instantiateSignature(PosOf(call), call.fun, sig, targs.slice(0, n) as Type[], xlist);
      // If the callee's parameter list was adjusted we need to update (instantiate)
      // it separately. Otherwise we can simply use the result signature's parameter
      // list.
      if (adjusted) {
        sigParams = this.subst(PosOf(call), sigParams, makeSubstMap(tparams.slice(0, n), targs.slice(0, n) as Type[]), null, this.context()) as Tuple;
      } else {
        sigParams = rsig.params;
      }
    }

    // compute argument signatures: instantiate if needed
    let j = n;
    for (const i of genericArgs) {
      const arg = args[i]!;
      const asig = arg.typ() as Signature;
      const k = j + asig.TypeParams()!.Len();
      // targs[j:k] are the inferred type arguments for asig
      arg.typ_ = this.instantiateSignature(PosOf(call), arg.expr, asig, targs.slice(j, k) as Type[], null); // TODO(gri) provide xlist if possible (partial instantiations)
      this.record(arg); // record here because we didn't use the usual expr evaluators
      j = k;
    }
  }

  // check arguments
  if (args.length > 0) {
    const context = this.sprintf("argument to %s", call.fun);
    for (let i = 0; i < args.length; i++) {
      const a = args[i]!;
      this.assignment(a, sigParams!.vars[i]!.typ, context);
    }
  }

  return rsig;
};

Checker.prototype.selector = function selector(x: operand, e0: unknown, wantType: boolean): void {
  const e = e0 as SelectorExpr;
  // these must be declared before the "goto Error" statements
  let obj: Object | null = null;
  let index: number[] | null = null;
  let indirect = false;

  let sel = e.selector.name;
  // If the identifier refers to a package, handle everything here
  // so we don't need a "package" mode for operands: package names
  // can only appear in qualified identifiers which are mapped to
  // selector expressions.
  if (e.object.kind === "Ident") {
    const looked = this.lookup(e.object.name);
    const pname = looked instanceof PkgName ? looked : null;
    if (pname !== null) {
      assert(pname.pkg === this.pkg);
      this.recordUse(e.object, pname);
      this.usedPkgNames.set(pname, true);
      const pkg = pname.imported;

      let exp: Object | null = null;
      let funcMode = value;
      if (pkg.cgo) {
        // cgo special cases C.malloc: it's
        // rewritten to _CMalloc and does not
        // support two-result calls.
        if (sel === "malloc") {
          sel = "_CMalloc";
        } else {
          funcMode = cgofunc;
        }
        for (const prefix of cgoPrefixes) {
          // cgo objects are part of the current package (in file
          // _cgo_gotypes.go). Use regular lookup.
          exp = this.lookup(prefix + sel);
          if (exp !== null) {
            break;
          }
        }
        if (exp === null) {
          if (isValidName(sel)) {
            this.errorf(e.selector, "UndeclaredImportedName", "undefined: %s", e); // cast to ast.Expr to silence vet
          }
          selectorError(this, x, e);
          return;
        }
        this.objDecl(exp);
      } else {
        exp = pkg.scope.Lookup(sel);
        if (exp === null) {
          if (!pkg.fake && isValidName(sel)) {
            // Try to give a better error message when selector matches an object name ignoring case.
            const exps = pkg.scope.lookupIgnoringCase(sel, true);
            if (exps.length >= 1) {
              // report just the first one
              this.errorf(e.selector, "UndeclaredImportedName", "undefined: %s (but have %s)", e, exps[0]!.Name());
            } else {
              this.errorf(e.selector, "UndeclaredImportedName", "undefined: %s", e);
            }
          }
          selectorError(this, x, e);
          return;
        }
        if (!exp.Exported()) {
          this.errorf(e.selector, "UnexportedName", "name %s not exported by package %s", sel, pkg.name);
          // ok to continue
        }
      }
      this.recordUse(e.selector, exp);

      // Simplified version of the code for *ast.Idents:
      // - imported objects are always fully initialized
      if (exp instanceof Const) {
        assert(exp.Val() !== null && exp.Val() !== undefined);
        x.mode_ = constant_;
        x.typ_ = exp.typ;
        x.val = exp.val;
      } else if (exp instanceof TypeName) {
        x.mode_ = typexpr;
        x.typ_ = exp.typ;
      } else if (exp instanceof Var) {
        x.mode_ = variable;
        x.typ_ = exp.typ;
        if (pkg.cgo && exp.name.startsWith("_Cvar_")) {
          x.typ_ = (x.typ() as Pointer).base;
        }
      } else if (exp instanceof Func) {
        x.mode_ = funcMode;
        x.typ_ = exp.typ;
        if (pkg.cgo && exp.name.startsWith("_Cmacro_")) {
          x.mode_ = value;
          x.typ_ = ((x.typ() as Signature).results!.vars[0]!).typ;
        }
      } else if (exp instanceof Builtin) {
        x.mode_ = builtin;
        x.typ_ = exp.typ;
        x.id = exp.id;
      } else {
        this.dump?.("%v: unexpected object %v", PosOf(e.selector), exp);
        throw new Error("unreachable");
      }
      x.expr = e;
      return;
    }
  }

  this.exprOrType(x, e.object, false);
  switch (x.mode()) {
    case builtin:
      // types2 uses the position of '.' for the error
      this.errorf(e.selector, "UncalledBuiltin", "invalid use of %s in selector expression", x);
      selectorError(this, x, e);
      return;
    case invalid:
      selectorError(this, x, e);
      return;
  }

  // We cannot select on an incomplete type; make sure it's complete.
  if (!this.isComplete?.(x.typ())) {
    selectorError(this, x, e);
    return;
  }

  // Avoid crashing when checking an invalid selector in a method declaration.
  //
  //   type S[T any] struct{}
  //   type V = S[any]
  //   func (fs *S[T]) M(x V.M) {}
  //
  // All codepaths below return a non-type expression. If we get here while
  // expecting a type expression, it is an error.
  //
  // See go.dev/issue/57522 for more details.
  if (wantType) {
    this.errorf(e.selector, "NotAType", "%s is not a type", e);
    selectorError(this, x, e);
    return;
  }

  // Additionally, if x.typ is a pointer type, selecting implicitly dereferences the value, meaning
  // its base type must also be complete.
  const p = x.typ()!.Underlying();
  if (p instanceof Pointer && !this.isComplete?.(p.base)) {
    selectorError(this, x, e);
    return;
  }

  [obj, index, indirect] = lookupFieldOrMethod(x.typ()!, x.mode() === variable, this.pkg, sel, false);
  if (obj === null) {
    // Don't report another error if the underlying type was invalid (go.dev/issue/49541).
    if (!isValid(x.typ()!.Underlying())) {
      selectorError(this, x, e);
      return;
    }

    if (index !== null) {
      // TODO(gri) should provide actual type where the conflict happens
      this.errorf(e.selector, "AmbiguousSelector", "ambiguous selector %s.%s", x.expr, sel);
      selectorError(this, x, e);
      return;
    }

    if (indirect) {
      if (x.mode() === typexpr) {
        this.errorf(e.selector, "InvalidMethodExpr", "invalid method expression %s.%s (needs pointer receiver (*%s).%s)", x.typ(), sel, x.typ(), sel);
      } else {
        this.errorf(e.selector, "InvalidMethodExpr", "cannot call pointer method %s on %s", sel, x.typ());
      }
      selectorError(this, x, e);
      return;
    }

    let why: string;
    if (isInterfacePtr(x.typ()!)) {
      why = this.interfacePtrError(x.typ()!);
    } else {
      const [alt] = lookupFieldOrMethod(x.typ()!, x.mode() === variable, this.pkg, sel, true);
      why = this.lookupError(x.typ()!, sel, alt, false);
    }
    this.errorf(e.selector, "MissingFieldOrMethod", "%s.%s undefined (%s)", x.expr, sel, why);
    selectorError(this, x, e);
    return;
  }
  // obj != nil

  if (obj instanceof Var) {
    if (x.mode() === typexpr) {
      this.errorf(e.object, "MissingFieldOrMethod", "operand for field selector %s must be value of type %s", sel, x.typ());
      selectorError(this, x, e);
      return;
    }

    // field value
    this.recordSelection(e, FieldVal, x.typ(), obj, index ?? [], indirect);
    if (x.mode() === variable || indirect) {
      x.mode_ = variable;
    } else {
      x.mode_ = value;
    }
    x.typ_ = obj.typ;
  } else if (obj instanceof Func) {
    this.objDecl(obj); // ensure fully set-up signature
    this.addDeclDep(obj);
    // TODO(mark): Assert that sig.rparams is nil here?

    if (x.mode() === typexpr) {
      // method expression
      this.recordSelection(e, MethodExpr, x.typ(), obj, index ?? [], indirect);

      const sig = obj.typ as Signature;
      if (sig.recv === null) {
        this.error(e, "InvalidDeclCycle", "illegal cycle in method declaration");
        selectorError(this, x, e);
        return;
      }

      // The receiver type becomes the type of the first function
      // argument of the method expression's function type.
      let params = sig.params?.vars ?? [];
      // Be consistent about named/unnamed parameters. This is not needed
      // for type-checking, but the newly constructed signature may appear
      // in an error message and then have mixed named/unnamed parameters.
      // (An alternative would be to not print parameter names in errors,
      // but it's useful to see them; this is cheap and method expressions
      // are rare.)
      let name = "";
      if (params.length > 0 && params[0]!.name !== "") {
        // name needed
        name = sig.recv.name;
        if (name === "") {
          name = "_";
        }
      }
      params = [NewParam(sig.recv.pos, sig.recv.pkg, name, x.typ()), ...params];
      x.mode_ = value;
      const msig = new Signature();
      msig.tparams = sig.tparams;
      msig.recvold = methodExprSentinel;
      msig.params = NewTuple(...params);
      msig.results = sig.results;
      msig.variadic = sig.variadic;
      x.typ_ = msig;
    } else {
      // method value

      // TODO(gri) If we needed to take into account the receiver's
      // addressability, should we report the type &(x.typ) instead?
      this.recordSelection(e, MethodVal, x.typ(), obj, index ?? [], indirect);

      x.mode_ = value;

      // remove/stash receiver
      const sig = clone(obj.typ as Signature);
      sig.recvold = sig.recv;
      sig.recv = null;
      x.typ_ = sig;
    }
  } else {
    throw new Error("unreachable");
  }

  // everything went well
  x.expr = e;
};

// use type-checks each argument.
// Useful to make sure expressions are evaluated
// (and variables are "used") in the presence of
// other errors. Arguments may be nil.
// Reports if all arguments evaluated without error.
Checker.prototype.use = function use(...args: unknown[]): boolean {
  return this.useN(args, false);
};

// useLHS is like use, but doesn't "use" top-level identifiers.
// It should be called instead of use if the arguments are
// expressions on the lhs of an assignment.
Checker.prototype.useLHS = function useLHS(...args: unknown[]): boolean {
  return this.useN(args, true);
};

Checker.prototype.useN = function useN(args: unknown[], lhs: boolean): boolean {
  let ok = true;
  for (const e of args) {
    if (!this.use1(e, lhs)) {
      ok = false;
    }
  }
  return ok;
};

Checker.prototype.use1 = function use1(e: unknown, lhs: boolean): boolean {
  const x = new operand();
  x.mode_ = value; // anything but invalid
  const n = e === null || e === undefined ? null : Unparen(e as Expr);
  switch (n?.kind) {
    case undefined:
      // nothing to do
      break;
    case "Ident": {
      // don't report an error evaluating blank
      if (n.name === "_") {
        break;
      }
      // If the lhs is an identifier denoting a variable v, this assignment
      // is not a 'use' of v. Remember current value of v.used and restore
      // after evaluating the lhs via check.rawExpr.
      let v: Var | null = null;
      let v_used = false;
      if (lhs) {
        const obj = this.lookup(n.name);
        if (obj !== null) {
          // It's ok to mark non-local variables, but ignore variables
          // from other packages to avoid potential race conditions with
          // dot-imported variables.
          if (obj instanceof Var && obj.pkg === this.pkg) {
            v = obj;
            v_used = this.usedVars.get(v) ?? false;
          }
        }
      }
      this.exprOrType(x, n, true);
      if (v !== null) {
        this.usedVars.set(v, v_used); // restore v.used
      }
      break;
    }
    default:
      this.rawExpr(null, x, e, null, true);
      break;
  }
  return x.isValid();
};

function hasDots(call: CallExpr): boolean {
  return call.ellipsis;
}

function operandTypesLocal(list: operand[]): Type[] {
  const res = new Array<Type>(list.length);
  for (let i = 0; i < list.length; i++) {
    res[i] = list[i]!.typ()!;
  }
  return res;
}

function varTypesLocal(list: Var[]): Type[] {
  const res = new Array<Type>(list.length);
  for (let i = 0; i < list.length; i++) {
    res[i] = list[i]!.typ!;
  }
  return res;
}

function selectorError(check: Checker, x: operand, e: SelectorExpr): void {
  x.invalidate();
  x.typ_ = Typ[0]!;
  x.expr = e;
}
