// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/chan.go

// Copyright 2011 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Mechanical TypeScript transliteration of go/types/chan.go.

import type { Type } from "./type.js";
import { TypeString } from "./typestring.js";

// A ChanDir value indicates a channel direction.
export enum ChanDir {
  SendRecv,
  SendOnly,
  RecvOnly
}

// A Chan represents a channel type.
export class Chan implements Type {
  public constructor(
    public readonly dir: ChanDir,
    public readonly elem: Type
  ) {}

  // Dir returns the direction of channel c.
  public Dir(): ChanDir { return this.dir; }

  // Elem returns the element type of channel c.
  public Elem(): Type { return this.elem; }

  public Underlying(): Type { return this; }
  public String(): string { return TypeString(this, null); }
}

// NewChan returns a new channel type for the given direction and element type.
export function NewChan(dir: ChanDir, elem: Type): Chan {
  return new Chan(dir, elem);
}
