// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/const.go

// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file implements functions for untyped constant operands.

import type { Type } from "./type.js";
import { Basic, Bool, Complex128, Complex64, Float32, Float64, Int, Int16, Int32, Int64, Int8, String as StringKind, Uint, Uint16, Uint32, Uint64, Uint8, Uintptr, UntypedComplex, UntypedFloat, UntypedInt } from "./basic.js";
import { Checker, atPos } from "./check.js";
import { constant_, operand } from "./operand.js";
import { isBoolean, isComplex, isInteger, isFloat, isNumeric, isString, isTyped, isTypeParam } from "./predicates.js";
import { stdSizes } from "./sizes.js";
import { Typ } from "./universe.js";
import { assert } from "./util.js";

declare module "./check.js" {
  interface Checker {
    overflow(x: operand, opPos: number): void;
    representable(x: operand, typ: Basic): void;
    representation(x: operand, typ: Basic): [unknown, unknown];
    invalidConversion(code: unknown, x: operand, target: Type): void;
    convertUntyped(x: operand, target: Type): void;
    updateExprVal(expr: unknown, val: unknown): void;
    updateExprType(expr: unknown, typ: Type, final: boolean): void;
  }
}

type constantKind = "unknown" | "bool" | "string" | "int" | "float" | "complex";

type complexValue = { re: unknown; im: unknown } | { real: unknown; imag: unknown };

// overflow checks that the constant x is representable by its type.
// For untyped constants, it checks that the value doesn't become
// arbitrarily large.
Checker.prototype.overflow = function overflow(x: operand, opPos: number): void {
  assert(x.mode() === constant_);

  if (constantKindOf(x.val) === "unknown") {
    // TODO(gri) We should report exactly what went wrong. At the
    //           moment we don't have the (go/constant) API for that.
    //           See also TODO in go/constant/value.go.
    this.error(atPos(opPos), "InvalidConstVal", "constant result is not representable");
    return;
  }

  // Typed constants must be representable in
  // their type after each constant operation.
  // x.typ cannot be a type parameter (type
  // parameters cannot be constant types).
  if (isTyped(x.typ()!)) {
    this.representable(x, x.typ()!.Underlying() as Basic);
    return;
  }

  // Untyped integer values must not grow arbitrarily.
  const prec = 512; // 512 is the constant precision
  if (constantKindOf(x.val) === "int" && bitLen(x.val) > prec) {
    let op = opName(x.expr);
    if (op !== "") {
      op += " ";
    }
    this.errorf(atPos(opPos), "InvalidConstVal", "constant %soverflow", op);
    x.val = makeUnknown();
    return;
  }

  // String values must not become arbitrarily long (go.dev/issue/78346).
  const maxLen = 2e9; // cmd/internal/obj.MaxSymSize
  if (constantKindOf(x.val) === "string") {
    const len = String(x.val).length;
    if (len > maxLen) {
      this.errorf(atPos(opPos), "InvalidConstVal", "constant string too long (%d bytes > %d bytes)", len, maxLen);
      x.val = makeUnknown();
      return;
    }
  }
};

// representableConst reports whether x can be represented as
// value of the given basic type and for the configuration
// provided (only needed for int/uint sizes).
//
// If rounded != nil, *rounded is set to the rounded value of x for
// representable floating-point and complex values, and to an Int
// value for integer values; it is left alone otherwise.
// It is ok to provide the addressof the first argument for rounded.
//
// The check parameter may be nil if representableConst is invoked
// (indirectly) through an exported API call (AssignableTo, ConvertibleTo)
// because we don't need the Checker's config for those calls.
export function representableConst(x: unknown, check: Checker | null, typ: Basic, rounded: { value: unknown } | null): boolean {
  if (constantKindOf(x) === "unknown") {
    return true; // avoid follow-up errors
  }

  const conf = check !== null ? check.conf : null;

  const sizeof = (T: Type): number => {
    const s = conf?.Sizes?.Sizeof(T) ?? stdSizes.Sizeof(T);
    return s;
  };

  switch (true) {
    case isInteger(typ): {
      const xi = toInt(x);
      if (xi === null) {
        return false;
      }
      if (rounded !== null) {
        rounded.value = xi;
      }
      if (fitsInt64(xi)) {
        const n = xi;
        switch (typ.kind) {
          case Int: {
            const s = BigInt(sizeof(typ) * 8);
            return (-(1n << (s - 1n))) <= n && n <= (1n << (s - 1n)) - 1n;
          }
          case Int8: {
            const s = 8n;
            return (-(1n << (s - 1n))) <= n && n <= (1n << (s - 1n)) - 1n;
          }
          case Int16: {
            const s = 16n;
            return (-(1n << (s - 1n))) <= n && n <= (1n << (s - 1n)) - 1n;
          }
          case Int32: {
            const s = 32n;
            return (-(1n << (s - 1n))) <= n && n <= (1n << (s - 1n)) - 1n;
          }
          case Int64:
          case UntypedInt:
            return true;
          case Uint:
          case Uintptr: {
            const s = BigInt(sizeof(typ) * 8);
            if (s < 64n) {
              return 0n <= n && n <= (1n << s) - 1n;
            }
            return 0n <= n;
          }
          case Uint8: {
            const s = 8n;
            return 0n <= n && n <= (1n << s) - 1n;
          }
          case Uint16: {
            const s = 16n;
            return 0n <= n && n <= (1n << s) - 1n;
          }
          case Uint32: {
            const s = 32n;
            return 0n <= n && n <= (1n << s) - 1n;
          }
          case Uint64:
            return 0n <= n;
          default:
            throw new Error("unreachable");
        }
      }
      // x does not fit into int64
      switch (typ.kind) {
        case Uint:
        case Uintptr: {
          const s = sizeof(typ) * 8;
          return sign(xi) >= 0 && bitLen(xi) <= s;
        }
        case Uint64:
          return sign(xi) >= 0 && bitLen(xi) <= 64;
        case UntypedInt:
          return true;
      }
      break;
    }

    case isFloat(typ): {
      const xf = toFloat(x);
      if (xf === null) {
        return false;
      }
      switch (typ.kind) {
        case Float32:
          if (rounded === null) {
            return fitsFloat32(xf);
          }
          {
            const r = roundFloat32(xf);
            if (r !== null) {
              rounded.value = r;
              return true;
            }
          }
          break;
        case Float64:
          if (rounded === null) {
            return fitsFloat64(xf);
          }
          {
            const r = roundFloat64(xf);
            if (r !== null) {
              rounded.value = r;
              return true;
            }
          }
          break;
        case UntypedFloat:
          return true;
        default:
          throw new Error("unreachable");
      }
      break;
    }

    case isComplex(typ): {
      const xc = toComplex(x);
      if (xc === null) {
        return false;
      }
      switch (typ.kind) {
        case Complex64:
          if (rounded === null) {
            return fitsFloat32(real(xc)) && fitsFloat32(imag(xc));
          }
          {
            const re = roundFloat32(real(xc));
            const im = roundFloat32(imag(xc));
            if (re !== null && im !== null) {
              rounded.value = makeComplex(re, im);
              return true;
            }
          }
          break;
        case Complex128:
          if (rounded === null) {
            return fitsFloat64(real(xc)) && fitsFloat64(imag(xc));
          }
          {
            const re = roundFloat64(real(xc));
            const im = roundFloat64(imag(xc));
            if (re !== null && im !== null) {
              rounded.value = makeComplex(re, im);
              return true;
            }
          }
          break;
        case UntypedComplex:
          return true;
        default:
          throw new Error("unreachable");
      }
      break;
    }

    case isString(typ):
      return constantKindOf(x) === "string";

    case isBoolean(typ):
      return constantKindOf(x) === "bool";
  }

  return false;
}

export function fitsFloat32(x: unknown): boolean {
  const f32 = Math.fround(Number(x));
  const f = Number(f32);
  return Number.isFinite(f);
}

export function roundFloat32(x: unknown): unknown {
  const f32 = Math.fround(Number(x));
  const f = Number(f32);
  if (Number.isFinite(f)) {
    return f;
  }
  return null;
}

export function fitsFloat64(x: unknown): boolean {
  const f = Number(x);
  return Number.isFinite(f);
}

export function roundFloat64(x: unknown): unknown {
  const f = Number(x);
  if (Number.isFinite(f)) {
    return f;
  }
  return null;
}

// representable checks that a constant operand is representable in the given
// basic type.
Checker.prototype.representable = function representable(x: operand, typ: Basic): void {
  const [v, code] = this.representation(x, typ);
  if (code !== 0) {
    this.invalidConversion(code, x, typ);
    x.invalidate();
    return;
  }
  assert(v !== null && v !== undefined);
  x.val = v;
};

// representation returns the representation of the constant operand x as the
// basic type typ.
//
// If no such representation is possible, it returns a non-zero error code.
Checker.prototype.representation = function representation(x: operand, typ: Basic): [unknown, unknown] {
  assert(x.mode() === constant_);
  const v = { value: x.val };
  if (!representableConst(x.val, this, typ, v)) {
    if (isNumeric(x.typ()!) && isNumeric(typ)) {
      // numeric conversion : error msg
      //
      // integer -> integer : overflows
      // integer -> float   : overflows (actually not possible)
      // float   -> integer : truncated
      // float   -> float   : overflows
      //
      if (!isInteger(x.typ()!) && isInteger(typ)) {
        return [null, "TruncatedFloat"];
      } else {
        return [null, "NumericOverflow"];
      }
    }
    return [null, "InvalidConstVal"];
  }
  return [v.value, 0];
};

Checker.prototype.invalidConversion = function invalidConversion(code: unknown, x: operand, target: Type): void {
  let msg = "cannot convert %s to type %s";
  switch (code) {
    case "TruncatedFloat":
      msg = "%s truncated to %s";
      break;
    case "NumericOverflow":
      msg = "%s overflows %s";
      break;
  }
  this.errorf(x, code, msg, x, target);
};

// convertUntyped attempts to set the type of an untyped value to the target type.
Checker.prototype.convertUntyped = function convertUntyped(x: operand, target: Type): void {
  let [newType, val, code] = this.implicitTypeAndValue(x, target);
  if (code !== 0) {
    let t = target;
    if (!isTypeParam(target)) {
      t = target.Underlying();
    }
    this.invalidConversion(code, x, t);
    x.invalidate();
    return;
  }
  if (val !== null && val !== undefined) {
    x.val = val;
    this.updateExprVal?.(x.expr, val);
  }
  if (newType !== x.typ()) {
    x.typ_ = newType;
    this.updateExprType?.(x.expr, newType!, false);
  }
};

export function constantKindOf(x: unknown): constantKind {
  if (x === null || x === undefined) {
    return "unknown";
  }
  const xo = x as { Kind?: () => string; kind?: string };
  const k = typeof xo.Kind === "function" ? xo.Kind() : xo.kind;
  if (typeof k === "string") {
    const lower = k.toLowerCase();
    if (lower.includes("unknown")) {
      return "unknown";
    }
    if (lower.includes("bool")) {
      return "bool";
    }
    if (lower.includes("string")) {
      return "string";
    }
    if (lower.includes("int")) {
      return "int";
    }
    if (lower.includes("float")) {
      return "float";
    }
    if (lower.includes("complex")) {
      return "complex";
    }
  }
  if (typeof x === "boolean") {
    return "bool";
  }
  if (typeof x === "string") {
    return "string";
  }
  if (typeof x === "bigint") {
    return "int";
  }
  if (typeof x === "number") {
    return Number.isInteger(x) ? "int" : "float";
  }
  if (isComplexValue(x)) {
    return "complex";
  }
  return "unknown";
}

export function toInt(x: unknown): bigint | null {
  if (typeof x === "bigint") {
    return x;
  }
  if (typeof x === "number" && Number.isInteger(x)) {
    return BigInt(x);
  }
  const xo = x as { toBigInt?: () => bigint; value?: unknown } | null;
  if (xo !== null && typeof xo === "object") {
    if (typeof xo.toBigInt === "function") {
      return xo.toBigInt();
    }
    if (xo.value !== undefined) {
      return toInt(xo.value);
    }
  }
  return null;
}

export function toFloat(x: unknown): number | null {
  if (typeof x === "number") {
    return x;
  }
  if (typeof x === "bigint") {
    return Number(x);
  }
  const xo = x as { value?: unknown } | null;
  if (xo !== null && typeof xo === "object" && xo.value !== undefined) {
    return toFloat(xo.value);
  }
  return null;
}

export function toComplex(x: unknown): complexValue | null {
  if (isComplexValue(x)) {
    return x;
  }
  const f = toFloat(x);
  if (f !== null) {
    return { re: f, im: 0 };
  }
  return null;
}

function isComplexValue(x: unknown): x is complexValue {
  if (x === null || typeof x !== "object") {
    return false;
  }
  return ("re" in x && "im" in x) || ("real" in x && "imag" in x);
}

export function real(x: complexValue): unknown {
  return "re" in x ? x.re : x.real;
}

export function imag(x: complexValue): unknown {
  return "im" in x ? x.im : x.imag;
}

export function makeComplex(re: unknown, im: unknown): complexValue {
  return { re, im };
}

function fitsInt64(x: bigint): boolean {
  return -(1n << 63n) <= x && x <= (1n << 63n) - 1n;
}

export function bitLen(x: unknown): number {
  const xi = toInt(x);
  if (xi === null) {
    return 0;
  }
  let n = xi < 0n ? -xi : xi;
  let bits = 0;
  while (n > 0n) {
    bits++;
    n >>= 1n;
  }
  return bits;
}

export function sign(x: bigint): number {
  if (x < 0n) {
    return -1;
  }
  if (x > 0n) {
    return 1;
  }
  return 0;
}

export function makeUnknown(): unknown {
  return { kind: "Unknown" };
}

function opName(expr: unknown): string {
  const e = expr as { op?: string; Op?: string } | null;
  return e?.op ?? e?.Op ?? "";
}
