// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/object.go

// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

import type { Pos } from "./token.js";
import { nopos, debug } from "./check.js";
import type { Package } from "./package.js";
import type { Scope } from "./scope.js";
import type { Type } from "./type.js";
import { assert } from "./util.js";
import { Basic, BasicKind, Invalid } from "./basic.js";
import { Typ, Unsafe, Universe, universeByte, universeRune, builtinId, predeclaredFuncs } from "./universe.js";
import { samePkg, Identical } from "./predicates.js";
import { Alias } from "./alias.js";
import { Named } from "./named.js";
import { TypeParam } from "./typeparam.js";
import { Interface, emptyInterface } from "./interface.js";
import { Signature } from "./signature.js";
import { TypeString, type Qualifier, WriteSignature, WriteType } from "./typestring.js";

// An Object is a named language entity.
// An Object may be a constant ([Const]), type name ([TypeName]),
// variable or struct field ([Var]), function or method ([Func]),
// imported package ([PkgName]), label ([Label]),
// built-in function ([Builtin]),
// or the predeclared identifier 'nil' ([Nil]).
//
// The environment, which is structured as a tree of Scopes,
// maps each name to the unique Object that it denotes.
export interface Object {
  Parent(): Scope | null; // scope in which this object is declared; nil for methods and struct fields
  Pos(): Pos; // position of object identifier in declaration
  Pkg(): Package | null; // package to which this object belongs; nil for labels and objects in the Universe scope
  Name(): string; // package local object name
  Type(): Type | null; // object type
  Exported(): boolean; // reports whether the name starts with a capital letter
  Id(): string; // object name if exported, qualified name if not exported (see func Id)

  // String returns a human-readable string of the object.
  // Use [ObjectString] to control how package names are formatted in the string.
  String(): string;

  // order reflects a package-level object's source order: if object
  // a is before object b in the source, then a.order() < b.order().
  // order returns a value > 0 for package-level objects; it returns
  // 0 for all other objects (including objects in file scopes).
  order(): number;

  // setType sets the type of the object.
  setType(typ: Type | null): void;

  // setOrder sets the order number of the object. It must be > 0.
  setOrder(order: number): void;

  // setParent sets the parent scope of the object.
  setParent(parent: Scope): void;

  // sameId reports whether obj.Id() and Id(pkg, name) are the same.
  // If foldCase is true, names are considered equal if they are equal with case folding
  // and their packages are ignored (e.g., pkg1.m, pkg1.M, pkg2.m, and pkg2.M are all equal).
  sameId(pkg: Package | null, name: string, foldCase: boolean): boolean;

  // scopePos returns the start position of the scope of this Object
  scopePos(): Pos;

  // setScopePos sets the start position of the scope for this Object.
  setScopePos(pos: Pos): void;
}

export function isExported(name: string): boolean {
  const ch = Array.from(name)[0] ?? "";
  return ch.toLocaleUpperCase() === ch && ch.toLocaleLowerCase() !== ch;
}

// Id returns name if it is exported, otherwise it
// returns the name qualified with the package path.
export function Id(pkg: Package | null, name: string): string {
  if (isExported(name)) {
    return name;
  }
  // unexported names need the package path for differentiation
  // (if there's no package, make sure we don't start with '.'
  // as that may change the order of methods between a setup
  // inside a package and outside a package - which breaks some
  // tests)
  let path = "_";
  // pkg is nil for objects in Universe scope and possibly types
  // introduced via Eval (see also comment in object.sameId)
  if (pkg !== null && pkg.path !== "") {
    path = pkg.path;
  }
  return path + "." + name;
}

// An object implements the common parts of an Object.
export class object_ implements Object {
  public constructor(
    public parent: Scope | null,
    public pos: Pos,
    public pkg: Package | null,
    public name: string,
    public typ: Type | null,
    public order_: number,
    public scopePos_: Pos
  ) {}

  // Parent returns the scope in which the object is declared.
  // The result is nil for methods and struct fields.
  public Parent(): Scope | null { return this.parent; }

  // Pos returns the declaration position of the object's identifier.
  public Pos(): Pos { return this.pos; }

  // Pkg returns the package to which the object belongs.
  // The result is nil for labels and objects in the Universe scope.
  public Pkg(): Package | null { return this.pkg; }

  // Name returns the object's (package-local, unqualified) name.
  public Name(): string { return this.name; }

  // Type returns the object's type.
  public Type(): Type | null { return this.typ; }

  // Exported reports whether the object is exported (starts with a capital letter).
  // It doesn't take into account whether the object is in a local (function) scope
  // or not.
  public Exported(): boolean { return isExported(this.name); }

  // Id is a wrapper for Id(obj.Pkg(), obj.Name()).
  public Id(): string { return Id(this.pkg, this.name); }

  public String(): string { throw new Error("abstract"); }
  public order(): number { return this.order_; }
  public scopePos(): Pos { return this.scopePos_; }

  public setParent(parent: Scope): void { this.parent = parent; }
  public setType(typ: Type | null): void { this.typ = typ; }
  public setOrder(order: number): void { assert(order > 0); this.order_ = order; }
  public setScopePos(pos: Pos): void { this.scopePos_ = pos; }

  public sameId(pkg: Package | null, name: string, foldCase: boolean): boolean {
    // If we don't care about capitalization, we also ignore packages.
    if (foldCase && this.name.toLocaleLowerCase() === name.toLocaleLowerCase()) {
      return true;
    }
    // spec:
    // "Two identifiers are different if they are spelled differently,
    // or if they appear in different packages and are not exported.
    // Otherwise, they are the same."
    if (this.name !== name) {
      return false;
    }
    // obj.Name == name
    if (this.Exported()) {
      return true;
    }
    // not exported, so packages must be the same
    return samePkg(this.pkg, pkg);
  }

  // cmp reports whether object a is ordered before object b.
  public cmp(b: object_ | null): number {
    const a: object_ | null = this;
    if (a === b) {
      return 0;
    }

    // Nil before non-nil.
    if (a === null) {
      return -1;
    }
    if (b === null) {
      return +1;
    }

    // Exported functions before non-exported.
    const ea = isExported(a.name);
    const eb = isExported(b.name);
    if (ea !== eb) {
      if (ea) {
        return -1;
      }
      return +1;
    }

    // Order by name and then (for non-exported names) by package.
    if (a.name !== b.name) {
      return a.name.localeCompare(b.name);
    }
    if (!ea) {
      return (a.pkg?.path ?? "").localeCompare(b.pkg?.path ?? "");
    }

    return 0;
  }
}

// A PkgName represents an imported Go package.
// PkgNames don't have a type.
export class PkgName extends object_ {
  public constructor(pos: Pos, pkg: Package | null, name: string, public imported: Package) {
    super(null, pos, pkg, name, Typ[Invalid]!, 0, nopos);
  }

  // Imported returns the package that was imported.
  // It is distinct from Pkg(), which is the package containing the import statement.
  public Imported(): Package { return this.imported; }

  public String(): string { return ObjectString(this, null); }
}

// NewPkgName returns a new PkgName object representing an imported package.
// The remaining arguments set the attributes found with all Objects.
export function NewPkgName(pos: Pos, pkg: Package | null, name: string, imported: Package): PkgName {
  return new PkgName(pos, pkg, name, imported);
}

// A Const represents a declared constant.
export class Const extends object_ {
  public constructor(pos: Pos, pkg: Package | null, name: string, typ: Type | null, public val: unknown) {
    super(null, pos, pkg, name, typ, 0, nopos);
  }

  // Val returns the constant's value.
  public Val(): unknown { return this.val; }

  public isDependency(): void {} // a constant may be a dependency of an initialization expression
  public String(): string { return ObjectString(this, null); }
}

// NewConst returns a new constant with value val.
// The remaining arguments set the attributes found with all Objects.
export function NewConst(pos: Pos, pkg: Package | null, name: string, typ: Type | null, val: unknown): Const {
  return new Const(pos, pkg, name, typ, val);
}

// A TypeName is an [Object] that represents a type with a name:
// a defined type ([Named]),
// an alias type ([Alias]),
// a type parameter ([TypeParam]),
// or a predeclared type such as int or error.
export class TypeName extends object_ {
  public constructor(pos: Pos, pkg: Package | null, name: string, typ: Type | null) {
    super(null, pos, pkg, name, typ, 0, nopos);
  }

  // IsAlias reports whether obj is an alias name for a type.
  public IsAlias(): boolean {
    const t = this.typ;
    if (t === null) {
      return false;
    }
    if (t instanceof Basic) {
      // unsafe.Pointer is not an alias.
      if (this.pkg === Unsafe) {
        return false;
      }
      // Any user-defined type name for a basic type is an alias for a
      // basic type (because basic types are pre-declared in the Universe
      // scope, outside any package scope), and so is any type name with
      // a different name than the name of the basic type it refers to.
      // Additionally, we need to look for "byte" and "rune" because they
      // are aliases but have the same names (for better error messages).
      return this.pkg !== null || t.name !== this.name || t === universeByte || t === universeRune;
    }
    if (t instanceof Named) {
      return this !== t.obj;
    }
    if (t instanceof TypeParam) {
      return this !== t.obj;
    }
    if (t instanceof Alias) {
      return true;
    }
    return true;
  }

  public String(): string { return ObjectString(this, null); }
}

// NewTypeName returns a new type name denoting the given typ.
// The remaining arguments set the attributes found with all Objects.
export function NewTypeName(pos: Pos, pkg: Package | null, name: string, typ: Type | null): TypeName {
  return new TypeName(pos, pkg, name, typ);
}

// NewTypeNameLazy returns a new defined type like NewTypeName, but it
// lazily calls unpack to finish constructing the Named object.
export function _NewTypeNameLazy(pos: Pos, pkg: Package | null, name: string, load: (named: Named) => [TypeParam[] | null, Type | null, Func[] | null, (() => void)[] | null]): TypeName {
  const obj = NewTypeName(pos, pkg, name, null);
  const n = new Named(null, obj, null, null);
  n.loader = load as Named["loader"];
  return obj;
}

// A Var represents a declared variable (including function parameters and results, and struct fields).
export class Var extends object_ {
  public origin: Var | null = null; // if non-nil, the Var from which this one was instantiated
  public kind: VarKind;
  public embedded = false; // if set, the variable is an embedded struct field, and name is the type name

  public constructor(kind: VarKind, pos: Pos, pkg: Package | null, name: string, typ: Type | null) {
    super(null, pos, pkg, name, typ, 0, nopos);
    this.kind = kind;
  }

  // Kind reports what kind of variable v is.
  public Kind(): VarKind { return this.kind; }

  // SetKind sets the kind of the variable.
  // It should be used only immediately after [NewVar] or [NewParam].
  public SetKind(kind: VarKind): void { this.kind = kind; }

  // Anonymous reports whether the variable is an embedded field.
  // Same as Embedded; only present for backward-compatibility.
  public Anonymous(): boolean { return this.embedded; }

  // Embedded reports whether the variable is an embedded field.
  public Embedded(): boolean { return this.embedded; }

  // IsField reports whether the variable is a struct field.
  public IsField(): boolean { return this.kind === VarKind.FieldVar; }

  // Origin returns the canonical Var for its receiver, i.e. the Var object
  // recorded in Info.Defs.
  public Origin(): Var {
    if (this.origin !== null) {
      return this.origin;
    }
    return this;
  }

  public isDependency(): void {} // a variable may be a dependency of an initialization expression
  public String(): string { return ObjectString(this, null); }
}

// A VarKind discriminates the various kinds of variables.
export enum VarKind {
  _ = 0, // (not meaningful)
  PackageVar, // a package-level variable
  LocalVar, // a local variable
  RecvVar, // a method receiver variable
  ParamVar, // a function parameter variable
  ResultVar, // a function result variable
  FieldVar // a struct field
}

export const PackageVar = VarKind.PackageVar;
export const LocalVar = VarKind.LocalVar;
export const RecvVar = VarKind.RecvVar;
export const ParamVar = VarKind.ParamVar;
export const ResultVar = VarKind.ResultVar;
export const FieldVar = VarKind.FieldVar;

export const varKindNames = [
  "VarKind(0)",
  "PackageVar",
  "LocalVar",
  "RecvVar",
  "ParamVar",
  "ResultVar",
  "FieldVar"
];

export function VarKindString(kind: VarKind): string {
  if (0 <= kind && kind < varKindNames.length) {
    return varKindNames[kind]!;
  }
  return `VarKind(${kind})`;
}

// NewVar returns a new variable.
// The arguments set the attributes found with all Objects.
export function NewVar(pos: Pos, pkg: Package | null, name: string, typ: Type | null): Var {
  return newVar(VarKind.PackageVar, pos, pkg, name, typ);
}

// NewParam returns a new variable representing a function parameter.
export function NewParam(pos: Pos, pkg: Package | null, name: string, typ: Type | null): Var {
  return newVar(VarKind.ParamVar, pos, pkg, name, typ);
}

// NewField returns a new variable representing a struct field.
// For embedded fields, the name is the unqualified type name
// under which the field is accessible.
export function NewField(pos: Pos, pkg: Package | null, name: string, typ: Type | null, embedded: boolean): Var {
  const v = newVar(VarKind.FieldVar, pos, pkg, name, typ);
  v.embedded = embedded;
  return v;
}

// newVar returns a new variable.
// The arguments set the attributes found with all Objects.
export function newVar(kind: VarKind, pos: Pos, pkg: Package | null, name: string, typ: Type | null): Var {
  return new Var(kind, pos, pkg, name, typ);
}

// A Func represents a declared function, concrete method, or abstract
// (interface) method. Its Type() is always a *Signature.
// An abstract method may belong to many interfaces due to embedding.
export class Func extends object_ {
  public origin: Func | null = null; // if non-nil, the Func from which this one was instantiated
  public hasPtrRecv_ = false; // only valid for methods that don't have a type yet; use hasPtrRecv() to read
  public nointerface = false;

  public constructor(pos: Pos, pkg: Package | null, name: string, sig: Signature | null) {
    let typ: Type | null = null;
    if (sig !== null) {
      typ = sig;
    } else {
      // Don't store a (typed) nil *Signature.
      // We can't simply replace it with new(Signature) either,
      // as this would violate object.{Type,color} invariants.
      // TODO(adonovan): propose to disallow NewFunc with nil *Signature.
    }
    super(null, pos, pkg, name, typ, 0, nopos);
  }

  // Signature returns the signature (type) of the function or method.
  public Signature(): Signature {
    if (this.typ instanceof Signature) {
      return this.typ; // normal case
    }
    // No signature: Signature was called either:
    // - within go/types, before a FuncDecl's initially
    //   nil Func.Type was lazily populated, indicating
    //   a types bug; or
    // - by a client after NewFunc(..., nil),
    //   which is arguably a client bug, but we need a
    //   proposal to tighten NewFunc's precondition.
    // For now, return a trivial signature.
    return new Signature();
  }

  // FullName returns the package- or receiver-type-qualified name of
  // function or method obj.
  public FullName(): string {
    const buf: string[] = [];
    writeFuncName(buf, this, null);
    return buf.join("");
  }

  // Scope returns the scope of the function's body block.
  // The result is nil for imported or instantiated functions and methods
  // (but there is also no mechanism to get to an instantiated function).
  public Scope(): Scope | null { return this.Signature().scope; }

  // Origin returns the canonical Func for its receiver, i.e. the Func object
  // recorded in Info.Defs.
  public Origin(): Func {
    if (this.origin !== null) {
      return this.origin;
    }
    return this;
  }

  // Pkg returns the package to which the function belongs.
  //
  // The result is nil for methods of types in the Universe scope,
  // like method Error of the error built-in interface type.
  public Pkg(): Package | null { return super.Pkg(); }

  // hasPtrRecv reports whether the receiver is of the form *T for the given method obj.
  public hasPtrRecv(): boolean {
    // If a method's receiver type is set, use that as the source of truth for the receiver.
    // Caution: Checker.funcDecl (decl.go) marks a function by setting its type to an empty
    // signature. We may reach here before the signature is fully set up: we must explicitly
    // check if the receiver is set (we cannot just look for non-nil obj.typ).
    if (this.typ instanceof Signature && this.typ.recv !== null) {
      return TypeString(this.typ.recv.typ ?? Typ[Invalid]!, null).startsWith("*");
    }

    // If a method's type is not set it may be a method/function that is:
    // 1) client-supplied (via NewFunc with no signature), or
    // 2) internally created but not yet type-checked.
    // For case 1) we can't do anything; the client must know what they are doing.
    // For case 2) we can use the information gathered by the resolver.
    return this.hasPtrRecv_;
  }

  public isDependency(): void {} // a function may be a dependency of an initialization expression
  public String(): string { return ObjectString(this, null); }
}

// NewFunc returns a new function with the given signature, representing
// the function's type.
export function NewFunc(pos: Pos, pkg: Package | null, name: string, sig: Signature | null): Func {
  return new Func(pos, pkg, name, sig);
}

// A Label represents a declared label.
// Labels don't have a type.
export class Label extends object_ {
  public used = false; // set if the label was used

  public constructor(pos: Pos, pkg: Package | null, name: string) {
    super(null, pos, pkg, name, Typ[Invalid]!, 0, nopos);
  }

  public String(): string { return ObjectString(this, null); }
}

// NewLabel returns a new label.
export function NewLabel(pos: Pos, pkg: Package | null, name: string): Label {
  return new Label(pos, pkg, name);
}

// A Builtin represents a built-in function.
// Builtins don't have a valid type.
export class Builtin extends object_ {
  public constructor(public id: builtinId) {
    super(null, nopos, null, predeclaredFuncs[id]!.name, Typ[Invalid]!, 0, nopos);
  }

  public String(): string { return ObjectString(this, null); }
}

export function newBuiltin(id: builtinId): Builtin {
  return new Builtin(id);
}

// Nil represents the predeclared value nil.
export class Nil extends object_ {
  public constructor() {
    super(null, nopos, null, "nil", Typ[BasicKind.UntypedNil]!, 0, nopos);
  }

  public String(): string { return ObjectString(this, null); }
}

export function writeObject(buf: string[], obj: Object, qf: Qualifier | null): void {
  let tname: TypeName | null = null;
  let typ = obj.Type();

  if (obj instanceof PkgName) {
    buf.push(`package ${obj.Name()}`);
    const path = obj.imported.path;
    if (path !== "" && path !== obj.name) {
      buf.push(` (${JSON.stringify(path)})`);
    }
    return;
  } else if (obj instanceof Const) {
    buf.push("const");
  } else if (obj instanceof TypeName) {
    tname = obj;
    buf.push("type");
    if (typ instanceof TypeParam) {
      buf.push(" parameter");
    }
  } else if (obj instanceof Var) {
    if (obj.IsField()) {
      buf.push("field");
    } else {
      buf.push("var");
    }
  } else if (obj instanceof Func) {
    buf.push("func ");
    writeFuncName(buf, obj, qf);
    if (typ instanceof Signature) {
      WriteSignature(buf, typ, qf);
    }
    return;
  } else if (obj instanceof Label) {
    buf.push("label");
    typ = null;
  } else if (obj instanceof Builtin) {
    buf.push("builtin");
    typ = null;
  } else if (obj instanceof Nil) {
    buf.push("nil");
    return;
  } else {
    throw new Error(`writeObject(${obj.constructor.name})`);
  }

  buf.push(" ");

  // For package-level objects, qualify the name.
  if (obj.Pkg() !== null && obj.Pkg()!.scope.Lookup(obj.Name()) === obj) {
    buf.push(packagePrefix(obj.Pkg(), qf));
  }
  buf.push(obj.Name());

  if (typ === null) {
    return;
  }

  if (tname !== null) {
    if (typ instanceof Basic) {
      // Don't print anything more for basic types since there's
      // no more information.
      return;
    }
    if (tname.IsAlias()) {
      buf.push(" =");
      if (typ instanceof Alias) {
        typ = typ.fromRHS;
      }
    } else if (typ instanceof TypeParam) {
      typ = typ.bound;
    } else {
      typ = typ.Underlying();
    }
  }

  // Special handling for any: because WriteType will format 'any' as 'any',
  // resulting in the object string `type any = any` rather than `type any =
  // interface{}`. To avoid this, swap in a different empty interface.
  if (obj.Name() === "any" && obj.Parent() === Universe) {
    assert(Identical(typ, emptyInterface));
    typ = emptyInterface;
  }

  buf.push(" ");
  WriteType(buf, typ, qf);
}

export function packagePrefix(pkg: Package | null, qf: Qualifier | null): string {
  if (pkg === null) {
    return "";
  }
  let s: string;
  if (qf !== null) {
    s = qf(pkg);
  } else {
    s = pkg.Path();
  }
  if (s !== "") {
    s += ".";
  }
  return s;
}

// ObjectString returns the string form of obj.
// The Qualifier controls the printing of
// package-level objects, and may be nil.
export function ObjectString(obj: Object, qf: Qualifier | null): string {
  const buf: string[] = [];
  writeObject(buf, obj, qf);
  return buf.join("");
}

export function writeFuncName(buf: string[], f: Func, qf: Qualifier | null): void {
  if (f.typ instanceof Signature) {
    const sig = f.typ;
    const recv = sig.Recv();
    if (recv !== null) {
      buf.push("(");
      if (recv.Type() instanceof Interface) {
        // gcimporter creates abstract methods of
        // named interfaces using the interface type
        // (not the named type) as the receiver.
        // Don't print it in full.
        buf.push("interface");
      } else {
        WriteType(buf, recv.Type(), qf);
      }
      buf.push(")");
      buf.push(".");
    } else if (f.pkg !== null) {
      buf.push(packagePrefix(f.pkg, qf));
    }
  }
  buf.push(f.name);
}

// objectKind returns a description of the object's kind.
export function objectKind(obj: Object): string {
  if (obj instanceof PkgName) {
    return "package name";
  }
  if (obj instanceof Const) {
    return "constant";
  }
  if (obj instanceof TypeName) {
    if (obj.IsAlias()) {
      return "type alias";
    } else if (obj.Type() instanceof TypeParam) {
      return "type parameter";
    } else {
      return "defined type";
    }
  }
  if (obj instanceof Var) {
    switch (obj.Kind()) {
      case VarKind.PackageVar:
        return "package-level variable";
      case VarKind.LocalVar:
        return "local variable";
      case VarKind.RecvVar:
        return "receiver";
      case VarKind.ParamVar:
        return "parameter";
      case VarKind.ResultVar:
        return "result variable";
      case VarKind.FieldVar:
        return "struct field";
    }
  }
  if (obj instanceof Func) {
    if (obj.Signature().Recv() !== null) {
      return "method";
    } else {
      return "function";
    }
  }
  if (obj instanceof Label) {
    return "label";
  }
  if (obj instanceof Builtin) {
    return "built-in function";
  }
  if (obj instanceof Nil) {
    return "untyped nil";
  }
  if (debug) {
    throw new Error(`unknown symbol (${obj.constructor.name})`);
  }
  return "unknown symbol";
}
