// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/package.go

// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

import { nopos } from "./check.js";
import { NewScope, type Scope } from "./scope.js";
import { Universe } from "./universe.js";

// A Package describes a Go package.
export class Package {
  public constructor(
    public path: string,
    public name: string,
    public scope: Scope,
    public imports: Package[] = [],
    public complete = false,
    public fake = false, // scope lookup errors are silently dropped if package is fake (internal use only)
    public cgo = false, // uses of this package will be rewritten into uses of declarations from _cgo_gotypes.go
    public goVersion = "" // minimum Go version required for package (by Config.GoVersion, typically from go.mod)
  ) {}

  // Path returns the package path.
  public Path(): string { return this.path; }

  // Name returns the package name.
  public Name(): string { return this.name; }

  // SetName sets the package name.
  public SetName(name: string): void { this.name = name; }

  // GoVersion returns the minimum Go version required by this package.
  // If the minimum version is unknown, GoVersion returns the empty string.
  // Individual source files may specify a different minimum Go version,
  // as reported in the [go/ast.File.GoVersion] field.
  public GoVersion(): string { return this.goVersion; }

  // Scope returns the (complete or incomplete) package scope
  // holding the objects declared at package level (TypeNames,
  // Consts, Vars, and Funcs).
  // For a nil pkg receiver, Scope returns the Universe scope.
  public Scope(): Scope {
    return this.scope;
  }

  // A package is complete if its scope contains (at least) all
  // exported objects; otherwise it is incomplete.
  public Complete(): boolean { return this.complete; }

  // MarkComplete marks a package as complete.
  public MarkComplete(): void { this.complete = true; }

  // Imports returns the list of packages directly imported by
  // pkg; the list is in source order.
  //
  // If pkg was loaded from export data, Imports includes packages that
  // provide package-level objects referenced by pkg. This may be more or
  // less than the set of packages directly imported by pkg's source code.
  //
  // If pkg uses cgo and the FakeImportC configuration option
  // was enabled, the imports list may contain a fake "C" package.
  public Imports(): Package[] { return this.imports; }

  // SetImports sets the list of explicitly imported packages to list.
  // It is the caller's responsibility to make sure list elements are unique.
  public SetImports(list: Package[]): void { this.imports = list; }

  public String(): string {
    return `package ${this.name} (${JSON.stringify(this.path)})`;
  }
}

// NewPackage returns a new Package for the given package path and name.
// The package is not complete and contains no explicit imports.
export function NewPackage(path: string, name: string): Package {
  const scope = NewScope(Universe, nopos, nopos, `package ${JSON.stringify(path)}`);
  return new Package(path, name, scope);
}
