// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/predicates.go

// Copyright 2011 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

import type { Package } from "./package.js";
import type { Type } from "./type.js";
import { Basic, BasicKind } from "./basic.js";

// samePkg reports whether packages a and b are the same.
export function samePkg(a: Package | null, b: Package | null): boolean {
  // package is nil for objects in universe scope
  if (a === null || b === null) {
    return a === b;
  }
  // a != nil && b != nil
  return a.path === b.path;
}

export function isValid(t: Type | null): boolean {
  if (t instanceof Basic) {
    return t.kind !== BasicKind.Invalid;
  }
  return t !== null;
}

export function Identical(x: Type | null, y: Type | null): boolean {
  return x === y;
}
