// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/recording.go

// Copyright 2024 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file implements recording of type information
// in the types2.Info maps.

import { Checker, instantiatedIdent } from "./check.js";
import { Basic, IsConstType } from "./basic.js";
import type { Type } from "./type.js";
import { Typ, universeError } from "./universe.js";
import { Invalid } from "./basic.js";
import { NewTuple } from "./tuple.js";
import { newTypeList } from "./typelists.js";
import { Instance, TypeAndValue } from "./api.js";
import { Func, LocalVar, newVar, type Object } from "./object.js";
import { methodExprSentinel, Signature } from "./signature.js";
import { operand, operandMode, invalid, novalue, constant_, builtin } from "./operand.js";
import type { Scope } from "./scope.js";
import { assert } from "./util.js";

declare module "./check.js" {
  interface Checker {
    record(x: operand): void;
    recordUntyped(): void;
    recordTypeAndValue(x: unknown, mode: operandMode, typ: Type, val: unknown): void;
    recordBuiltinType(f: unknown, sig: Signature): void;
    recordCommaOkTypes(x: unknown, a: operand[]): void;
    recordInstance(expr: unknown, targs: Type[], typ: Type): void;
    recordDef(id: unknown, obj: Object | null): void;
    recordUse(id: unknown, obj: Object): void;
    recordImplicit(node: unknown, obj: Object): void;
    recordSelection(x: unknown, kind: unknown, recv: Type | null, obj: Object, index: number[], indirect: boolean): void;
    recordScope(node: unknown, scope: Scope): void;
  }
}

Checker.prototype.record = function record(x: operand): void {
  let typ: Type | null;
  let val: unknown = null;
  switch (x.mode()) {
    case invalid:
      typ = Typ[Invalid]!;
      break;
    case novalue:
      typ = null;
      break;
    case constant_:
      typ = x.typ();
      val = x.val;
      break;
    default:
      typ = x.typ();
  }
  assert(x.expr !== null && typ !== null);

  if (isUntyped(typ)) {
    this.rememberUntyped(x.expr, false, x.mode(), typ as Basic, val);
  } else {
    this.recordTypeAndValue(x.expr, x.mode(), typ, val);
  }
};

Checker.prototype.recordUntyped = function recordUntyped(): void {
  if (!this.Info.recordTypes()) {
    return; // nothing to do
  }

  for (const [x, info] of this.untyped ?? []) {
    this.recordTypeAndValue(x, info.mode, info.typ, info.val);
  }
};

Checker.prototype.recordTypeAndValue = function recordTypeAndValue(x: unknown, mode: operandMode, typ: Type, val: unknown): void {
  assert(x !== null && x !== undefined);
  assert(typ !== null);
  if (mode === invalid) {
    return; // omit
  }
  if (mode === constant_) {
    assert(val !== null && val !== undefined);
    assert(!isValid(typ) || allBasic(typ, IsConstType));
  }
  const m = this.Info.Types;
  if (m !== null) {
    m.set(x, new TypeAndValue(mode, typ, val));
  }
  this.recordTypeAndValueInSyntax(x, mode, typ, val);
};

Checker.prototype.recordBuiltinType = function recordBuiltinType(f: unknown, sig: Signature): void {
  for (;;) {
    this.recordTypeAndValue(f, builtin, sig, null);
    const node = f as { kind?: string; X?: unknown };
    switch (node.kind) {
      case "Ident":
      case "SelectorExpr":
        return;
      case "ParenExpr":
        f = node.X;
        break;
      default:
        throw new Error("unreachable");
    }
  }
};

Checker.prototype.recordCommaOkTypes = function recordCommaOkTypes(x: unknown, a: operand[]): void {
  assert(x !== null && x !== undefined);
  assert(a.length === 2);
  if (a[0]!.mode() === invalid) {
    return;
  }
  const t0 = a[0]!.typ()!;
  const t1 = a[1]!.typ()!;
  assert(isTyped(t0) && isTyped(t1) && (allBoolean(t1) || t1 === universeError));
  const m = this.Info.Types;
  if (m !== null) {
    for (;;) {
      const tv = m.get(x);
      assert(tv?.Type !== null && tv?.Type !== undefined);
      const pos = (x as { Pos?: () => number }).Pos?.() ?? 0;
      tv.Type = NewTuple(
        newVar(LocalVar, pos, this.pkg, "", t0),
        newVar(LocalVar, pos, this.pkg, "", t1)
      );
      m.set(x, tv);
      const p = x as { kind?: string; X?: unknown };
      if (p.kind !== "ParenExpr") {
        break;
      }
      x = p.X;
    }
  }
  this.recordCommaOkTypesInSyntax(x, t0, t1);
};

Checker.prototype.recordInstance = function recordInstance(expr: unknown, targs: Type[], typ: Type): void {
  const ident = instantiatedIdent(expr);
  assert(ident !== null && ident !== undefined);
  assert(typ !== null);
  const m = this.Info.Instances;
  if (m !== null) {
    if (typ instanceof Signature && typ.recvold !== null) {
      const copy = Object.assign(new Signature(), typ);
      copy.recvold = null;
      if (typ.recvold === methodExprSentinel) {
        const pars = typ.params;
        if (pars !== null) {
          copy.recv = pars.vars[0]!;
          copy.params = NewTuple(...pars.vars.slice(1));
        }
        m.set(ident, new Instance(newTypeList(targs), copy));
        return;
      }
      copy.recv = typ.recvold;
      m.set(ident, new Instance(newTypeList(targs), copy));
      return;
    }
    m.set(ident, new Instance(newTypeList(targs), typ));
  }
};

Checker.prototype.recordDef = function recordDef(id: unknown, obj: Object | null): void {
  assert(id !== null && id !== undefined);
  const m = this.Info.Defs;
  if (m !== null) {
    m.set(id, obj);
  }
};

Checker.prototype.recordUse = function recordUse(id: unknown, obj: Object): void {
  assert(id !== null && id !== undefined);
  assert(obj !== null);
  const m = this.Info.Uses;
  if (m !== null) {
    m.set(id, obj);
  }
};

Checker.prototype.recordImplicit = function recordImplicit(node: unknown, obj: Object): void {
  assert(node !== null && node !== undefined);
  assert(obj !== null);
  const m = this.Info.Implicits;
  if (m !== null) {
    m.set(node, obj);
  }
};

Checker.prototype.recordSelection = function recordSelection(x: unknown, kind: unknown, recv: Type | null, obj: Object, index: number[], indirect: boolean): void {
  assert(obj !== null && (recv === null || index.length > 0));
  this.recordUse((x as { Sel?: unknown }).Sel, obj);
  const m = this.Info.Selections;
  if (m !== null) {
    m.set(x, { kind, recv, obj, index, indirect } as never);
  }
};

Checker.prototype.recordScope = function recordScope(node: unknown, scope: Scope): void {
  assert(node !== null && node !== undefined);
  assert(scope !== null);
  const m = this.Info.Scopes;
  if (m !== null) {
    m.set(node, scope);
  }
};

function isUntyped(typ: Type): boolean {
  return typ instanceof Basic && (typ.info & 64) !== 0;
}

function isTyped(typ: Type): boolean {
  return !isUntyped(typ);
}

function isValid(typ: Type): boolean {
  return typ !== Typ[Invalid];
}

function allBasic(typ: Type, info: number): boolean {
  return typ instanceof Basic && (typ.info & info) !== 0;
}

function allBoolean(typ: Type): boolean {
  return typ instanceof Basic && typ.name === "bool";
}
