// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/scope.go

// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file implements Scopes.

import type { Pos } from "./token.js";
import type { Object } from "./object.js";

export interface Writer {
  write(s: string): unknown;
}

function scopeIsExported(name: string): boolean {
  const ch = Array.from(name)[0] ?? "";
  return ch.toLocaleUpperCase() === ch && ch.toLocaleLowerCase() !== ch;
}

type scopeUniverseGlobal = typeof globalThis & { __gojrScopeUniverse?: Scope | null };

export function setScopeUniverse(scope: Scope): void {
  (globalThis as scopeUniverseGlobal).__gojrScopeUniverse = scope;
}

export function scopeUniverse(): Scope | null {
  return (globalThis as scopeUniverseGlobal).__gojrScopeUniverse ?? null;
}

// A Scope maintains a set of objects and links to its containing
// (parent) and contained (children) scopes. Objects may be inserted
// and looked up by name. The zero value for Scope is a ready-to-use
// empty scope.
export class Scope {
  public parent: Scope | null;
  public children: Scope[];
  public number: number; // parent.children[number-1] is this scope; 0 if there is no parent
  public elems: Map<string, Object>; // lazily allocated
  public pos: Pos;
  public end: Pos; // scope extent; may be invalid
  public comment: string; // for debugging only
  public isFunc: boolean; // set if this is a function scope (internal use only)

  public constructor(parent: Scope | null, children: Scope[] | null, number: number, elems: Map<string, Object> | null, pos: Pos, end: Pos, comment: string, isFunc: boolean) {
    this.parent = parent;
    this.children = children ?? [];
    this.number = number;
    this.elems = elems ?? new Map();
    this.pos = pos;
    this.end = end;
    this.comment = comment;
    this.isFunc = isFunc;
  }

  // Parent returns the scope's containing (parent) scope.
  public Parent(): Scope | null { return this.parent; }

  // Len returns the number of scope elements.
  public Len(): number { return this.elems.size; }

  // Names returns the scope's element names in sorted order.
  public Names(): string[] {
    const names = Array.from(this.elems.keys());
    names.sort();
    return names;
  }

  // NumChildren returns the number of scopes nested in s.
  public NumChildren(): number { return this.children.length; }

  // Child returns the i'th child scope for 0 <= i < NumChildren().
  public Child(i: number): Scope { return this.children[i]!; }

  // Lookup returns the object in scope s with the given name if such an
  // object exists; otherwise the result is nil.
  public Lookup(name: string): Object | null { return resolve(name, this.elems.get(name) ?? null); }

  // lookupIgnoringCase returns the objects in scope s whose names match
  // the given name ignoring case. If exported is set, only exported names
  // are returned.
  public lookupIgnoringCase(name: string, exported: boolean): Object[] {
    const matches: Object[] = [];
    for (const n of this.Names()) {
      if ((!exported || scopeIsExported(n)) && n.toLocaleLowerCase() === name.toLocaleLowerCase()) {
        const obj = this.Lookup(n);
        if (obj !== null) {
          matches.push(obj);
        }
      }
    }
    return matches;
  }

  // Insert attempts to insert an object obj into scope s.
  // If s already contains an alternative object alt with
  // the same name, Insert leaves s unchanged and returns alt.
  // Otherwise it inserts obj, sets the object's parent scope
  // if not already set, and returns nil.
  public Insert(obj: Object): Object | null {
    const name = obj.Name();
    const alt = this.Lookup(name);
    if (alt !== null) {
      return alt;
    }
    this.insert(name, obj);
    // TODO(gri) Can we always set the parent to s (or is there
    // a need to keep the original parent or some race condition)?
    // If we can, than we may not need environment.lookupScope
    // which is only there so that we get the correct scope for
    // marking "used" dot-imported packages.
    if (obj.Parent() === null) {
      obj.setParent(this);
    }
    return null;
  }

  // InsertLazy is like Insert, but allows deferring construction of the
  // inserted object until it's accessed with Lookup. The Object
  // returned by resolve must have the same name as given to InsertLazy.
  // If s already contains an alternative object with the same name,
  // InsertLazy leaves s unchanged and returns false. Otherwise it
  // records the binding and returns true. The object's parent scope
  // will be set to s after resolve is called.
  public _InsertLazy(name: string, resolve_: () => Object): boolean {
    if (this.elems.get(name) !== undefined) {
      return false;
    }
    this.insert(name, new lazyObject(this, resolve_));
    return true;
  }

  public insert(name: string, obj: Object): void {
    this.elems.set(name, obj);
  }

  // WriteTo writes a string representation of the scope to w,
  // with the scope elements sorted by name.
  // The level of indentation is controlled by n >= 0, with
  // n == 0 for no indentation.
  // If recurse is set, it also writes nested (children) scopes.
  public WriteTo(w: Writer, n: number, recurse: boolean): void {
    const ind = ".  ";
    const indn = ind.repeat(n);

    w.write(`${indn}${this.comment} scope ${String(this)} {\n`);

    const indn1 = indn + ind;
    for (const name of this.Names()) {
      w.write(`${indn1}${String(this.Lookup(name)?.String() ?? "<nil>")}\n`);
    }

    if (recurse) {
      for (const s of this.children) {
        s.WriteTo(w, n + 1, recurse);
      }
    }

    w.write(`${indn}}\n`);
  }

  // String returns a string representation of the scope, for debugging.
  public String(): string {
    const buf: string[] = [];
    this.WriteTo({ write: (s: string) => { buf.push(s); } }, 0, false);
    return buf.join("");
  }
}

// NewScope returns a new, empty scope contained in the given parent
// scope, if any. The comment is for debugging only.
export function NewScope(parent: Scope | null, pos: Pos, end: Pos, comment: string): Scope {
  const s = new Scope(parent, null, 0, null, pos, end, comment, false);
  // don't add children to Universe scope!
  if (parent !== null && parent !== scopeUniverse()) {
    parent.children.push(s);
    s.number = parent.children.length;
  }
  return s;
}

// A lazyObject represents an imported Object that has not been fully
// resolved yet by its importer.
class lazyObject implements Object {
  public obj: Object | null = null;
  public done = false;

  public constructor(
    public parent: Scope,
    public resolve_: () => Object
  ) {}

  // stub implementations so *lazyObject implements Object and we can
  // store them directly into Scope.elems.
  public Parent(): Scope | null { throw new Error("unreachable"); }
  public Pos(): Pos { throw new Error("unreachable"); }
  public Pkg(): import("./package.js").Package | null { throw new Error("unreachable"); }
  public Name(): string { throw new Error("unreachable"); }
  public Type(): import("./type.js").Type | null { throw new Error("unreachable"); }
  public Exported(): boolean { throw new Error("unreachable"); }
  public Id(): string { throw new Error("unreachable"); }
  public String(): string { throw new Error("unreachable"); }
  public order(): number { throw new Error("unreachable"); }
  public setType(_typ: import("./type.js").Type | null): void { throw new Error("unreachable"); }
  public setOrder(_order: number): void { throw new Error("unreachable"); }
  public setParent(_parent: Scope): void { throw new Error("unreachable"); }
  public sameId(_pkg: import("./package.js").Package | null, _name: string, _foldCase: boolean): boolean { throw new Error("unreachable"); }
  public scopePos(): Pos { throw new Error("unreachable"); }
  public setScopePos(_pos: Pos): void { throw new Error("unreachable"); }
}

// resolve returns the Object represented by obj, resolving lazy
// objects as appropriate.
export function resolve(name: string, obj: Object | null): Object | null {
  if (obj instanceof lazyObject) {
    const lazy = obj;
    if (!lazy.done) {
      const resolved = lazy.resolve_();

      if (resolved instanceof lazyObject) {
        throw new Error("recursive lazy object");
      }
      if (resolved.Name() !== name) {
        throw new Error("lazy object has unexpected name");
      }

      if (resolved.Parent() === null) {
        resolved.setParent(lazy.parent);
      }
      lazy.obj = resolved;
      lazy.done = true;
    }

    obj = lazy.obj;
  }
  return obj;
}
