// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/sizes.go

// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file implements Sizes.

import type { Type } from "./type.js";
import * as arrayTypes from "./array.js";
import { Basic, Bool, Complex128, Complex64, Float32, Float64, Int16, Int32, Int64, Int8, IsString, String as StringKind, Uint16, Uint32, Uint64, Uint8 } from "./basic.js";
import * as sliceTypes from "./slice.js";
import * as structTypes from "./struct.js";
import * as interfaceTypes from "./interface.js";
import * as typeparamTypes from "./typeparam.js";
import * as unionTypes from "./union.js";
import { asNamed } from "./alias.js";
import type { Var } from "./object.js";
import { isTypeParam, isTyped } from "./predicates.js";
import { assert } from "./util.js";

declare module "./api.js" {
  interface Config {
    alignof(T: Type): number;
    offsetsof(T: structTypes.Struct): number[];
    offsetof(T: Type, index: number[]): number;
    sizeof(T: Type): number;
  }
}

interface configSizingReceiver {
  Sizes: Sizes | null;
  alignof(T: Type): number;
  offsetsof(T: structTypes.Struct): number[];
  offsetof(T: Type, index: number[]): number;
  sizeof(T: Type): number;
}

type configMethod = (this: configSizingReceiver, ...args: any[]) => any;
type configCtor = { prototype: any };
type configMethodRecord = [string, configMethod];

function configMethodQueue(): configMethodRecord[] {
  const g = globalThis as typeof globalThis & { __gojrPendingConfigMethods?: configMethodRecord[] };
  if (g.__gojrPendingConfigMethods === undefined) {
    g.__gojrPendingConfigMethods = [];
  }
  return g.__gojrPendingConfigMethods;
}

function registerConfigMethod(name: string, fn: configMethod): void {
  const g = globalThis as typeof globalThis & { __gojrConfigCtor?: configCtor };
  if (g.__gojrConfigCtor !== undefined) {
    g.__gojrConfigCtor.prototype[name] = fn;
    return;
  }
  configMethodQueue().push([name, fn]);
}

// Sizes defines the sizing functions for package unsafe.
export interface Sizes {
  // Alignof returns the alignment of a variable of type T.
  Alignof(T: Type): number;

  // Offsetsof returns the offsets of the given struct fields, in bytes.
  Offsetsof(fields: Var[]): number[];

  // Sizeof returns the size of a variable of type T.
  Sizeof(T: Type): number;
}

// StdSizes is a convenience type for creating commonly used Sizes.
export class StdSizes implements Sizes {
  public constructor(
    public WordSize: number, // word size in bytes - must be >= 4 (32bits)
    public MaxAlign: number // maximum alignment in bytes - must be >= 1
  ) {}

  public Alignof(T: Type): number {
    let result: number;

    // For arrays and structs, alignment is defined in terms
    // of alignment of the elements and fields, respectively.
    const t = T.Underlying();
    if (t instanceof arrayTypes.Array) {
      // spec: "For a variable x of array type: unsafe.Alignof(x)
      // is the same as unsafe.Alignof(x[0]), but at least 1."
      result = this.Alignof(t.elem);
    } else if (t instanceof structTypes.Struct) {
      if ((t.fields?.length ?? 0) === 0 && _IsSyncAtomicAlign64(T)) {
        result = 8;
      } else {
        // spec: "For a variable x of struct type: unsafe.Alignof(x)
        // is the largest of the values unsafe.Alignof(x.f) for each
        // field f of x, but at least 1."
        let max = 1;
        for (const f of t.fields ?? []) {
          const a = this.Alignof(f.typ!);
          if (a > max) {
            max = a;
          }
        }
        result = max;
      }
    } else if (t instanceof sliceTypes.Slice || t instanceof interfaceTypes.Interface) {
      assert(!isTypeParam(T));
      result = this.WordSize;
    } else if (t instanceof Basic && (t.Info() & IsString) !== 0) {
      result = this.WordSize;
    } else if (t instanceof typeparamTypes.TypeParam || t instanceof unionTypes.Union) {
      throw new Error("unreachable");
    } else {
      let a = this.Sizeof(T); // may be 0 or negative
      // spec: "For a variable x of any type: unsafe.Alignof(x) is at least 1."
      if (a < 1) {
        result = 1;
      } else {
        // complex{64,128} are aligned like [2]float{32,64}.
        if (isComplex(T)) {
          a /= 2;
        }
        if (a > this.MaxAlign) {
          result = this.MaxAlign;
        } else {
          result = a;
        }
      }
    }

    assert(result >= 1);
    return result;
  }

  public Offsetsof(fields: Var[]): number[] {
    const offsets = new globalThis.Array<number>(fields.length);
    let offs = 0;
    for (let i = 0; i < fields.length; i++) {
      const f = fields[i]!;
      if (offs < 0) {
        // all remaining offsets are too large
        offsets[i] = -1;
        continue;
      }
      // offs >= 0
      const a = this.Alignof(f.typ!);
      offs = align(offs, a); // possibly < 0 if align overflows
      offsets[i] = offs;
      const d = this.Sizeof(f.typ!);
      if (d >= 0 && offs >= 0) {
        offs += d; // ok to overflow to < 0
      } else {
        offs = -1; // f.typ or offs is too large
      }
    }
    return offsets;
  }

  public Sizeof(T: Type): number {
    const t = T.Underlying();
    if (t instanceof Basic) {
      assert(isTyped(T));
      const k = t.kind;
      if (k < basicSizes.length) {
        const s = basicSizes[k] ?? 0;
        if (s > 0) {
          return s;
        }
      }
      if (k === StringKind) {
        return this.WordSize * 2;
      }
    } else if (t instanceof arrayTypes.Array) {
      const n = t.len;
      if (n <= 0) {
        return 0;
      }
      // n > 0
      const esize = this.Sizeof(t.elem);
      if (esize < 0) {
        return -1; // element too large
      }
      if (esize === 0) {
        return 0; // 0-size element
      }
      // esize > 0
      const a = this.Alignof(t.elem);
      const ea = align(esize, a); // possibly < 0 if align overflows
      if (ea < 0) {
        return -1;
      }
      // ea >= 1
      const n1 = n - 1; // n1 >= 0
      const maxInt64 = 2 ** 63 - 1;
      if (n1 > 0 && ea > maxInt64 / n1) {
        return -1; // ea*n1 overflows
      }
      return ea * n1 + esize; // may still overflow to < 0 which is ok
    } else if (t instanceof sliceTypes.Slice) {
      return this.WordSize * 3;
    } else if (t instanceof structTypes.Struct) {
      const n = t.NumFields();
      if (n === 0) {
        return 0;
      }
      const offsets = this.Offsetsof(t.fields ?? []);
      const offs = offsets[n - 1]!;
      const size = this.Sizeof((t.fields ?? [])[n - 1]!.typ!);
      if (offs < 0 || size < 0) {
        return -1; // type too large
      }
      return offs + size; // may overflow to < 0 which is ok
    } else if (t instanceof interfaceTypes.Interface) {
      assert(!isTypeParam(T));
      return this.WordSize * 2;
    } else if (t instanceof typeparamTypes.TypeParam || t instanceof unionTypes.Union) {
      throw new Error("unreachable");
    }
    return this.WordSize; // catch-all
  }
}

export function _IsSyncAtomicAlign64(T: Type): boolean {
  const named = asNamed(T);
  if (named === null) {
    return false;
  }
  const obj = named.Obj();
  return obj.Name() === "align64" &&
    obj.Pkg() !== null &&
    (obj.Pkg()!.Path() === "sync/atomic" ||
      obj.Pkg()!.Path() === "internal/runtime/atomic");
}

export const basicSizes: number[] = [];
basicSizes[Bool] = 1;
basicSizes[Int8] = 1;
basicSizes[Int16] = 2;
basicSizes[Int32] = 4;
basicSizes[Int64] = 8;
basicSizes[Uint8] = 1;
basicSizes[Uint16] = 2;
basicSizes[Uint32] = 4;
basicSizes[Uint64] = 8;
basicSizes[Float32] = 4;
basicSizes[Float64] = 8;
basicSizes[Complex64] = 8;
basicSizes[Complex128] = 16;

export class gcSizes extends StdSizes {
  public Alignof(T: Type): number {
    let result: number;

    // For arrays and structs, alignment is defined in terms
    // of alignment of the elements and fields, respectively.
    const t = T.Underlying();
    if (t instanceof arrayTypes.Array) {
      // spec: "For a variable x of array type: unsafe.Alignof(x)
      // is the same as unsafe.Alignof(x[0]), but at least 1."
      result = this.Alignof(t.elem);
    } else if (t instanceof structTypes.Struct) {
      if ((t.fields?.length ?? 0) === 0 && _IsSyncAtomicAlign64(T)) {
        // Special case: sync/atomic.align64 is an
        // empty struct we recognize as a signal that
        // the struct it contains must be
        // 64-bit-aligned.
        //
        // This logic is equivalent to the logic in
        // cmd/compile/internal/types/size.go:calcStructOffset
        result = 8;
      } else {
        // spec: "For a variable x of struct type: unsafe.Alignof(x)
        // is the largest of the values unsafe.Alignof(x.f) for each
        // field f of x, but at least 1."
        let max = 1;
        for (const f of t.fields ?? []) {
          const a = this.Alignof(f.typ!);
          if (a > max) {
            max = a;
          }
        }
        result = max;
      }
    } else if (t instanceof sliceTypes.Slice || t instanceof interfaceTypes.Interface) {
      // Multiword data structures are effectively structs
      // in which each element has size WordSize.
      // Type parameters lead to variable sizes/alignments;
      // StdSizes.Alignof won't be called for them.
      assert(!isTypeParam(T));
      result = this.WordSize;
    } else if (t instanceof Basic) {
      // Strings are like slices and interfaces.
      if ((t.Info() & IsString) !== 0) {
        result = this.WordSize;
      } else {
        result = this.alignofDefault(T);
      }
    } else if (t instanceof typeparamTypes.TypeParam || t instanceof unionTypes.Union) {
      throw new Error("unreachable");
    } else {
      result = this.alignofDefault(T);
    }

    assert(result >= 1);
    return result;
  }

  private alignofDefault(T: Type): number {
    let a = this.Sizeof(T); // may be 0 or negative
    // spec: "For a variable x of any type: unsafe.Alignof(x) is at least 1."
    if (a < 1) {
      return 1;
    }
    // complex{64,128} are aligned like [2]float{32,64}.
    if (isComplex(T)) {
      a /= 2;
    }
    if (a > this.MaxAlign) {
      return this.MaxAlign;
    }
    return a;
  }

  public Offsetsof(fields: Var[]): number[] {
    const offsets = new globalThis.Array<number>(fields.length);
    let offs = 0;
    for (let i = 0; i < fields.length; i++) {
      const f = fields[i]!;
      if (offs < 0) {
        // all remaining offsets are too large
        offsets[i] = -1;
        continue;
      }
      // offs >= 0
      const a = this.Alignof(f.typ!);
      offs = align(offs, a); // possibly < 0 if align overflows
      offsets[i] = offs;
      const d = this.Sizeof(f.typ!);
      if (d >= 0 && offs >= 0) {
        offs += d; // ok to overflow to < 0
      } else {
        offs = -1; // f.typ or offs is too large
      }
    }
    return offsets;
  }

  public Sizeof(T: Type): number {
    const t = T.Underlying();
    if (t instanceof arrayTypes.Array) {
      const n = t.len;
      if (n <= 0) {
        return 0;
      }
      const esize = this.Sizeof(t.elem);
      if (esize < 0) {
        return -1;
      }
      if (esize === 0) {
        return 0;
      }
      const maxInt64 = 2 ** 63 - 1;
      if (esize > maxInt64 / n) {
        return -1;
      }
      return esize * n;
    }
    if (t instanceof structTypes.Struct) {
      const n = t.NumFields();
      if (n === 0) {
        return 0;
      }
      const offsets = this.Offsetsof(t.fields ?? []);
      const offs = offsets[n - 1]!;
      let size = this.Sizeof((t.fields ?? [])[n - 1]!.typ!);
      if (offs < 0 || size < 0) {
        return -1;
      }
      if (offs > 0 && size === 0) {
        size = 1;
      }
      return align(offs + size, this.Alignof(t));
    }
    return super.Sizeof(T);
  }
}

export const gcArchSizes: Record<string, gcSizes> = {
  "386": new gcSizes(4, 4),
  "amd64": new gcSizes(8, 8),
  "amd64p32": new gcSizes(4, 8),
  "arm": new gcSizes(4, 4),
  "arm64": new gcSizes(8, 8),
  "loong64": new gcSizes(8, 8),
  "mips": new gcSizes(4, 4),
  "mipsle": new gcSizes(4, 4),
  "mips64": new gcSizes(8, 8),
  "mips64le": new gcSizes(8, 8),
  "ppc64": new gcSizes(8, 8),
  "ppc64le": new gcSizes(8, 8),
  "riscv64": new gcSizes(8, 8),
  "s390x": new gcSizes(8, 8),
  "sparc64": new gcSizes(8, 8),
  "wasm": new gcSizes(8, 8)
};

export const gccgoArchSizes: Record<string, StdSizes> = {
  "386": new StdSizes(4, 4),
  "alpha": new StdSizes(8, 8),
  "amd64": new StdSizes(8, 8),
  "amd64p32": new StdSizes(4, 8),
  "arm": new StdSizes(4, 8),
  "armbe": new StdSizes(4, 8),
  "arm64": new StdSizes(8, 8),
  "arm64be": new StdSizes(8, 8),
  "wasm": new StdSizes(8, 8)
};

export function SizesFor(compiler: string, arch: string): Sizes | null {
  switch (compiler) {
    case "gc": {
      const s = gcSizesFor(compiler, arch);
      if (s !== null) {
        return s;
      }
      break;
    }
    case "gccgo": {
      const s = gccgoArchSizes[arch];
      if (s !== undefined) {
        return s;
      }
      break;
    }
  }
  return null;
}

// stdSizes is used if Config.Sizes == nil.
export const stdSizes = SizesFor("gc", "amd64")!;

registerConfigMethod("alignof", function alignof(T: Type): number {
  let f = stdSizes.Alignof.bind(stdSizes);
  if (this.Sizes !== null) {
    f = this.Sizes.Alignof.bind(this.Sizes);
  }
  const a = f(T);
  if (a >= 1) {
    return a;
  }
  throw new Error("implementation of alignof returned an alignment < 1");
});

registerConfigMethod("offsetsof", function offsetsof(T: structTypes.Struct): number[] {
  let offsets: number[] = [];
  if (T.NumFields() > 0) {
    // compute offsets on demand
    let f = stdSizes.Offsetsof.bind(stdSizes);
    if (this.Sizes !== null) {
      f = this.Sizes.Offsetsof.bind(this.Sizes);
    }
    offsets = f(T.fields ?? []);
    // sanity checks
    if (offsets.length !== T.NumFields()) {
      throw new Error("implementation of offsetsof returned the wrong number of offsets");
    }
  }
  return offsets;
});

// offsetof returns the offset of the field specified via
// the index sequence relative to T. All embedded fields
// must be structs (rather than pointers to structs).
// If the offset is too large (because T is too large),
// the result is negative.
registerConfigMethod("offsetof", function offsetof(T: Type, index: number[]): number {
  let offs = 0;
  for (const i of index) {
    const s = T.Underlying() as structTypes.Struct;
    const d = this.offsetsof(s)[i]!;
    if (d < 0) {
      return -1;
    }
    offs += d;
    if (offs < 0) {
      return -1;
    }
    T = s.fields![i]!.typ!;
  }
  return offs;
});

// sizeof returns the size of T.
// If T is too large, the result is negative.
registerConfigMethod("sizeof", function sizeof(T: Type): number {
  let f = stdSizes.Sizeof.bind(stdSizes);
  if (this.Sizes !== null) {
    f = this.Sizes.Sizeof.bind(this.Sizes);
  }
  return f(T);
});

// align returns the smallest y >= x such that y % a == 0.
// a must be within 1 and 8 and it must be a power of 2.
// The result may be negative due to overflow.
export function align(x: number, a: number): number {
  assert(x >= 0 && 1 <= a && a <= 8 && (a & (a - 1)) === 0);
  return Math.floor((x + a - 1) / a) * a;
}

// gcSizesFor returns the Sizes used by gc for an architecture.
// The result is a nil *gcSizes pointer (which is not a valid types.Sizes)
// if a compiler/architecture pair is not known.
export function gcSizesFor(compiler: string, arch: string): gcSizes | null {
  if (compiler !== "gc") {
    return null;
  }
  return gcArchSizes[arch] ?? null;
}

function isComplex(T: Type): boolean {
  return T instanceof Basic && (T.kind === Complex64 || T.kind === Complex128);
}
