// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/under.go

// Copyright 2011 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

import type { Type } from "./type.js";
import { Unalias } from "./alias.js";
import { TypeParam } from "./typeparam.js";
import { term } from "./typeterm.js";
import { Identical } from "./predicates.js";
import { Chan, ChanDir } from "./chan.js";
import { Checker } from "./check.js";

// If typ is a type parameter, underIs returns the result of typ.underIs(f).
// Otherwise, underIs returns the result of f(typ.Underlying()).
export function underIs(typ: Type, f: (typ: Type | null) => boolean): boolean {
  return all(typ, (_t, u) => f(u));
}

// all reports whether f(t, u) is true for all (type/underlying type)
// pairs in the typeset of t. See [typeset] for details of sequence.
export function all(t: Type, f: (t: Type | null, u: Type | null) => boolean): boolean {
  const p = Unalias(t);
  if (p instanceof TypeParam) {
    return typesetOfTypeParam(p, f);
  }
  return f(t, t.Underlying());
}

function typesetOfTypeParam(p: TypeParam, f: (t: Type | null, u: Type | null) => boolean): boolean {
  const iface = p.iface();
  return iface.typeSet().all(f);
}

// typeset is an iterator over the (type/underlying type) pairs of the
// specific type terms of the type set implied by t.
// If t is a type parameter, the implied type set is the type set of t's constraint.
// In this case, if there are no specific terms, the iterator produces (nil, nil).
// If t is not a type parameter, the implied type set consists of just t.
// In any case, typeset is guaranteed to produce at least one set of results.
export function typeset(t: Type): Iterable<[Type | null, Type | null]> {
  return {
    [Symbol.iterator]: function* () {
      let yielded = false;
      all(t, (tt, u) => {
        yielded = true;
        (function* noop() {})();
        return true;
      });
      const pairs: [Type | null, Type | null][] = [];
      all(t, (tt, u) => {
        pairs.push([tt, u]);
        return true;
      });
      if (!yielded) {
        pairs.push([null, null]);
      }
      yield* pairs;
    }
  };
}

// A typeError describes a type error.
export class typeError {
  public constructor(
    public format_: string,
    public args: unknown[] = []
  ) {}

  // format formats a type error as a string.
  // check may be nil.
  public format(check: Checker | null): string {
    return (check as Checker | null)?.sprintf(this.format_, ...this.args) ?? this.format_;
  }
}

export const emptyTypeError = new typeError("");

export function typeErrorf(format: string, ...args: unknown[]): typeError {
  if (format === "") {
    return emptyTypeError;
  }
  return new typeError(format, args);
}

// If t is a type parameter, cond is nil, and t's type set contains no channel types,
// commonUnder returns the common underlying type of all types in t's type set if
// it exists, or nil and a type error otherwise.
//
// If t is a type parameter, cond is nil, and there are channel types, t's type set
// must only contain channel types, they must all have the same element types,
// channel directions must not conflict, and commonUnder returns one of the most
// restricted channels. Otherwise, the function returns nil and a type error.
//
// If cond != nil, each pair (t, u) of type and underlying type in t's type set
// must satisfy the condition expressed by cond. If the result of cond is != nil,
// commonUnder returns nil and the type error reported by cond.
// Note that cond is called before any other conditions are checked; specifically
// cond may be called with (nil, nil) if the type set contains no specific types.
//
// If t is not a type parameter, commonUnder behaves as if t was a type parameter
// with the single type t in its type set.
export function commonUnder(t0: Type, cond: ((t: Type | null, u: Type | null) => typeError | null) | null): [Type | null, typeError | null] {
  let ct: Type | null = null;
  let cu: Type | null = null; // type and respective common underlying type
  for (const [t, u] of typeset(t0)) {
    if (cond !== null) {
      const err = cond(t, u);
      if (err !== null) {
        return [null, err];
      }
    }

    if (u === null) {
      return [null, typeErrorf("no specific type")];
    }

    // If this is the first type we're seeing, we're done.
    if (cu === null) {
      ct = t;
      cu = u;
      continue;
    }

    // If we've seen a channel before, and we have a channel now, they must be compatible.
    if (cu instanceof Chan) {
      if (u instanceof Chan) {
        if (!Identical(cu.elem, u.elem)) {
          return [null, typeErrorf("channels %s and %s have different element types", ct, t)];
        }
        // If we have different channel directions, keep the restricted one
        // and complain if they conflict.
        switch (true) {
          case cu.dir === u.dir:
            // nothing to do
            break;
          case cu.dir === ChanDir.SendRecv:
            ct = t;
            cu = u; // switch to restricted channel
            break;
          case u.dir !== ChanDir.SendRecv:
            return [null, typeErrorf("channels %s and %s have conflicting directions", ct, t)];
        }
        continue;
      }
    }

    // Otherwise, the current type must have the same underlying type as all previous types.
    if (!Identical(cu, u)) {
      return [null, typeErrorf("%s and %s have different underlying types", ct, t)];
    }
  }
  return [cu, null];
}

export { term };
