// Code generated by goyacc -o grammar_v16.go -p v16 grammar_v16.y. DO NOT EDIT.

//line grammar_v16.y:10
package v16

import __yyfmt__ "fmt"

//line grammar_v16.y:10

import (
	"github.com/glycerine/goivy/ast"
)

//line grammar_v16.y:18
type v16SymType struct {
	yys   int
	node  ast.Node
	nodes []ast.Node
	str   string
}

const TOK_SYMBOL = 57346
const TOK_VARIABLE = 57347
const TOK_PRESYMBOL = 57348
const TOK_LPAREN = 57349
const TOK_RPAREN = 57350
const TOK_LB = 57351
const TOK_RB = 57352
const TOK_LCB = 57353
const TOK_RCB = 57354
const TOK_COMMA = 57355
const TOK_SEMI = 57356
const TOK_COLON = 57357
const TOK_DOT = 57358
const TOK_PLUS = 57359
const TOK_MINUS = 57360
const TOK_TIMES = 57361
const TOK_DIV = 57362
const TOK_EQ = 57363
const TOK_TILDAEQ = 57364
const TOK_TILDA = 57365
const TOK_LE = 57366
const TOK_LT = 57367
const TOK_GE = 57368
const TOK_GT = 57369
const TOK_AND = 57370
const TOK_OR = 57371
const TOK_ARROW = 57372
const TOK_IFF = 57373
const TOK_PTO = 57374
const TOK_DOLLAR = 57375
const TOK_FORALL = 57376
const TOK_EXISTS = 57377
const TOK_TRUE = 57378
const TOK_FALSE = 57379
const TOK_OLD = 57380
const TOK_THIS = 57381
const TOK_ISA = 57382
const TOK_IF = 57383
const TOK_ELSE = 57384
const TOK_GLOBALLY = 57385
const TOK_EVENTUALLY = 57386
const TOK_WHENNEXT = 57387
const TOK_WHENPREV = 57388
const TOK_WHENFIRST = 57389
const TOK_WHENLAST = 57390

var v16Toknames = [...]string{
	"$end",
	"error",
	"$unk",
	"TOK_SYMBOL",
	"TOK_VARIABLE",
	"TOK_PRESYMBOL",
	"TOK_LPAREN",
	"TOK_RPAREN",
	"TOK_LB",
	"TOK_RB",
	"TOK_LCB",
	"TOK_RCB",
	"TOK_COMMA",
	"TOK_SEMI",
	"TOK_COLON",
	"TOK_DOT",
	"TOK_PLUS",
	"TOK_MINUS",
	"TOK_TIMES",
	"TOK_DIV",
	"TOK_EQ",
	"TOK_TILDAEQ",
	"TOK_TILDA",
	"TOK_LE",
	"TOK_LT",
	"TOK_GE",
	"TOK_GT",
	"TOK_AND",
	"TOK_OR",
	"TOK_ARROW",
	"TOK_IFF",
	"TOK_PTO",
	"TOK_DOLLAR",
	"TOK_FORALL",
	"TOK_EXISTS",
	"TOK_TRUE",
	"TOK_FALSE",
	"TOK_OLD",
	"TOK_THIS",
	"TOK_ISA",
	"TOK_IF",
	"TOK_ELSE",
	"TOK_GLOBALLY",
	"TOK_EVENTUALLY",
	"TOK_WHENNEXT",
	"TOK_WHENPREV",
	"TOK_WHENFIRST",
	"TOK_WHENLAST",
}

var v16Statenames = [...]string{}

const v16EofCode = 1
const v16ErrCode = 2
const v16InitialStackSize = 16

//line grammar_v16.y:241

//line yacctab:1
var v16Exca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const v16Private = 57344

const v16Last = 137

var v16Act = [...]int8{
	3, 15, 39, 25, 17, 35, 22, 23, 24, 25,
	29, 28, 80, 30, 31, 32, 33, 22, 23, 24,
	25, 34, 64, 52, 54, 55, 56, 47, 58, 59,
	26, 2, 18, 19, 20, 21, 36, 71, 38, 37,
	61, 26, 42, 43, 17, 67, 73, 68, 41, 70,
	48, 49, 50, 51, 72, 16, 17, 4, 57, 60,
	18, 19, 20, 21, 12, 74, 76, 40, 22, 23,
	24, 25, 44, 7, 81, 27, 16, 17, 53, 46,
	82, 45, 83, 66, 8, 9, 5, 6, 14, 60,
	20, 21, 26, 10, 11, 75, 69, 77, 22, 23,
	24, 25, 29, 28, 13, 30, 31, 32, 33, 14,
	23, 24, 25, 34, 18, 19, 20, 21, 18, 1,
	20, 21, 26, 22, 23, 24, 25, 24, 25, 62,
	62, 78, 65, 63, 0, 0, 79,
}

var v16Pact = [...]int16{
	50, -1000, 86, -11, 50, -1000, -1000, 50, 62, 62,
	50, 50, 65, -1000, 38, -1000, 12, -1000, 50, 50,
	50, 50, 71, 71, 71, 71, 50, 71, 71, -1000,
	-1000, -1000, -1000, -1000, -1000, 81, 32, 60, 117, -1000,
	7, 116, 86, 86, 71, 38, 65, -2, 60, 90,
	86, 86, 92, 71, 108, -17, -1000, 4, 0, 0,
	-1000, -1000, 62, 50, 38, 50, 123, 0, -1000, -4,
	-1000, -1000, 51, 71, -1000, 86, -1000, 86, -1000, 71,
	38, 106, 0, -1000,
}

var v16Pgo = [...]int8{
	0, 119, 31, 0, 64, 104, 2, 96, 83, 83,
	38, 75, 1,
}

var v16R1 = [...]int8{
	0, 1, 12, 7, 7, 7, 4, 4, 4, 5,
	5, 6, 6, 9, 9, 10, 10, 8, 8, 8,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 11,
	11, 11, 11, 11, 11, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
}

var v16R2 = [...]int8{
	0, 1, 1, 1, 3, 1, 1, 4, 3, 1,
	3, 1, 3, 1, 3, 1, 3, 0, 1, 3,
	1, 1, 2, 3, 3, 3, 3, 3, 5, 1,
	1, 1, 1, 1, 1, 1, 3, 3, 3, 1,
	1, 2, 3, 3, 3, 3, 4, 4, 2, 2,
}

var v16Chk = [...]int16{
	-1000, -1, -2, -3, 7, 36, 37, 23, 34, 35,
	43, 44, -4, -5, 38, -12, 5, 6, 28, 29,
	30, 31, 17, 18, 19, 20, 41, -11, 22, 21,
	24, 25, 26, 27, 32, -3, -2, -2, -10, -6,
	5, -10, -2, -2, 7, 16, -4, 15, -2, -2,
	-2, -2, -3, 7, -3, -3, -3, -2, -3, -3,
	8, 8, 13, 16, 15, 16, -8, -3, -12, -7,
	-12, 39, -3, 42, -6, -2, -12, -2, 8, 13,
	16, -3, -3, -12,
}

var v16Def = [...]int8{
	0, -2, 1, 35, 0, 39, 40, 0, 0, 0,
	0, 0, 20, 21, 0, 6, 9, 2, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 29,
	30, 31, 32, 33, 34, 35, 0, 41, 0, 15,
	11, 0, 48, 49, 17, 0, 22, 0, 42, 43,
	44, 45, 24, 0, 25, 26, 27, 0, 36, 37,
	23, 38, 0, 0, 0, 0, 0, 18, 8, 10,
	3, 5, 0, 0, 16, 46, 12, 47, 7, 0,
	0, 28, 19, 4,
}

var v16Tok1 = [...]int8{
	1,
}

var v16Tok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48,
}

var v16Tok3 = [...]int8{
	0,
}

var v16ErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	v16Debug        = 0
	v16ErrorVerbose = false
)

type v16Lexer interface {
	Lex(lval *v16SymType) int
	Error(s string)
}

type v16Parser interface {
	Parse(v16Lexer) int
	Lookahead() int
}

type v16ParserImpl struct {
	lval  v16SymType
	stack [v16InitialStackSize]v16SymType
	char  int
}

func (p *v16ParserImpl) Lookahead() int {
	return p.char
}

func v16NewParser() v16Parser {
	return &v16ParserImpl{}
}

const v16Flag = -1000

func v16Tokname(c int) string {
	if c >= 1 && c-1 < len(v16Toknames) {
		if v16Toknames[c-1] != "" {
			return v16Toknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func v16Statname(s int) string {
	if s >= 0 && s < len(v16Statenames) {
		if v16Statenames[s] != "" {
			return v16Statenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func v16ErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !v16ErrorVerbose {
		return "syntax error"
	}

	for _, e := range v16ErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + v16Tokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(v16Pact[state])
	for tok := TOKSTART; tok-1 < len(v16Toknames); tok++ {
		if n := base + tok; n >= 0 && n < v16Last && int(v16Chk[int(v16Act[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if v16Def[state] == -2 {
		i := 0
		for v16Exca[i] != -1 || int(v16Exca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; v16Exca[i] >= 0; i += 2 {
			tok := int(v16Exca[i])
			if tok < TOKSTART || v16Exca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if v16Exca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += v16Tokname(tok)
	}
	return res
}

func v16lex1(lex v16Lexer, lval *v16SymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(v16Tok1[0])
		goto out
	}
	if char < len(v16Tok1) {
		token = int(v16Tok1[char])
		goto out
	}
	if char >= v16Private {
		if char < v16Private+len(v16Tok2) {
			token = int(v16Tok2[char-v16Private])
			goto out
		}
	}
	for i := 0; i < len(v16Tok3); i += 2 {
		token = int(v16Tok3[i+0])
		if token == char {
			token = int(v16Tok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(v16Tok2[1]) /* unknown char */
	}
	if v16Debug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", v16Tokname(token), uint(char))
	}
	return char, token
}

func v16Parse(v16lex v16Lexer) int {
	return v16NewParser().Parse(v16lex)
}

func (v16rcvr *v16ParserImpl) Parse(v16lex v16Lexer) int {
	var v16n int
	var v16VAL v16SymType
	var v16Dollar []v16SymType
	_ = v16Dollar // silence set and not used
	v16S := v16rcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	v16state := 0
	v16rcvr.char = -1
	v16token := -1 // v16rcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		v16state = -1
		v16rcvr.char = -1
		v16token = -1
	}()
	v16p := -1
	goto v16stack

ret0:
	return 0

ret1:
	return 1

v16stack:
	/* put a state and value onto the stack */
	if v16Debug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", v16Tokname(v16token), v16Statname(v16state))
	}

	v16p++
	if v16p >= len(v16S) {
		nyys := make([]v16SymType, len(v16S)*2)
		copy(nyys, v16S)
		v16S = nyys
	}
	v16S[v16p] = v16VAL
	v16S[v16p].yys = v16state

v16newstate:
	v16n = int(v16Pact[v16state])
	if v16n <= v16Flag {
		goto v16default /* simple state */
	}
	if v16rcvr.char < 0 {
		v16rcvr.char, v16token = v16lex1(v16lex, &v16rcvr.lval)
	}
	v16n += v16token
	if v16n < 0 || v16n >= v16Last {
		goto v16default
	}
	v16n = int(v16Act[v16n])
	if int(v16Chk[v16n]) == v16token { /* valid shift */
		v16rcvr.char = -1
		v16token = -1
		v16VAL = v16rcvr.lval
		v16state = v16n
		if Errflag > 0 {
			Errflag--
		}
		goto v16stack
	}

v16default:
	/* default state action */
	v16n = int(v16Def[v16state])
	if v16n == -2 {
		if v16rcvr.char < 0 {
			v16rcvr.char, v16token = v16lex1(v16lex, &v16rcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if v16Exca[xi+0] == -1 && int(v16Exca[xi+1]) == v16state {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			v16n = int(v16Exca[xi+0])
			if v16n < 0 || v16n == v16token {
				break
			}
		}
		v16n = int(v16Exca[xi+1])
		if v16n < 0 {
			goto ret0
		}
	}
	if v16n == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			v16lex.Error(v16ErrorMessage(v16state, v16token))
			Nerrs++
			if v16Debug >= 1 {
				__yyfmt__.Printf("%s", v16Statname(v16state))
				__yyfmt__.Printf(" saw %s\n", v16Tokname(v16token))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for v16p >= 0 {
				v16n = int(v16Pact[v16S[v16p].yys]) + v16ErrCode
				if v16n >= 0 && v16n < v16Last {
					v16state = int(v16Act[v16n]) /* simulate a shift of "error" */
					if int(v16Chk[v16state]) == v16ErrCode {
						goto v16stack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if v16Debug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", v16S[v16p].yys)
				}
				v16p--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if v16Debug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", v16Tokname(v16token))
			}
			if v16token == v16EofCode {
				goto ret1
			}
			v16rcvr.char = -1
			v16token = -1
			goto v16newstate /* try again in the same state */
		}
	}

	/* reduction by production v16n */
	if v16Debug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", v16n, v16Statname(v16state))
	}

	v16nt := v16n
	v16pt := v16p
	_ = v16pt // guard against "declared and not used"

	v16p -= int(v16R2[v16n])
	// v16p is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if v16p+1 >= len(v16S) {
		nyys := make([]v16SymType, len(v16S)*2)
		copy(nyys, v16S)
		v16S = nyys
	}
	v16VAL = v16S[v16p+1]

	/* consult goto table to find next state */
	v16n = int(v16R1[v16n])
	v16g := int(v16Pgo[v16n])
	v16j := v16g + v16S[v16p].yys + 1

	if v16j >= v16Last {
		v16state = int(v16Act[v16g])
	} else {
		v16state = int(v16Act[v16j])
		if int(v16Chk[v16state]) != -v16n {
			v16state = int(v16Act[v16g])
		}
	}
	// dummy call; replaced with literal code
	switch v16nt {

	case 1:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:65
		{
			v16lex.(*v16LexAdapter).result = v16Dollar[1].node
		}
	case 2:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:72
		{
			v16VAL.str = v16Dollar[1].str
		}
	case 3:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:79
		{
			v16VAL.node = &ast.Symbol{Rep: v16Dollar[1].str}
		}
	case 4:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:83
		{
			if _, ok := v16Dollar[1].node.(*ast.This); ok {
				v16VAL.node = &ast.Symbol{Rep: v16Dollar[3].str}
			} else if sym, ok := v16Dollar[1].node.(*ast.Symbol); ok {
				v16VAL.node = &ast.Symbol{Rep: sym.Rep + "." + v16Dollar[3].str}
			} else {
				v16VAL.node = &ast.Symbol{Rep: v16Dollar[3].str}
			}
		}
	case 5:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:93
		{
			v16VAL.node = &ast.This{}
		}
	case 6:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:102
		{
			v16VAL.node = &ast.Atom{Rep: v16Dollar[1].str}
		}
	case 7:
		v16Dollar = v16S[v16pt-4 : v16pt+1]
//line grammar_v16.y:106
		{
			a := v16Dollar[1].node.(*ast.Atom)
			a.Terms = append(a.Terms, v16Dollar[3].nodes...)
			v16VAL.node = a
		}
	case 8:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:112
		{
			lhs := v16Dollar[1].node.(*ast.Atom)
			v16VAL.node = &ast.Atom{Rep: lhs.Rep + "." + v16Dollar[3].str, Terms: lhs.Terms}
		}
	case 9:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:120
		{
			v16VAL.node = &ast.Variable{Rep: v16Dollar[1].str}
		}
	case 10:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:124
		{
			v := &ast.Variable{Rep: v16Dollar[1].str}
			v.VSort = v16Dollar[3].node
			v16VAL.node = v
		}
	case 11:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:133
		{
			v16VAL.node = &ast.Variable{Rep: v16Dollar[1].str}
		}
	case 12:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:137
		{
			v := &ast.Variable{Rep: v16Dollar[1].str}
			v.VSort = &ast.Symbol{Rep: v16Dollar[3].str}
			v16VAL.node = v
		}
	case 13:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:146
		{
			v16VAL.nodes = []ast.Node{v16Dollar[1].node}
		}
	case 14:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:148
		{
			v16VAL.nodes = append(v16Dollar[1].nodes, v16Dollar[3].node)
		}
	case 15:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:153
		{
			v16VAL.nodes = []ast.Node{v16Dollar[1].node}
		}
	case 16:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:155
		{
			v16VAL.nodes = append(v16Dollar[1].nodes, v16Dollar[3].node)
		}
	case 17:
		v16Dollar = v16S[v16pt-0 : v16pt+1]
//line grammar_v16.y:160
		{
			v16VAL.nodes = nil
		}
	case 18:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:162
		{
			v16VAL.nodes = []ast.Node{v16Dollar[1].node}
		}
	case 19:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:164
		{
			v16VAL.nodes = append(v16Dollar[1].nodes, v16Dollar[3].node)
		}
	case 20:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:171
		{
			v16VAL.node = v16Dollar[1].node
		}
	case 21:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:173
		{
			v16VAL.node = v16Dollar[1].node
		}
	case 22:
		v16Dollar = v16S[v16pt-2 : v16pt+1]
//line grammar_v16.y:175
		{
			v16VAL.node = &ast.Old{Term: v16Dollar[2].node}
		}
	case 23:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:177
		{
			v16VAL.node = v16Dollar[2].node
		}
	case 24:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:179
		{
			v16VAL.node = &ast.Atom{Rep: "+", Terms: []ast.Node{v16Dollar[1].node, v16Dollar[3].node}}
		}
	case 25:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:181
		{
			v16VAL.node = &ast.Atom{Rep: "-", Terms: []ast.Node{v16Dollar[1].node, v16Dollar[3].node}}
		}
	case 26:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:183
		{
			v16VAL.node = &ast.Atom{Rep: "*", Terms: []ast.Node{v16Dollar[1].node, v16Dollar[3].node}}
		}
	case 27:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:185
		{
			v16VAL.node = &ast.Atom{Rep: "/", Terms: []ast.Node{v16Dollar[1].node, v16Dollar[3].node}}
		}
	case 28:
		v16Dollar = v16S[v16pt-5 : v16pt+1]
//line grammar_v16.y:187
		{
			v16VAL.node = &ast.Ite{Cond: v16Dollar[3].node, Then: v16Dollar[1].node, Else: v16Dollar[5].node}
		}
	case 29:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:191
		{
			v16VAL.str = "="
		}
	case 30:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:192
		{
			v16VAL.str = "<="
		}
	case 31:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:193
		{
			v16VAL.str = "<"
		}
	case 32:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:194
		{
			v16VAL.str = ">="
		}
	case 33:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:195
		{
			v16VAL.str = ">"
		}
	case 34:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:196
		{
			v16VAL.str = "*>"
		}
	case 35:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:203
		{
			// Convert bare term to atom (app_to_atom)
			v16VAL.node = v16Dollar[1].node
		}
	case 36:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:208
		{
			v16VAL.node = &ast.Atom{Rep: v16Dollar[2].str, Terms: []ast.Node{v16Dollar[1].node, v16Dollar[3].node}}
		}
	case 37:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:212
		{
			v16VAL.node = &ast.Not{Body: &ast.Atom{Rep: "=", Terms: []ast.Node{v16Dollar[1].node, v16Dollar[3].node}}}
		}
	case 38:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:216
		{
			v16VAL.node = v16Dollar[2].node
		}
	case 39:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:218
		{
			v16VAL.node = &ast.And{}
		}
	case 40:
		v16Dollar = v16S[v16pt-1 : v16pt+1]
//line grammar_v16.y:220
		{
			v16VAL.node = &ast.Or{}
		}
	case 41:
		v16Dollar = v16S[v16pt-2 : v16pt+1]
//line grammar_v16.y:222
		{
			v16VAL.node = &ast.Not{Body: v16Dollar[2].node}
		}
	case 42:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:224
		{
			v16VAL.node = &ast.And{Terms: []ast.Node{v16Dollar[1].node, v16Dollar[3].node}}
		}
	case 43:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:226
		{
			v16VAL.node = &ast.Or{Terms: []ast.Node{v16Dollar[1].node, v16Dollar[3].node}}
		}
	case 44:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:228
		{
			v16VAL.node = &ast.Implies{T1: v16Dollar[1].node, T2: v16Dollar[3].node}
		}
	case 45:
		v16Dollar = v16S[v16pt-3 : v16pt+1]
//line grammar_v16.y:230
		{
			v16VAL.node = &ast.Iff{T1: v16Dollar[1].node, T2: v16Dollar[3].node}
		}
	case 46:
		v16Dollar = v16S[v16pt-4 : v16pt+1]
//line grammar_v16.y:232
		{
			v16VAL.node = &ast.Forall{Bounds: v16Dollar[2].nodes, Body: v16Dollar[4].node}
		}
	case 47:
		v16Dollar = v16S[v16pt-4 : v16pt+1]
//line grammar_v16.y:234
		{
			v16VAL.node = &ast.Exists{Bounds: v16Dollar[2].nodes, Body: v16Dollar[4].node}
		}
	case 48:
		v16Dollar = v16S[v16pt-2 : v16pt+1]
//line grammar_v16.y:236
		{
			v16VAL.node = &ast.Globally{Body: v16Dollar[2].node}
		}
	case 49:
		v16Dollar = v16S[v16pt-2 : v16pt+1]
//line grammar_v16.y:238
		{
			v16VAL.node = &ast.Eventually{Body: v16Dollar[2].node}
		}
	}
	goto v16stack /* stack new state and value */
}
