#lang ivy1.7

# note: in  lang ivy1.7, the monitor is written differently than in 1.6.
#  Warning: the assert does not fire for preventing over-draft if you
#  use the old 1.6 version! we cannot wrap inside a separate object any more?!?

type money

# did not fix.
#function (X:money + Y:money) : money

object account = {

    individual balance : money
    after init {
        balance := 0
    }

    action deposit(x:money) = {
        balance := balance + x
    }

    action withdraw(x:money) = {
        balance := balance - x
    }

    action get_balance returns(x:money) = {
        x := balance
    }

## wrapping inside another object makes these checks NEVER happen, bad! 
## we must avoid this, despite it being in the tutorial:  object spec = {

    before deposit {
       assert x >= 0;
       assert balance + x >= balance;
    }

    before withdraw {
        assert x >= 0;
        assert x <= balance
    }

 # }

}


export account.deposit
export account.withdraw
export account.get_balance

interpret money -> bv[16]
