// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/alias.go

// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

import type { Type } from "./type.js";
import { registerCheckerMethod } from "./check.js";
import type { TypeName } from "./object.js";
import type { TypeList, TypeParamList } from "./typelists.js";
import { bindTParams } from "./typelists.js";
import type { Named } from "./named.js";
import type { TypeParam } from "./typeparam.js";

declare module "./check.js" {
  interface Checker {
    newAlias(obj: TypeName, rhs: Type | null): Alias;
  }
}

// An Alias represents an alias type.
export class Alias implements Type {
  public obj: TypeName; // corresponding declared alias object
  public orig: Alias; // original, uninstantiated alias
  public tparams: TypeParamList | null = null; // type parameters, or nil
  public targs: TypeList | null = null; // type arguments, or nil
  public fromRHS: Type | null; // RHS of type alias declaration; may be an alias
  public actual: Type | null = null; // actual (aliased) type; never an alias

  public constructor(obj: TypeName, rhs: Type | null) {
    this.obj = obj;
    this.orig = this;
    this.fromRHS = rhs;
    if (obj.typ === null) {
      obj.typ = this;
    }
  }

  // Obj returns the type name for the declaration defining the alias type a.
  // For instantiated types, this is same as the type name of the origin type.
  public Obj(): TypeName { return this.orig.obj; }

  public String(): string { return this.obj.name; }

  // Underlying returns the [underlying type] of the alias type a, which is the
  // underlying type of the aliased type. Underlying types are never Named,
  // TypeParam, or Alias types.
  public Underlying(): Type { return unalias(this)?.Underlying() ?? this; }

  // Origin returns the generic Alias type of which a is an instance.
  // If a is not an instance of a generic alias, Origin returns a.
  public Origin(): Alias { return this.orig; }

  // TypeParams returns the type parameters of the alias type a, or nil.
  // A generic Alias and its instances have the same type parameters.
  public TypeParams(): TypeParamList | null { return this.tparams; }

  // SetTypeParams sets the type parameters of the alias type a.
  // The alias a must not have type arguments.
  public SetTypeParams(tparams: TypeParam[]): void {
    if (this.targs !== null) {
      throw new Error("assertion failed");
    }
    this.tparams = bindTParams(tparams);
  }

  // TypeArgs returns the type arguments used to instantiate the Alias type.
  // If a is not an instance of a generic alias, the result is nil.
  public TypeArgs(): TypeList | null { return this.targs; }

  // Rhs returns the type R on the right-hand side of an alias
  // declaration "type A = R", which may be another alias.
  public Rhs(): Type | null { return this.fromRHS; }

  public cleanup(): void {
    this.actual = unalias(this);
  }
}

// NewAlias creates a new Alias type with the given type name and rhs.
// If rhs is nil, the alias is incomplete.
export function NewAlias(obj: TypeName, rhs: Type | null): Alias {
  const alias = new Alias(obj, rhs);
  // Ensure that alias.actual is set (#65455).
  alias.cleanup();
  return alias;
}

registerCheckerMethod("newAlias", function newAliasMethod(obj: TypeName, rhs: Type | null): Alias {
  return new Alias(obj, rhs);
});

// Unalias returns t if it is not an alias type;
// otherwise it follows t's alias chain until it
// reaches a non-alias type which is then returned.
// Consequently, the result is never an alias type.
// Returns nil if the alias is incomplete.
export function Unalias(t: Type | null): Type | null {
  if (isAlias(t)) {
    return unalias(t as Alias);
  }
  return t;
}

export function unalias(a0: Alias): Type | null {
  if (a0.actual !== null) {
    return a0.actual;
  }
  let t: Type | null = null;
  for (let a: Alias | null = a0; a !== null; a = isAlias(t) ? t as Alias : null) {
    t = a.fromRHS;
  }
  // It's fine to memoize nil types since it's the zero value for actual.
  // It accomplishes nothing.
  a0.actual = t;
  return t;
}

// asNamed returns t as *Named if that is t's
// actual type. It returns nil otherwise.
export function asNamed(t: Type | null): Named | null {
  const n = Unalias(t);
  return n !== null && (n as { constructor?: { name?: string } }).constructor?.name === "Named" ? n as Named : null;
}

function isAlias(t: Type | null): boolean {
  return t !== null && (t as { constructor?: { name?: string } }).constructor?.name === "Alias";
}
