// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/array.go

// Copyright 2011 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Mechanical TypeScript transliteration of go/types/array.go.

import type { Type } from "./type.js";
import { TypeString } from "./typestring.js";

// An Array represents an array type.
export class Array implements Type {
  public constructor(
    public len: number,
    public readonly elem: Type
  ) {}

  // Len returns the length of array a.
  // A negative result indicates an unknown length.
  public Len(): number { return this.len; }

  // Elem returns element type of array a.
  public Elem(): Type { return this.elem; }

  public Underlying(): Type { return this; }
  public String(): string { return TypeString(this, null); }
}

// NewArray returns a new array type for the given element type and length.
// A negative length indicates an unknown length.
export function NewArray(elem: Type, len: number): Array {
  return new Array(len, elem);
}
