// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/index.go

// Copyright 2021 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file implements typechecking of index/slice expressions.

import { EndOf, PosOf, type Expr } from "../../front/ast.js";
import type { Type } from "./type.js";
import { Array as ArrayType } from "./array.js";
import { Basic, Int, String as StringKind } from "./basic.js";
import { Checker , registerCheckerMethod } from "./check.js";
import { representableConst } from "./const.js";
import { Interface } from "./interface.js";
import { Map as MapType } from "./map.js";
import { Pointer } from "./pointer.js";
import { allInteger, Identical, isString, isTypeParam, isUntyped, isValid } from "./predicates.js";
import { Signature } from "./signature.js";
import { NewSlice, Slice } from "./slice.js";
import { typeset, underIs } from "./under.js";
import { Typ, universeByte } from "./universe.js";
import { assert } from "./util.js";
import { constant_, invalid, mapindex, operand, typexpr, value, variable } from "./operand.js";

declare module "./check.js" {
  interface Checker {
    indexExpr(x: operand, e: indexedExpr): boolean;
    sliceExpr(x: operand, e: unknown): void;
    singleIndex(expr: indexedExpr): unknown | null;
    index(index: unknown, max: number): [Type, number];
    isValidIndex(x: operand, code: unknown, what: string, allowNegative: boolean): boolean;
    unpackIndexedExpr(e: unknown): indexedExpr | null;
  }
}

const invalidArg = "invalid argument: ";
const invalidOp = "invalid operation: ";

// If e is a valid function instantiation, indexExpr returns true.
// In that case x represents the uninstantiated function value and
// it is the caller's responsibility to instantiate the function.
registerCheckerMethod("indexExpr", function indexExpr(x: operand, e: indexedExpr): boolean {
  this.exprOrType(x, e.x, true);
  // x may be generic

  switch (x.mode()) {
    case invalid:
      this.use(...e.indices);
      return false;

    case typexpr:
      // type instantiation
      x.invalidate();
      // TODO(gri) here we re-evaluate e.X - try to avoid this
      x.typ_ = this.varType?.(e.orig) ?? Typ[0]!;
      if (isValid(x.typ())) {
        x.mode_ = typexpr;
      }
      return false;

    case value:
      if (x.typ()!.Underlying() instanceof Signature && (x.typ()!.Underlying() as Signature).TypeParams()!.Len() > 0) {
        // function instantiation
        return true;
      }
      break;
  }

  // x should not be generic at this point, but be safe and check
  this.nonGeneric?.(null, x);
  if (!x.isValid()) {
    return false;
  }

  // We cannot index on an incomplete type; make sure it's complete.
  if (!this.isComplete?.(x.typ())) {
    x.invalidate();
    return false;
  }
  const xu = x.typ()!.Underlying();
  if (xu instanceof Pointer) {
    // Additionally, if x.typ is a pointer to an array type, indexing implicitly dereferences the value, meaning
    // its base type must also be complete.
    if (!this.isComplete?.(xu.base)) {
      x.invalidate();
      return false;
    }
  } else if (xu instanceof MapType) {
    // Lastly, if x.typ is a map type, indexing must produce a value of a complete type, meaning
    // its element type must also be complete.
    if (!this.isComplete?.(xu.elem)) {
      x.invalidate();
      return false;
    }
  }

  // ordinary index expression
  let valid = false;
  let length = -1; // valid if >= 0
  const typ = x.typ()!.Underlying();
  if (typ instanceof Basic) {
    if (isString(typ)) {
      valid = true;
      if (x.mode() === constant_) {
        length = String(x.val).length;
      }
      // an indexed string always yields a byte value
      // (not a constant) even if the string and the
      // index are constant
      x.mode_ = value;
      x.typ_ = universeByte; // use 'byte' name
    }
  } else if (typ instanceof ArrayType) {
    valid = true;
    length = typ.len;
    if (x.mode() !== variable) {
      x.mode_ = value;
    }
    x.typ_ = typ.elem;
  } else if (typ instanceof Pointer) {
    const a = typ.base.Underlying();
    if (a instanceof ArrayType) {
      valid = true;
      length = a.len;
      x.mode_ = variable;
      x.typ_ = a.elem;
    }
  } else if (typ instanceof Slice) {
    valid = true;
    x.mode_ = variable;
    x.typ_ = typ.elem;
  } else if (typ instanceof MapType) {
    const index = this.singleIndex(e);
    if (index === null) {
      x.invalidate();
      return false;
    }
    const key = new operand();
    this.genericExpr(key, index, null);
    this.assignment(key, typ.key, "map index");
    // ok to continue even if indexing failed - map element type is known
    x.mode_ = mapindex;
    x.typ_ = typ.elem;
    x.expr = e.orig;
    return false;
  } else if (typ instanceof Interface) {
    if (!isTypeParam(x.typ()!)) {
      // fall through to invalid
    } else {
      // TODO(gri) report detailed failure cause for better error messages
      let key: Type | null = null;
      let elem: Type | null = null; // key != nil: we must have all maps
      let mode = variable; // non-maps result mode
      // TODO(gri) factor out closure and use it for non-typeparam cases as well
      if (underIs(x.typ()!, (u: Type | null) => {
        let l = -1; // valid if >= 0
        let k: Type | null = null;
        let ee: Type | null = null; // k is only set for maps
        if (u instanceof Basic) {
          if (isString(u)) {
            ee = universeByte;
            mode = value;
          }
        } else if (u instanceof ArrayType) {
          l = u.len;
          ee = u.elem;
          if (x.mode() !== variable) {
            mode = value;
          }
        } else if (u instanceof Pointer) {
          const a = u.base.Underlying();
          if (a instanceof ArrayType) {
            l = a.len;
            ee = a.elem;
          }
        } else if (u instanceof Slice) {
          ee = u.elem;
        } else if (u instanceof MapType) {
          k = u.key;
          ee = u.elem;
        }
        if (ee === null) {
          return false;
        }
        if (elem === null) {
          // first type
          length = l;
          key = k;
          elem = ee;
          return true;
        }
        // all map keys must be identical (incl. all nil)
        // (that is, we cannot mix maps with other types)
        if (!Identical(key, k)) {
          return false;
        }
        // all element types must be identical
        if (!Identical(elem, ee)) {
          return false;
        }
        // track the minimal length for arrays, if any
        if (l >= 0 && l < length) {
          length = l;
        }
        return true;
      })) {
        // For maps, the index expression must be assignable to the map key type.
        if (key !== null) {
          const index = this.singleIndex(e);
          if (index === null) {
            x.invalidate();
            return false;
          }
          const k = new operand();
          this.genericExpr(k, index, null);
          this.assignment(k, key, "map index");
          // ok to continue even if indexing failed - map element type is known
          x.mode_ = mapindex;
          x.typ_ = elem;
          x.expr = e.orig;
          return false;
        }

        // no maps
        valid = true;
        x.mode_ = mode;
        x.typ_ = elem;
      }
    }
  }

  if (!valid) {
    // types2 uses the position of '[' for the error
    this.errorf(x, "NonIndexableOperand", "cannot index %s", x);
    this.use(...e.indices);
    x.invalidate();
    return false;
  }

  const index = this.singleIndex(e);
  if (index === null) {
    x.invalidate();
    return false;
  }

  // In pathological (invalid) cases (e.g.: type T1 [][[]T1{}[0][0]]T0)
  // the element type may be accessed before it's set. Make sure we have
  // a valid type.
  if (x.typ() === null) {
    x.typ_ = Typ[0]!;
  }

  this.index(index, length);
  return false;
});

registerCheckerMethod("sliceExpr", function sliceExpr(x: operand, e0: unknown): void {
  const e = e0 as { object?: unknown; low?: unknown; high?: unknown; max?: unknown };
  this.expr(null, x, e.object);
  if (!x.isValid()) {
    this.use(e.low, e.high, e.max);
    return;
  }

  // determine common underlying type cu
  let ct: Type | null = null;
  let cu: Type | null = null; // type and respective common underlying type
  let hasString = false;
  // TODO(adonovan): use go1.23 "range typeset()".
  for (const [t, u0] of typeset(x.typ()!)) {
    let u = u0;
    if (u === null) {
      this.errorf(x, "NonSliceableOperand", "cannot slice %s: no specific type in %s", x, x.typ());
      cu = null;
      break;
    }

    // Treat strings like byte slices but remember that we saw a string.
    if (isString(u)) {
      u = NewSlice(universeByte);
      hasString = true;
    }

    // If this is the first type we're seeing, we're done.
    if (cu === null) {
      ct = t;
      cu = u;
      continue;
    }

    // Otherwise, the current type must have the same underlying type as all previous types.
    if (!Identical(cu, u)) {
      this.errorf(x, "NonSliceableOperand", "cannot slice %s: %s and %s have different underlying types", x, ct, t);
      cu = null;
      break;
    }
  }
  if (hasString) {
    // If we saw a string, proceed with string type,
    // but don't go from untyped string to string.
    cu = Typ[StringKind]!;
    if (!isTypeParam(x.typ()!)) {
      cu = x.typ()!.Underlying(); // untyped string remains untyped
    }
  }

  // Note that we don't permit slice expressions where x is a type expression, so we don't check for that here.
  // However, if x.typ is a pointer to an array type, slicing implicitly dereferences the value, meaning
  // its base type must also be complete.
  const p = x.typ()!.Underlying();
  if (p instanceof Pointer && !this.isComplete?.(p.base)) {
    x.invalidate();
    return;
  }

  let valid = false;
  let length = -1; // valid if >= 0
  if (cu === null) {
    // error reported above
    x.invalidate();
    return;
  } else if (cu instanceof Basic) {
    if (isString(cu)) {
      if (e.max !== undefined) {
        const at = e.max ?? e0;
        this.error(at, "InvalidSliceExpr", invalidOp + "3-index slice of string");
        x.invalidate();
        return;
      }
      valid = true;
      if (x.mode() === constant_) {
        length = String(x.val).length;
      }
      // spec: "For untyped string operands the result
      // is a non-constant value of type string."
      if (isUntyped(x.typ()!)) {
        x.typ_ = Typ[StringKind]!;
      }
    }
  } else if (cu instanceof ArrayType) {
    valid = true;
    length = cu.len;
    if (x.mode() !== variable) {
      this.errorf(x, "NonSliceableOperand", "cannot slice unaddressable value %s", x);
      x.invalidate();
      return;
    }
    x.typ_ = NewSlice(cu.elem);
  } else if (cu instanceof Pointer) {
    const a = cu.base.Underlying();
    if (a instanceof ArrayType) {
      valid = true;
      length = a.len;
      x.typ_ = NewSlice(a.elem);
    }
  } else if (cu instanceof Slice) {
    valid = true;
    // x.typ doesn't change
  }

  if (!valid) {
    this.errorf(x, "NonSliceableOperand", "cannot slice %s", x);
    x.invalidate();
    return;
  }

  x.mode_ = value;

  // spec: "Only the first index may be omitted; it defaults to 0."
  if (e.max !== undefined && (e.high === undefined || e.max === undefined)) {
    this.error(e0, "InvalidSyntaxTree", "2nd and 3rd index required in 3-index slice");
    x.invalidate();
    return;
  }

  // check indices
  const ind = [-1, -1, -1];
  const exprs = [e.low, e.high, e.max];
  for (let i = 0; i < exprs.length; i++) {
    const expr = exprs[i];
    let xx = -1;
    if (expr !== undefined && expr !== null) {
        // The "capacity" is only known statically for strings, arrays,
        // and pointers to arrays, and it is the same as the length for
        // those types.
        {
          let max = -1;
          if (length >= 0) {
            max = length + 1;
          }
          const [, v] = this.index(expr, max);
          if (v >= 0) {
            xx = v;
          }
        }
    } else if (i === 0) {
        // default is 0 for the first index
        xx = 0;
    } else if (length >= 0) {
        // default is length (== capacity) otherwise
        xx = length;
    }
    ind[i] = xx;
  }

  // constant indices must be in range
  // (check.index already checks that existing indices >= 0)
  outer:
  for (let i = 0; i < ind.length - 1; i++) {
    const xx = ind[i]!;
    if (xx > 0) {
      for (let j = 0; j < ind.slice(i + 1).length; j++) {
        const y = ind[i + 1 + j]!;
        if (y >= 0 && y < xx) {
          // The value y corresponds to the expression e.Index[i+1+j].
          // Because y >= 0, it must have been set from the expression
          // when checking indices and thus e.Index[i+1+j] is not nil.
          const at = exprs[i + 1 + j];
          this.errorf(at, "SwappedSliceIndices", "invalid slice indices: %d < %d", y, xx);
          break outer; // only report one error, ok to continue
        }
      }
    }
  }
});

// singleIndex returns the (single) index from the index expression e.
// If the index is missing, or if there are multiple indices, an error
// is reported and the result is nil.
registerCheckerMethod("singleIndex", function singleIndex(expr: indexedExpr): unknown | null {
  if (expr.indices.length === 0) {
    this.errorf(expr.orig, "InvalidSyntaxTree", "index expression %v with 0 indices", expr);
    return null;
  }
  if (expr.indices.length > 1) {
    // TODO(rFindley) should this get a distinct error code?
    this.error(expr.indices[1], "InvalidIndex", invalidOp + "more than one index");
  }
  return expr.indices[0]!;
});

// index checks an index expression for validity.
// If max >= 0, it is the upper bound for index.
// If the result typ is != Typ[Invalid], index is valid and typ is its (possibly named) integer type.
// If the result val >= 0, index is valid and val is its constant int value.
registerCheckerMethod("index", function index(index: unknown, max: number): [Type, number] {
  let typ: Type = Typ[0]!;
  let val = -1;

  const x = new operand();
  this.expr(null, x, index);
  if (!this.isValidIndex(x, "InvalidIndex", "index", false)) {
    return [typ, val];
  }

  if (x.mode() !== constant_) {
    return [x.typ()!, -1];
  }

  if (isUnknown(x.val)) {
    return [typ, val];
  }

  const v = toInt(x.val);
  assert(v !== null);
  if (max >= 0 && v >= BigInt(max)) {
    this.errorf(x, "InvalidIndex", invalidArg + "index %s out of bounds [0:%d]", String(x.val), max);
    return [typ, val];
  }

  // 0 <= v [ && v < max ]
  typ = x.typ()!;
  val = Number(v);
  return [typ, val];
});

registerCheckerMethod("isValidIndex", function isValidIndex(x: operand, code: unknown, what: string, allowNegative: boolean): boolean {
  if (!x.isValid()) {
    return false;
  }

  // spec: "a constant index that is untyped is given type int"
  this.convertUntyped(x, Typ[Int]!);
  if (!x.isValid()) {
    return false;
  }

  // spec: "the index x must be of integer type or an untyped constant"
  if (!allInteger(x.typ()!)) {
    this.errorf(x, code, invalidArg + "%s %s must be integer", what, x);
    return false;
  }

  if (x.mode() === constant_) {
    // spec: "a constant index must be non-negative ..."
    const v = toInt(x.val);
    if (!allowNegative && v !== null && v < 0n) {
      this.errorf(x, code, invalidArg + "%s %s must not be negative", what, x);
      return false;
    }

    // spec: "... and representable by a value of type int"
    const rounded = { value: x.val };
    if (!representableConst(x.val, this, Typ[Int] as Basic, rounded)) {
      this.errorf(x, code, invalidArg + "%s %s overflows int", what, x);
      return false;
    }
    x.val = rounded.value;
  }

  return true;
});

// indexedExpr wraps an ast.IndexExpr or ast.IndexListExpr.
//
// Orig holds the original ast.Expr from which this indexedExpr was derived.
//
// Note: indexedExpr (intentionally) does not wrap ast.Expr, as that leads to
// accidental misuse such as encountered in golang/go#63933.
//
// TODO(rfindley): remove this helper, in favor of just having a helper
// function that returns indices.
export class indexedExpr {
  public constructor(
    public orig: unknown, // the wrapped expr, which may be distinct from the IndexListExpr below.
    public x: unknown, // expression
    public lbrack: number, // position of "["
    public indices: unknown[], // index expressions
    public rbrack: number // position of "]"
  ) {}

  public Pos(): number {
    return PosOf(this.orig as Expr);
  }
}

export function unpackIndexedExpr(n: unknown): indexedExpr | null {
  const e = n as { kind?: string; object?: unknown; index?: unknown; indices?: unknown[] } | null;
  switch (e?.kind) {
    case "IndexExpr":
      return new indexedExpr(
        e,
        e.object,
        PosOf(e as Expr),
        [e.index],
        EndOf(e as Expr)
      );
    case "IndexListExpr":
      return new indexedExpr(
        e,
        e.object,
        PosOf(e as Expr),
        e.indices ?? [],
        EndOf(e as Expr)
      );
  }
  return null;
}

registerCheckerMethod("unpackIndexedExpr", function unpackIndexedExprMethod(e: unknown): indexedExpr | null {
  return unpackIndexedExpr(e);
});

function toInt(x: unknown): bigint | null {
  if (typeof x === "bigint") {
    return x;
  }
  if (typeof x === "number" && Number.isInteger(x)) {
    return BigInt(x);
  }
  const obj = x as { value?: unknown; toBigInt?: () => bigint } | null;
  if (obj !== null && typeof obj === "object") {
    if (typeof obj.toBigInt === "function") {
      return obj.toBigInt();
    }
    if (obj.value !== undefined) {
      return toInt(obj.value);
    }
  }
  return null;
}

function isUnknown(x: unknown): boolean {
  return x === null || x === undefined || (typeof x === "object" && (x as { kind?: string }).kind === "Unknown");
}
