// Code generated by goyacc -o lalr_logicparser_grammar_v17.go -p lalr17 lalr_logicparser_grammar_v17.y. DO NOT EDIT.

//line lalr_logicparser_grammar_v17.y:16
package goivy

import __yyfmt__ "fmt"

//line lalr_logicparser_grammar_v17.y:16

import (
	"fmt"
)

// labelCounter is a package-level counter for generating unique mixer names.
var lalrLabelCounter int

// acfg extracts the *AstConfig from the lexer for use in grammar actions.
func lalr17Acfg(lex lalr17Lexer) *AstConfig {
	return lex.(*lalr17LexAdapter).cfg
}

// atypeToString extracts the string sort name from an atype Node.
func lalr17AtypeToString(n Node) string {
	switch v := n.(type) {
	case *Symbol:
		return v.Rep
	case *This:
		return "this"
	default:
		return fmt.Sprint(n)
	}
}

//line lalr_logicparser_grammar_v17.y:45
type lalr17SymType struct {
	yys   int
	node  Node
	nodes []Node
	str   string
}

const LALR17_TOK_SYMBOL = 57346
const LALR17_TOK_VARIABLE = 57347
const LALR17_TOK_PRESYMBOL = 57348
const LALR17_TOK_LPAREN = 57349
const LALR17_TOK_RPAREN = 57350
const LALR17_TOK_LB = 57351
const LALR17_TOK_RB = 57352
const LALR17_TOK_LCB = 57353
const LALR17_TOK_RCB = 57354
const LALR17_TOK_COMMA = 57355
const LALR17_TOK_SEMI = 57356
const LALR17_TOK_COLON = 57357
const LALR17_TOK_DOT = 57358
const LALR17_TOK_PLUS = 57359
const LALR17_TOK_MINUS = 57360
const LALR17_TOK_TIMES = 57361
const LALR17_TOK_DIV = 57362
const LALR17_TOK_EQ = 57363
const LALR17_TOK_TILDAEQ = 57364
const LALR17_TOK_TILDA = 57365
const LALR17_TOK_LE = 57366
const LALR17_TOK_LT = 57367
const LALR17_TOK_GE = 57368
const LALR17_TOK_GT = 57369
const LALR17_TOK_AND = 57370
const LALR17_TOK_OR = 57371
const LALR17_TOK_ARROW = 57372
const LALR17_TOK_IFF = 57373
const LALR17_TOK_PTO = 57374
const LALR17_TOK_DOLLAR = 57375
const LALR17_TOK_FORALL = 57376
const LALR17_TOK_EXISTS = 57377
const LALR17_TOK_TRUE = 57378
const LALR17_TOK_FALSE = 57379
const LALR17_TOK_OLD = 57380
const LALR17_TOK_THIS = 57381
const LALR17_TOK_ISA = 57382
const LALR17_TOK_IF = 57383
const LALR17_TOK_ELSE = 57384
const LALR17_TOK_GLOBALLY = 57385
const LALR17_TOK_EVENTUALLY = 57386
const LALR17_TOK_WHENNEXT = 57387
const LALR17_TOK_WHENPREV = 57388
const LALR17_TOK_WHENFIRST = 57389
const LALR17_TOK_WHENLAST = 57390
const LALR17_TOK_ASSUME = 57391
const LALR17_TOK_ASSERT = 57392
const LALR17_TOK_REQUIRE = 57393
const LALR17_TOK_ENSURE = 57394
const LALR17_TOK_ASSIGN = 57395
const LALR17_TOK_VAR = 57396
const LALR17_TOK_LOCAL = 57397
const LALR17_TOK_LET = 57398
const LALR17_TOK_CALL = 57399
const LALR17_TOK_WHILE = 57400
const LALR17_TOK_FOR = 57401
const LALR17_TOK_IN = 57402
const LALR17_TOK_INVARIANT = 57403
const LALR17_TOK_DECREASES = 57404
const LALR17_TOK_RETURNS = 57405
const LALR17_TOK_SOME = 57406
const LALR17_TOK_MINIMIZING = 57407
const LALR17_TOK_MAXIMIZING = 57408
const LALR17_TOK_DEBUG = 57409
const LALR17_TOK_THUNK = 57410
const LALR17_TOK_UNPROVABLE = 57411
const LALR17_TOK_PROOF = 57412
const LALR17_TOK_INSTANTIATE = 57413
const LALR17_TOK_LABEL = 57414
const LALR17_TOK_CARET = 57415
const LALR17_TOK_METHOD = 57416
const LALR17_TOK_NULL = 57417
const LALR17_TOK_SET = 57418
const LALR17_TOK_WITH = 57419
const LALR17_TOK_SCENARIO = 57420
const LALR17_TOK_BEFORE = 57421
const LALR17_TOK_AFTER = 57422
const LALR17_TOK_TACTIC = 57423
const LALR17_TOK_DEFINITION = 57424
const LALR17_TOK_TRIGGER = 57425
const LALR17_TOK_SHOWGOALS = 57426
const LALR17_TOK_DEFERGOAL = 57427
const LALR17_TOK_SPOIL = 57428
const LALR17_TOK_UNFOLD = 57429
const LALR17_TOK_FORGET = 57430
const LALR17_TOK_PROPERTY = 57431
const LALR17_TOK_FUNCTION = 57432
const LALR17_TOK_THEOREM = 57433
const LALR17_TOK_APPLY = 57434

var lalr17Toknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LALR17_TOK_SYMBOL",
	"LALR17_TOK_VARIABLE",
	"LALR17_TOK_PRESYMBOL",
	"LALR17_TOK_LPAREN",
	"LALR17_TOK_RPAREN",
	"LALR17_TOK_LB",
	"LALR17_TOK_RB",
	"LALR17_TOK_LCB",
	"LALR17_TOK_RCB",
	"LALR17_TOK_COMMA",
	"LALR17_TOK_SEMI",
	"LALR17_TOK_COLON",
	"LALR17_TOK_DOT",
	"LALR17_TOK_PLUS",
	"LALR17_TOK_MINUS",
	"LALR17_TOK_TIMES",
	"LALR17_TOK_DIV",
	"LALR17_TOK_EQ",
	"LALR17_TOK_TILDAEQ",
	"LALR17_TOK_TILDA",
	"LALR17_TOK_LE",
	"LALR17_TOK_LT",
	"LALR17_TOK_GE",
	"LALR17_TOK_GT",
	"LALR17_TOK_AND",
	"LALR17_TOK_OR",
	"LALR17_TOK_ARROW",
	"LALR17_TOK_IFF",
	"LALR17_TOK_PTO",
	"LALR17_TOK_DOLLAR",
	"LALR17_TOK_FORALL",
	"LALR17_TOK_EXISTS",
	"LALR17_TOK_TRUE",
	"LALR17_TOK_FALSE",
	"LALR17_TOK_OLD",
	"LALR17_TOK_THIS",
	"LALR17_TOK_ISA",
	"LALR17_TOK_IF",
	"LALR17_TOK_ELSE",
	"LALR17_TOK_GLOBALLY",
	"LALR17_TOK_EVENTUALLY",
	"LALR17_TOK_WHENNEXT",
	"LALR17_TOK_WHENPREV",
	"LALR17_TOK_WHENFIRST",
	"LALR17_TOK_WHENLAST",
	"LALR17_TOK_ASSUME",
	"LALR17_TOK_ASSERT",
	"LALR17_TOK_REQUIRE",
	"LALR17_TOK_ENSURE",
	"LALR17_TOK_ASSIGN",
	"LALR17_TOK_VAR",
	"LALR17_TOK_LOCAL",
	"LALR17_TOK_LET",
	"LALR17_TOK_CALL",
	"LALR17_TOK_WHILE",
	"LALR17_TOK_FOR",
	"LALR17_TOK_IN",
	"LALR17_TOK_INVARIANT",
	"LALR17_TOK_DECREASES",
	"LALR17_TOK_RETURNS",
	"LALR17_TOK_SOME",
	"LALR17_TOK_MINIMIZING",
	"LALR17_TOK_MAXIMIZING",
	"LALR17_TOK_DEBUG",
	"LALR17_TOK_THUNK",
	"LALR17_TOK_UNPROVABLE",
	"LALR17_TOK_PROOF",
	"LALR17_TOK_INSTANTIATE",
	"LALR17_TOK_LABEL",
	"LALR17_TOK_CARET",
	"LALR17_TOK_METHOD",
	"LALR17_TOK_NULL",
	"LALR17_TOK_SET",
	"LALR17_TOK_WITH",
	"LALR17_TOK_SCENARIO",
	"LALR17_TOK_BEFORE",
	"LALR17_TOK_AFTER",
	"LALR17_TOK_TACTIC",
	"LALR17_TOK_DEFINITION",
	"LALR17_TOK_TRIGGER",
	"LALR17_TOK_SHOWGOALS",
	"LALR17_TOK_DEFERGOAL",
	"LALR17_TOK_SPOIL",
	"LALR17_TOK_UNFOLD",
	"LALR17_TOK_FORGET",
	"LALR17_TOK_PROPERTY",
	"LALR17_TOK_FUNCTION",
	"LALR17_TOK_THEOREM",
	"LALR17_TOK_APPLY",
}

var lalr17Statenames = [...]string{}

const lalr17EofCode = 1
const lalr17ErrCode = 2
const lalr17InitialStackSize = 16

//line lalr_logicparser_grammar_v17.y:999

// lalrMakeSequence wraps a list of action nodes into a single And node (sequence).
func lalr17MakeSequence(cfg *AstConfig, stmts []Node) Node {
	// Lower var declarations into nested local scopes, matching Python/HW parser.
	stmts = LowerVarStatements(stmts)
	if len(stmts) == 0 {
		return cfg.NewAnd()
	}
	if len(stmts) == 1 {
		return stmts[0]
	}
	return cfg.NewAnd(stmts...)
}

//line yacctab:1
var lalr17Exca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const lalr17Private = 57344

const lalr17Last = 1018

var lalr17Act = [...]int16{
	7, 206, 88, 294, 22, 153, 157, 156, 164, 61,
	26, 136, 163, 54, 74, 162, 89, 76, 125, 161,
	83, 84, 79, 66, 3, 89, 85, 146, 11, 240,
	119, 94, 95, 96, 97, 91, 99, 100, 101, 102,
	103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
	113, 171, 23, 260, 238, 26, 26, 77, 160, 24,
	165, 295, 296, 236, 128, 129, 61, 126, 24, 28,
	8, 276, 55, 192, 126, 137, 81, 90, 286, 56,
	143, 166, 167, 29, 247, 25, 263, 154, 134, 121,
	122, 123, 26, 246, 158, 24, 187, 8, 116, 186,
	117, 141, 165, 226, 151, 252, 80, 147, 165, 10,
	150, 147, 46, 47, 48, 49, 89, 151, 61, 168,
	198, 152, 73, 166, 167, 245, 138, 67, 27, 166,
	167, 189, 194, 118, 152, 127, 114, 115, 130, 93,
	202, 70, 71, 203, 68, 69, 210, 254, 144, 289,
	214, 255, 254, 213, 298, 195, 196, 197, 193, 201,
	120, 2, 29, 204, 288, 32, 33, 209, 148, 205,
	89, 26, 26, 155, 221, 262, 186, 26, 26, 87,
	220, 26, 26, 144, 26, 8, 149, 200, 242, 219,
	26, 46, 47, 48, 49, 98, 223, 237, 26, 144,
	222, 208, 145, 8, 126, 137, 305, 26, 89, 234,
	168, 219, 250, 257, 218, 254, 258, 215, 249, 219,
	259, 229, 211, 199, 8, 212, 92, 72, 131, 133,
	211, 261, 139, 221, 290, 186, 266, 297, 207, 80,
	256, 82, 267, 268, 278, 26, 270, 61, 61, 86,
	26, 168, 224, 225, 269, 280, 207, 26, 230, 231,
	273, 274, 232, 233, 154, 235, 80, 168, 78, 284,
	281, 241, 275, 24, 285, 23, 80, 159, 169, 244,
	265, 253, 279, 140, 4, 190, 135, 53, 251, 1,
	293, 92, 227, 291, 228, 0, 0, 0, 154, 0,
	26, 26, 302, 301, 0, 0, 0, 0, 0, 0,
	0, 292, 216, 217, 0, 0, 0, 0, 92, 170,
	0, 183, 0, 303, 304, 0, 271, 0, 0, 173,
	0, 272, 0, 0, 0, 0, 181, 0, 277, 0,
	0, 0, 0, 0, 239, 0, 0, 0, 183, 0,
	180, 182, 0, 243, 0, 0, 173, 0, 0, 248,
	0, 177, 0, 181, 174, 175, 176, 184, 185, 178,
	179, 0, 172, 92, 0, 0, 0, 180, 182, 0,
	0, 299, 300, 0, 0, 0, 0, 264, 177, 0,
	0, 174, 175, 176, 184, 185, 178, 179, 0, 172,
	0, 0, 0, 183, 0, 0, 0, 0, 0, 0,
	0, 173, 0, 0, 0, 0, 282, 0, 181, 0,
	0, 0, 0, 283, 0, 0, 0, 0, 0, 0,
	0, 0, 180, 182, 0, 0, 0, 287, 23, 24,
	13, 0, 0, 177, 8, 188, 174, 175, 176, 184,
	185, 178, 179, 0, 172, 0, 16, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 21, 17, 18, 14,
	15, 12, 0, 0, 67, 0, 19, 20, 0, 0,
	0, 0, 57, 58, 59, 60, 0, 62, 70, 71,
	63, 68, 69, 23, 24, 13, 0, 0, 0, 8,
	52, 0, 65, 0, 64, 0, 0, 0, 0, 0,
	0, 16, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 21, 17, 18, 14, 15, 12, 0, 0, 67,
	0, 19, 20, 0, 0, 0, 0, 57, 58, 59,
	60, 0, 62, 70, 71, 63, 68, 69, 23, 24,
	13, 0, 0, 0, 8, 0, 0, 65, 0, 64,
	0, 0, 0, 0, 0, 0, 16, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 21, 17, 18, 14,
	15, 12, 0, 0, 67, 0, 19, 20, 0, 0,
	0, 0, 57, 58, 59, 60, 0, 62, 70, 71,
	63, 68, 69, 23, 24, 13, 0, 0, 0, 8,
	0, 0, 65, 0, 64, 51, 29, 30, 31, 32,
	33, 16, 0, 0, 0, 23, 24, 13, 0, 0,
	0, 21, 17, 18, 14, 15, 12, 0, 0, 0,
	0, 19, 20, 16, 0, 46, 47, 48, 49, 0,
	0, 0, 0, 21, 17, 18, 14, 15, 12, 0,
	0, 0, 0, 19, 20, 0, 0, 0, 6, 57,
	58, 59, 60, 0, 62, 0, 9, 63, 0, 5,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 65,
	0, 64, 51, 29, 30, 31, 32, 33, 35, 41,
	0, 36, 37, 38, 39, 42, 43, 44, 45, 40,
	0, 0, 0, 0, 0, 0, 0, 50, 34, 0,
	0, 0, 46, 47, 48, 49, 142, 0, 0, 0,
	124, 0, 0, 51, 29, 30, 31, 32, 33, 35,
	41, 0, 36, 37, 38, 39, 42, 43, 44, 45,
	40, 0, 0, 0, 0, 0, 0, 0, 50, 34,
	0, 0, 0, 46, 47, 48, 49, 51, 29, 30,
	31, 32, 33, 35, 41, 0, 36, 37, 38, 39,
	42, 43, 44, 45, 40, 0, 0, 0, 0, 0,
	0, 0, 50, 34, 0, 0, 0, 46, 47, 48,
	49, 51, 29, 30, 31, 32, 33, 35, 41, 0,
	36, 37, 38, 39, 42, 43, 0, 0, 40, 0,
	0, 0, 0, 0, 0, 0, 50, 34, 0, 0,
	0, 46, 47, 48, 49, 51, 29, 30, 31, 32,
	33, 35, 41, 0, 36, 37, 38, 39, 42, 0,
	0, 0, 40, 0, 0, 0, 0, 0, 0, 0,
	50, 34, 0, 0, 0, 46, 47, 48, 49, 51,
	29, 30, 31, 32, 33, 35, 41, 0, 36, 37,
	38, 39, 0, 0, 0, 0, 40, 51, 29, 30,
	31, 32, 33, 0, 50, 34, 0, 0, 0, 46,
	47, 48, 49, 51, 29, 30, 31, 32, 33, 0,
	41, 0, 0, 34, 23, 24, 13, 46, 47, 48,
	49, 0, 0, 0, 0, 0, 0, 0, 191, 34,
	0, 0, 16, 46, 47, 48, 49, 23, 24, 13,
	0, 0, 21, 17, 18, 14, 15, 12, 0, 0,
	0, 132, 19, 20, 0, 16, 23, 24, 13, 0,
	0, 0, 0, 0, 0, 21, 17, 18, 14, 15,
	12, 0, 0, 0, 16, 19, 20, 0, 23, 24,
	13, 0, 0, 0, 21, 17, 18, 14, 15, 12,
	0, 0, 0, 0, 19, 20, 16, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 75, 17, 18, 14,
	15, 12, 0, 0, 0, 0, 19, 20,
}

var lalr17Pact = [...]int16{
	598, -1000, -1000, -1000, -1000, 89, -3, 752, 488, 216,
	-1000, -1000, 267, 973, -1000, -1000, 951, 261, 234, 951,
	951, 267, 242, 164, -1000, 0, -1000, -1000, 215, 267,
	951, 951, 951, 951, 951, 951, 951, 951, 951, 951,
	951, 951, 951, 951, 951, 951, 951, 951, 951, 951,
	89, 89, -1000, 86, -1000, -1000, -1000, 951, 951, 951,
	951, 677, 62, 951, 951, 620, -1000, 932, 951, 62,
	53, 951, 71, -1000, 718, 267, 854, 186, 270, -1000,
	153, 170, 270, 752, 752, 88, 951, 89, 215, 267,
	47, -1000, 307, -1000, 146, 146, 67, 67, 54, 888,
	888, 888, 888, 888, 888, 872, 854, 820, 786, 786,
	752, 752, 752, 752, 100, 100, -1000, 433, -1000, -1000,
	-1000, -1000, -1000, -1000, 909, 20, 143, 267, 752, 752,
	-1000, 213, 213, 59, 210, 174, -1000, 125, 267, 213,
	155, 250, -1000, 101, 271, 951, 217, -1000, 267, 951,
	209, 951, 951, 206, 752, 100, -1000, -1000, -1000, -1000,
	-1, -1, 187, -1000, -1000, 951, 89, 89, 82, 280,
	-1000, -1000, 89, 89, -1000, -1000, 89, 89, 951, 89,
	-9, 270, -23, 951, -48, 89, -1000, 951, -1000, -1000,
	-1000, -1000, 951, 89, 110, 51, 42, -1000, 951, 62,
	53, -1000, 89, 90, -1000, -1000, 202, -1000, 135, -1000,
	752, 270, 951, -1000, 752, 951, -1000, -1000, -1000, 951,
	41, -1000, 270, -1000, 154, 9, 951, -1000, 362, -1000,
	100, 100, 100, 0, 215, 100, 215, 187, 270, 215,
	89, 100, 600, -1000, 100, 89, 543, 543, 213, 11,
	-1000, 100, 89, 232, 264, 951, -1000, 752, 752, 752,
	-1000, -1000, 951, 951, -1000, -1000, 215, -1000, -1000, 187,
	36, 100, 100, -1000, -1000, -1000, 951, 100, -1000, -1000,
	134, -1000, 226, -1000, 176, -1000, 215, 213, 250, -18,
	230, -1000, -1000, 139, -1000, 89, 89, 951, -18, 192,
	192, 198, -1000, -1000, -1000, -1000,
}

var lalr17Pgo = [...]int16{
	0, 289, 0, 160, 109, 28, 22, 85, 5, 27,
	57, 4, 289, 13, 72, 79, 23, 30, 18, 289,
	287, 286, 11, 284, 283, 3, 282, 281, 1, 51,
	278, 6, 7, 2, 277, 12, 19, 15, 8,
}

var lalr17R1 = [...]int8{
	0, 1, 1, 1, 1, 1, 11, 12, 12, 12,
	7, 7, 7, 4, 4, 5, 5, 6, 6, 9,
	9, 10, 10, 8, 8, 8, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 3, 17, 18, 18, 18,
	19, 19, 22, 22, 21, 21, 16, 16, 16, 20,
	20, 20, 13, 13, 14, 14, 14, 14, 14, 14,
	14, 14, 14, 14, 14, 14, 15, 15, 15, 15,
	15, 15, 15, 15, 15, 23, 24, 28, 28, 27,
	27, 26, 26, 25, 25, 38, 37, 37, 35, 35,
	35, 36, 36, 34, 34, 33, 33, 33, 31, 31,
	32, 32, 30, 30, 30, 29, 29, 29, 29, 29,
	29, 29, 29, 29, 29, 29, 29, 29, 29, 29,
}

var lalr17R2 = [...]int8{
	0, 1, 1, 1, 4, 3, 1, 1, 1, 3,
	1, 3, 1, 1, 4, 1, 3, 1, 3, 1,
	3, 1, 3, 0, 1, 3, 1, 1, 2, 3,
	3, 3, 3, 3, 3, 5, 3, 3, 3, 3,
	3, 3, 3, 1, 1, 2, 3, 3, 3, 3,
	4, 4, 5, 5, 2, 2, 3, 3, 3, 3,
	3, 3, 10, 4, 4, 1, 1, 1, 3, 4,
	1, 3, 3, 4, 1, 3, 2, 3, 4, 1,
	3, 2, 1, 1, 2, 2, 2, 2, 3, 3,
	2, 4, 2, 2, 2, 1, 1, 3, 5, 5,
	3, 5, 7, 3, 3, 6, 2, 1, 3, 0,
	2, 5, 3, 3, 3, 3, 1, 3, 2, 4,
	4, 1, 2, 1, 1, 0, 2, 4, 3, 2,
	0, 1, 1, 3, 2, 2, 2, 1, 1, 2,
	4, 3, 2, 3, 2, 3, 5, 3, 2, 1,
}

var lalr17Chk = [...]int16{
	-1000, -1, -3, -16, -23, 81, 70, -2, 11, 78,
	-4, -5, 38, 7, 36, 37, 23, 34, 35, 43,
	44, 33, -11, 5, 6, -7, -11, 39, 72, 16,
	17, 18, 19, 20, 41, 21, 24, 25, 26, 27,
	32, 22, 28, 29, 30, 31, 45, 46, 47, 48,
	40, 15, 12, -20, -13, -14, -15, 49, 50, 51,
	52, -2, 54, 57, 71, 69, -16, 41, 58, 59,
	55, 56, 11, -4, -2, 33, -2, -10, 7, -6,
	5, -10, 7, -2, -2, -11, 7, 15, -33, 16,
	77, -31, 11, -4, -2, -2, -2, -2, -3, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -7, -7, 12, 14, -15, -17,
	-3, -17, -17, -17, 53, -18, -11, 73, -2, -2,
	-14, -3, 19, -3, -18, -21, -22, -11, 73, -3,
	-24, 30, 8, -11, 13, 16, -9, -5, 15, 16,
	-9, 16, 33, -8, -2, -7, -32, -31, -11, -34,
	11, -36, -37, -35, -38, 61, 82, 83, -5, -30,
	12, -29, 92, 49, 84, 85, 86, 81, 89, 90,
	70, 56, 71, 41, 87, 88, -31, 42, 12, -13,
	-3, 19, 53, 15, -11, -16, -16, -16, 61, 13,
	13, -16, 15, -11, -16, 14, -28, 6, -10, -6,
	-2, 13, 8, -11, -2, 8, -3, -3, 8, 13,
	-36, -35, 13, -17, -7, -7, 21, 12, 14, -29,
	-7, -7, -7, -7, -17, -7, 72, -37, 77, -3,
	77, -7, -2, -3, -7, 15, 42, 42, -3, -18,
	-22, -7, 15, -27, 13, 16, -5, -2, -2, -2,
	12, -38, 21, 77, -3, -29, -33, -32, -31, -37,
	-31, -7, -7, -13, -13, -16, 60, -7, 12, -26,
	-28, 6, -3, -3, -8, -32, 42, -3, 30, 15,
	8, -31, -16, -28, -25, 79, 80, 7, 15, -7,
	-7, -8, -25, -16, -16, 8,
}

var lalr17Def = [...]int16{
	0, -2, 1, 2, 3, 0, 0, 65, 0, 0,
	26, 27, 0, 0, 43, 44, 0, 0, 0, 0,
	0, 0, 13, 15, 6, 125, 10, 12, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 76, 0, 79, 82, 83, 0, 0, 0,
	0, 95, 0, 0, 0, 0, 96, 0, 0, 0,
	0, 0, 0, 28, 0, 0, 45, 0, 0, 21,
	17, 0, 0, 54, 55, 0, 23, 0, 130, 0,
	0, 5, 0, 29, 31, 32, 33, 34, 0, 36,
	37, 38, 39, 40, 41, 42, 46, 47, 48, 49,
	56, 57, 58, 59, 60, 61, 77, 0, 81, 84,
	66, 85, 86, 87, 0, 90, 67, 0, 92, 93,
	94, 0, 0, 0, 0, 0, 74, 0, 0, 0,
	0, 0, 30, 0, 0, 0, 0, 19, 0, 0,
	0, 0, 0, 0, 24, 16, 4, 131, 11, 126,
	0, 123, 124, 121, 116, 0, 0, 0, 0, 0,
	129, 132, 0, 0, 137, 138, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 149, 0, 78, 80,
	88, 89, 0, 0, 0, 97, 0, 100, 0, 0,
	0, 103, 0, 0, 104, 109, 106, 107, 0, 22,
	50, 0, 0, 18, 51, 0, 63, 64, 14, 0,
	0, 122, 0, 118, 0, 0, 0, 128, 0, 134,
	135, 136, 139, 125, 130, 142, 0, 144, 0, 0,
	0, 148, 35, 91, 68, 0, 0, 0, 0, 0,
	75, 72, 0, 0, 0, 0, 20, 52, 53, 25,
	127, 117, 0, 23, 115, 133, 130, 141, 143, 145,
	0, 147, 69, 98, 99, 101, 0, 73, 105, 110,
	0, 108, 0, 119, 120, 140, 0, 0, 0, 0,
	0, 146, 102, 0, 112, 0, 0, 23, 0, 0,
	0, 0, 111, 113, 114, 62,
}

var lalr17Tok1 = [...]int8{
	1,
}

var lalr17Tok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92,
}

var lalr17Tok3 = [...]int8{
	0,
}

var lalr17ErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	lalr17Debug        = 0
	lalr17ErrorVerbose = false
)

type lalr17Lexer interface {
	Lex(lval *lalr17SymType) int
	Error(s string)
}

type lalr17Parser interface {
	Parse(lalr17Lexer) int
	Lookahead() int
}

type lalr17ParserImpl struct {
	lval  lalr17SymType
	stack [lalr17InitialStackSize]lalr17SymType
	char  int
}

func (p *lalr17ParserImpl) Lookahead() int {
	return p.char
}

func lalr17NewParser() lalr17Parser {
	return &lalr17ParserImpl{}
}

const lalr17Flag = -1000

func lalr17Tokname(c int) string {
	if c >= 1 && c-1 < len(lalr17Toknames) {
		if lalr17Toknames[c-1] != "" {
			return lalr17Toknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func lalr17Statname(s int) string {
	if s >= 0 && s < len(lalr17Statenames) {
		if lalr17Statenames[s] != "" {
			return lalr17Statenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func lalr17ErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !lalr17ErrorVerbose {
		return "syntax error"
	}

	for _, e := range lalr17ErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + lalr17Tokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(lalr17Pact[state])
	for tok := TOKSTART; tok-1 < len(lalr17Toknames); tok++ {
		if n := base + tok; n >= 0 && n < lalr17Last && int(lalr17Chk[int(lalr17Act[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if lalr17Def[state] == -2 {
		i := 0
		for lalr17Exca[i] != -1 || int(lalr17Exca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; lalr17Exca[i] >= 0; i += 2 {
			tok := int(lalr17Exca[i])
			if tok < TOKSTART || lalr17Exca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if lalr17Exca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += lalr17Tokname(tok)
	}
	return res
}

func lalr17lex1(lex lalr17Lexer, lval *lalr17SymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(lalr17Tok1[0])
		goto out
	}
	if char < len(lalr17Tok1) {
		token = int(lalr17Tok1[char])
		goto out
	}
	if char >= lalr17Private {
		if char < lalr17Private+len(lalr17Tok2) {
			token = int(lalr17Tok2[char-lalr17Private])
			goto out
		}
	}
	for i := 0; i < len(lalr17Tok3); i += 2 {
		token = int(lalr17Tok3[i+0])
		if token == char {
			token = int(lalr17Tok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(lalr17Tok2[1]) /* unknown char */
	}
	if lalr17Debug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", lalr17Tokname(token), uint(char))
	}
	return char, token
}

func lalr17Parse(lalr17lex lalr17Lexer) int {
	return lalr17NewParser().Parse(lalr17lex)
}

func (lalr17rcvr *lalr17ParserImpl) Parse(lalr17lex lalr17Lexer) int {
	var lalr17n int
	var lalr17VAL lalr17SymType
	var lalr17Dollar []lalr17SymType
	_ = lalr17Dollar // silence set and not used
	lalr17S := lalr17rcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	lalr17state := 0
	lalr17rcvr.char = -1
	lalr17token := -1 // lalr17rcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		lalr17state = -1
		lalr17rcvr.char = -1
		lalr17token = -1
	}()
	lalr17p := -1
	goto lalr17stack

ret0:
	return 0

ret1:
	return 1

lalr17stack:
	/* put a state and value onto the stack */
	if lalr17Debug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", lalr17Tokname(lalr17token), lalr17Statname(lalr17state))
	}

	lalr17p++
	if lalr17p >= len(lalr17S) {
		nyys := make([]lalr17SymType, len(lalr17S)*2)
		copy(nyys, lalr17S)
		lalr17S = nyys
	}
	lalr17S[lalr17p] = lalr17VAL
	lalr17S[lalr17p].yys = lalr17state

lalr17newstate:
	lalr17n = int(lalr17Pact[lalr17state])
	if lalr17n <= lalr17Flag {
		goto lalr17default /* simple state */
	}
	if lalr17rcvr.char < 0 {
		lalr17rcvr.char, lalr17token = lalr17lex1(lalr17lex, &lalr17rcvr.lval)
	}
	lalr17n += lalr17token
	if lalr17n < 0 || lalr17n >= lalr17Last {
		goto lalr17default
	}
	lalr17n = int(lalr17Act[lalr17n])
	if int(lalr17Chk[lalr17n]) == lalr17token { /* valid shift */
		lalr17rcvr.char = -1
		lalr17token = -1
		lalr17VAL = lalr17rcvr.lval
		lalr17state = lalr17n
		if Errflag > 0 {
			Errflag--
		}
		goto lalr17stack
	}

lalr17default:
	/* default state action */
	lalr17n = int(lalr17Def[lalr17state])
	if lalr17n == -2 {
		if lalr17rcvr.char < 0 {
			lalr17rcvr.char, lalr17token = lalr17lex1(lalr17lex, &lalr17rcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if lalr17Exca[xi+0] == -1 && int(lalr17Exca[xi+1]) == lalr17state {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			lalr17n = int(lalr17Exca[xi+0])
			if lalr17n < 0 || lalr17n == lalr17token {
				break
			}
		}
		lalr17n = int(lalr17Exca[xi+1])
		if lalr17n < 0 {
			goto ret0
		}
	}
	if lalr17n == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			lalr17lex.Error(lalr17ErrorMessage(lalr17state, lalr17token))
			Nerrs++
			if lalr17Debug >= 1 {
				__yyfmt__.Printf("%s", lalr17Statname(lalr17state))
				__yyfmt__.Printf(" saw %s\n", lalr17Tokname(lalr17token))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for lalr17p >= 0 {
				lalr17n = int(lalr17Pact[lalr17S[lalr17p].yys]) + lalr17ErrCode
				if lalr17n >= 0 && lalr17n < lalr17Last {
					lalr17state = int(lalr17Act[lalr17n]) /* simulate a shift of "error" */
					if int(lalr17Chk[lalr17state]) == lalr17ErrCode {
						goto lalr17stack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if lalr17Debug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", lalr17S[lalr17p].yys)
				}
				lalr17p--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if lalr17Debug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", lalr17Tokname(lalr17token))
			}
			if lalr17token == lalr17EofCode {
				goto ret1
			}
			lalr17rcvr.char = -1
			lalr17token = -1
			goto lalr17newstate /* try again in the same state */
		}
	}

	/* reduction by production lalr17n */
	if lalr17Debug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", lalr17n, lalr17Statname(lalr17state))
	}

	lalr17nt := lalr17n
	lalr17pt := lalr17p
	_ = lalr17pt // guard against "declared and not used"

	lalr17p -= int(lalr17R2[lalr17n])
	// lalr17p is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if lalr17p+1 >= len(lalr17S) {
		nyys := make([]lalr17SymType, len(lalr17S)*2)
		copy(nyys, lalr17S)
		lalr17S = nyys
	}
	lalr17VAL = lalr17S[lalr17p+1]

	/* consult goto table to find next state */
	lalr17n = int(lalr17R1[lalr17n])
	lalr17g := int(lalr17Pgo[lalr17n])
	lalr17j := lalr17g + lalr17S[lalr17p].yys + 1

	if lalr17j >= lalr17Last {
		lalr17state = int(lalr17Act[lalr17g])
	} else {
		lalr17state = int(lalr17Act[lalr17j])
		if int(lalr17Chk[lalr17state]) != -lalr17n {
			lalr17state = int(lalr17Act[lalr17g])
		}
	}
	// dummy call; replaced with literal code
	switch lalr17nt {

	case 1:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:130
		{
			lalr17lex.(*lalr17LexAdapter).result = lalr17Dollar[1].node
		}
	case 2:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:134
		{
			lalr17lex.(*lalr17LexAdapter).result = lalr17Dollar[1].node
		}
	case 3:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:138
		{
			lalr17lex.(*lalr17LexAdapter).result = lalr17Dollar[1].node
		}
	case 4:
		lalr17Dollar = lalr17S[lalr17pt-4 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:143
		{
			lalr17lex.(*lalr17LexAdapter).result = lalr17Acfg(lalr17lex).NewTacticTactic(lalr17Dollar[2].node, lalr17Dollar[3].node, lalr17Dollar[4].node)
		}
	case 5:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:148
		{
			lalr17lex.(*lalr17LexAdapter).result = lalr17Acfg(lalr17lex).NewProofTactic(lalr17Acfg(lalr17lex).NewAtom(lalr17Dollar[2].str), lalr17Dollar[3].node)
		}
	case 6:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:157
		{
			lalr17VAL.str = lalr17Dollar[1].str
		}
	case 7:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:164
		{
			lalr17VAL.str = lalr17Dollar[1].str
		}
	case 8:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:168
		{
			lalr17VAL.str = "this"
		}
	case 9:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:172
		{
			lalr17VAL.str = lalr17Dollar[1].str + "." + lalr17Dollar[3].str
		}
	case 10:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:181
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewSymbol(lalr17Dollar[1].str, nil)
		}
	case 11:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:185
		{
			if _, ok := lalr17Dollar[1].node.(*This); ok {
				lalr17VAL.node = lalr17Acfg(lalr17lex).NewSymbol(lalr17Dollar[3].str, nil)
			} else if sym, ok := lalr17Dollar[1].node.(*Symbol); ok {
				lalr17VAL.node = lalr17Acfg(lalr17lex).NewSymbol(sym.Rep+"."+lalr17Dollar[3].str, nil)
			} else {
				lalr17VAL.node = lalr17Acfg(lalr17lex).NewSymbol(lalr17Dollar[3].str, nil)
			}
		}
	case 12:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:195
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewThis()
		}
	case 13:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:206
		{
			// Python: App(p[1]) — appelem produces App, not Atom.
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewApp(lalr17Acfg(lalr17lex).NewSymbol(lalr17Dollar[1].str, nil))
		}
	case 14:
		lalr17Dollar = lalr17S[lalr17pt-4 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:211
		{
			// Python: App(p[1], p[3])
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewApp(lalr17Acfg(lalr17lex).NewSymbol(lalr17Dollar[1].str, nil), lalr17Dollar[3].nodes...)
		}
	case 15:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:221
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewVariable(lalr17Dollar[1].str, "")
		}
	case 16:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:225
		{
			v := lalr17Acfg(lalr17lex).NewVariable(lalr17Dollar[1].str, lalr17AtypeToString(lalr17Dollar[3].node))
			lalr17VAL.node = v
		}
	case 17:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:233
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewVariable(lalr17Dollar[1].str, "S")
		}
	case 18:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:237
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewVariable(lalr17Dollar[1].str, lalr17Dollar[3].str)
		}
	case 19:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:244
		{
			lalr17VAL.nodes = []Node{lalr17Dollar[1].node}
		}
	case 20:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:248
		{
			lalr17VAL.nodes = append(lalr17Dollar[1].nodes, lalr17Dollar[3].node)
		}
	case 21:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:255
		{
			lalr17VAL.nodes = []Node{lalr17Dollar[1].node}
		}
	case 22:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:259
		{
			lalr17VAL.nodes = append(lalr17Dollar[1].nodes, lalr17Dollar[3].node)
		}
	case 23:
		lalr17Dollar = lalr17S[lalr17pt-0 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:268
		{
			lalr17VAL.nodes = nil
		}
	case 24:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:272
		{
			lalr17VAL.nodes = []Node{lalr17Dollar[1].node}
		}
	case 25:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:276
		{
			lalr17VAL.nodes = append(lalr17Dollar[1].nodes, lalr17Dollar[3].node)
		}
	case 26:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:285
		{
			lalr17VAL.node = lalr17Dollar[1].node
		}
	case 27:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:289
		{
			lalr17VAL.node = lalr17Dollar[1].node
		}
	case 28:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:293
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewOld(lalr17Dollar[2].node)
		}
	case 29:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:297
		{
			switch lhs := lalr17Dollar[1].node.(type) {
			case *Atom:
				rhs := lalr17Dollar[3].node.(*Atom)
				newRep := lhs.Rep + "." + rhs.Rep
				newTerms := make([]Node, 0, len(lhs.Terms)+len(rhs.Terms))
				newTerms = append(newTerms, lhs.Terms...)
				newTerms = append(newTerms, rhs.Terms...)
				lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom(newRep, newTerms...)
			case *Old:
				if inner, ok := lhs.Term.(*Atom); ok {
					rhs := lalr17Dollar[3].node.(*Atom)
					newRep := inner.Rep + "." + rhs.Rep
					newTerms := make([]Node, 0, len(inner.Terms)+len(rhs.Terms))
					newTerms = append(newTerms, inner.Terms...)
					newTerms = append(newTerms, rhs.Terms...)
					lhs.Term = lalr17Acfg(lalr17lex).NewAtom(newRep, newTerms...)
					lalr17VAL.node = lhs
				} else {
					lalr17VAL.node = lalr17Acfg(lalr17lex).NewMethodCall(lalr17Dollar[1].node, lalr17Dollar[3].node)
				}
			default:
				lalr17VAL.node = lalr17Acfg(lalr17lex).NewMethodCall(lalr17Dollar[1].node, lalr17Dollar[3].node)
			}
		}
	case 30:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:323
		{
			lalr17VAL.node = lalr17Dollar[2].node
		}
	case 31:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:328
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewApp(lalr17Acfg(lalr17lex).NewSymbol("+", nil), lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 32:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:332
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewApp(lalr17Acfg(lalr17lex).NewSymbol("-", nil), lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 33:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:336
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewApp(lalr17Acfg(lalr17lex).NewSymbol("*", nil), lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 34:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:340
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewApp(lalr17Acfg(lalr17lex).NewSymbol("/", nil), lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 35:
		lalr17Dollar = lalr17S[lalr17pt-5 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:345
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewIte(lalr17Dollar[3].node, lalr17Dollar[1].node, lalr17Dollar[5].node)
		}
	case 36:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:350
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom("=", lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 37:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:354
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom("<=", lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 38:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:358
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom("<", lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 39:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:362
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom(">=", lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 40:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:366
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom(">", lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 41:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:370
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewApp(lalr17Acfg(lalr17lex).NewSymbol("*>", nil), lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 42:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:374
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewNot(lalr17Acfg(lalr17lex).NewAtom("=", lalr17Dollar[1].node, lalr17Dollar[3].node))
		}
	case 43:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:379
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAnd()
		}
	case 44:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:383
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewOr()
		}
	case 45:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:387
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewNot(lalr17Dollar[2].node)
		}
	case 46:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:391
		{
			// Python: if isinstance(p[1], And): p[0] = p[1]; p[0].args.append(p[3])
			//         else: p[0] = And(p[1], p[3])
			// This flattens left-associative chains and absorbs true (And{}) identity.
			if a, ok := lalr17Dollar[1].node.(*And); ok {
				a.Terms = append(a.Terms, lalr17Dollar[3].node)
				lalr17VAL.node = a
			} else {
				lalr17VAL.node = lalr17Acfg(lalr17lex).NewAnd(lalr17Dollar[1].node, lalr17Dollar[3].node)
			}
		}
	case 47:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:403
		{
			// Python: if isinstance(p[1], Or): p[0] = p[1]; p[0].args.append(p[3])
			//         else: p[0] = Or(p[1], p[3])
			if o, ok := lalr17Dollar[1].node.(*Or); ok {
				o.Terms = append(o.Terms, lalr17Dollar[3].node)
				lalr17VAL.node = o
			} else {
				lalr17VAL.node = lalr17Acfg(lalr17lex).NewOr(lalr17Dollar[1].node, lalr17Dollar[3].node)
			}
		}
	case 48:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:414
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewImplies(lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 49:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:418
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewIff(lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 50:
		lalr17Dollar = lalr17S[lalr17pt-4 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:423
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewForall(lalr17Dollar[2].nodes, lalr17Dollar[4].node)
		}
	case 51:
		lalr17Dollar = lalr17S[lalr17pt-4 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:427
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewExists(lalr17Dollar[2].nodes, lalr17Dollar[4].node)
		}
	case 52:
		lalr17Dollar = lalr17S[lalr17pt-5 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:431
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewForall(lalr17Dollar[3].nodes, lalr17Dollar[5].node)
		}
	case 53:
		lalr17Dollar = lalr17S[lalr17pt-5 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:435
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewExists(lalr17Dollar[3].nodes, lalr17Dollar[5].node)
		}
	case 54:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:440
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewGlobally(lalr17Dollar[2].node)
		}
	case 55:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:444
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewEventually(lalr17Dollar[2].node)
		}
	case 56:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:448
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewWhenOperator("next", lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 57:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:452
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewWhenOperator("prev", lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 58:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:456
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewWhenOperator("first", lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 59:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:460
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewWhenOperator("last", lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 60:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:465
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewIsa(lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 61:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:470
		{
			if v, ok := lalr17Dollar[1].node.(*Variable); ok {
				v.VSort = lalr17AtypeToString(lalr17Dollar[3].node)
			}
			lalr17VAL.node = lalr17Dollar[1].node
		}
	case 62:
		lalr17Dollar = lalr17S[lalr17pt-10 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:478
		{
			binder := lalr17Acfg(lalr17lex).NewNamedBinder(lalr17Dollar[3].str, lalr17Dollar[4].nodes, lalr17Dollar[6].node)
			//binder.SetLineno(getLineno(lalr17lex))
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewApp(binder, lalr17Dollar[9].nodes...)
			//$$.(*App).SetLineno(getLineno(lalr17lex))
		}
	case 63:
		lalr17Dollar = lalr17S[lalr17pt-4 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:485
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewNamedBinder(lalr17Dollar[2].str, nil, lalr17Dollar[4].node)
		}
	case 64:
		lalr17Dollar = lalr17S[lalr17pt-4 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:489
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewNamedBinder(lalr17Dollar[2].str, nil, lalr17Dollar[4].node)
		}
	case 65:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:498
		{
			// Python: app_to_atom(p[1]) — convert top-level App to Atom in formula position.
			lalr17VAL.node = AppToAtom(lalr17Dollar[1].node)
		}
	case 66:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:510
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewLabeledFormula(nil, lalr17Dollar[1].node)
		}
	case 67:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:523
		{
			a := lalr17Acfg(lalr17lex).NewAtom(lalr17Dollar[1].str)
			lalr17VAL.node = a
		}
	case 68:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:528
		{
			a := lalr17Acfg(lalr17lex).NewAtom(lalr17Dollar[1].str)
			a.ASort = lalr17Dollar[3].node
			lalr17VAL.node = a
		}
	case 69:
		lalr17Dollar = lalr17S[lalr17pt-4 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:534
		{
			// Ghost parameter: ^name : type
			a := lalr17Acfg(lalr17lex).NewAtom(lalr17Dollar[2].str)
			a.ASort = lalr17Dollar[4].node
			lalr17VAL.node = a
		}
	case 70:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:544
		{
			lalr17VAL.nodes = []Node{lalr17Dollar[1].node}
		}
	case 71:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:548
		{
			lalr17VAL.nodes = append(lalr17Dollar[1].nodes, lalr17Dollar[3].node)
		}
	case 72:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:557
		{
			a := lalr17Acfg(lalr17lex).NewAtom(lalr17Dollar[1].str)
			a.ASort = lalr17Dollar[3].node
			lalr17VAL.node = a
		}
	case 73:
		lalr17Dollar = lalr17S[lalr17pt-4 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:563
		{
			a := lalr17Acfg(lalr17lex).NewAtom(lalr17Dollar[2].str)
			a.ASort = lalr17Dollar[4].node
			lalr17VAL.node = a
		}
	case 74:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:572
		{
			lalr17VAL.nodes = []Node{lalr17Dollar[1].node}
		}
	case 75:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:576
		{
			lalr17VAL.nodes = append(lalr17Dollar[1].nodes, lalr17Dollar[3].node)
		}
	case 76:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:585
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAnd()
		}
	case 77:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:589
		{
			lalr17VAL.node = lalr17MakeSequence(lalr17Acfg(lalr17lex), lalr17Dollar[2].nodes)
		}
	case 78:
		lalr17Dollar = lalr17S[lalr17pt-4 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:593
		{
			lalr17VAL.node = lalr17MakeSequence(lalr17Acfg(lalr17lex), lalr17Dollar[2].nodes)
		}
	case 79:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:600
		{
			lalr17VAL.nodes = []Node{lalr17Dollar[1].node}
		}
	case 80:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:604
		{
			lalr17VAL.nodes = append(lalr17Dollar[1].nodes, lalr17Dollar[3].node)
		}
	case 81:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:608
		{
			// complexact after complexact (no semicolon needed)
			lalr17VAL.nodes = append(lalr17Dollar[1].nodes, lalr17Dollar[2].node)
		}
	case 82:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:616
		{
			lalr17VAL.node = lalr17Dollar[1].node
		}
	case 83:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:620
		{
			lalr17VAL.node = lalr17Dollar[1].node
		}
	case 84:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:629
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom("assume", lalr17Dollar[2].node)
		}
	case 85:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:633
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom("assert", lalr17Dollar[2].node)
		}
	case 86:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:637
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom("require", lalr17Dollar[2].node)
		}
	case 87:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:641
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom("ensure", lalr17Dollar[2].node)
		}
	case 88:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:645
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom(":=", lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 89:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:649
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom("havoc", lalr17Dollar[1].node)
		}
	case 90:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:653
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewVarAction(lalr17Dollar[2].node)
		}
	case 91:
		lalr17Dollar = lalr17S[lalr17pt-4 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:657
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewVarAction(lalr17Dollar[2].node, lalr17Dollar[4].node)
		}
	case 92:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:661
		{
			// Simple call: call f(x)
			lalr17VAL.node = lalr17Dollar[2].node
		}
	case 93:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:666
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom("instantiate", lalr17Dollar[2].node)
		}
	case 94:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:670
		{
			// When check_unprovable is False (default), unprovable statements are no-ops
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAnd()
		}
	case 95:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:675
		{
			// Bare expression (procedure call)
			lalr17VAL.node = lalr17Dollar[1].node
		}
	case 96:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:685
		{
			lalr17VAL.node = lalr17Dollar[1].node
		}
	case 97:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:689
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewIte(lalr17Dollar[2].node, lalr17Dollar[3].node, lalr17Acfg(lalr17lex).NewAnd())
		}
	case 98:
		lalr17Dollar = lalr17S[lalr17pt-5 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:693
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewIte(lalr17Dollar[2].node, lalr17Dollar[3].node, lalr17Dollar[5].node)
		}
	case 99:
		lalr17Dollar = lalr17S[lalr17pt-5 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:697
		{
			// ChoiceAction: if * { ... } else { ... }
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewIte(lalr17Acfg(lalr17lex).NewSymbol("*", nil), lalr17Dollar[3].node, lalr17Dollar[5].node)
		}
	case 100:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:702
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom("while", lalr17Dollar[2].node, lalr17Dollar[3].node)
		}
	case 101:
		lalr17Dollar = lalr17S[lalr17pt-5 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:706
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom("while", lalr17Dollar[2].node, lalr17Dollar[5].node)
		}
	case 102:
		lalr17Dollar = lalr17S[lalr17pt-7 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:710
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom("for", lalr17Dollar[2].node, lalr17Dollar[4].node, lalr17Dollar[6].node, lalr17Dollar[7].node)
		}
	case 103:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:714
		{
			args := append(lalr17Dollar[2].nodes, lalr17Dollar[3].node)
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom("local", args...)
		}
	case 104:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:719
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAtom("let", lalr17Dollar[2].node, lalr17Dollar[3].node)
		}
	case 105:
		lalr17Dollar = lalr17S[lalr17pt-6 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:730
		{
			elems := append([]Node{lalr17Dollar[3].node}, lalr17Dollar[5].nodes...)
			sdef := lalr17Acfg(lalr17lex).NewScenarioDef(elems)
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewScenarioDecl(sdef)
		}
	case 106:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:739
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewPlaceList(lalr17Dollar[2].nodes)
		}
	case 107:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:746
		{
			lalr17VAL.nodes = []Node{lalr17Acfg(lalr17lex).NewAtom(lalr17Dollar[1].str)}
		}
	case 108:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:750
		{
			lalr17VAL.nodes = append(lalr17Dollar[1].nodes, lalr17Acfg(lalr17lex).NewAtom(lalr17Dollar[3].str))
		}
	case 109:
		lalr17Dollar = lalr17S[lalr17pt-0 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:757
		{
			lalr17VAL.nodes = nil
		}
	case 110:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:761
		{
			lalr17VAL.nodes = append(lalr17Dollar[1].nodes, lalr17Dollar[2].node)
		}
	case 111:
		lalr17Dollar = lalr17S[lalr17pt-5 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:768
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewScenarioTransition(lalr17Acfg(lalr17lex).NewPlaceList(lalr17Dollar[1].nodes), lalr17Acfg(lalr17lex).NewPlaceList(lalr17Dollar[3].nodes), lalr17Dollar[5].node)
		}
	case 112:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:772
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewScenarioTransition(lalr17Acfg(lalr17lex).NewPlaceList(lalr17Dollar[1].nodes), lalr17Acfg(lalr17lex).NewPlaceList(nil), lalr17Dollar[3].node)
		}
	case 113:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:779
		{
			atom := lalr17Acfg(lalr17lex).NewAtom(lalr17Dollar[2].node.(*Symbol).Rep)
			lalrLabelCounter++
			mixerName := fmt.Sprintf("%s[before%d]", atom.Rep, lalrLabelCounter)
			mixer := lalr17Acfg(lalr17lex).NewAtom(mixerName)
			adef := lalr17Acfg(lalr17lex).NewActionDef(atom, lalr17Dollar[3].node, nil, nil)
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewScenarioBeforeMixin(mixer, adef)
		}
	case 114:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:788
		{
			atom := lalr17Acfg(lalr17lex).NewAtom(lalr17Dollar[2].node.(*Symbol).Rep)
			lalrLabelCounter++
			mixerName := fmt.Sprintf("%s[after%d]", atom.Rep, lalrLabelCounter)
			mixer := lalr17Acfg(lalr17lex).NewAtom(mixerName)
			adef := lalr17Acfg(lalr17lex).NewActionDef(atom, lalr17Dollar[3].node, nil, nil)
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewScenarioAfterMixin(mixer, adef)
		}
	case 115:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:807
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewDefinition(lalr17Dollar[1].node, lalr17Dollar[3].node)
		}
	case 116:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:815
		{
			lalr17VAL.nodes = []Node{lalr17Dollar[1].node}
		}
	case 117:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:819
		{
			lalr17VAL.nodes = append(lalr17Dollar[1].nodes, lalr17Dollar[3].node)
		}
	case 118:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:827
		{
			lalr17VAL.node = lalr17Dollar[2].node
		}
	case 119:
		lalr17Dollar = lalr17S[lalr17pt-4 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:831
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewDefinition(lalr17Dollar[2].node, lalr17Dollar[4].node)
		}
	case 120:
		lalr17Dollar = lalr17S[lalr17pt-4 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:835
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewTrigger(nil, append([]Node{lalr17Dollar[2].node}, lalr17Dollar[4].nodes...)...)
		}
	case 121:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:843
		{
			lalr17VAL.nodes = []Node{lalr17Dollar[1].node}
		}
	case 122:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:847
		{
			lalr17VAL.nodes = append(lalr17Dollar[1].nodes, lalr17Dollar[2].node)
		}
	case 123:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:855
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewTacticWith(lalr17Dollar[1].nodes)
		}
	case 124:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:859
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewTacticLets(lalr17Dollar[1].nodes)
		}
	case 125:
		lalr17Dollar = lalr17S[lalr17pt-0 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:867
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewTacticWith(nil)
		}
	case 126:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:871
		{
			lalr17VAL.node = lalr17Dollar[2].node
		}
	case 127:
		lalr17Dollar = lalr17S[lalr17pt-4 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:875
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewTacticWith(lalr17Dollar[3].nodes)
		}
	case 128:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:883
		{
			lalr17VAL.node = lalr17Dollar[2].node
		}
	case 129:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:887
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewNullTactic()
		}
	case 130:
		lalr17Dollar = lalr17S[lalr17pt-0 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:895
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewNoneAST()
		}
	case 131:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:899
		{
			lalr17VAL.node = lalr17Dollar[1].node
		}
	case 132:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:907
		{
			lalr17VAL.node = lalr17Dollar[1].node
		}
	case 133:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:911
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewComposeTactics([]Node{lalr17Dollar[1].node, lalr17Dollar[3].node})
		}
	case 134:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:915
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewComposeTactics([]Node{lalr17Dollar[1].node, lalr17Dollar[2].node})
		}
	case 135:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:924
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewSchemaInstantiation(lalr17Dollar[2].node, lalr17Acfg(lalr17lex).NewNoneAST())
		}
	case 136:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:929
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewAssumeTactic(lalr17Dollar[2].node, lalr17Acfg(lalr17lex).NewNoneAST())
		}
	case 137:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:934
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewShowGoalsTactic()
		}
	case 138:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:939
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewDeferGoalTactic()
		}
	case 139:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:944
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewSpoilTactic(lalr17Dollar[2].node)
		}
	case 140:
		lalr17Dollar = lalr17S[lalr17pt-4 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:949
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewTacticTactic(lalr17Dollar[2].node, lalr17Dollar[3].node, lalr17Dollar[4].node)
		}
	case 141:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:954
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewPropertyTactic(lalr17Dollar[2].node, lalr17Acfg(lalr17lex).NewNoneAST(), lalr17Dollar[3].node)
		}
	case 142:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:959
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewFunctionTactic([]Node{lalr17Dollar[2].node})
		}
	case 143:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:964
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewProofTactic(lalr17Acfg(lalr17lex).NewAtom(lalr17Dollar[2].str), lalr17Dollar[3].node)
		}
	case 144:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:969
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewLetTactic(lalr17Dollar[2].nodes)
		}
	case 145:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:974
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewWitnessTactic(lalr17Dollar[3].nodes)
		}
	case 146:
		lalr17Dollar = lalr17S[lalr17pt-5 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:979
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewIfTactic(lalr17Dollar[2].node, lalr17Dollar[3].node, lalr17Dollar[5].node)
		}
	case 147:
		lalr17Dollar = lalr17S[lalr17pt-3 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:984
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewUnfoldTactic(lalr17Acfg(lalr17lex).NewNoneAST(), []Node{lalr17Dollar[3].node})
		}
	case 148:
		lalr17Dollar = lalr17S[lalr17pt-2 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:989
		{
			lalr17VAL.node = lalr17Acfg(lalr17lex).NewForgetTactic([]Node{lalr17Dollar[2].node})
		}
	case 149:
		lalr17Dollar = lalr17S[lalr17pt-1 : lalr17pt+1]
//line lalr_logicparser_grammar_v17.y:994
		{
			lalr17VAL.node = lalr17Dollar[1].node
		}
	}
	goto lalr17stack /* stack new state and value */
}
