package goivy

import "fmt"

// TokenType identifies the kind of token.
type TokenType int

const (
	// Special
	EOF TokenType = iota
	ERROR

	// Punctuation
	COMMA     // ,
	LPAREN    // (
	RPAREN    // )
	LCB       // {
	RCB       // }
	LB        // [
	RB        // ]
	SEMI      // ;
	COLON     // :
	DOT       // .
	DOTS      // ..
	DOTDOTDOT // ...

	// Operators
	PLUS    // +
	MINUS   // -
	TIMES   // *
	DIV     // /
	EQ      // =
	TILDAEQ // ~=
	TILDA   // ~
	LE      // <=
	LT      // <
	GE      // >=
	GT      // >
	AND     // &
	OR      // |
	ARROW   // ->
	IFF     // <->
	ASSIGN  // :=
	PTO     // *>
	DOLLAR  // $
	CARET   // ^

	// Identifiers / Literals
	SYMBOL      // lowercase identifier or quoted string
	VARIABLE    // uppercase identifier
	NATIVEQUOTE // <<<...>>>

	// Keywords (reserved words map to these)
	RELATION
	INDIV
	FUNCTION
	AXIOM
	CONJECTURE
	SCHEMA
	INSTANTIATE
	DERIVED
	CONCEPT
	INIT
	ACTION
	METHOD
	FIELD
	STATE
	ASSUME
	ASSERT
	SET
	NULL
	OLD
	FROM
	UPDATE
	PARAMS
	IN
	MATCH
	ENSURES
	REQUIRES
	MODIFIES
	TRUE
	FALSE
	FRESH
	MODULE
	OBJECT
	CLASS
	TYPE
	IF
	ELSE
	LOCAL
	LET
	CALL
	ENTRY
	MACRO
	INTERPRET
	FORALL
	EXISTS
	RETURNS
	MIXIN
	BEFORE
	AFTER
	ISOLATE
	WITH
	EXPORT
	DELEGATE
	IMPORT
	USING
	INCLUDE
	PROGRESS
	RELY
	MIXORD
	EXTRACT
	DESTRUCTOR
	SOME
	MAXIMIZING
	MINIMIZING
	PRIVATE
	IMPLEMENT
	PROPERTY
	WHILE
	INVARIANT
	STRUCT
	DEFINITION
	GHOST
	ALIAS
	TRUSTED
	THIS
	VAR
	ATTRIBUTE
	VARIANT
	OF
	SCENARIO
	PROOF
	NAMED
	TEMPORAL
	GLOBALLY
	EVENTUALLY
	DECREASES
	SPECIFICATION
	IMPLEMENTATION
	GLOBAL
	COMMON
	ENSURE
	REQUIRE
	AROUND
	PARAMETER
	APPLY
	THEOREM
	SHOWGOALS
	DEFERGOAL
	SPOIL
	EXPLICIT
	THUNK
	ISA
	AUTOINSTANCE
	CONSTRUCTOR
	FINITE
	TACTIC
	UNFOLD
	FORGET
	DEBUG
	FOR
	SUBCLASS
	WHENFIRST
	WHENLAST
	WHENPREV
	WHENNEXT
	UNPROVABLE
	TRIGGER
)

// tokenNames maps token types to their display names.
var tokenNames = map[TokenType]string{
	EOF: "EOF", ERROR: "ERROR",
	COMMA: "COMMA", LPAREN: "LPAREN", RPAREN: "RPAREN",
	LCB: "LCB", RCB: "RCB", LB: "LB", RB: "RB",
	SEMI: "SEMI", COLON: "COLON", DOT: "DOT", DOTS: "DOTS", DOTDOTDOT: "DOTDOTDOT",
	PLUS: "PLUS", MINUS: "MINUS", TIMES: "TIMES", DIV: "DIV",
	EQ: "EQ", TILDAEQ: "TILDAEQ", TILDA: "TILDA",
	LE: "LE", LT: "LT", GE: "GE", GT: "GT",
	AND: "AND", OR: "OR", ARROW: "ARROW", IFF: "IFF",
	ASSIGN: "ASSIGN", PTO: "PTO", DOLLAR: "DOLLAR", CARET: "CARET",
	SYMBOL: "SYMBOL", VARIABLE: "VARIABLE", NATIVEQUOTE: "NATIVEQUOTE",
	RELATION: "RELATION", INDIV: "INDIV", FUNCTION: "FUNCTION",
	AXIOM: "AXIOM", CONJECTURE: "CONJECTURE", SCHEMA: "SCHEMA",
	INSTANTIATE: "INSTANTIATE", DERIVED: "DERIVED", CONCEPT: "CONCEPT",
	INIT: "INIT", ACTION: "ACTION", METHOD: "METHOD", FIELD: "FIELD",
	STATE: "STATE", ASSUME: "ASSUME", ASSERT: "ASSERT",
	SET: "SET", NULL: "NULL", OLD: "OLD", FROM: "FROM",
	UPDATE: "UPDATE", PARAMS: "PARAMS", IN: "IN", MATCH: "MATCH",
	ENSURES: "ENSURES", REQUIRES: "REQUIRES", MODIFIES: "MODIFIES",
	TRUE: "TRUE", FALSE: "FALSE", FRESH: "FRESH",
	MODULE: "MODULE", OBJECT: "OBJECT", CLASS: "CLASS", TYPE: "TYPE",
	IF: "IF", ELSE: "ELSE", LOCAL: "LOCAL", LET: "LET",
	CALL: "CALL", ENTRY: "ENTRY", MACRO: "MACRO", INTERPRET: "INTERPRET",
	FORALL: "FORALL", EXISTS: "EXISTS", RETURNS: "RETURNS",
	MIXIN: "MIXIN", BEFORE: "BEFORE", AFTER: "AFTER",
	ISOLATE: "ISOLATE", WITH: "WITH", EXPORT: "EXPORT",
	DELEGATE: "DELEGATE", IMPORT: "IMPORT", USING: "USING", INCLUDE: "INCLUDE",
	PROGRESS: "PROGRESS", RELY: "RELY", MIXORD: "MIXORD", EXTRACT: "EXTRACT",
	DESTRUCTOR: "DESTRUCTOR", SOME: "SOME",
	MAXIMIZING: "MAXIMIZING", MINIMIZING: "MINIMIZING",
	PRIVATE: "PRIVATE", IMPLEMENT: "IMPLEMENT", PROPERTY: "PROPERTY",
	WHILE: "WHILE", INVARIANT: "INVARIANT", STRUCT: "STRUCT",
	DEFINITION: "DEFINITION", GHOST: "GHOST", ALIAS: "ALIAS",
	TRUSTED: "TRUSTED", THIS: "THIS", VAR: "VAR",
	ATTRIBUTE: "ATTRIBUTE", VARIANT: "VARIANT", OF: "OF",
	SCENARIO: "SCENARIO", PROOF: "PROOF", NAMED: "NAMED",
	TEMPORAL: "TEMPORAL", GLOBALLY: "GLOBALLY", EVENTUALLY: "EVENTUALLY",
	DECREASES: "DECREASES", SPECIFICATION: "SPECIFICATION",
	IMPLEMENTATION: "IMPLEMENTATION", GLOBAL: "GLOBAL", COMMON: "COMMON",
	ENSURE: "ENSURE", REQUIRE: "REQUIRE", AROUND: "AROUND",
	PARAMETER: "PARAMETER", APPLY: "APPLY", THEOREM: "THEOREM",
	SHOWGOALS: "SHOWGOALS", DEFERGOAL: "DEFERGOAL", SPOIL: "SPOIL",
	EXPLICIT: "EXPLICIT", THUNK: "THUNK", ISA: "ISA",
	AUTOINSTANCE: "AUTOINSTANCE", CONSTRUCTOR: "CONSTRUCTOR",
	FINITE: "FINITE", TACTIC: "TACTIC", UNFOLD: "UNFOLD", FORGET: "FORGET",
	DEBUG: "DEBUG", FOR: "FOR", SUBCLASS: "SUBCLASS",
	WHENFIRST: "WHENFIRST", WHENLAST: "WHENLAST",
	WHENPREV: "WHENPREV", WHENNEXT: "WHENNEXT",
	UNPROVABLE: "UNPROVABLE", TRIGGER: "TRIGGER",
}

func (t TokenType) String() string {
	if name, ok := tokenNames[t]; ok {
		return name
	}
	return fmt.Sprintf("TokenType(%d)", int(t))
}

// Token represents a single lexical token.
type Token struct {
	Type   TokenType
	Value  string
	Line   int
	Column int
}

func (t Token) String() string {
	return fmt.Sprintf("%s(%q) at %d:%d", t.Type, t.Value, t.Line, t.Column)
}
