// Code generated by goyacc -o parser_grammar_v16.go -p parser16 parser_grammar_v16.y. DO NOT EDIT.

//line parser_grammar_v16.y:8
package goivy

import __yyfmt__ "fmt"

//line parser_grammar_v16.y:8

import "github.com/glycerine/ivy/goivy/xtracer"

//line parser_grammar_v16.y:14
type parser16SymType struct {
	yys   int
	node  Node
	nodes []Node
	str   string
	tok   TokenInfo
	bval  bool
	accum *ivyAccum
}

const PARSER16_TOK_PRESYMBOL = 57346
const PARSER16_TOK_VARIABLE = 57347
const PARSER16_TOK_LPAREN = 57348
const PARSER16_TOK_RPAREN = 57349
const PARSER16_TOK_LB = 57350
const PARSER16_TOK_RB = 57351
const PARSER16_TOK_LCB = 57352
const PARSER16_TOK_RCB = 57353
const PARSER16_TOK_COMMA = 57354
const PARSER16_TOK_SEMI = 57355
const PARSER16_TOK_COLON = 57356
const PARSER16_TOK_DOT = 57357
const PARSER16_TOK_PLUS = 57358
const PARSER16_TOK_MINUS = 57359
const PARSER16_TOK_TIMES = 57360
const PARSER16_TOK_DIV = 57361
const PARSER16_TOK_EQ = 57362
const PARSER16_TOK_TILDAEQ = 57363
const PARSER16_TOK_TILDA = 57364
const PARSER16_TOK_LE = 57365
const PARSER16_TOK_LT = 57366
const PARSER16_TOK_GE = 57367
const PARSER16_TOK_GT = 57368
const PARSER16_TOK_AND = 57369
const PARSER16_TOK_OR = 57370
const PARSER16_TOK_ARROW = 57371
const PARSER16_TOK_IFF = 57372
const PARSER16_TOK_PTO = 57373
const PARSER16_TOK_DOLLAR = 57374
const PARSER16_TOK_ASSIGN = 57375
const PARSER16_TOK_FORALL = 57376
const PARSER16_TOK_EXISTS = 57377
const PARSER16_TOK_TRUE = 57378
const PARSER16_TOK_FALSE = 57379
const PARSER16_TOK_OLD = 57380
const PARSER16_TOK_THIS = 57381
const PARSER16_TOK_IF = 57382
const PARSER16_TOK_ELSE = 57383
const PARSER16_TOK_GLOBALLY = 57384
const PARSER16_TOK_EVENTUALLY = 57385
const PARSER16_TOK_TYPE = 57386
const PARSER16_TOK_INDIV = 57387
const PARSER16_TOK_VAR = 57388
const PARSER16_TOK_FUNCTION = 57389
const PARSER16_TOK_RELATION = 57390
const PARSER16_TOK_DERIVED = 57391
const PARSER16_TOK_AXIOM = 57392
const PARSER16_TOK_PROPERTY = 57393
const PARSER16_TOK_CONJECTURE = 57394
const PARSER16_TOK_ASSERT = 57395
const PARSER16_TOK_DEFINITION = 57396
const PARSER16_TOK_PROOF = 57397
const PARSER16_TOK_WITH = 57398
const PARSER16_TOK_INIT = 57399
const PARSER16_TOK_INCLUDE = 57400
const PARSER16_TOK_ACTION = 57401
const PARSER16_TOK_CALL = 57402
const PARSER16_TOK_IMPORT = 57403
const PARSER16_TOK_EXPORT = 57404
const PARSER16_TOK_PRIVATE = 57405
const PARSER16_TOK_MACRO = 57406
const PARSER16_TOK_ALIAS = 57407
const PARSER16_TOK_PROGRESS = 57408
const PARSER16_TOK_RELY = 57409
const PARSER16_TOK_MIXORD = 57410

var parser16Toknames = [...]string{
	"$end",
	"error",
	"$unk",
	"PARSER16_TOK_PRESYMBOL",
	"PARSER16_TOK_VARIABLE",
	"PARSER16_TOK_LPAREN",
	"PARSER16_TOK_RPAREN",
	"PARSER16_TOK_LB",
	"PARSER16_TOK_RB",
	"PARSER16_TOK_LCB",
	"PARSER16_TOK_RCB",
	"PARSER16_TOK_COMMA",
	"PARSER16_TOK_SEMI",
	"PARSER16_TOK_COLON",
	"PARSER16_TOK_DOT",
	"PARSER16_TOK_PLUS",
	"PARSER16_TOK_MINUS",
	"PARSER16_TOK_TIMES",
	"PARSER16_TOK_DIV",
	"PARSER16_TOK_EQ",
	"PARSER16_TOK_TILDAEQ",
	"PARSER16_TOK_TILDA",
	"PARSER16_TOK_LE",
	"PARSER16_TOK_LT",
	"PARSER16_TOK_GE",
	"PARSER16_TOK_GT",
	"PARSER16_TOK_AND",
	"PARSER16_TOK_OR",
	"PARSER16_TOK_ARROW",
	"PARSER16_TOK_IFF",
	"PARSER16_TOK_PTO",
	"PARSER16_TOK_DOLLAR",
	"PARSER16_TOK_ASSIGN",
	"PARSER16_TOK_FORALL",
	"PARSER16_TOK_EXISTS",
	"PARSER16_TOK_TRUE",
	"PARSER16_TOK_FALSE",
	"PARSER16_TOK_OLD",
	"PARSER16_TOK_THIS",
	"PARSER16_TOK_IF",
	"PARSER16_TOK_ELSE",
	"PARSER16_TOK_GLOBALLY",
	"PARSER16_TOK_EVENTUALLY",
	"PARSER16_TOK_TYPE",
	"PARSER16_TOK_INDIV",
	"PARSER16_TOK_VAR",
	"PARSER16_TOK_FUNCTION",
	"PARSER16_TOK_RELATION",
	"PARSER16_TOK_DERIVED",
	"PARSER16_TOK_AXIOM",
	"PARSER16_TOK_PROPERTY",
	"PARSER16_TOK_CONJECTURE",
	"PARSER16_TOK_ASSERT",
	"PARSER16_TOK_DEFINITION",
	"PARSER16_TOK_PROOF",
	"PARSER16_TOK_WITH",
	"PARSER16_TOK_INIT",
	"PARSER16_TOK_INCLUDE",
	"PARSER16_TOK_ACTION",
	"PARSER16_TOK_CALL",
	"PARSER16_TOK_IMPORT",
	"PARSER16_TOK_EXPORT",
	"PARSER16_TOK_PRIVATE",
	"PARSER16_TOK_MACRO",
	"PARSER16_TOK_ALIAS",
	"PARSER16_TOK_PROGRESS",
	"PARSER16_TOK_RELY",
	"PARSER16_TOK_MIXORD",
}

var parser16Statenames = [...]string{}

const parser16EofCode = 1
const parser16ErrCode = 2
const parser16InitialStackSize = 16

//line parser_grammar_v16.y:784

//line yacctab:1
var parser16Exca = [...]int8{
	-1, 1,
	1, -1,
	59, 34,
	-2, 32,
	-1, 33,
	20, 89,
	-2, 53,
}

const parser16Private = 57344

const parser16Last = 352

var parser16Act = [...]uint8{
	65, 181, 66, 203, 77, 146, 33, 40, 40, 40,
	45, 47, 45, 127, 53, 44, 116, 42, 47, 47,
	47, 32, 40, 34, 135, 40, 40, 49, 36, 38,
	79, 115, 71, 192, 128, 39, 27, 68, 133, 87,
	55, 35, 124, 52, 26, 29, 46, 50, 51, 94,
	95, 96, 97, 78, 78, 94, 69, 96, 97, 70,
	88, 27, 75, 184, 72, 73, 74, 209, 122, 98,
	67, 113, 190, 27, 114, 96, 97, 119, 120, 101,
	102, 33, 128, 27, 68, 133, 40, 126, 40, 45,
	47, 47, 182, 118, 92, 93, 48, 112, 34, 139,
	91, 141, 130, 27, 143, 142, 121, 148, 137, 149,
	150, 151, 152, 125, 39, 140, 86, 67, 157, 100,
	101, 102, 132, 84, 134, 136, 102, 47, 90, 179,
	40, 164, 99, 100, 101, 102, 144, 145, 30, 169,
	153, 154, 155, 156, 162, 158, 159, 165, 167, 198,
	90, 160, 94, 95, 96, 97, 103, 195, 175, 196,
	99, 100, 101, 102, 89, 136, 99, 100, 101, 102,
	174, 123, 40, 172, 178, 208, 191, 41, 186, 185,
	188, 161, 81, 47, 103, 129, 43, 87, 183, 162,
	103, 82, 163, 40, 85, 205, 200, 80, 206, 76,
	78, 94, 95, 96, 97, 147, 187, 171, 166, 40,
	204, 205, 210, 207, 99, 100, 101, 102, 193, 117,
	27, 194, 201, 54, 211, 199, 204, 129, 23, 197,
	3, 24, 25, 6, 5, 7, 176, 183, 13, 14,
	21, 177, 104, 15, 2, 27, 68, 18, 17, 19,
	11, 20, 8, 9, 10, 27, 68, 56, 180, 64,
	81, 170, 202, 37, 31, 27, 68, 56, 83, 82,
	131, 168, 16, 59, 189, 12, 173, 138, 22, 4,
	28, 1, 0, 59, 0, 60, 61, 57, 58, 67,
	0, 0, 0, 62, 63, 60, 61, 57, 58, 67,
	160, 0, 0, 62, 63, 0, 0, 0, 0, 99,
	100, 101, 102, 106, 105, 0, 107, 108, 109, 110,
	0, 0, 0, 0, 111, 0, 0, 99, 100, 101,
	102, 106, 105, 103, 107, 108, 109, 110, 0, 0,
	0, 0, 111, 0, 0, 0, 0, 0, 0, 0,
	0, 103,
}

var parser16Pact = [...]int16{
	-1000, 186, 216, 99, -1000, 216, 216, 216, 216, 216,
	57, 216, -3, 251, 216, 251, -27, 57, 57, 57,
	216, 216, -1000, -1000, 216, 216, -1000, -1000, -1000, -1000,
	-1000, 185, -1000, 254, -1000, -1000, 103, 182, -1000, 96,
	254, 175, -1000, 175, 31, 176, 135, 176, -1000, 80,
	251, 251, -1000, 125, 261, 311, 261, -1000, -1000, 261,
	214, 214, 261, 261, 216, 176, -1000, 216, 157, 13,
	-1000, 216, 113, 113, 113, 67, 27, 173, -1000, 173,
	216, 79, 216, 69, 261, 216, 261, 216, 216, 57,
	57, 195, -1000, -21, 261, 261, 261, 261, 125, 79,
	79, 79, 79, 261, 79, 79, -1000, -1000, -1000, -1000,
	-1000, -1000, 293, 174, 46, 177, -1000, 117, 132, 125,
	125, 199, 176, 69, 261, 201, 57, -1000, 216, 216,
	-1000, 229, 150, 79, -1000, 114, -1000, -1000, -1000, 125,
	-1000, 125, -1000, -1000, 113, 113, -1000, 32, -1000, 46,
	28, 125, 125, 102, 61, 107, -1000, 22, 150, 150,
	-1000, -1000, 214, 261, 216, 261, -1000, 114, -1000, 125,
	52, 216, 113, -1000, -23, -1000, -1000, 79, 144, 216,
	146, -1000, 57, 116, 79, -1000, 125, -1000, 125, -1000,
	195, 215, 241, 150, -1000, -1000, 32, 113, 261, 198,
	-1000, -1000, 163, -1000, -1000, 47, -1000, 125, 241, 261,
	-1000, 125,
}

var parser16Pgo = [...]int16{
	0, 281, 43, 14, 40, 0, 2, 16, 24, 28,
	280, 279, 278, 21, 29, 17, 277, 13, 276, 3,
	275, 274, 5, 1, 46, 15, 272, 271, 270, 270,
	31, 4, 264, 263, 177, 262, 261, 258, 242, 41,
	223,
}

var parser16R1 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 17, 17, 18, 18, 19, 19,
	35, 35, 20, 20, 26, 26, 26, 21, 21, 22,
	37, 37, 37, 23, 23, 36, 36, 2, 2, 40,
	11, 12, 12, 13, 13, 32, 32, 14, 14, 33,
	33, 16, 15, 34, 34, 10, 10, 39, 8, 8,
	8, 5, 5, 5, 24, 24, 24, 25, 6, 6,
	7, 7, 29, 29, 30, 30, 28, 28, 28, 9,
	9, 31, 31, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 38, 38, 38, 38, 38, 38, 27, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3,
}

var parser16R2 = [...]int8{
	0, 0, 3, 3, 2, 3, 3, 3, 3, 5,
	3, 5, 5, 4, 5, 3, 5, 3, 6, 3,
	3, 3, 5, 4, 0, 2, 1, 3, 1, 3,
	1, 3, 0, 1, 0, 1, 1, 0, 2, 3,
	0, 1, 3, 2, 3, 0, 3, 1, 2, 3,
	1, 2, 2, 1, 1, 1, 3, 1, 3, 1,
	3, 1, 3, 1, 3, 1, 1, 1, 1, 3,
	1, 1, 4, 3, 1, 1, 3, 1, 1, 3,
	1, 3, 1, 3, 1, 3, 0, 1, 3, 1,
	3, 1, 3, 1, 1, 2, 3, 3, 3, 3,
	3, 5, 1, 1, 1, 1, 1, 1, 1, 1,
	3, 3, 3, 1, 1, 2, 3, 3, 3, 3,
	4, 4, 2, 2,
}

var parser16Chk = [...]int16{
	-1000, -1, 58, 44, -11, 48, 47, 49, 66, 67,
	68, 64, -20, 52, 53, 57, -26, 62, 61, 63,
	65, 54, -12, 42, 45, 46, -39, 4, -10, -39,
	39, -32, -13, -5, -15, -39, -9, -33, -14, -9,
	-5, -34, -15, -34, -25, -5, -24, -5, 39, -25,
	50, 51, -2, -3, -40, -4, 6, 36, 37, 22,
	34, 35, 42, 43, 8, -5, -6, 38, 5, -39,
	-2, 59, -24, -24, -24, -39, -34, -31, -9, -31,
	12, 6, 15, 14, 20, 12, 20, 12, 29, 29,
	15, 20, -2, -2, 27, 28, 29, 30, -3, 16,
	17, 18, 19, 40, -38, 21, 20, 23, 24, 25,
	26, 31, -4, -3, -3, -30, -7, 5, -30, -3,
	-3, -39, -5, 14, 29, -39, 20, -17, 55, 12,
	-13, -28, -4, 6, -39, -8, -39, 39, -16, -3,
	-14, -3, -15, -25, -24, -24, -22, 10, -17, -3,
	-3, -3, -3, -4, -4, -4, -4, -3, -4, -4,
	7, 7, 12, 15, 14, 15, 9, -8, -27, -3,
	-36, 6, -24, -18, -39, -9, 7, 12, -4, 15,
	-37, -23, 60, -4, 41, -7, -3, -39, -3, -21,
	20, -31, 56, -4, -39, 11, 13, -24, 33, -4,
	-22, 7, -35, -19, -15, -6, -23, -3, 12, 20,
	-19, -3,
}

var parser16Def = [...]int8{
	1, -2, 0, 0, 4, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 35, 36, 0,
	0, 0, 50, 33, 0, 0, 2, 67, 3, 65,
	66, 5, 55, -2, 54, 71, 0, 6, 59, 57,
	89, 7, 63, 8, 10, 77, 0, 74, 75, 0,
	0, 0, 15, 47, 0, 109, 0, 113, 114, 0,
	0, 0, 0, 0, 0, 93, 94, 0, 78, 0,
	17, 0, 19, 20, 21, 0, 24, 51, 91, 52,
	0, 86, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 13, 24, 0, 0, 0, 0, 48, 0,
	0, 0, 0, 0, 0, 0, 102, 103, 104, 105,
	106, 107, 109, 0, 115, 0, 84, 80, 0, 122,
	123, 0, 95, 0, 0, 45, 0, 23, 0, 0,
	56, 0, 87, 0, 73, 90, 68, 70, 62, 61,
	60, 58, 64, 9, 11, 76, 12, 40, 14, 116,
	117, 118, 119, 97, 98, 99, 100, 0, 110, 111,
	96, 112, 0, 0, 0, 0, 49, 79, 16, 108,
	37, 0, 22, 25, 26, 92, 72, 0, 0, 0,
	0, 41, 0, 0, 0, 85, 120, 81, 121, 18,
	0, 0, 0, 88, 69, 39, 0, 43, 0, 101,
	38, 46, 27, 30, 28, 0, 42, 44, 0, 0,
	31, 29,
}

var parser16Tok1 = [...]int8{
	1,
}

var parser16Tok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68,
}

var parser16Tok3 = [...]int8{
	0,
}

var parser16ErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	parser16Debug        = 0
	parser16ErrorVerbose = false
)

type parser16Lexer interface {
	Lex(lval *parser16SymType) int
	Error(s string)
}

type parser16Parser interface {
	Parse(parser16Lexer) int
	Lookahead() int
}

type parser16ParserImpl struct {
	lval  parser16SymType
	stack [parser16InitialStackSize]parser16SymType
	char  int
}

func (p *parser16ParserImpl) Lookahead() int {
	return p.char
}

func parser16NewParser() parser16Parser {
	return &parser16ParserImpl{}
}

const parser16Flag = -1000

func parser16Tokname(c int) string {
	if c >= 1 && c-1 < len(parser16Toknames) {
		if parser16Toknames[c-1] != "" {
			return parser16Toknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func parser16Statname(s int) string {
	if s >= 0 && s < len(parser16Statenames) {
		if parser16Statenames[s] != "" {
			return parser16Statenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func parser16ErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !parser16ErrorVerbose {
		return "syntax error"
	}

	for _, e := range parser16ErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + parser16Tokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(parser16Pact[state])
	for tok := TOKSTART; tok-1 < len(parser16Toknames); tok++ {
		if n := base + tok; n >= 0 && n < parser16Last && int(parser16Chk[int(parser16Act[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if parser16Def[state] == -2 {
		i := 0
		for parser16Exca[i] != -1 || int(parser16Exca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; parser16Exca[i] >= 0; i += 2 {
			tok := int(parser16Exca[i])
			if tok < TOKSTART || parser16Exca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if parser16Exca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += parser16Tokname(tok)
	}
	return res
}

func parser16lex1(lex parser16Lexer, lval *parser16SymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(parser16Tok1[0])
		goto out
	}
	if char < len(parser16Tok1) {
		token = int(parser16Tok1[char])
		goto out
	}
	if char >= parser16Private {
		if char < parser16Private+len(parser16Tok2) {
			token = int(parser16Tok2[char-parser16Private])
			goto out
		}
	}
	for i := 0; i < len(parser16Tok3); i += 2 {
		token = int(parser16Tok3[i+0])
		if token == char {
			token = int(parser16Tok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(parser16Tok2[1]) /* unknown char */
	}
	if parser16Debug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", parser16Tokname(token), uint(char))
	}
	return char, token
}

func parser16Parse(parser16lex parser16Lexer) int {
	return parser16NewParser().Parse(parser16lex)
}

func (parser16rcvr *parser16ParserImpl) Parse(parser16lex parser16Lexer) int {
	var parser16n int
	var parser16VAL parser16SymType
	var parser16Dollar []parser16SymType
	_ = parser16Dollar // silence set and not used
	parser16S := parser16rcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	parser16state := 0
	parser16rcvr.char = -1
	parser16token := -1 // parser16rcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		parser16state = -1
		parser16rcvr.char = -1
		parser16token = -1
	}()
	parser16p := -1
	goto parser16stack

ret0:
	return 0

ret1:
	return 1

parser16stack:
	/* put a state and value onto the stack */
	if parser16Debug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", parser16Tokname(parser16token), parser16Statname(parser16state))
	}

	parser16p++
	if parser16p >= len(parser16S) {
		nyys := make([]parser16SymType, len(parser16S)*2)
		copy(nyys, parser16S)
		parser16S = nyys
	}
	parser16S[parser16p] = parser16VAL
	parser16S[parser16p].yys = parser16state

parser16newstate:
	parser16n = int(parser16Pact[parser16state])
	if parser16n <= parser16Flag {
		goto parser16default /* simple state */
	}
	if parser16rcvr.char < 0 {
		parser16rcvr.char, parser16token = parser16lex1(parser16lex, &parser16rcvr.lval)
	}
	parser16n += parser16token
	if parser16n < 0 || parser16n >= parser16Last {
		goto parser16default
	}
	parser16n = int(parser16Act[parser16n])
	if int(parser16Chk[parser16n]) == parser16token { /* valid shift */
		parser16rcvr.char = -1
		parser16token = -1
		parser16VAL = parser16rcvr.lval
		parser16state = parser16n
		if Errflag > 0 {
			Errflag--
		}
		goto parser16stack
	}

parser16default:
	/* default state action */
	parser16n = int(parser16Def[parser16state])
	// Always read lookahead before reducing, to match PLY trace order.
	if parser16rcvr.char < 0 {
		parser16rcvr.char, parser16token = parser16lex1(parser16lex, &parser16rcvr.lval)
	}
	if parser16n == -2 {

		/* look through exception table */
		xi := 0
		for {
			if parser16Exca[xi+0] == -1 && int(parser16Exca[xi+1]) == parser16state {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			parser16n = int(parser16Exca[xi+0])
			if parser16n < 0 || parser16n == parser16token {
				break
			}
		}
		parser16n = int(parser16Exca[xi+1])
		if parser16n < 0 {
			goto ret0
		}
	}
	if parser16n == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			parser16lex.Error(parser16ErrorMessage(parser16state, parser16token))
			Nerrs++
			if parser16Debug >= 1 {
				__yyfmt__.Printf("%s", parser16Statname(parser16state))
				__yyfmt__.Printf(" saw %s\n", parser16Tokname(parser16token))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for parser16p >= 0 {
				parser16n = int(parser16Pact[parser16S[parser16p].yys]) + parser16ErrCode
				if parser16n >= 0 && parser16n < parser16Last {
					parser16state = int(parser16Act[parser16n]) /* simulate a shift of "error" */
					if int(parser16Chk[parser16state]) == parser16ErrCode {
						goto parser16stack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if parser16Debug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", parser16S[parser16p].yys)
				}
				parser16p--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if parser16Debug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", parser16Tokname(parser16token))
			}
			if parser16token == parser16EofCode {
				goto ret1
			}
			parser16rcvr.char = -1
			parser16token = -1
			goto parser16newstate /* try again in the same state */
		}
	}

	/* reduction by production parser16n */
	if parser16Debug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", parser16n, parser16Statname(parser16state))
	}

	parser16nt := parser16n
	parser16pt := parser16p
	_ = parser16pt // guard against "declared and not used"

	parser16p -= int(parser16R2[parser16n])
	// parser16p is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if parser16p+1 >= len(parser16S) {
		nyys := make([]parser16SymType, len(parser16S)*2)
		copy(nyys, parser16S)
		parser16S = nyys
	}
	parser16VAL = parser16S[parser16p+1]

	/* consult goto table to find next state */
	parser16n = int(parser16R1[parser16n])
	parser16g := int(parser16Pgo[parser16n])
	parser16j := parser16g + parser16S[parser16p].yys + 1

	if parser16j >= parser16Last {
		parser16state = int(parser16Act[parser16g])
	} else {
		parser16state = int(parser16Act[parser16j])
		if int(parser16Chk[parser16state]) != -parser16n {
			parser16state = int(parser16Act[parser16g])
		}
	}
	// dummy call; replaced with literal code
	switch parser16nt {

	case 1:
		parser16Dollar = parser16S[parser16pt-0 : parser16pt+1]
//line parser_grammar_v16.y:70
		{
			xtracer.Trace("parser.p_top ENTER (top)")
			lex := parser16lex.(*parser16LexAdapter)
			parent := lex.accum
			parser16VAL.accum = newIvyAccum(parent, lex.parentObjName)
			parser16VAL.accum.filename = lex.filename
			lex.parentObjName = ""
			parser16VAL.accum.parent = parent
			if parser16VAL.accum.astCfg == nil {
				parser16VAL.accum.astCfg = lex.astCfg
			}
			lex.accum = parser16VAL.accum
		}
	case 2:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:84
		{
			xtracer.Trace("parser.p_top_include_symbol ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			lex := parser16lex.(*parser16LexAdapter)
			parserDeclareInclude(parser16Acfg(parser16lex), parser16VAL.accum, lex.accum, lex.importer, parser16Dollar[3].str, tok16Lineno(lex, parser16Dollar[2].tok))
		}
	case 3:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:91
		{
			xtracer.Trace("parser.p_top_type_symbol ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			parser16DeclareType(parser16Acfg(parser16lex), parser16VAL.accum, parser16Dollar[3].node.(*Atom), tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[2].tok))
		}
	case 4:
		parser16Dollar = parser16S[parser16pt-2 : parser16pt+1]
//line parser_grammar_v16.y:97
		{
			xtracer.Trace("parser.p_top_symdecl ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			parser16VAL.accum.declare(parser16Dollar[2].node)
		}
	case 5:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:103
		{
			xtracer.Trace("parser.p_top_relation_rels ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			for _, d := range parser16Dollar[3].nodes {
				parser16VAL.accum.declare(d)
			}
		}
	case 6:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:111
		{
			xtracer.Trace("parser.p_top_function_tapp_colon_atype ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			for _, d := range parser16Dollar[3].nodes {
				parser16VAL.accum.declare(d)
			}
		}
	case 7:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:119
		{
			xtracer.Trace("parser.p_top_derived_defns ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			args := make([]Node, len(parser16Dollar[3].nodes))
			for i, x := range parser16Dollar[3].nodes {
				args[i] = parser17MkLF(parser16Acfg(parser16lex), x)
			}
			dd := parser16Acfg(parser16lex).NewDerivedDecl(args...)
			parser16VAL.accum.declare(dd)
		}
	case 8:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:130
		{
			xtracer.Trace("parser.p_top_progress_defns ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			pd := parser16Acfg(parser16lex).NewProgressDecl(parser16Dollar[3].nodes...)
			parser16VAL.accum.declare(pd)
		}
	case 9:
		parser16Dollar = parser16S[parser16pt-5 : parser16pt+1]
//line parser_grammar_v16.y:137
		{
			xtracer.Trace("parser.p_top_rely_atom_arrow_atom ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			imp := parser16Acfg(parser16lex).NewImplies(parser16Dollar[3].node, parser16Dollar[5].node)
			rd := parser16Acfg(parser16lex).NewRelyDecl(imp)
			parser16VAL.accum.declare(rd)
		}
	case 10:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:145
		{
			xtracer.Trace("parser.p_top_rely_atom ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			rd := parser16Acfg(parser16lex).NewRelyDecl(parser16Dollar[3].node)
			parser16VAL.accum.declare(rd)
		}
	case 11:
		parser16Dollar = parser16S[parser16pt-5 : parser16pt+1]
//line parser_grammar_v16.y:152
		{
			xtracer.Trace("parser.p_top_mixord_callatom_arrow_callatom ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			imp := parser16Acfg(parser16lex).NewImplies(parser16Dollar[3].node, parser16Dollar[5].node)
			md := parser16Acfg(parser16lex).NewMixOrdDecl(imp)
			parser16VAL.accum.declare(md)
		}
	case 12:
		parser16Dollar = parser16S[parser16pt-5 : parser16pt+1]
//line parser_grammar_v16.y:160
		{
			xtracer.Trace("parser.p_top_macro_atom_eq_lcb_action_rcb ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			d := parser16Acfg(parser16lex).NewDefinition(AppToAtom(parser16Dollar[3].node), parser16Dollar[5].node)
			md := parser16Acfg(parser16lex).NewMacroDecl(d)
			parser16VAL.accum.declare(md)
		}
	case 13:
		parser16Dollar = parser16S[parser16pt-4 : parser16pt+1]
//line parser_grammar_v16.y:168
		{
			xtracer.Trace("parser.p_top_axiom_optlabel_gprop ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			parser16DeclareAxiom(parser16Acfg(parser16lex), parser16VAL.accum, parser16Dollar[4].node.(*LabeledFormula), parser16Dollar[2].node != nil, tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[3].tok))
		}
	case 14:
		parser16Dollar = parser16S[parser16pt-5 : parser16pt+1]
//line parser_grammar_v16.y:174
		{
			xtracer.Trace("parser.p_top_property_labeledfmla ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			parser16DeclareProperty(parser16Acfg(parser16lex), parser16VAL.accum, parser16Dollar[4].node.(*LabeledFormula), parser16Dollar[2].node != nil, tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[3].tok))
			if parser16Dollar[5].node != nil {
				parser16VAL.accum.declare(parser16Acfg(parser16lex).NewProofDecl(parser16Dollar[5].node))
			}
		}
	case 15:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:183
		{
			xtracer.Trace("parser.p_top_conjecture_labeledfmla ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			parser16DeclareConjecture(parser16Acfg(parser16lex), parser16VAL.accum, parser16Dollar[3].node.(*LabeledFormula), tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[2].tok))
		}
	case 16:
		parser16Dollar = parser16S[parser16pt-5 : parser16pt+1]
//line parser_grammar_v16.y:189
		{
			xtracer.Trace("parser.p_top_assert_symbol_arrow_assert_rhs ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			thing := parser16Acfg(parser16lex).NewImplies(parser16Acfg(parser16lex).NewAtom(parser16Dollar[3].str), parser16Dollar[5].node)
			thing.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[4].tok))
			d := parser16Acfg(parser16lex).NewAssertDecl(thing)
			d.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[2].tok))
			parser16VAL.accum.declare(d)
		}
	case 17:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:199
		{
			xtracer.Trace("parser.p_top_init_labeledfmla ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			parser16DeclareInit(parser16Acfg(parser16lex), parser16VAL.accum, parser16Dollar[3].node.(*LabeledFormula), tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[2].tok))
		}
	case 18:
		parser16Dollar = parser16S[parser16pt-6 : parser16pt+1]
//line parser_grammar_v16.y:205
		{
			xtracer.Trace("parser.p_top_optimpex_action_symbol_optargs_eq_action ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			parser17DeclareAction(parser16Acfg(parser16lex), parser16VAL.accum, parser16Dollar[2].node, false, parser16Dollar[4].str, parser16Dollar[5].nodes, nil, parser16Dollar[6].node, tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[3].tok))
		}
	case 19:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:211
		{
			xtracer.Trace("parser.p_top_export_callatom ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			d := parser16Acfg(parser16lex).NewExportDecl(parser16Acfg(parser16lex).NewExportDef(parser16Dollar[3].node, parser16Acfg(parser16lex).NewAtom("")))
			d.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[2].tok))
			parser16VAL.accum.declare(d)
		}
	case 20:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:219
		{
			xtracer.Trace("parser.p_top_import_callatom ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			d := parser16Acfg(parser16lex).NewImportDecl(parser16Acfg(parser16lex).NewImportDef(parser16Dollar[3].node, parser16Acfg(parser16lex).NewAtom("")))
			d.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[2].tok))
			parser16VAL.accum.declare(d)
		}
	case 21:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:227
		{
			xtracer.Trace("parser.p_top_private_callatom ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			d := parser16Acfg(parser16lex).NewPrivateDecl(parser16Acfg(parser16lex).NewPrivateDef(parser16Dollar[3].node))
			d.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[2].tok))
			parser16VAL.accum.declare(d)
		}
	case 22:
		parser16Dollar = parser16S[parser16pt-5 : parser16pt+1]
//line parser_grammar_v16.y:235
		{
			xtracer.Trace("parser.p_top_aliase_symbol_eq_callatom ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			d := parser16Acfg(parser16lex).NewAliasDecl(parser16Acfg(parser16lex).NewDefinition(parser16Acfg(parser16lex).NewAtom(parser16Dollar[3].str), parser16Dollar[5].node))
			d.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[2].tok))
			parser16VAL.accum.declare(d)
		}
	case 23:
		parser16Dollar = parser16S[parser16pt-4 : parser16pt+1]
//line parser_grammar_v16.y:243
		{
			xtracer.Trace("parser.p_top_definition_defns ENTER (top)")
			parser16VAL.accum = parser16Dollar[1].accum
			lfs := make([]Node, 0, len(parser16Dollar[3].nodes))
			for _, def := range parser16Dollar[3].nodes {
				lfs = append(lfs, parser17MkLF(parser16Acfg(parser16lex), def))
			}
			d := parser16Acfg(parser16lex).NewDefinitionDecl(lfs...)
			d.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[2].tok))
			parser16VAL.accum.declare(d)
			if parser16Dollar[4].node != nil {
				parser16VAL.accum.declare(parser16Acfg(parser16lex).NewProofDecl(parser16Dollar[4].node))
			}
		}
	case 24:
		parser16Dollar = parser16S[parser16pt-0 : parser16pt+1]
//line parser_grammar_v16.y:261
		{
			xtracer.Trace("parser.p_optproof ENTER (optproof)")
			parser16VAL.node = nil
		}
	case 25:
		parser16Dollar = parser16S[parser16pt-2 : parser16pt+1]
//line parser_grammar_v16.y:266
		{
			xtracer.Trace("parser.p_optproof_symbol ENTER (optproof)")
			parser16VAL.node = parser16Dollar[2].node
		}
	case 26:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:274
		{
			xtracer.Trace("parser.p_proofstep_symbol ENTER (proofstep)")
			a := parser16Acfg(parser16lex).NewAtom(parser16Dollar[1].str)
			si := parser16Acfg(parser16lex).NewSchemaInstantiation(a, parser16Acfg(parser16lex).NewRenaming(nil))
			parser16VAL.node = si
		}
	case 27:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:281
		{
			xtracer.Trace("parser.p_proofstep_symbol_with_defns ENTER (proofstep)")
			a := parser16Acfg(parser16lex).NewAtom(parser16Dollar[1].str)
			si := parser16Acfg(parser16lex).NewSchemaInstantiationWithMatches(a, parser16Acfg(parser16lex).NewRenaming(nil), parser16Dollar[3].nodes)
			parser16VAL.node = si
		}
	case 28:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:291
		{
			xtracer.Trace("parser.p_match_defn ENTER (match)")
			parser16VAL.node = parser16Dollar[1].node
		}
	case 29:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:296
		{
			xtracer.Trace("parser.p_match_var_eq_fmla ENTER (match)")
			parser16VAL.node = parser16Acfg(parser16lex).NewDefinition(parser16Dollar[1].node, checkNonTemporal(parser16Dollar[3].node))
			parser16VAL.node.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[2].tok))
		}
	case 30:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:305
		{
			xtracer.Trace("parser.p_matches ENTER (matches)")
			parser16VAL.nodes = []Node{parser16Dollar[1].node}
		}
	case 31:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:310
		{
			xtracer.Trace("parser.p_matches_matches_comma_match ENTER (matches)")
			parser16VAL.nodes = append(parser16Dollar[1].nodes, parser16Dollar[3].node)
		}
	case 32:
		parser16Dollar = parser16S[parser16pt-0 : parser16pt+1]
//line parser_grammar_v16.y:318
		{
			xtracer.Trace("parser.p_opttemporal ENTER (opttemporal)")
			parser16VAL.node = nil
		}
	case 33:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:323
		{
			xtracer.Trace("parser.p_opttemporal_temporal ENTER (opttemporal)")
			parser16VAL.node = parser16Acfg(parser16lex).NewAtom("globally")
		}
	case 34:
		parser16Dollar = parser16S[parser16pt-0 : parser16pt+1]
//line parser_grammar_v16.y:331
		{
			xtracer.Trace("parser.p_optimpex ENTER (optimpex)")
			parser16VAL.node = nil
		}
	case 35:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:336
		{
			xtracer.Trace("parser.p_optimpex_export ENTER (optimpex)")
			parser16VAL.node = parser16Acfg(parser16lex).NewExportDecl()
		}
	case 36:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:341
		{
			xtracer.Trace("parser.p_optimpex_import ENTER (optimpex)")
			parser16VAL.node = parser16Acfg(parser16lex).NewImportDecl()
		}
	case 37:
		parser16Dollar = parser16S[parser16pt-0 : parser16pt+1]
//line parser_grammar_v16.y:349
		{
			xtracer.Trace("parser.p_optactiondef ENTER (optactiondef)")
			parser16VAL.node = parser16Acfg(parser16lex).NewSequence()
		}
	case 38:
		parser16Dollar = parser16S[parser16pt-2 : parser16pt+1]
//line parser_grammar_v16.y:354
		{
			xtracer.Trace("parser.p_optactiondef_eq_sequence ENTER (optactiondef)")
			parser16VAL.node = parser16Dollar[2].node
		}
	case 39:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:362
		{
			xtracer.Trace("parser.p_sequence_lcb_actseq_rcb ENTER (sequence)")
			parser16VAL.node = parser17MakeSequence(parser16Acfg(parser16lex), parser16Dollar[2].nodes)
			parser16VAL.node.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[1].tok))
		}
	case 40:
		parser16Dollar = parser16S[parser16pt-0 : parser16pt+1]
//line parser_grammar_v16.y:371
		{
			xtracer.Trace("parser.p_actseq ENTER (actseq)")
			parser16VAL.nodes = nil
		}
	case 41:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:376
		{
			xtracer.Trace("parser.p_actseq_action ENTER (actseq)")
			parser16VAL.nodes = []Node{parser16Dollar[1].node}
		}
	case 42:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:381
		{
			xtracer.Trace("parser.p_actseq_actseq_semi_action ENTER (actseq)")
			parser16VAL.nodes = append(parser16Dollar[1].nodes, parser16Dollar[3].node)
		}
	case 43:
		parser16Dollar = parser16S[parser16pt-2 : parser16pt+1]
//line parser_grammar_v16.y:389
		{
			xtracer.Trace("parser.p_action_call_callatom ENTER (simpleact)")
			parser16VAL.node = parser16Acfg(parser16lex).NewCallAction(parser16Dollar[2].node)
			parser16VAL.node.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[1].tok))
		}
	case 44:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:395
		{
			xtracer.Trace("parser.p_action_assign ENTER (simpleact)")
			parser16VAL.node = parser16Acfg(parser16lex).NewAssignAction(parser16Dollar[1].node, checkNonTemporal(parser16Dollar[3].node))
			parser16VAL.node.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[2].tok))
		}
	case 45:
		parser16Dollar = parser16S[parser16pt-0 : parser16pt+1]
//line parser_grammar_v16.y:404
		{
			xtracer.Trace("parser.p_optargs ENTER (optargs)")
			parser16VAL.nodes = nil
		}
	case 46:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:409
		{
			xtracer.Trace("parser.p_optargs_params ENTER (optargs)")
			parser16VAL.nodes = parser16Dollar[2].nodes
		}
	case 47:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:417
		{
			xtracer.Trace("parser.p_labeledfmla_fmla ENTER (labeledfmla)")
			lf := parser16Acfg(parser16lex).NewLabeledFormula(nil, parser16Dollar[1].node)
			if parser16Dollar[1].node != nil && parser16Dollar[1].node.GetLineno().Line > 0 {
				lf.SetLineno(parser16Dollar[1].node.GetLineno())
			}
			parser16VAL.node = lf
		}
	case 48:
		parser16Dollar = parser16S[parser16pt-2 : parser16pt+1]
//line parser_grammar_v16.y:426
		{
			xtracer.Trace("parser.p_labeledfmla_label_fmla ENTER (labeledfmla)")
			lf := parser16Acfg(parser16lex).NewLabeledFormula(parser16Acfg(parser16lex).NewAtom(parser16Dollar[1].tok.Val), parser16Dollar[2].node)
			lf.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[1].tok))
			parser16VAL.node = lf
		}
	case 49:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:436
		{
			xtracer.Trace("parser.p_LABEL_LB_SYMBOL_RB ENTER (LABEL)")
			parser16VAL.tok = TokenInfo{Val: parser16Dollar[2].str, Line: parser16Dollar[1].tok.Line}
		}
	case 50:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:444
		{
			xtracer.Trace("parser.p_symdecl_constantdecl ENTER (symdecl)")
			parser16VAL.node = parser16Dollar[1].node
		}
	case 51:
		parser16Dollar = parser16S[parser16pt-2 : parser16pt+1]
//line parser_grammar_v16.y:452
		{
			xtracer.Trace("parser.p_constantdecl_constant_tterms ENTER (constantdecl)")
			d := parser16Acfg(parser16lex).NewConstantDecl(parser16Dollar[2].nodes...)
			d.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[1].tok))
			parser16VAL.node = d
		}
	case 52:
		parser16Dollar = parser16S[parser16pt-2 : parser16pt+1]
//line parser_grammar_v16.y:459
		{
			xtracer.Trace("parser.p_constantdecl_var_tterms ENTER (constantdecl)")
			d := parser16Acfg(parser16lex).NewConstantDecl(parser16Dollar[2].nodes...)
			d.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[1].tok))
			parser16VAL.node = d
		}
	case 53:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:469
		{
			xtracer.Trace("parser.p_rel_defnlhs ENTER (rel)")
			if a, ok := parser16Dollar[1].node.(*Atom); ok {
				a.ASort = parser16Acfg(parser16lex).NewSymbol("bool", nil)
			}
			parser16VAL.node = parser16Acfg(parser16lex).NewConstantDecl(parser16Dollar[1].node)
		}
	case 54:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:477
		{
			xtracer.Trace("parser.p_rel_defn ENTER (rel)")
			lf := parser17MkLF(parser16Acfg(parser16lex), parser16Dollar[1].node)
			d := parser16Acfg(parser16lex).NewDerivedDecl(lf)
			parser16VAL.node = d
		}
	case 55:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:487
		{
			xtracer.Trace("parser.p_rels_rel ENTER (rels)")
			parser16VAL.nodes = []Node{parser16Dollar[1].node}
		}
	case 56:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:492
		{
			xtracer.Trace("parser.p_rels_rels_comma_rel ENTER (rels)")
			parser16VAL.nodes = append(parser16Dollar[1].nodes, parser16Dollar[3].node)
		}
	case 57:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:500
		{
			xtracer.Trace("parser.p_fun_defnlhs_colon_atype ENTER (fun)")
			d := parser16Acfg(parser16lex).NewConstantDecl(parser16Dollar[1].node)
			parser16VAL.node = d
		}
	case 58:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:506
		{
			xtracer.Trace("parser.p_fun_defn ENTER (fun)")
			df := parser16Acfg(parser16lex).NewDefinition(AppToAtom(parser16Dollar[1].node), checkNonTemporal(parser16Dollar[3].node))
			df.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[2].tok))
			lf := parser17MkLF(parser16Acfg(parser16lex), df)
			d := parser16Acfg(parser16lex).NewDerivedDecl(lf)
			parser16VAL.node = d
		}
	case 59:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:518
		{
			xtracer.Trace("parser.p_funs_fun ENTER (funs)")
			parser16VAL.nodes = []Node{parser16Dollar[1].node}
		}
	case 60:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:523
		{
			xtracer.Trace("parser.p_funs_funs_comma_fun ENTER (funs)")
			parser16VAL.nodes = append(parser16Dollar[1].nodes, parser16Dollar[3].node)
		}
	case 61:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:531
		{
			xtracer.Trace("parser.p_defnrhs_fmla ENTER (defnrhs)")
			parser16VAL.node = checkNonTemporal(parser16Dollar[1].node)
		}
	case 62:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:539
		{
			xtracer.Trace("parser.p_defn_atom_fmla ENTER (defn)")
			d := parser16Acfg(parser16lex).NewDefinition(AppToAtom(parser16Dollar[1].node), parser16Dollar[3].node)
			d.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[2].tok))
			parser16VAL.node = d
		}
	case 63:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:549
		{
			xtracer.Trace("parser.p_defns_defn ENTER (defns)")
			parser16VAL.nodes = []Node{parser16Dollar[1].node}
		}
	case 64:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:554
		{
			xtracer.Trace("parser.p_defns_defns_comma_defn ENTER (defns)")
			parser16VAL.nodes = append(parser16Dollar[1].nodes, parser16Dollar[3].node)
		}
	case 65:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:562
		{
			xtracer.Trace("parser.p_typesymbol_symbol ENTER (typesymbol)")
			parser16VAL.node = parser16Acfg(parser16lex).NewAtom(parser16Dollar[1].str)
		}
	case 66:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:567
		{
			xtracer.Trace("parser.p_typesymbol_this ENTER (typesymbol)")
			a := parser16Acfg(parser16lex).NewAtom("this")
			a.SetLineno(tok16Lineno(parser16lex.(*parser16LexAdapter), parser16Dollar[1].tok))
			parser16VAL.node = a
		}
	case 67:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:577
		{
			parser16VAL.str = parser16Dollar[1].tok.Val
		}
	case 68:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:584
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewSymbol(parser16Dollar[1].str, nil)
		}
	case 69:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:588
		{
			if _, ok := parser16Dollar[1].node.(*This); ok {
				parser16VAL.node = parser16Acfg(parser16lex).NewSymbol(parser16Dollar[3].str, nil)
			} else if sym, ok := parser16Dollar[1].node.(*Symbol); ok {
				parser16VAL.node = parser16Acfg(parser16lex).NewSymbol(sym.Rep+"."+parser16Dollar[3].str, nil)
			} else {
				parser16VAL.node = parser16Acfg(parser16lex).NewSymbol(parser16Dollar[3].str, nil)
			}
		}
	case 70:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:598
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewThis()
		}
	case 71:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:605
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewAtom(parser16Dollar[1].str)
		}
	case 72:
		parser16Dollar = parser16S[parser16pt-4 : parser16pt+1]
//line parser_grammar_v16.y:609
		{
			a := parser16Dollar[1].node.(*Atom)
			a.Terms = append(a.Terms, parser16Dollar[3].nodes...)
			parser16VAL.node = a
		}
	case 73:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:615
		{
			lhs := parser16Dollar[1].node.(*Atom)
			parser16VAL.node = parser16Acfg(parser16lex).NewAtom(lhs.Rep+"."+parser16Dollar[3].str, lhs.Terms...)
		}
	case 74:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:623
		{
			xtracer.Trace("parser.p_callatom_atom ENTER (callatom)")
			parser16VAL.node = parser16Dollar[1].node
		}
	case 75:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:628
		{
			xtracer.Trace("parser.p_callatom_this ENTER (callatom)")
			parser16VAL.node = parser16Acfg(parser16lex).NewAtom("this")
		}
	case 76:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:633
		{
			xtracer.Trace("parser.p_callatom_callatom_dot_callatom ENTER (callatom)")
			parser16VAL.node = ComposeAtoms(parser16Dollar[1].node.(*Atom), parser16Dollar[3].node.(*Atom))
		}
	case 77:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:641
		{
			xtracer.Trace("parser.p_atom_tatom ENTER (atom)")
			parser16VAL.node = parser16Dollar[1].node
		}
	case 78:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:649
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewVariable(parser16Dollar[1].tok.Val, "S")
		}
	case 79:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:651
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewVariable(parser16Dollar[1].tok.Val, parser17AtypeToString(parser16Dollar[3].node))
		}
	case 80:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:656
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewVariable(parser16Dollar[1].tok.Val, "S")
		}
	case 81:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:658
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewVariable(parser16Dollar[1].tok.Val, parser16Dollar[3].str)
		}
	case 82:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:663
		{
			parser16VAL.nodes = []Node{parser16Dollar[1].node}
		}
	case 83:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:665
		{
			parser16VAL.nodes = append(parser16Dollar[1].nodes, parser16Dollar[3].node)
		}
	case 84:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:670
		{
			parser16VAL.nodes = []Node{parser16Dollar[1].node}
		}
	case 85:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:672
		{
			parser16VAL.nodes = append(parser16Dollar[1].nodes, parser16Dollar[3].node)
		}
	case 86:
		parser16Dollar = parser16S[parser16pt-0 : parser16pt+1]
//line parser_grammar_v16.y:677
		{
			parser16VAL.nodes = nil
		}
	case 87:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:679
		{
			parser16VAL.nodes = []Node{parser16Dollar[1].node}
		}
	case 88:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:681
		{
			parser16VAL.nodes = append(parser16Dollar[1].nodes, parser16Dollar[3].node)
		}
	case 89:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:686
		{
			xtracer.Trace("parser.p_tterm_term ENTER (tterm)")
			parser16VAL.node = parser16Dollar[1].node
		}
	case 90:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:691
		{
			xtracer.Trace("parser.p_tterm_term_colon_symbol ENTER (tterm)")
			if a, ok := parser16Dollar[1].node.(*Atom); ok {
				a.ASort = parser16Dollar[3].node
			}
			parser16VAL.node = parser16Dollar[1].node
		}
	case 91:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:702
		{
			xtracer.Trace("parser.p_tterms_tterm ENTER (tterms)")
			parser16VAL.nodes = []Node{parser16Dollar[1].node}
		}
	case 92:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:707
		{
			xtracer.Trace("parser.p_tterms_tterms_comma_tterm ENTER (tterms)")
			parser16VAL.nodes = append(parser16Dollar[1].nodes, parser16Dollar[3].node)
		}
	case 93:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:715
		{
			parser16VAL.node = parser16Dollar[1].node
		}
	case 94:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:717
		{
			parser16VAL.node = parser16Dollar[1].node
		}
	case 95:
		parser16Dollar = parser16S[parser16pt-2 : parser16pt+1]
//line parser_grammar_v16.y:719
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewOld(parser16Dollar[2].node)
		}
	case 96:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:721
		{
			parser16VAL.node = parser16Dollar[2].node
		}
	case 97:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:723
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewAtom("+", parser16Dollar[1].node, parser16Dollar[3].node)
		}
	case 98:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:725
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewAtom("-", parser16Dollar[1].node, parser16Dollar[3].node)
		}
	case 99:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:727
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewAtom("*", parser16Dollar[1].node, parser16Dollar[3].node)
		}
	case 100:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:729
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewAtom("/", parser16Dollar[1].node, parser16Dollar[3].node)
		}
	case 101:
		parser16Dollar = parser16S[parser16pt-5 : parser16pt+1]
//line parser_grammar_v16.y:731
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewIte(parser16Dollar[3].node, parser16Dollar[1].node, parser16Dollar[5].node)
		}
	case 102:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:735
		{
			parser16VAL.str = "="
		}
	case 103:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:736
		{
			parser16VAL.str = "<="
		}
	case 104:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:737
		{
			parser16VAL.str = "<"
		}
	case 105:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:738
		{
			parser16VAL.str = ">="
		}
	case 106:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:739
		{
			parser16VAL.str = ">"
		}
	case 107:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:740
		{
			parser16VAL.str = "*>"
		}
	case 108:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:745
		{
			xtracer.Trace("parser.p_assert_rhs_fmla ENTER (assert_rhs)")
			parser16VAL.node = checkNonTemporal(parser16Dollar[1].node)
		}
	case 109:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:753
		{
			parser16VAL.node = parser16Dollar[1].node
		}
	case 110:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:755
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewAtom(parser16Dollar[2].str, parser16Dollar[1].node, parser16Dollar[3].node)
		}
	case 111:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:757
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewNot(parser16Acfg(parser16lex).NewAtom("=", parser16Dollar[1].node, parser16Dollar[3].node))
		}
	case 112:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:759
		{
			parser16VAL.node = parser16Dollar[2].node
		}
	case 113:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:761
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewAnd()
		}
	case 114:
		parser16Dollar = parser16S[parser16pt-1 : parser16pt+1]
//line parser_grammar_v16.y:763
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewOr()
		}
	case 115:
		parser16Dollar = parser16S[parser16pt-2 : parser16pt+1]
//line parser_grammar_v16.y:765
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewNot(parser16Dollar[2].node)
		}
	case 116:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:767
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewAnd(parser16Dollar[1].node, parser16Dollar[3].node)
		}
	case 117:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:769
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewOr(parser16Dollar[1].node, parser16Dollar[3].node)
		}
	case 118:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:771
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewImplies(parser16Dollar[1].node, parser16Dollar[3].node)
		}
	case 119:
		parser16Dollar = parser16S[parser16pt-3 : parser16pt+1]
//line parser_grammar_v16.y:773
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewIff(parser16Dollar[1].node, parser16Dollar[3].node)
		}
	case 120:
		parser16Dollar = parser16S[parser16pt-4 : parser16pt+1]
//line parser_grammar_v16.y:775
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewForall(parser16Dollar[2].nodes, parser16Dollar[4].node)
		}
	case 121:
		parser16Dollar = parser16S[parser16pt-4 : parser16pt+1]
//line parser_grammar_v16.y:777
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewExists(parser16Dollar[2].nodes, parser16Dollar[4].node)
		}
	case 122:
		parser16Dollar = parser16S[parser16pt-2 : parser16pt+1]
//line parser_grammar_v16.y:779
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewGlobally(parser16Dollar[2].node)
		}
	case 123:
		parser16Dollar = parser16S[parser16pt-2 : parser16pt+1]
//line parser_grammar_v16.y:781
		{
			parser16VAL.node = parser16Acfg(parser16lex).NewEventually(parser16Dollar[2].node)
		}
	}
	goto parser16stack /* stack new state and value */
}
