// Code generated by goyacc -o v12_grammar_v12.go -p lalr12 v12_grammar_v12.y. DO NOT EDIT.

//line v12_grammar_v12.y:11
package goivy

import __yyfmt__ "fmt"

//line v12_grammar_v12.y:11

import (
	"fmt"
)

func lalr12AtypeToString(n Node) string {
	switch v := n.(type) {
	case *Symbol:
		return v.Rep
	case *This:
		return "this"
	default:
		return fmt.Sprint(n)
	}
}

func lalr12Acfg(lex lalr12Lexer) *AstConfig {
	return lex.(*lalr12LexAdapter).cfg
}

//line v12_grammar_v12.y:34
type lalr12SymType struct {
	yys   int
	node  Node
	nodes []Node
	str   string
}

const LALR12_TOK_SYMBOL = 57346
const LALR12_TOK_VARIABLE = 57347
const LALR12_TOK_PRESYMBOL = 57348
const LALR12_TOK_LPAREN = 57349
const LALR12_TOK_RPAREN = 57350
const LALR12_TOK_LB = 57351
const LALR12_TOK_RB = 57352
const LALR12_TOK_LCB = 57353
const LALR12_TOK_RCB = 57354
const LALR12_TOK_COMMA = 57355
const LALR12_TOK_SEMI = 57356
const LALR12_TOK_COLON = 57357
const LALR12_TOK_DOT = 57358
const LALR12_TOK_PLUS = 57359
const LALR12_TOK_MINUS = 57360
const LALR12_TOK_TIMES = 57361
const LALR12_TOK_DIV = 57362
const LALR12_TOK_EQ = 57363
const LALR12_TOK_TILDAEQ = 57364
const LALR12_TOK_TILDA = 57365
const LALR12_TOK_LE = 57366
const LALR12_TOK_LT = 57367
const LALR12_TOK_GE = 57368
const LALR12_TOK_GT = 57369
const LALR12_TOK_AND = 57370
const LALR12_TOK_OR = 57371
const LALR12_TOK_ARROW = 57372
const LALR12_TOK_IFF = 57373
const LALR12_TOK_PTO = 57374
const LALR12_TOK_DOLLAR = 57375
const LALR12_TOK_FORALL = 57376
const LALR12_TOK_EXISTS = 57377
const LALR12_TOK_TRUE = 57378
const LALR12_TOK_FALSE = 57379
const LALR12_TOK_OLD = 57380
const LALR12_TOK_THIS = 57381
const LALR12_TOK_ISA = 57382
const LALR12_TOK_IF = 57383
const LALR12_TOK_ELSE = 57384
const LALR12_TOK_GLOBALLY = 57385
const LALR12_TOK_EVENTUALLY = 57386
const LALR12_TOK_WHENNEXT = 57387
const LALR12_TOK_WHENPREV = 57388
const LALR12_TOK_WHENFIRST = 57389
const LALR12_TOK_WHENLAST = 57390

var lalr12Toknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LALR12_TOK_SYMBOL",
	"LALR12_TOK_VARIABLE",
	"LALR12_TOK_PRESYMBOL",
	"LALR12_TOK_LPAREN",
	"LALR12_TOK_RPAREN",
	"LALR12_TOK_LB",
	"LALR12_TOK_RB",
	"LALR12_TOK_LCB",
	"LALR12_TOK_RCB",
	"LALR12_TOK_COMMA",
	"LALR12_TOK_SEMI",
	"LALR12_TOK_COLON",
	"LALR12_TOK_DOT",
	"LALR12_TOK_PLUS",
	"LALR12_TOK_MINUS",
	"LALR12_TOK_TIMES",
	"LALR12_TOK_DIV",
	"LALR12_TOK_EQ",
	"LALR12_TOK_TILDAEQ",
	"LALR12_TOK_TILDA",
	"LALR12_TOK_LE",
	"LALR12_TOK_LT",
	"LALR12_TOK_GE",
	"LALR12_TOK_GT",
	"LALR12_TOK_AND",
	"LALR12_TOK_OR",
	"LALR12_TOK_ARROW",
	"LALR12_TOK_IFF",
	"LALR12_TOK_PTO",
	"LALR12_TOK_DOLLAR",
	"LALR12_TOK_FORALL",
	"LALR12_TOK_EXISTS",
	"LALR12_TOK_TRUE",
	"LALR12_TOK_FALSE",
	"LALR12_TOK_OLD",
	"LALR12_TOK_THIS",
	"LALR12_TOK_ISA",
	"LALR12_TOK_IF",
	"LALR12_TOK_ELSE",
	"LALR12_TOK_GLOBALLY",
	"LALR12_TOK_EVENTUALLY",
	"LALR12_TOK_WHENNEXT",
	"LALR12_TOK_WHENPREV",
	"LALR12_TOK_WHENFIRST",
	"LALR12_TOK_WHENLAST",
}

var lalr12Statenames = [...]string{}

const lalr12EofCode = 1
const lalr12ErrCode = 2
const lalr12InitialStackSize = 16

//line v12_grammar_v12.y:199

//line yacctab:1
var lalr12Exca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const lalr12Private = 57344

const lalr12Last = 79

var lalr12Act = [...]int8{
	3, 13, 18, 47, 30, 26, 2, 14, 15, 41,
	16, 27, 36, 18, 28, 14, 15, 4, 15, 45,
	40, 42, 48, 37, 38, 39, 16, 17, 10, 18,
	43, 44, 45, 7, 50, 46, 51, 31, 53, 19,
	12, 35, 54, 49, 8, 9, 5, 6, 12, 57,
	55, 16, 17, 56, 18, 58, 43, 29, 33, 21,
	20, 61, 22, 23, 24, 25, 34, 32, 52, 21,
	20, 59, 22, 23, 24, 25, 60, 11, 1,
}

var lalr12Pact = [...]int16{
	10, -1000, -2, 38, 10, -1000, -1000, 10, 32, 32,
	51, -1000, 12, -1000, -3, -1000, 10, 10, 10, 2,
	2, -1000, -1000, -1000, -1000, -1000, 48, 23, -29, 19,
	-1000, -12, 6, 2, 12, 51, 12, -29, -18, -2,
	-1000, 2, -1000, -1000, -1000, 32, 10, 12, 10, 63,
	-1000, -1000, -1000, -1000, 22, -1000, -2, -1000, -2, -1000,
	2, -1000,
}

var lalr12Pgo = [...]int8{
	0, 78, 6, 0, 28, 77, 4, 68, 43, 43,
	57, 39, 1,
}

var lalr12R1 = [...]int8{
	0, 1, 12, 7, 4, 4, 4, 5, 5, 6,
	6, 9, 9, 10, 10, 8, 8, 8, 3, 3,
	3, 3, 11, 11, 11, 11, 11, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2,
}

var lalr12R2 = [...]int8{
	0, 1, 1, 1, 1, 4, 3, 1, 3, 1,
	3, 1, 3, 1, 3, 0, 1, 3, 1, 1,
	2, 3, 1, 1, 1, 1, 1, 1, 3, 3,
	3, 1, 1, 2, 3, 3, 3, 4, 4,
}

var lalr12Chk = [...]int16{
	-1000, -1, -2, -3, 7, 36, 37, 23, 34, 35,
	-4, -5, 38, -12, 5, 6, 28, 29, 31, -11,
	22, 21, 24, 25, 26, 27, -3, -2, -2, -10,
	-6, 5, -10, 7, 15, -4, 15, -2, -2, -2,
	-3, 7, -3, 8, 8, 13, 16, 15, 16, -8,
	-3, -12, -7, -12, -3, -6, -2, -12, -2, 8,
	13, -3,
}

var lalr12Def = [...]int8{
	0, -2, 1, 27, 0, 31, 32, 0, 0, 0,
	18, 19, 0, 4, 7, 2, 0, 0, 0, 0,
	0, 22, 23, 24, 25, 26, 27, 0, 33, 0,
	13, 9, 0, 15, 0, 20, 0, 34, 35, 36,
	28, 0, 29, 21, 30, 0, 0, 0, 0, 0,
	16, 6, 8, 3, 0, 14, 37, 10, 38, 5,
	0, 17,
}

var lalr12Tok1 = [...]int8{
	1,
}

var lalr12Tok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48,
}

var lalr12Tok3 = [...]int8{
	0,
}

var lalr12ErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	lalr12Debug        = 0
	lalr12ErrorVerbose = false
)

type lalr12Lexer interface {
	Lex(lval *lalr12SymType) int
	Error(s string)
}

type lalr12Parser interface {
	Parse(lalr12Lexer) int
	Lookahead() int
}

type lalr12ParserImpl struct {
	lval  lalr12SymType
	stack [lalr12InitialStackSize]lalr12SymType
	char  int
}

func (p *lalr12ParserImpl) Lookahead() int {
	return p.char
}

func lalr12NewParser() lalr12Parser {
	return &lalr12ParserImpl{}
}

const lalr12Flag = -1000

func lalr12Tokname(c int) string {
	if c >= 1 && c-1 < len(lalr12Toknames) {
		if lalr12Toknames[c-1] != "" {
			return lalr12Toknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func lalr12Statname(s int) string {
	if s >= 0 && s < len(lalr12Statenames) {
		if lalr12Statenames[s] != "" {
			return lalr12Statenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func lalr12ErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !lalr12ErrorVerbose {
		return "syntax error"
	}

	for _, e := range lalr12ErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + lalr12Tokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(lalr12Pact[state])
	for tok := TOKSTART; tok-1 < len(lalr12Toknames); tok++ {
		if n := base + tok; n >= 0 && n < lalr12Last && int(lalr12Chk[int(lalr12Act[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if lalr12Def[state] == -2 {
		i := 0
		for lalr12Exca[i] != -1 || int(lalr12Exca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; lalr12Exca[i] >= 0; i += 2 {
			tok := int(lalr12Exca[i])
			if tok < TOKSTART || lalr12Exca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if lalr12Exca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += lalr12Tokname(tok)
	}
	return res
}

func lalr12lex1(lex lalr12Lexer, lval *lalr12SymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(lalr12Tok1[0])
		goto out
	}
	if char < len(lalr12Tok1) {
		token = int(lalr12Tok1[char])
		goto out
	}
	if char >= lalr12Private {
		if char < lalr12Private+len(lalr12Tok2) {
			token = int(lalr12Tok2[char-lalr12Private])
			goto out
		}
	}
	for i := 0; i < len(lalr12Tok3); i += 2 {
		token = int(lalr12Tok3[i+0])
		if token == char {
			token = int(lalr12Tok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(lalr12Tok2[1]) /* unknown char */
	}
	if lalr12Debug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", lalr12Tokname(token), uint(char))
	}
	return char, token
}

func lalr12Parse(lalr12lex lalr12Lexer) int {
	return lalr12NewParser().Parse(lalr12lex)
}

func (lalr12rcvr *lalr12ParserImpl) Parse(lalr12lex lalr12Lexer) int {
	var lalr12n int
	var lalr12VAL lalr12SymType
	var lalr12Dollar []lalr12SymType
	_ = lalr12Dollar // silence set and not used
	lalr12S := lalr12rcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	lalr12state := 0
	lalr12rcvr.char = -1
	lalr12token := -1 // lalr12rcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		lalr12state = -1
		lalr12rcvr.char = -1
		lalr12token = -1
	}()
	lalr12p := -1
	goto lalr12stack

ret0:
	return 0

ret1:
	return 1

lalr12stack:
	/* put a state and value onto the stack */
	if lalr12Debug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", lalr12Tokname(lalr12token), lalr12Statname(lalr12state))
	}

	lalr12p++
	if lalr12p >= len(lalr12S) {
		nyys := make([]lalr12SymType, len(lalr12S)*2)
		copy(nyys, lalr12S)
		lalr12S = nyys
	}
	lalr12S[lalr12p] = lalr12VAL
	lalr12S[lalr12p].yys = lalr12state

lalr12newstate:
	lalr12n = int(lalr12Pact[lalr12state])
	if lalr12n <= lalr12Flag {
		goto lalr12default /* simple state */
	}
	if lalr12rcvr.char < 0 {
		lalr12rcvr.char, lalr12token = lalr12lex1(lalr12lex, &lalr12rcvr.lval)
	}
	lalr12n += lalr12token
	if lalr12n < 0 || lalr12n >= lalr12Last {
		goto lalr12default
	}
	lalr12n = int(lalr12Act[lalr12n])
	if int(lalr12Chk[lalr12n]) == lalr12token { /* valid shift */
		lalr12rcvr.char = -1
		lalr12token = -1
		lalr12VAL = lalr12rcvr.lval
		lalr12state = lalr12n
		if Errflag > 0 {
			Errflag--
		}
		goto lalr12stack
	}

lalr12default:
	/* default state action */
	lalr12n = int(lalr12Def[lalr12state])
	if lalr12n == -2 {
		if lalr12rcvr.char < 0 {
			lalr12rcvr.char, lalr12token = lalr12lex1(lalr12lex, &lalr12rcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if lalr12Exca[xi+0] == -1 && int(lalr12Exca[xi+1]) == lalr12state {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			lalr12n = int(lalr12Exca[xi+0])
			if lalr12n < 0 || lalr12n == lalr12token {
				break
			}
		}
		lalr12n = int(lalr12Exca[xi+1])
		if lalr12n < 0 {
			goto ret0
		}
	}
	if lalr12n == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			lalr12lex.Error(lalr12ErrorMessage(lalr12state, lalr12token))
			Nerrs++
			if lalr12Debug >= 1 {
				__yyfmt__.Printf("%s", lalr12Statname(lalr12state))
				__yyfmt__.Printf(" saw %s\n", lalr12Tokname(lalr12token))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for lalr12p >= 0 {
				lalr12n = int(lalr12Pact[lalr12S[lalr12p].yys]) + lalr12ErrCode
				if lalr12n >= 0 && lalr12n < lalr12Last {
					lalr12state = int(lalr12Act[lalr12n]) /* simulate a shift of "error" */
					if int(lalr12Chk[lalr12state]) == lalr12ErrCode {
						goto lalr12stack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if lalr12Debug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", lalr12S[lalr12p].yys)
				}
				lalr12p--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if lalr12Debug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", lalr12Tokname(lalr12token))
			}
			if lalr12token == lalr12EofCode {
				goto ret1
			}
			lalr12rcvr.char = -1
			lalr12token = -1
			goto lalr12newstate /* try again in the same state */
		}
	}

	/* reduction by production lalr12n */
	if lalr12Debug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", lalr12n, lalr12Statname(lalr12state))
	}

	lalr12nt := lalr12n
	lalr12pt := lalr12p
	_ = lalr12pt // guard against "declared and not used"

	lalr12p -= int(lalr12R2[lalr12n])
	// lalr12p is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if lalr12p+1 >= len(lalr12S) {
		nyys := make([]lalr12SymType, len(lalr12S)*2)
		copy(nyys, lalr12S)
		lalr12S = nyys
	}
	lalr12VAL = lalr12S[lalr12p+1]

	/* consult goto table to find next state */
	lalr12n = int(lalr12R1[lalr12n])
	lalr12g := int(lalr12Pgo[lalr12n])
	lalr12j := lalr12g + lalr12S[lalr12p].yys + 1

	if lalr12j >= lalr12Last {
		lalr12state = int(lalr12Act[lalr12g])
	} else {
		lalr12state = int(lalr12Act[lalr12j])
		if int(lalr12Chk[lalr12state]) != -lalr12n {
			lalr12state = int(lalr12Act[lalr12g])
		}
	}
	// dummy call; replaced with literal code
	switch lalr12nt {

	case 1:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:79
		{
			lalr12lex.(*lalr12LexAdapter).result = lalr12Dollar[1].node
		}
	case 2:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:86
		{
			lalr12VAL.str = lalr12Dollar[1].str
		}
	case 3:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:91
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewSymbol(lalr12Dollar[1].str, nil)
		}
	case 4:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:98
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewAtom(lalr12Dollar[1].str)
		}
	case 5:
		lalr12Dollar = lalr12S[lalr12pt-4 : lalr12pt+1]
//line v12_grammar_v12.y:100
		{
			a := lalr12Dollar[1].node.(*Atom)
			a.Terms = append(a.Terms, lalr12Dollar[3].nodes...)
			lalr12VAL.node = a
		}
	case 6:
		lalr12Dollar = lalr12S[lalr12pt-3 : lalr12pt+1]
//line v12_grammar_v12.y:106
		{
			lhs := lalr12Dollar[1].node.(*Atom)
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewAtom(lhs.Rep+":"+lalr12Dollar[3].str, lhs.Terms...)
		}
	case 7:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:114
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewVariable(lalr12Dollar[1].str, "S")
		}
	case 8:
		lalr12Dollar = lalr12S[lalr12pt-3 : lalr12pt+1]
//line v12_grammar_v12.y:116
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewVariable(lalr12Dollar[1].str, lalr12AtypeToString(lalr12Dollar[3].node))
		}
	case 9:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:121
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewVariable(lalr12Dollar[1].str, "S")
		}
	case 10:
		lalr12Dollar = lalr12S[lalr12pt-3 : lalr12pt+1]
//line v12_grammar_v12.y:123
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewVariable(lalr12Dollar[1].str, lalr12Dollar[3].str)
		}
	case 11:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:128
		{
			lalr12VAL.nodes = []Node{lalr12Dollar[1].node}
		}
	case 12:
		lalr12Dollar = lalr12S[lalr12pt-3 : lalr12pt+1]
//line v12_grammar_v12.y:130
		{
			lalr12VAL.nodes = append(lalr12Dollar[1].nodes, lalr12Dollar[3].node)
		}
	case 13:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:135
		{
			lalr12VAL.nodes = []Node{lalr12Dollar[1].node}
		}
	case 14:
		lalr12Dollar = lalr12S[lalr12pt-3 : lalr12pt+1]
//line v12_grammar_v12.y:137
		{
			lalr12VAL.nodes = append(lalr12Dollar[1].nodes, lalr12Dollar[3].node)
		}
	case 15:
		lalr12Dollar = lalr12S[lalr12pt-0 : lalr12pt+1]
//line v12_grammar_v12.y:142
		{
			lalr12VAL.nodes = nil
		}
	case 16:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:144
		{
			lalr12VAL.nodes = []Node{lalr12Dollar[1].node}
		}
	case 17:
		lalr12Dollar = lalr12S[lalr12pt-3 : lalr12pt+1]
//line v12_grammar_v12.y:146
		{
			lalr12VAL.nodes = append(lalr12Dollar[1].nodes, lalr12Dollar[3].node)
		}
	case 18:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:153
		{
			lalr12VAL.node = lalr12Dollar[1].node
		}
	case 19:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:155
		{
			lalr12VAL.node = lalr12Dollar[1].node
		}
	case 20:
		lalr12Dollar = lalr12S[lalr12pt-2 : lalr12pt+1]
//line v12_grammar_v12.y:157
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewOld(lalr12Dollar[2].node)
		}
	case 21:
		lalr12Dollar = lalr12S[lalr12pt-3 : lalr12pt+1]
//line v12_grammar_v12.y:159
		{
			lalr12VAL.node = lalr12Dollar[2].node
		}
	case 22:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:163
		{
			lalr12VAL.str = "="
		}
	case 23:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:164
		{
			lalr12VAL.str = "<="
		}
	case 24:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:165
		{
			lalr12VAL.str = "<"
		}
	case 25:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:166
		{
			lalr12VAL.str = ">="
		}
	case 26:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:167
		{
			lalr12VAL.str = ">"
		}
	case 27:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:174
		{
			lalr12VAL.node = lalr12Dollar[1].node
		}
	case 28:
		lalr12Dollar = lalr12S[lalr12pt-3 : lalr12pt+1]
//line v12_grammar_v12.y:176
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewAtom(lalr12Dollar[2].str, lalr12Dollar[1].node, lalr12Dollar[3].node)
		}
	case 29:
		lalr12Dollar = lalr12S[lalr12pt-3 : lalr12pt+1]
//line v12_grammar_v12.y:178
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewNot(lalr12Acfg(lalr12lex).NewAtom("=", lalr12Dollar[1].node, lalr12Dollar[3].node))
		}
	case 30:
		lalr12Dollar = lalr12S[lalr12pt-3 : lalr12pt+1]
//line v12_grammar_v12.y:180
		{
			lalr12VAL.node = lalr12Dollar[2].node
		}
	case 31:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:182
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewAnd()
		}
	case 32:
		lalr12Dollar = lalr12S[lalr12pt-1 : lalr12pt+1]
//line v12_grammar_v12.y:184
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewOr()
		}
	case 33:
		lalr12Dollar = lalr12S[lalr12pt-2 : lalr12pt+1]
//line v12_grammar_v12.y:186
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewNot(lalr12Dollar[2].node)
		}
	case 34:
		lalr12Dollar = lalr12S[lalr12pt-3 : lalr12pt+1]
//line v12_grammar_v12.y:188
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewAnd(lalr12Dollar[1].node, lalr12Dollar[3].node)
		}
	case 35:
		lalr12Dollar = lalr12S[lalr12pt-3 : lalr12pt+1]
//line v12_grammar_v12.y:190
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewOr(lalr12Dollar[1].node, lalr12Dollar[3].node)
		}
	case 36:
		lalr12Dollar = lalr12S[lalr12pt-3 : lalr12pt+1]
//line v12_grammar_v12.y:192
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewIff(lalr12Dollar[1].node, lalr12Dollar[3].node)
		}
	case 37:
		lalr12Dollar = lalr12S[lalr12pt-4 : lalr12pt+1]
//line v12_grammar_v12.y:194
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewForall(lalr12Dollar[2].nodes, lalr12Dollar[4].node)
		}
	case 38:
		lalr12Dollar = lalr12S[lalr12pt-4 : lalr12pt+1]
//line v12_grammar_v12.y:196
		{
			lalr12VAL.node = lalr12Acfg(lalr12lex).NewExists(lalr12Dollar[2].nodes, lalr12Dollar[4].node)
		}
	}
	goto lalr12stack /* stack new state and value */
}
