// Code generated by goyacc -o v16_logicgrammar_v16.go -p lalr16 v16_logicgrammar_v16.y. DO NOT EDIT.

//line v16_logicgrammar_v16.y:10
package goivy

import __yyfmt__ "fmt"

//line v16_logicgrammar_v16.y:10

import (
	"fmt"
)

func lalr16AtypeToString(n Node) string {
	switch v := n.(type) {
	case *Symbol:
		return v.Rep
	case *This:
		return "this"
	default:
		return fmt.Sprint(n)
	}
}

func lalr16Acfg(lex lalr16Lexer) *AstConfig {
	return lex.(*lalr16LexAdapter).cfg
}

//line v16_logicgrammar_v16.y:33
type lalr16SymType struct {
	yys   int
	node  Node
	nodes []Node
	str   string
}

const LALR16_TOK_SYMBOL = 57346
const LALR16_TOK_VARIABLE = 57347
const LALR16_TOK_PRESYMBOL = 57348
const LALR16_TOK_LPAREN = 57349
const LALR16_TOK_RPAREN = 57350
const LALR16_TOK_LB = 57351
const LALR16_TOK_RB = 57352
const LALR16_TOK_LCB = 57353
const LALR16_TOK_RCB = 57354
const LALR16_TOK_COMMA = 57355
const LALR16_TOK_SEMI = 57356
const LALR16_TOK_COLON = 57357
const LALR16_TOK_DOT = 57358
const LALR16_TOK_PLUS = 57359
const LALR16_TOK_MINUS = 57360
const LALR16_TOK_TIMES = 57361
const LALR16_TOK_DIV = 57362
const LALR16_TOK_EQ = 57363
const LALR16_TOK_TILDAEQ = 57364
const LALR16_TOK_TILDA = 57365
const LALR16_TOK_LE = 57366
const LALR16_TOK_LT = 57367
const LALR16_TOK_GE = 57368
const LALR16_TOK_GT = 57369
const LALR16_TOK_AND = 57370
const LALR16_TOK_OR = 57371
const LALR16_TOK_ARROW = 57372
const LALR16_TOK_IFF = 57373
const LALR16_TOK_PTO = 57374
const LALR16_TOK_DOLLAR = 57375
const LALR16_TOK_FORALL = 57376
const LALR16_TOK_EXISTS = 57377
const LALR16_TOK_TRUE = 57378
const LALR16_TOK_FALSE = 57379
const LALR16_TOK_OLD = 57380
const LALR16_TOK_THIS = 57381
const LALR16_TOK_ISA = 57382
const LALR16_TOK_IF = 57383
const LALR16_TOK_ELSE = 57384
const LALR16_TOK_GLOBALLY = 57385
const LALR16_TOK_EVENTUALLY = 57386
const LALR16_TOK_WHENNEXT = 57387
const LALR16_TOK_WHENPREV = 57388
const LALR16_TOK_WHENFIRST = 57389
const LALR16_TOK_WHENLAST = 57390
const LALR16_TOK_START_TERM = 57391

var lalr16Toknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LALR16_TOK_SYMBOL",
	"LALR16_TOK_VARIABLE",
	"LALR16_TOK_PRESYMBOL",
	"LALR16_TOK_LPAREN",
	"LALR16_TOK_RPAREN",
	"LALR16_TOK_LB",
	"LALR16_TOK_RB",
	"LALR16_TOK_LCB",
	"LALR16_TOK_RCB",
	"LALR16_TOK_COMMA",
	"LALR16_TOK_SEMI",
	"LALR16_TOK_COLON",
	"LALR16_TOK_DOT",
	"LALR16_TOK_PLUS",
	"LALR16_TOK_MINUS",
	"LALR16_TOK_TIMES",
	"LALR16_TOK_DIV",
	"LALR16_TOK_EQ",
	"LALR16_TOK_TILDAEQ",
	"LALR16_TOK_TILDA",
	"LALR16_TOK_LE",
	"LALR16_TOK_LT",
	"LALR16_TOK_GE",
	"LALR16_TOK_GT",
	"LALR16_TOK_AND",
	"LALR16_TOK_OR",
	"LALR16_TOK_ARROW",
	"LALR16_TOK_IFF",
	"LALR16_TOK_PTO",
	"LALR16_TOK_DOLLAR",
	"LALR16_TOK_FORALL",
	"LALR16_TOK_EXISTS",
	"LALR16_TOK_TRUE",
	"LALR16_TOK_FALSE",
	"LALR16_TOK_OLD",
	"LALR16_TOK_THIS",
	"LALR16_TOK_ISA",
	"LALR16_TOK_IF",
	"LALR16_TOK_ELSE",
	"LALR16_TOK_GLOBALLY",
	"LALR16_TOK_EVENTUALLY",
	"LALR16_TOK_WHENNEXT",
	"LALR16_TOK_WHENPREV",
	"LALR16_TOK_WHENFIRST",
	"LALR16_TOK_WHENLAST",
	"LALR16_TOK_START_TERM",
}

var lalr16Statenames = [...]string{}

const lalr16EofCode = 1
const lalr16ErrCode = 2
const lalr16InitialStackSize = 16

//line v16_logicgrammar_v16.y:281

//line yacctab:1
var lalr16Exca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const lalr16Private = 57344

const lalr16Last = 213

var lalr16Act = [...]int8{
	4, 74, 44, 17, 24, 29, 40, 43, 20, 21,
	22, 23, 26, 27, 28, 29, 53, 97, 46, 72,
	52, 70, 85, 77, 99, 2, 59, 60, 61, 62,
	63, 41, 65, 66, 42, 19, 30, 47, 48, 19,
	78, 54, 20, 67, 22, 23, 55, 56, 57, 58,
	75, 18, 19, 5, 76, 68, 64, 80, 83, 18,
	19, 25, 22, 23, 26, 27, 28, 29, 84, 8,
	28, 29, 81, 87, 45, 86, 89, 53, 53, 16,
	9, 10, 6, 7, 15, 77, 98, 16, 30, 11,
	12, 104, 15, 100, 105, 3, 49, 88, 69, 90,
	101, 102, 78, 93, 94, 50, 75, 106, 18, 19,
	5, 20, 21, 22, 23, 18, 19, 25, 20, 21,
	22, 23, 27, 28, 29, 103, 8, 18, 19, 5,
	20, 21, 22, 23, 19, 45, 16, 9, 10, 6,
	7, 15, 79, 39, 31, 8, 11, 12, 15, 26,
	27, 28, 29, 13, 82, 39, 9, 10, 6, 7,
	15, 68, 95, 14, 70, 11, 12, 73, 96, 51,
	26, 27, 28, 29, 33, 32, 1, 34, 35, 36,
	37, 70, 107, 0, 71, 38, 0, 92, 26, 27,
	28, 29, 33, 32, 30, 34, 35, 36, 37, 91,
	0, 0, 0, 38, 92, 0, 0, 0, 0, 0,
	0, 0, 30,
}

var lalr16Pact = [...]int16{
	46, -1000, 102, 54, 171, 122, -1000, -1000, 103, 130,
	130, 103, 103, 89, -1000, 128, 128, 68, 26, -1000,
	103, 103, 103, 103, -5, 110, 54, 54, 54, 54,
	103, 54, 54, -1000, -1000, -1000, -1000, -1000, -1000, 128,
	153, 90, 32, 168, -1000, 4, 151, 102, 102, 54,
	128, 89, 7, 33, 29, 32, 14, 102, 102, 47,
	104, 51, -15, -1000, -20, -5, 132, 69, -1000, -1000,
	130, 103, 128, 103, 191, -5, 68, 103, 103, 152,
	68, -1000, 1, 68, -1000, 54, 8, -1000, 102, 68,
	102, -1000, 54, 102, 102, -1000, 128, 128, 132, 103,
	-5, 68, 68, 83, 87, 54, 174, -1000,
}

var lalr16Pgo = [...]uint8{
	0, 176, 25, 0, 153, 163, 2, 154, 1, 154,
	7, 144, 3, 142,
}

var lalr16R1 = [...]int8{
	0, 1, 1, 12, 12, 13, 13, 13, 7, 7,
	7, 4, 4, 4, 5, 5, 6, 6, 9, 9,
	10, 10, 8, 8, 8, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 11, 11, 11,
	11, 11, 11, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2,
}

var lalr16R2 = [...]int8{
	0, 1, 2, 1, 4, 1, 1, 3, 1, 3,
	1, 1, 4, 3, 1, 3, 1, 3, 1, 3,
	1, 3, 0, 1, 3, 1, 1, 2, 10, 4,
	4, 3, 3, 3, 3, 3, 5, 1, 1, 1,
	1, 1, 1, 1, 3, 3, 3, 1, 1, 2,
	3, 3, 3, 3, 4, 4, 2, 2,
}

var lalr16Chk = [...]int16{
	-1000, -1, -2, 49, -3, 7, 36, 37, 23, 34,
	35, 43, 44, -4, -5, 38, 33, -12, 5, 6,
	28, 29, 30, 31, -3, 7, 17, 18, 19, 20,
	41, -11, 22, 21, 24, 25, 26, 27, 32, 33,
	-3, -2, -2, -10, -6, 5, -10, -2, -2, 7,
	16, -4, -12, 9, 15, -2, -2, -2, -2, -3,
	-3, -3, -3, -3, -2, -3, -3, -12, 8, 8,
	13, 16, 15, 16, -8, -3, -12, 16, 33, -13,
	-12, 39, -7, -12, 39, 42, -10, -6, -2, -12,
	-2, 8, 13, -2, -2, 10, 16, 16, -3, 16,
	-3, -12, -12, -2, 8, 7, -8, 8,
}

var lalr16Def = [...]int8{
	0, -2, 1, 0, 43, 0, 47, 48, 0, 0,
	0, 0, 0, 25, 26, 0, 0, 11, 14, 3,
	0, 0, 0, 0, 2, 0, 0, 0, 0, 0,
	0, 0, 0, 37, 38, 39, 40, 41, 42, 0,
	43, 0, 49, 0, 20, 16, 0, 56, 57, 22,
	0, 27, 0, 0, 0, 50, 51, 52, 53, 0,
	32, 33, 34, 35, 0, 44, 45, 0, 31, 46,
	0, 0, 0, 0, 0, 23, 13, 0, 0, 0,
	5, 6, 15, 8, 10, 0, 0, 21, 54, 17,
	55, 12, 0, 29, 30, 4, 0, 0, 36, 0,
	24, 7, 9, 0, 0, 22, 0, 28,
}

var lalr16Tok1 = [...]int8{
	1,
}

var lalr16Tok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49,
}

var lalr16Tok3 = [...]int8{
	0,
}

var lalr16ErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	lalr16Debug        = 0
	lalr16ErrorVerbose = false
)

type lalr16Lexer interface {
	Lex(lval *lalr16SymType) int
	Error(s string)
}

type lalr16Parser interface {
	Parse(lalr16Lexer) int
	Lookahead() int
}

type lalr16ParserImpl struct {
	lval  lalr16SymType
	stack [lalr16InitialStackSize]lalr16SymType
	char  int
}

func (p *lalr16ParserImpl) Lookahead() int {
	return p.char
}

func lalr16NewParser() lalr16Parser {
	return &lalr16ParserImpl{}
}

const lalr16Flag = -1000

func lalr16Tokname(c int) string {
	if c >= 1 && c-1 < len(lalr16Toknames) {
		if lalr16Toknames[c-1] != "" {
			return lalr16Toknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func lalr16Statname(s int) string {
	if s >= 0 && s < len(lalr16Statenames) {
		if lalr16Statenames[s] != "" {
			return lalr16Statenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func lalr16ErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !lalr16ErrorVerbose {
		return "syntax error"
	}

	for _, e := range lalr16ErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + lalr16Tokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(lalr16Pact[state])
	for tok := TOKSTART; tok-1 < len(lalr16Toknames); tok++ {
		if n := base + tok; n >= 0 && n < lalr16Last && int(lalr16Chk[int(lalr16Act[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if lalr16Def[state] == -2 {
		i := 0
		for lalr16Exca[i] != -1 || int(lalr16Exca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; lalr16Exca[i] >= 0; i += 2 {
			tok := int(lalr16Exca[i])
			if tok < TOKSTART || lalr16Exca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if lalr16Exca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += lalr16Tokname(tok)
	}
	return res
}

func lalr16lex1(lex lalr16Lexer, lval *lalr16SymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(lalr16Tok1[0])
		goto out
	}
	if char < len(lalr16Tok1) {
		token = int(lalr16Tok1[char])
		goto out
	}
	if char >= lalr16Private {
		if char < lalr16Private+len(lalr16Tok2) {
			token = int(lalr16Tok2[char-lalr16Private])
			goto out
		}
	}
	for i := 0; i < len(lalr16Tok3); i += 2 {
		token = int(lalr16Tok3[i+0])
		if token == char {
			token = int(lalr16Tok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(lalr16Tok2[1]) /* unknown char */
	}
	if lalr16Debug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", lalr16Tokname(token), uint(char))
	}
	return char, token
}

func lalr16Parse(lalr16lex lalr16Lexer) int {
	return lalr16NewParser().Parse(lalr16lex)
}

func (lalr16rcvr *lalr16ParserImpl) Parse(lalr16lex lalr16Lexer) int {
	var lalr16n int
	var lalr16VAL lalr16SymType
	var lalr16Dollar []lalr16SymType
	_ = lalr16Dollar // silence set and not used
	lalr16S := lalr16rcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	lalr16state := 0
	lalr16rcvr.char = -1
	lalr16token := -1 // lalr16rcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		lalr16state = -1
		lalr16rcvr.char = -1
		lalr16token = -1
	}()
	lalr16p := -1
	goto lalr16stack

ret0:
	return 0

ret1:
	return 1

lalr16stack:
	/* put a state and value onto the stack */
	if lalr16Debug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", lalr16Tokname(lalr16token), lalr16Statname(lalr16state))
	}

	lalr16p++
	if lalr16p >= len(lalr16S) {
		nyys := make([]lalr16SymType, len(lalr16S)*2)
		copy(nyys, lalr16S)
		lalr16S = nyys
	}
	lalr16S[lalr16p] = lalr16VAL
	lalr16S[lalr16p].yys = lalr16state

lalr16newstate:
	lalr16n = int(lalr16Pact[lalr16state])
	if lalr16n <= lalr16Flag {
		goto lalr16default /* simple state */
	}
	if lalr16rcvr.char < 0 {
		lalr16rcvr.char, lalr16token = lalr16lex1(lalr16lex, &lalr16rcvr.lval)
	}
	lalr16n += lalr16token
	if lalr16n < 0 || lalr16n >= lalr16Last {
		goto lalr16default
	}
	lalr16n = int(lalr16Act[lalr16n])
	if int(lalr16Chk[lalr16n]) == lalr16token { /* valid shift */
		lalr16rcvr.char = -1
		lalr16token = -1
		lalr16VAL = lalr16rcvr.lval
		lalr16state = lalr16n
		if Errflag > 0 {
			Errflag--
		}
		goto lalr16stack
	}

lalr16default:
	/* default state action */
	lalr16n = int(lalr16Def[lalr16state])
	if lalr16n == -2 {
		if lalr16rcvr.char < 0 {
			lalr16rcvr.char, lalr16token = lalr16lex1(lalr16lex, &lalr16rcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if lalr16Exca[xi+0] == -1 && int(lalr16Exca[xi+1]) == lalr16state {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			lalr16n = int(lalr16Exca[xi+0])
			if lalr16n < 0 || lalr16n == lalr16token {
				break
			}
		}
		lalr16n = int(lalr16Exca[xi+1])
		if lalr16n < 0 {
			goto ret0
		}
	}
	if lalr16n == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			lalr16lex.Error(lalr16ErrorMessage(lalr16state, lalr16token))
			Nerrs++
			if lalr16Debug >= 1 {
				__yyfmt__.Printf("%s", lalr16Statname(lalr16state))
				__yyfmt__.Printf(" saw %s\n", lalr16Tokname(lalr16token))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for lalr16p >= 0 {
				lalr16n = int(lalr16Pact[lalr16S[lalr16p].yys]) + lalr16ErrCode
				if lalr16n >= 0 && lalr16n < lalr16Last {
					lalr16state = int(lalr16Act[lalr16n]) /* simulate a shift of "error" */
					if int(lalr16Chk[lalr16state]) == lalr16ErrCode {
						goto lalr16stack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if lalr16Debug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", lalr16S[lalr16p].yys)
				}
				lalr16p--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if lalr16Debug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", lalr16Tokname(lalr16token))
			}
			if lalr16token == lalr16EofCode {
				goto ret1
			}
			lalr16rcvr.char = -1
			lalr16token = -1
			goto lalr16newstate /* try again in the same state */
		}
	}

	/* reduction by production lalr16n */
	if lalr16Debug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", lalr16n, lalr16Statname(lalr16state))
	}

	lalr16nt := lalr16n
	lalr16pt := lalr16p
	_ = lalr16pt // guard against "declared and not used"

	lalr16p -= int(lalr16R2[lalr16n])
	// lalr16p is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if lalr16p+1 >= len(lalr16S) {
		nyys := make([]lalr16SymType, len(lalr16S)*2)
		copy(nyys, lalr16S)
		lalr16S = nyys
	}
	lalr16VAL = lalr16S[lalr16p+1]

	/* consult goto table to find next state */
	lalr16n = int(lalr16R1[lalr16n])
	lalr16g := int(lalr16Pgo[lalr16n])
	lalr16j := lalr16g + lalr16S[lalr16p].yys + 1

	if lalr16j >= lalr16Last {
		lalr16state = int(lalr16Act[lalr16g])
	} else {
		lalr16state = int(lalr16Act[lalr16j])
		if int(lalr16Chk[lalr16state]) != -lalr16n {
			lalr16state = int(lalr16Act[lalr16g])
		}
	}
	// dummy call; replaced with literal code
	switch lalr16nt {

	case 1:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:81
		{
			lalr16lex.(*lalr16LexAdapter).result = lalr16Dollar[1].node
		}
	case 2:
		lalr16Dollar = lalr16S[lalr16pt-2 : lalr16pt+1]
//line v16_logicgrammar_v16.y:85
		{
			lalr16lex.(*lalr16LexAdapter).result = lalr16Dollar[2].node
		}
	case 3:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:92
		{
			lalr16VAL.str = lalr16Dollar[1].str
		}
	case 4:
		lalr16Dollar = lalr16S[lalr16pt-4 : lalr16pt+1]
//line v16_logicgrammar_v16.y:96
		{
			lalr16VAL.str = lalr16Dollar[1].str + "[" + lalr16Dollar[3].str + "]"
		}
	case 5:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:103
		{
			lalr16VAL.str = lalr16Dollar[1].str
		}
	case 6:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:107
		{
			lalr16VAL.str = "this"
		}
	case 7:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:111
		{
			lalr16VAL.str = lalr16Dollar[1].str + "." + lalr16Dollar[3].str
		}
	case 8:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:118
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewSymbol(lalr16Dollar[1].str, nil)
		}
	case 9:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:122
		{
			if _, ok := lalr16Dollar[1].node.(*This); ok {
				lalr16VAL.node = lalr16Acfg(lalr16lex).NewSymbol(lalr16Dollar[3].str, nil)
			} else if sym, ok := lalr16Dollar[1].node.(*Symbol); ok {
				lalr16VAL.node = lalr16Acfg(lalr16lex).NewSymbol(sym.Rep+"."+lalr16Dollar[3].str, nil)
			} else {
				lalr16VAL.node = lalr16Acfg(lalr16lex).NewSymbol(lalr16Dollar[3].str, nil)
			}
		}
	case 10:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:132
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewThis()
		}
	case 11:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:141
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewAtom(lalr16Dollar[1].str)
		}
	case 12:
		lalr16Dollar = lalr16S[lalr16pt-4 : lalr16pt+1]
//line v16_logicgrammar_v16.y:145
		{
			a := lalr16Dollar[1].node.(*Atom)
			a.Terms = append(a.Terms, lalr16Dollar[3].nodes...)
			lalr16VAL.node = a
		}
	case 13:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:151
		{
			lhs := lalr16Dollar[1].node.(*Atom)
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewAtom(lhs.Rep+"."+lalr16Dollar[3].str, lhs.Terms...)
		}
	case 14:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:159
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewVariable(lalr16Dollar[1].str, "S")
		}
	case 15:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:161
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewVariable(lalr16Dollar[1].str, lalr16AtypeToString(lalr16Dollar[3].node))
		}
	case 16:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:166
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewVariable(lalr16Dollar[1].str, "S")
		}
	case 17:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:168
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewVariable(lalr16Dollar[1].str, lalr16Dollar[3].str)
		}
	case 18:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:173
		{
			lalr16VAL.nodes = []Node{lalr16Dollar[1].node}
		}
	case 19:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:175
		{
			lalr16VAL.nodes = append(lalr16Dollar[1].nodes, lalr16Dollar[3].node)
		}
	case 20:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:180
		{
			lalr16VAL.nodes = []Node{lalr16Dollar[1].node}
		}
	case 21:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:182
		{
			lalr16VAL.nodes = append(lalr16Dollar[1].nodes, lalr16Dollar[3].node)
		}
	case 22:
		lalr16Dollar = lalr16S[lalr16pt-0 : lalr16pt+1]
//line v16_logicgrammar_v16.y:187
		{
			lalr16VAL.nodes = nil
		}
	case 23:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:189
		{
			lalr16VAL.nodes = []Node{lalr16Dollar[1].node}
		}
	case 24:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:191
		{
			lalr16VAL.nodes = append(lalr16Dollar[1].nodes, lalr16Dollar[3].node)
		}
	case 25:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:198
		{
			lalr16VAL.node = lalr16Dollar[1].node
		}
	case 26:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:200
		{
			lalr16VAL.node = lalr16Dollar[1].node
		}
	case 27:
		lalr16Dollar = lalr16S[lalr16pt-2 : lalr16pt+1]
//line v16_logicgrammar_v16.y:202
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewOld(lalr16Dollar[2].node)
		}
	case 28:
		lalr16Dollar = lalr16S[lalr16pt-10 : lalr16pt+1]
//line v16_logicgrammar_v16.y:204
		{
			binder := lalr16Acfg(lalr16lex).NewNamedBinder(lalr16Dollar[3].str, lalr16Dollar[4].nodes, lalr16Dollar[6].node)
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewApp(binder, lalr16Dollar[9].nodes...)
		}
	case 29:
		lalr16Dollar = lalr16S[lalr16pt-4 : lalr16pt+1]
//line v16_logicgrammar_v16.y:209
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewNamedBinder(lalr16Dollar[2].str, nil, lalr16Dollar[4].node)
		}
	case 30:
		lalr16Dollar = lalr16S[lalr16pt-4 : lalr16pt+1]
//line v16_logicgrammar_v16.y:213
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewNamedBinder(lalr16Dollar[2].str, nil, lalr16Dollar[4].node)
		}
	case 31:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:217
		{
			lalr16VAL.node = lalr16Dollar[2].node
		}
	case 32:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:219
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewAtom("+", lalr16Dollar[1].node, lalr16Dollar[3].node)
		}
	case 33:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:221
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewAtom("-", lalr16Dollar[1].node, lalr16Dollar[3].node)
		}
	case 34:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:223
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewAtom("*", lalr16Dollar[1].node, lalr16Dollar[3].node)
		}
	case 35:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:225
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewAtom("/", lalr16Dollar[1].node, lalr16Dollar[3].node)
		}
	case 36:
		lalr16Dollar = lalr16S[lalr16pt-5 : lalr16pt+1]
//line v16_logicgrammar_v16.y:227
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewIte(lalr16Dollar[3].node, lalr16Dollar[1].node, lalr16Dollar[5].node)
		}
	case 37:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:231
		{
			lalr16VAL.str = "="
		}
	case 38:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:232
		{
			lalr16VAL.str = "<="
		}
	case 39:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:233
		{
			lalr16VAL.str = "<"
		}
	case 40:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:234
		{
			lalr16VAL.str = ">="
		}
	case 41:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:235
		{
			lalr16VAL.str = ">"
		}
	case 42:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:236
		{
			lalr16VAL.str = "*>"
		}
	case 43:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:243
		{
			// Convert bare term to atom (app_to_atom)
			lalr16VAL.node = lalr16Dollar[1].node
		}
	case 44:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:248
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewAtom(lalr16Dollar[2].str, lalr16Dollar[1].node, lalr16Dollar[3].node)
		}
	case 45:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:252
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewNot(lalr16Acfg(lalr16lex).NewAtom("=", lalr16Dollar[1].node, lalr16Dollar[3].node))
		}
	case 46:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:256
		{
			lalr16VAL.node = lalr16Dollar[2].node
		}
	case 47:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:258
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewAnd()
		}
	case 48:
		lalr16Dollar = lalr16S[lalr16pt-1 : lalr16pt+1]
//line v16_logicgrammar_v16.y:260
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewOr()
		}
	case 49:
		lalr16Dollar = lalr16S[lalr16pt-2 : lalr16pt+1]
//line v16_logicgrammar_v16.y:262
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewNot(lalr16Dollar[2].node)
		}
	case 50:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:264
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewAnd(lalr16Dollar[1].node, lalr16Dollar[3].node)
		}
	case 51:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:266
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewOr(lalr16Dollar[1].node, lalr16Dollar[3].node)
		}
	case 52:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:268
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewImplies(lalr16Dollar[1].node, lalr16Dollar[3].node)
		}
	case 53:
		lalr16Dollar = lalr16S[lalr16pt-3 : lalr16pt+1]
//line v16_logicgrammar_v16.y:270
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewIff(lalr16Dollar[1].node, lalr16Dollar[3].node)
		}
	case 54:
		lalr16Dollar = lalr16S[lalr16pt-4 : lalr16pt+1]
//line v16_logicgrammar_v16.y:272
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewForall(lalr16Dollar[2].nodes, lalr16Dollar[4].node)
		}
	case 55:
		lalr16Dollar = lalr16S[lalr16pt-4 : lalr16pt+1]
//line v16_logicgrammar_v16.y:274
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewExists(lalr16Dollar[2].nodes, lalr16Dollar[4].node)
		}
	case 56:
		lalr16Dollar = lalr16S[lalr16pt-2 : lalr16pt+1]
//line v16_logicgrammar_v16.y:276
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewGlobally(lalr16Dollar[2].node)
		}
	case 57:
		lalr16Dollar = lalr16S[lalr16pt-2 : lalr16pt+1]
//line v16_logicgrammar_v16.y:278
		{
			lalr16VAL.node = lalr16Acfg(lalr16lex).NewEventually(lalr16Dollar[2].node)
		}
	}
	goto lalr16stack /* stack new state and value */
}
